In [7]:
# STEP 1 — Direct Parquet download
# Bypasses the Hugging Face Dataset API

import pandas as pd
import os

BASE_URL = "https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/main"

files = {
    "train": f"{BASE_URL}/data/train-00000-of-00001.parquet",
    "test": f"{BASE_URL}/data/test-00000-of-00001.parquet"
}

os.makedirs("/content/arabic_faq_data", exist_ok=True)

for split, url in files.items():
    output_path = f"/content/arabic_faq_data/{split}.parquet"

    print(f"\nDownloading {split}...")
    print(url)

    try:
        df = pd.read_parquet(url)

        df.to_parquet(output_path, index=False)

        print(f"✓ {split} downloaded successfully")
        print(f"Rows: {len(df):,}")
        print(f"Columns: {list(df.columns)}")
        print(f"Saved to: {output_path}")

    except Exception as e:
        print(f"✗ Failed to download {split}")
        print(type(e).__name__)
        print(e)

Downloading train...
https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/main/data/train-00000-of-00001.parquet
✗ Failed to download train
HTTPError
HTTP Error 404: Not Found

Downloading test...
https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/main/data/test-00000-of-00001.parquet
✗ Failed to download test
HTTPError
HTTP Error 404: Not Found

In [8]:
# STEP 1 — Try Hugging Face Dataset Viewer Parquet endpoint

import requests
import pandas as pd
from io import BytesIO

url = "https://datasets-server.huggingface.co/parquet?dataset=oddadmix/arabic-rag-support-25K"

print("Requesting Parquet metadata...")
response = requests.get(url, timeout=60)

print("Status code:", response.status_code)
print("Response:", response.text[:2000])

Requesting Parquet metadata...
Status code: 200
Response: {"parquet_files":[{"dataset":"oddadmix/arabic-rag-support-25K","config":"default","split":"test","url":"https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/refs%2Fconvert%2Fparquet/default/test/0000.parquet","filename":"0000.parquet","size":1214145},{"dataset":"oddadmix/arabic-rag-support-25K","config":"default","split":"train","url":"https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/refs%2Fconvert%2Fparquet/default/train/0000.parquet","filename":"0000.parquet","size":65878957}],"pending":[],"failed":[],"partial":false}

In [9]:
# STEP 1 — Download the verified Parquet files

import pandas as pd
import os

train_url = "https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/refs%2Fconvert%2Fparquet/default/train/0000.parquet"
test_url  = "https://huggingface.co/datasets/oddadmix/arabic-rag-support-25K/resolve/refs%2Fconvert%2Fparquet/default/test/0000.parquet"

os.makedirs("/content/arabic_faq_data", exist_ok=True)

# Load Train
print("Loading TRAIN...")
train_df = pd.read_parquet(train_url)

# Load Test
print("Loading TEST...")
test_df = pd.read_parquet(test_url)

# Save local copies
train_path = "/content/arabic_faq_data/train.parquet"
test_path  = "/content/arabic_faq_data/test.parquet"

train_df.to_parquet(train_path, index=False)
test_df.to_parquet(test_path, index=False)

print("\n" + "="*60)
print("DATASET LOADED SUCCESSFULLY")
print("="*60)

print(f"\nTrain shape: {train_df.shape}")
print(f"Test shape : {test_df.shape}")

print("\nTrain columns:")
print(train_df.columns.tolist())

print("\nTest columns:")
print(test_df.columns.tolist())

print("\nTrain sample:")
display(train_df.head(2))

print("\nTest sample:")
display(test_df.head(2))

print("\nLocal files:")
print(train_path)
print(test_path)

Loading TRAIN...
Loading TEST...

============================================================
DATASET LOADED SUCCESSFULLY
============================================================

Train shape: (27427, 13)
Test shape : (500, 13)

Train columns:
['id', 'company_id', 'company', 'domain', 'country', 'chunks', 'question', 'answer', 'answerable', 'gold_chunk_ids', 'question_type', 'tone', 'n_tokens']

Test columns:
['id', 'company_id', 'company', 'domain', 'country', 'chunks', 'question', 'answer', 'answerable', 'gold_chunk_ids', 'question_type', 'tone', 'n_tokens']

Train sample:

,id,company_id,company,domain,country,chunks,question,answer,answerable,gold_chunk_ids,question_type,tone,n_tokens
0,0-0,0,شركة نماء للمياه المتكاملة,water utility,Oman,[تعتمد باقة 'المنزل الأساسية' على استهلاك شهري...,ألاحظ وجود مبلغ إضافي في فاتورتي لهذا الشهر، أ...,تفرض الشركة رسوماً إضافية في حال تجاوز الحد ال...,True,[1],billing dispute or a charge on the account,neutral and to the point,408
1,0-1,0,شركة نماء للمياه المتكاملة,water utility,Oman,[تعتمد باقة 'المنزل الأساسية' على استهلاك شهري...,تفاصيل باقة المنزل المطور؟,توفر باقة 'المنزل المطور' استهلاكاً يصل إلى 50...,True,[0],"product or plan details (specs, what is included)","very brief, almost telegraphic",394

Test sample:

,id,company_id,company,domain,country,chunks,question,answer,answerable,gold_chunk_ids,question_type,tone,n_tokens
0,6875-0,6875,شركة سديم لخدمات المياه,water utility,Tunisia,[تقدم شركة سديم باقتين أساسيتين للمنازل: الباق...,أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجرا...,يمكنكم طلب إغلاق الحساب من خلال تقديم طلب كتاب...,True,[2],"account or subscription management (upgrade, r...",frustrated and impatient (but not abusive),417
1,6875-1,6875,شركة سديم لخدمات المياه,water utility,Tunisia,[تقدم شركة سديم باقتين أساسيتين للمنازل: الباق...,فاتورة زائدة. متر إضافي كم سعره؟,يتم احتساب كل متر مكعب إضافي يتجاوز سعة الباقة...,True,[1],billing dispute or a charge on the account,"very brief, almost telegraphic",393

Local files:
/content/arabic_faq_data/train.parquet
/content/arabic_faq_data/test.parquet

In [10]:
# STEP 2A — Dataset EDA & Data Quality Check

import pandas as pd
import numpy as np

print("=" * 70)
print("DATASET QUALITY CHECK")
print("=" * 70)

# --------------------------------------------------
# 1. Basic information
# --------------------------------------------------

print("\n[1] SHAPES")
print(f"Train: {train_df.shape}")
print(f"Test : {test_df.shape}")

# --------------------------------------------------
# 2. Missing values
# --------------------------------------------------

print("\n[2] MISSING VALUES — TRAIN")
print(train_df.isnull().sum())

print("\n[3] MISSING VALUES — TEST")
print(test_df.isnull().sum())

# --------------------------------------------------
# 3. Duplicate questions
# --------------------------------------------------

print("\n[4] DUPLICATE QUESTIONS")

train_dup_questions = train_df["question"].duplicated().sum()
test_dup_questions = test_df["question"].duplicated().sum()

print(f"Train duplicate questions: {train_dup_questions}")
print(f"Test duplicate questions : {test_dup_questions}")

# --------------------------------------------------
# 4. Duplicate IDs
# --------------------------------------------------

print("\n[5] DUPLICATE IDs")

print("Train duplicate IDs:", train_df["id"].duplicated().sum())
print("Test duplicate IDs :", test_df["id"].duplicated().sum())

# --------------------------------------------------
# 5. Answerable distribution
# --------------------------------------------------

print("\n[6] ANSWERABLE DISTRIBUTION")

print("\nTrain:")
print(train_df["answerable"].value_counts(dropna=False))

print("\nTest:")
print(test_df["answerable"].value_counts(dropna=False))

# --------------------------------------------------
# 6. Question type distribution
# --------------------------------------------------

print("\n[7] QUESTION TYPES — TOP 15")

print(
    train_df["question_type"]
    .value_counts(dropna=False)
    .head(15)
)

# --------------------------------------------------
# 7. Domain distribution
# --------------------------------------------------

print("\n[8] DOMAINS")

print(
    train_df["domain"]
    .value_counts(dropna=False)
)

# --------------------------------------------------
# 8. Country distribution
# --------------------------------------------------

print("\n[9] COUNTRIES — TOP 20")

print(
    train_df["country"]
    .value_counts(dropna=False)
    .head(20)
)

# --------------------------------------------------
# 9. Company distribution
# --------------------------------------------------

print("\n[10] COMPANIES — TOP 15")

print(
    train_df["company"]
    .value_counts(dropna=False)
    .head(15)
)

# --------------------------------------------------
# 10. Text statistics
# --------------------------------------------------

train_df["question_chars"] = train_df["question"].astype(str).str.len()
test_df["question_chars"] = test_df["question"].astype(str).str.len()

train_df["answer_chars"] = train_df["answer"].astype(str).str.len()
test_df["answer_chars"] = test_df["answer"].astype(str).str.len()

print("\n[11] TEXT LENGTH STATISTICS")

print("\nTrain Question Length:")
print(train_df["question_chars"].describe())

print("\nTrain Answer Length:")
print(train_df["answer_chars"].describe())

# --------------------------------------------------
# 11. Inspect chunks / gold_chunk_ids
# --------------------------------------------------

print("\n[12] CHUNKS / GOLD CHUNK IDS")

print("Example chunks type:")
print(type(train_df.loc[0, "chunks"]))

print("\nExample chunks:")
print(train_df.loc[0, "chunks"])

print("\nExample gold_chunk_ids type:")
print(type(train_df.loc[0, "gold_chunk_ids"]))

print("\nExample gold_chunk_ids:")
print(train_df.loc[0, "gold_chunk_ids"])

# --------------------------------------------------
# 12. Test examples
# --------------------------------------------------

print("\n[13] TEST EXAMPLES")

display(
    test_df[
        [
            "id",
            "company",
            "domain",
            "question",
            "answer",
            "answerable",
            "gold_chunk_ids"
        ]
    ].head(5)
)

print("\n" + "=" * 70)
print("EDA CHECK COMPLETED")
print("=" * 70)

======================================================================
DATASET QUALITY CHECK
======================================================================

[1] SHAPES
Train: (27427, 13)
Test : (500, 13)

[2] MISSING VALUES — TRAIN
id                0
company_id        0
company           0
domain            0
country           0
chunks            0
question          0
answer            0
answerable        0
gold_chunk_ids    0
question_type     0
tone              0
n_tokens          0
dtype: int64

[3] MISSING VALUES — TEST
id                0
company_id        0
company           0
domain            0
country           0
chunks            0
question          0
answer            0
answerable        0
gold_chunk_ids    0
question_type     0
tone              0
n_tokens          0
dtype: int64

[4] DUPLICATE QUESTIONS
Train duplicate questions: 2483
Test duplicate questions : 8

[5] DUPLICATE IDs
Train duplicate IDs: 0
Test duplicate IDs : 0

[6] ANSWERABLE DISTRIBUTION

Train:
answerable
True     24066
False     3361
Name: count, dtype: int64

Test:
answerable
True     446
False     54
Name: count, dtype: int64

[7] QUESTION TYPES — TOP 15
question_type
product or plan details (specs, what is included)                 3474
billing dispute or a charge on the account                        3446
troubleshooting a problem with the product or service             3444
account or subscription management (upgrade, renewal, closing)    3429
policy (refund, cancellation, warranty, exchange)                 3425
pricing or fees                                                   3414
availability, coverage or delivery time                           3408
comparison between two products or plans                          3387
Name: count, dtype: int64

[8] DOMAINS
domain
ride-hailing app                1493
furniture store                 1475
retail bank                     1446
electricity utility             1437
telecom / mobile network        1403
airline                         1395
car insurance                   1387
streaming service               1378
gym / fitness club chain        1377
food delivery app               1371
health insurance                1357
mobile wallet / payments app    1348
car rental agency               1341
courier / parcel delivery       1339
internet service provider       1329
hotel chain                     1327
online electronics store        1325
water utility                   1303
e-commerce marketplace          1300
private hospital group          1296
Name: count, dtype: int64

[9] COUNTRIES — TOP 20
country
Morocco                     2302
Saudi Arabia                2195
Algeria                     2185
Egypt                       2156
Bahrain                     2107
Kuwait                      2103
the United Arab Emirates    2098
Lebanon                     2092
Tunisia                     2073
Oman                        2070
Qatar                       2060
Jordan                      2022
Iraq                        1964
Name: count, dtype: int64

[10] COMPANIES — TOP 15
company
سديم للبث الرقمي                          880
شركة سديم للاتصالات                       624
نادي القمة للياقة البدنية                 478
فنادق لؤلؤة الخليج                        431
شركة أثير للاتصالات                       412
نادي صرح اللياقة                          372
محفظة سند الرقمية                         352
مشوارك                                    330
شركة البرق السريع للنقل                   319
نادي جسور اللياقة                         300
مجموعة الشفاء المتكاملة للرعاية الصحية    275
محفظة سديم الرقمية                        216
مجموعة الشفاء التخصصية                    212
البرق السريع للنقل                        196
شركة درع الخليج للتأمين                   196
Name: count, dtype: int64

[11] TEXT LENGTH STATISTICS

Train Question Length:
count    27427.000000
mean        79.474350
std         46.508516
min          9.000000
25%         37.000000
50%         73.000000
75%        116.000000
max        252.000000
Name: question_chars, dtype: float64

Train Answer Length:
count    27427.000000
mean       127.724031
std         31.991466
min         29.000000
25%        108.000000
50%        129.000000
75%        149.000000
max        260.000000
Name: answer_chars, dtype: float64

[12] CHUNKS / GOLD CHUNK IDS
Example chunks type:
<class 'numpy.ndarray'>

Example chunks:
["تعتمد باقة 'المنزل الأساسية' على استهلاك شهري يصل إلى 20 متكعباً من المياه بسعر 12 ريالاً عمانياً، بينما توفر باقة 'المنزل المطور' استهلاكاً يصل إلى 50 متكعباً بسعر 25 ريالاً عمانياً، وتتضمن الأخيرة خدمة صيانة دورية مجانية كل 6 أشهر."
 "تفرض الشركة رسوماً إضافية في حال تجاوز الحد المسموح به في الباقة، حيث يتم احتساب كل متر مكعب إضافي بسعر 0.700 ريال عماني. يتم تحصيل هذه الرسوم تلقائياً في فاتورة الشهر التالي وتظهر تحت بند 'تجاوز الاستهلاك'."
 'في حال وجود خطأ في الفوترة، يمكن للعميل تقديم طلب اعتراض عبر التطبيق خلال 15 يوماً من تاريخ صدور الفاتورة. تقوم الشركة بمراجعة الطلب والرد خلال 7 أيام عمل، وفي حال ثبوت الخطأ، يتم خصم المبلغ الزائد من فاتورة الشهر القادم بنسبة 100%.'
 'تلتزم الشركة بتقديم خدمة توصيل العدادات الجديدة للمناطق السكنية خلال 10 أيام عمل من تاريخ التعاقد. تبلغ رسوم تركيب العداد الأساسي 40 ريالاً عمانياً، وهي رسوم غير قابلة للاسترداد بعد مرور 48 ساعة على عملية التركيب.'
 "تتوفر خدمة 'الري الذكي' للمزارع الصغيرة، حيث يتم تركيب نظام استشعار للرطوبة بتكلفة 150 ريالاً عمانياً. يقلل هذا النظام من هدر المياه بنسبة 30% ويضمن توزيعاً متساوياً للمياه في المساحات التي لا تتجاوز 1000 متر مربع."]

Example gold_chunk_ids type:
<class 'numpy.ndarray'>

Example gold_chunk_ids:
[1]

[13] TEST EXAMPLES

,id,company,domain,question,answer,answerable,gold_chunk_ids
0,6875-0,شركة سديم لخدمات المياه,water utility,أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجرا...,يمكنكم طلب إغلاق الحساب من خلال تقديم طلب كتاب...,True,[2]
1,6875-1,شركة سديم لخدمات المياه,water utility,فاتورة زائدة. متر إضافي كم سعره؟,يتم احتساب كل متر مكعب إضافي يتجاوز سعة الباقة...,True,[1]
2,6875-2,شركة سديم لخدمات المياه,water utility,السلام عليكم، أنا مشترك لديكم منذ فترة وأرغب ف...,وعليكم السلام، نعم تمنح الشركة خصماً قدره 15% ...,True,[5]
3,6875-3,شركة سديم لخدمات المياه,water utility,تحية طيبة، أفكر في تغيير باقتي الحالية وأود مع...,الباقة الفضية سعرها 45 دينار تونسي شهرياً وتوف...,True,[0]
4,6876-0,مؤسسة ركن الفخامة للأثاث,furniture store,أنا غاضب جداً! لقد اشتريت خزانة ملابس وبها كسر...,نعتذر عن الإزعاج، ولكن هذه المعلومات غير متوفر...,False,[]

======================================================================
EDA CHECK COMPLETED
======================================================================

In [11]:
# STEP 2B — Validate chunks and gold_chunk_ids
# This determines the correct retrieval/evaluation structure.

import numpy as np
import pandas as pd

def validate_chunk_structure(df, name):
    invalid_gold_ids = []
    empty_chunks = 0
    total_gold_ids = 0

    for idx, row in df.iterrows():

        chunks = row["chunks"]
        gold_ids = row["gold_chunk_ids"]

        # Convert safely to lists
        chunks = list(chunks) if chunks is not None else []
        gold_ids = list(gold_ids) if gold_ids is not None else []

        if len(chunks) == 0:
            empty_chunks += 1

        total_gold_ids += len(gold_ids)

        for gold_id in gold_ids:
            if not isinstance(gold_id, (int, np.integer)):
                invalid_gold_ids.append(
                    (idx, gold_id, "non_integer")
                )
            elif gold_id < 0 or gold_id >= len(chunks):
                invalid_gold_ids.append(
                    (idx, gold_id, len(chunks))
                )

    print("=" * 70)
    print(f"{name} CHUNK VALIDATION")
    print("=" * 70)

    print(f"Rows: {len(df):,}")
    print(f"Rows with empty chunks: {empty_chunks:,}")
    print(f"Total gold chunk IDs: {total_gold_ids:,}")
    print(f"Invalid gold chunk IDs: {len(invalid_gold_ids):,}")

    if invalid_gold_ids:
        print("\nFirst invalid examples:")
        print(invalid_gold_ids[:10])
    else:
        print("\n✓ All gold_chunk_ids are valid.")

    print()


# Validate Train
validate_chunk_structure(train_df, "TRAIN")

# Validate Test
validate_chunk_structure(test_df, "TEST")


# --------------------------------------------------
# Chunk count statistics
# --------------------------------------------------

print("=" * 70)
print("CHUNK COUNT STATISTICS")
print("=" * 70)

train_chunk_counts = train_df["chunks"].apply(len)
test_chunk_counts = test_df["chunks"].apply(len)

print("\nTrain:")
print(train_chunk_counts.describe())

print("\nTest:")
print(test_chunk_counts.describe())


# --------------------------------------------------
# Gold chunk count statistics
# --------------------------------------------------

print("\n" + "=" * 70)
print("GOLD CHUNK ID STATISTICS")
print("=" * 70)

train_gold_counts = train_df["gold_chunk_ids"].apply(len)
test_gold_counts = test_df["gold_chunk_ids"].apply(len)

print("\nTrain:")
print(train_gold_counts.value_counts().sort_index())

print("\nTest:")
print(test_gold_counts.value_counts().sort_index())


# --------------------------------------------------
# Inspect several real examples
# --------------------------------------------------

print("\n" + "=" * 70)
print("REAL RETRIEVAL EXAMPLES")
print("=" * 70)

for i in range(min(3, len(test_df))):

    row = test_df.iloc[i]

    print(f"\n--- Test Example {i} ---")
    print("Question:")
    print(row["question"])

    print("\nGold chunk IDs:")
    print(row["gold_chunk_ids"])

    print("\nCorresponding gold chunks:")

    for gold_id in row["gold_chunk_ids"]:
        print(f"\n[Chunk {gold_id}]")
        print(row["chunks"][gold_id])

    print("\n" + "-" * 70)

======================================================================
TRAIN CHUNK VALIDATION
======================================================================
Rows: 27,427
Rows with empty chunks: 0
Total gold chunk IDs: 25,130
Invalid gold chunk IDs: 0

✓ All gold_chunk_ids are valid.

======================================================================
TEST CHUNK VALIDATION
======================================================================
Rows: 500
Rows with empty chunks: 0
Total gold chunk IDs: 465
Invalid gold chunk IDs: 0

✓ All gold_chunk_ids are valid.

======================================================================
CHUNK COUNT STATISTICS
======================================================================

Train:
count    27427.000000
mean         5.996135
std          0.820674
min          5.000000
25%          5.000000
50%          6.000000
75%          7.000000
max          7.000000
Name: chunks, dtype: float64

Test:
count    500.000000
mean       6.016000
std        0.800641
min        5.000000
25%        5.000000
50%        6.000000
75%        7.000000
max        7.000000
Name: chunks, dtype: float64

======================================================================
GOLD CHUNK ID STATISTICS
======================================================================

Train:
gold_chunk_ids
0     3361
1    23006
2     1056
3        4
Name: count, dtype: int64

Test:
gold_chunk_ids
0     54
1    428
2     17
3      1
Name: count, dtype: int64

======================================================================
REAL RETRIEVAL EXAMPLES
======================================================================

--- Test Example 0 ---
Question:
أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!

Gold chunk IDs:
[2]

Corresponding gold chunks:

[Chunk 2]
يمكن للعملاء طلب إغلاق الحساب أو إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الشهر الجاري، مع سداد كافة المستحقات المتأخرة قبل إتمام عملية الإغلاق.

----------------------------------------------------------------------

--- Test Example 1 ---
Question:
فاتورة زائدة. متر إضافي كم سعره؟

Gold chunk IDs:
[1]

Corresponding gold chunks:

[Chunk 1]
في حال تجاوز الاستهلاك السعة المحددة في الباقة، يتم احتساب كل متر مكعب إضافي بسعر 3 دينارات تونسية، وتضاف هذه الرسوم تلقائياً إلى فاتورة الشهر التالي دون الحاجة إلى إشعار مسبق.

----------------------------------------------------------------------

--- Test Example 2 ---
Question:
السلام عليكم، أنا مشترك لديكم منذ فترة وأرغب في تحويل اشتراكي إلى خاصية الدفع التلقائي لضمان عدم التأخر في السداد، هل هناك أي ميزات أو خصومات عند تفعيل هذه الخاصية؟

Gold chunk IDs:
[5]

Corresponding gold chunks:

[Chunk 5]
تمنح الشركة خصماً قدره 15% على الفاتورة السنوية للعملاء الذين يقومون بتفعيل خاصية الدفع التلقائي عبر البطاقة البنكية، ويتم تطبيق هذا الخصم في نهاية كل سنة تعاقدية.

----------------------------------------------------------------------

In [12]:
# STEP 2C — Build Retrieval Corpus
# No embeddings yet. No FAISS yet.

import pandas as pd
import numpy as np

def build_chunk_corpus(df):
    records = []

    for row_idx, row in df.iterrows():

        chunks = list(row["chunks"])

        for chunk_idx, chunk_text in enumerate(chunks):

            records.append({
                "row_idx": row_idx,
                "id": row["id"],
                "company_id": row["company_id"],
                "company": row["company"],
                "domain": row["domain"],
                "country": row["country"],
                "chunk_idx": chunk_idx,
                "chunk_text": str(chunk_text),
                "question": row["question"],
                "answer": row["answer"],
                "answerable": row["answerable"],
            })

    return pd.DataFrame(records)


# Build TRAIN retrieval corpus
train_chunks = build_chunk_corpus(train_df)

# Build TEST retrieval corpus only for inspection
test_chunks = build_chunk_corpus(test_df)


print("=" * 70)
print("RETRIEVAL CORPUS")
print("=" * 70)

print(f"\nTrain records : {len(train_df):,}")
print(f"Train chunks  : {len(train_chunks):,}")

print(f"\nTest records  : {len(test_df):,}")
print(f"Test chunks   : {len(test_chunks):,}")

print("\nAverage train chunks per record:")
print(f"{len(train_chunks) / len(train_df):.3f}")

print("\nAverage test chunks per record:")
print(f"{len(test_chunks) / len(test_df):.3f}")


# --------------------------------------------------
# Validate chunk metadata
# --------------------------------------------------

print("\n" + "=" * 70)
print("CORPUS VALIDATION")
print("=" * 70)

print("\nMissing values:")
print(train_chunks.isnull().sum())

print("\nDuplicate chunk IDs within same record:")

duplicate_pairs = train_chunks.duplicated(
    subset=["id", "chunk_idx"]
).sum()

print(duplicate_pairs)

print("\nUnique train records:", train_chunks["id"].nunique())
print("Unique train chunks :", len(train_chunks))

print("\nChunk text length:")
print(train_chunks["chunk_text"].str.len().describe())


# --------------------------------------------------
# Inspect real corpus examples
# --------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE RETRIEVAL CORPUS")
print("=" * 70)

display(
    train_chunks[
        [
            "id",
            "company",
            "domain",
            "country",
            "chunk_idx",
            "chunk_text"
        ]
    ].head(10)
)

======================================================================
RETRIEVAL CORPUS
======================================================================

Train records : 27,427
Train chunks  : 164,456

Test records  : 500
Test chunks   : 3,008

Average train chunks per record:
5.996

Average test chunks per record:
6.016

======================================================================
CORPUS VALIDATION
======================================================================

Missing values:
row_idx       0
id            0
company_id    0
company       0
domain        0
country       0
chunk_idx     0
chunk_text    0
question      0
answer        0
answerable    0
dtype: int64

Duplicate chunk IDs within same record:
0

Unique train records: 27427
Unique train chunks : 164456

Chunk text length:
count    164456.000000
mean        203.143412
std          29.187684
min         106.000000
25%         183.000000
50%         202.000000
75%         223.000000
max         331.000000
Name: chunk_text, dtype: float64

======================================================================
SAMPLE RETRIEVAL CORPUS
======================================================================

,id,company,domain,country,chunk_idx,chunk_text
0,0-0,شركة نماء للمياه المتكاملة,water utility,Oman,0,تعتمد باقة 'المنزل الأساسية' على استهلاك شهري ...
1,0-0,شركة نماء للمياه المتكاملة,water utility,Oman,1,تفرض الشركة رسوماً إضافية في حال تجاوز الحد ال...
2,0-0,شركة نماء للمياه المتكاملة,water utility,Oman,2,في حال وجود خطأ في الفوترة، يمكن للعميل تقديم ...
3,0-0,شركة نماء للمياه المتكاملة,water utility,Oman,3,تلتزم الشركة بتقديم خدمة توصيل العدادات الجديد...
4,0-0,شركة نماء للمياه المتكاملة,water utility,Oman,4,تتوفر خدمة 'الري الذكي' للمزارع الصغيرة، حيث ي...
5,0-1,شركة نماء للمياه المتكاملة,water utility,Oman,0,تعتمد باقة 'المنزل الأساسية' على استهلاك شهري ...
6,0-1,شركة نماء للمياه المتكاملة,water utility,Oman,1,تفرض الشركة رسوماً إضافية في حال تجاوز الحد ال...
7,0-1,شركة نماء للمياه المتكاملة,water utility,Oman,2,في حال وجود خطأ في الفوترة، يمكن للعميل تقديم ...
8,0-1,شركة نماء للمياه المتكاملة,water utility,Oman,3,تلتزم الشركة بتقديم خدمة توصيل العدادات الجديد...
9,0-1,شركة نماء للمياه المتكاملة,water utility,Oman,4,تتوفر خدمة 'الري الذكي' للمزارع الصغيرة، حيث ي...

In [13]:
# STEP 3A — Load and test the embedding model

!pip -q install -U sentence-transformers

import torch
from sentence_transformers import SentenceTransformer

MODEL_NAME = "intfloat/multilingual-e5-base"

print("=" * 70)
print("EMBEDDING MODEL SETUP")
print("=" * 70)

# --------------------------------------------------
# Check device
# --------------------------------------------------

device = "cuda" if torch.cuda.is_available() else "cpu"

print("\nDevice:", device)

if device == "cuda":
    print("GPU:", torch.cuda.get_device_name(0))
    print("CUDA version:", torch.version.cuda)
else:
    print("WARNING: CUDA is not available.")

# --------------------------------------------------
# Load model
# --------------------------------------------------

print("\nLoading model...")

model = SentenceTransformer(
    MODEL_NAME,
    device=device
)

print("✓ Model loaded successfully")

# --------------------------------------------------
# Test embedding
# --------------------------------------------------

test_texts = [
    "query: ازاي اقدر ارجع المنتج؟",
    "passage: يمكن للعملاء طلب إرجاع المنتج خلال فترة الإرجاع المحددة."
]

embeddings = model.encode(
    test_texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=False
)

print("\nEmbedding shape:", embeddings.shape)

print("Embedding dtype:", embeddings.dtype)

print(
    "Embedding norms:",
    [round(float((x ** 2).sum() ** 0.5), 4) for x in embeddings]
)

# --------------------------------------------------
# Similarity sanity check
# --------------------------------------------------

similarity = float(embeddings[0] @ embeddings[1])

print("\nQuery ↔ Passage cosine similarity:", round(similarity, 4))

print("\n" + "=" * 70)
print("STEP 3A COMPLETED")
print("=" * 70)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 739.8/739.8 kB 18.4 MB/s eta 0:00:00
======================================================================
EMBEDDING MODEL SETUP
======================================================================

Device: cuda
GPU: Tesla T4
CUDA version: 12.8

Loading model...

modules.json:   0%|          | 0.00/387 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/179k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/57.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/694 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.11GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/418 [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/280 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

✓ Model loaded successfully

Embedding shape: (2, 768)
Embedding dtype: float32
Embedding norms: [1.0, 1.0]

Query ↔ Passage cosine similarity: 0.8403

======================================================================
STEP 3A COMPLETED
======================================================================

In [14]:
# STEP 3B — Real Arabic embedding batch test
# We test on 100 REAL training chunks before embedding the full corpus.

import time
import torch
import numpy as np

# --------------------------------------------------
# Configuration
# --------------------------------------------------

SAMPLE_SIZE = 100
BATCH_SIZE = 32

sample_texts = (
    "passage: " +
    train_chunks["chunk_text"]
    .head(SAMPLE_SIZE)
    .astype(str)
).tolist()

print("=" * 70)
print("REAL ARABIC EMBEDDING TEST")
print("=" * 70)

print(f"\nSamples: {len(sample_texts)}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Device: {device}")

# --------------------------------------------------
# GPU memory before
# --------------------------------------------------

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    before_memory = torch.cuda.memory_allocated() / (1024 ** 3)
    print(f"GPU memory before: {before_memory:.2f} GB")

# --------------------------------------------------
# Generate embeddings
# --------------------------------------------------

start_time = time.time()

sample_embeddings = model.encode(
    sample_texts,
    batch_size=BATCH_SIZE,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

elapsed = time.time() - start_time

# --------------------------------------------------
# Results
# --------------------------------------------------

print("\n" + "=" * 70)
print("RESULT")
print("=" * 70)

print(f"\nEmbedding shape: {sample_embeddings.shape}")
print(f"Embedding dtype: {sample_embeddings.dtype}")
print(f"Time: {elapsed:.2f} seconds")

# Check dimensions
assert sample_embeddings.shape == (SAMPLE_SIZE, 768)

# Check NaN / Inf
print("\nNaN values:", np.isnan(sample_embeddings).sum())
print("Inf values:", np.isinf(sample_embeddings).sum())

# Check normalization
norms = np.linalg.norm(sample_embeddings, axis=1)

print(
    "Norm range:",
    round(float(norms.min()), 4),
    "→",
    round(float(norms.max()), 4)
)

# --------------------------------------------------
# GPU memory after
# --------------------------------------------------

if torch.cuda.is_available():
    after_memory = torch.cuda.memory_allocated() / (1024 ** 3)
    peak_memory = torch.cuda.max_memory_allocated() / (1024 ** 3)

    print(f"\nGPU memory after: {after_memory:.2f} GB")
    print(f"GPU peak memory : {peak_memory:.2f} GB")

print("\n✓ Real Arabic embedding test completed successfully.")

======================================================================
REAL ARABIC EMBEDDING TEST
======================================================================

Samples: 100
Batch size: 32
Device: cuda
GPU memory before: 1.04 GB

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

======================================================================
RESULT
======================================================================

Embedding shape: (100, 768)
Embedding dtype: float32
Time: 0.57 seconds

NaN values: 0
Inf values: 0
Norm range: 1.0 → 1.0

GPU memory after: 1.04 GB
GPU peak memory : 1.14 GB

✓ Real Arabic embedding test completed successfully.

In [15]:
# STEP 3C — FULL TRAIN CHUNK EMBEDDING
import os
import time
import numpy as np
import torch

BATCH_SIZE = 32
EMBEDDINGS_PATH = "/content/arabic_faq_data/train_chunk_embeddings.npy"

# --------------------------------------------------
# Prepare corpus
# --------------------------------------------------

train_texts = (
    "passage: " +
    train_chunks["chunk_text"]
    .astype(str)
).tolist()

print("=" * 70)
print("FULL TRAIN CHUNK EMBEDDING")
print("=" * 70)

print(f"\nTotal chunks: {len(train_texts):,}")
print(f"Batch size: {BATCH_SIZE}")
print(f"Embedding dimension: 768")
print(f"Device: {device}")
print(f"Output path: {EMBEDDINGS_PATH}")

# --------------------------------------------------
# GPU memory cleanup
# --------------------------------------------------

if torch.cuda.is_available():
    torch.cuda.empty_cache()
    torch.cuda.reset_peak_memory_stats()

# --------------------------------------------------
# Encode
# --------------------------------------------------

start_time = time.time()

train_embeddings = model.encode(
    train_texts,
    batch_size=BATCH_SIZE,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

elapsed = time.time() - start_time

# --------------------------------------------------
# Validate
# --------------------------------------------------

print("\n" + "=" * 70)
print("EMBEDDING RESULT")
print("=" * 70)

print(f"\nShape: {train_embeddings.shape}")
print(f"Dtype: {train_embeddings.dtype}")
print(f"Time: {elapsed:.2f} seconds")

assert train_embeddings.shape == (len(train_chunks), 768)

nan_count = np.isnan(train_embeddings).sum()
inf_count = np.isinf(train_embeddings).sum()

print(f"\nNaN values: {nan_count:,}")
print(f"Inf values: {inf_count:,}")

norms = np.linalg.norm(train_embeddings, axis=1)

print(
    "Norm range:",
    round(float(norms.min()), 4),
    "→",
    round(float(norms.max()), 4)
)

assert nan_count == 0
assert inf_count == 0

# --------------------------------------------------
# Save embeddings
# --------------------------------------------------

np.save(EMBEDDINGS_PATH, train_embeddings)

file_size_mb = os.path.getsize(EMBEDDINGS_PATH) / (1024 ** 2)

print(f"\nSaved successfully: {EMBEDDINGS_PATH}")
print(f"File size: {file_size_mb:.2f} MB")

# --------------------------------------------------
# GPU memory
# --------------------------------------------------

if torch.cuda.is_available():
    peak_memory = torch.cuda.max_memory_allocated() / (1024 ** 3)
    print(f"\nGPU peak memory: {peak_memory:.2f} GB")

print("\n✓ FULL TRAIN CHUNK EMBEDDING COMPLETED SUCCESSFULLY.")

======================================================================
FULL TRAIN CHUNK EMBEDDING
======================================================================

Total chunks: 164,456
Batch size: 32
Embedding dimension: 768
Device: cuda
Output path: /content/arabic_faq_data/train_chunk_embeddings.npy

Batches:   0%|          | 0/5140 [00:00<?, ?it/s]

======================================================================
EMBEDDING RESULT
======================================================================

Shape: (164456, 768)
Dtype: float32
Time: 731.93 seconds

NaN values: 0
Inf values: 0
Norm range: 1.0 → 1.0

Saved successfully: /content/arabic_faq_data/train_chunk_embeddings.npy
File size: 481.80 MB

GPU peak memory: 1.18 GB

✓ FULL TRAIN CHUNK EMBEDDING COMPLETED SUCCESSFULLY.

In [16]:
# STEP 4 — BUILD FAISS VECTOR INDEX

!pip -q install faiss-cpu

import os
import time
import faiss
import numpy as np

EMBEDDINGS_PATH = "/content/arabic_faq_data/train_chunk_embeddings.npy"
FAISS_INDEX_PATH = "/content/arabic_faq_data/train_chunks.faiss"

print("=" * 70)
print("STEP 4 — BUILD FAISS VECTOR INDEX")
print("=" * 70)

# --------------------------------------------------
# Load embeddings
# --------------------------------------------------

print("\nLoading train embeddings...")

train_embeddings = np.load(EMBEDDINGS_PATH)

print(f"Embedding shape: {train_embeddings.shape}")
print(f"Embedding dtype: {train_embeddings.dtype}")

# --------------------------------------------------
# Validation
# --------------------------------------------------

assert train_embeddings.shape == (len(train_chunks), 768)
assert train_embeddings.dtype == np.float32

print("✓ Embedding shape validated")
print("✓ Embedding dtype validated")

# --------------------------------------------------
# Check normalization
# --------------------------------------------------

norms = np.linalg.norm(train_embeddings, axis=1)

print(
    f"\nEmbedding norm range: "
    f"{norms.min():.4f} → {norms.max():.4f}"
)

assert np.allclose(norms, 1.0, atol=1e-5)

print("✓ Embeddings are normalized")

# --------------------------------------------------
# Build FAISS index
# --------------------------------------------------

dimension = train_embeddings.shape[1]

print(f"\nBuilding FAISS IndexFlatIP...")
print(f"Dimension: {dimension}")
print(f"Vectors: {len(train_embeddings):,}")

start_time = time.time()

index = faiss.IndexFlatIP(dimension)

index.add(train_embeddings)

elapsed = time.time() - start_time

print(f"\nFAISS build time: {elapsed:.2f} seconds")

# --------------------------------------------------
# Validate index
# --------------------------------------------------

print("\n" + "=" * 70)
print("FAISS VALIDATION")
print("=" * 70)

print(f"\nIndex type: {type(index).__name__}")
print(f"Index dimension: {index.d}")
print(f"Index vectors: {index.ntotal:,}")

assert index.d == 768
assert index.ntotal == len(train_chunks)

print("\n✓ Index dimension validated")
print("✓ Number of indexed vectors validated")

# --------------------------------------------------
# Save index
# --------------------------------------------------

faiss.write_index(index, FAISS_INDEX_PATH)

file_size_mb = os.path.getsize(FAISS_INDEX_PATH) / (1024 ** 2)

print(f"\nSaved successfully:")
print(FAISS_INDEX_PATH)
print(f"File size: {file_size_mb:.2f} MB")

print("\n✓ STEP 4 COMPLETED SUCCESSFULLY.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.8/18.8 MB 83.8 MB/s eta 0:00:00
======================================================================
STEP 4 — BUILD FAISS VECTOR INDEX
======================================================================

Loading train embeddings...
Embedding shape: (164456, 768)
Embedding dtype: float32
✓ Embedding shape validated
✓ Embedding dtype validated

Embedding norm range: 1.0000 → 1.0000
✓ Embeddings are normalized

Building FAISS IndexFlatIP...
Dimension: 768
Vectors: 164,456

FAISS build time: 0.43 seconds

======================================================================
FAISS VALIDATION
======================================================================

Index type: IndexFlatIP
Index dimension: 768
Index vectors: 164,456

✓ Index dimension validated
✓ Number of indexed vectors validated

Saved successfully:
/content/arabic_faq_data/train_chunks.faiss
File size: 481.80 MB

✓ STEP 4 COMPLETED SUCCESSFULLY.

In [17]:
# STEP 5 — REAL RETRIEVAL SANITY TEST

import numpy as np
import pandas as pd
import faiss

TOP_K = 5

print("=" * 70)
print("STEP 5 — REAL RETRIEVAL SANITY TEST")
print("=" * 70)

# --------------------------------------------------
# Select a real test example
# --------------------------------------------------

test_idx = 0
test_row = test_df.iloc[test_idx]

question = str(test_row["question"])
gold_chunk_ids = np.asarray(test_row["gold_chunk_ids"], dtype=int)

print("\nTEST EXAMPLE")
print("-" * 70)
print(f"Test row index : {test_idx}")
print(f"Question       : {question}")
print(f"Gold chunk IDs : {gold_chunk_ids.tolist()}")

# --------------------------------------------------
# Load FAISS index
# --------------------------------------------------

index = faiss.read_index(FAISS_INDEX_PATH)

print(f"\nFAISS index vectors: {index.ntotal:,}")

assert index.ntotal == len(train_chunks)

# --------------------------------------------------
# Encode query
# --------------------------------------------------

query_text = "query: " + question

query_embedding = model.encode(
    [query_text],
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=False
).astype(np.float32)

print(f"Query embedding shape: {query_embedding.shape}")

assert query_embedding.shape == (1, 768)

# --------------------------------------------------
# FAISS search
# --------------------------------------------------

scores, retrieved_indices = index.search(
    query_embedding,
    TOP_K
)

# --------------------------------------------------
# Display results
# --------------------------------------------------

print("\n" + "=" * 70)
print(f"TOP-{TOP_K} RETRIEVED CHUNKS")
print("=" * 70)

retrieved_indices = retrieved_indices[0]
scores = scores[0]

for rank, (vector_idx, score) in enumerate(
    zip(retrieved_indices, scores),
    start=1
):
    chunk = train_chunks.iloc[int(vector_idx)]

    print(f"\nRank {rank}")
    print("-" * 70)
    print(f"Vector index : {vector_idx}")
    print(f"Score        : {score:.4f}")
    print(f"Record ID    : {chunk['id']}")
    print(f"Chunk index  : {chunk['chunk_idx']}")
    print(f"Company      : {chunk['company']}")
    print(f"Domain       : {chunk['domain']}")
    print(f"Country      : {chunk['country']}")
    print(f"Chunk text   : {chunk['chunk_text']}")

# --------------------------------------------------
# Check whether gold chunk was retrieved
# --------------------------------------------------

retrieved_pairs = []

for vector_idx in retrieved_indices:
    chunk = train_chunks.iloc[int(vector_idx)]

    retrieved_pairs.append(
        (chunk["id"], int(chunk["chunk_idx"]))
    )

gold_pairs = [
    (test_row["id"], int(chunk_id))
    for chunk_id in gold_chunk_ids
]

hit = any(pair in gold_pairs for pair in retrieved_pairs)

print("\n" + "=" * 70)
print("SANITY CHECK")
print("=" * 70)

print(f"\nGold pairs      : {gold_pairs}")
print(f"Retrieved pairs : {retrieved_pairs}")
print(f"\nGold chunk found in Top-{TOP_K}: {hit}")

print("\n✓ STEP 5 RETRIEVAL SANITY TEST COMPLETED.")

======================================================================
STEP 5 — REAL RETRIEVAL SANITY TEST
======================================================================

TEST EXAMPLE
----------------------------------------------------------------------
Test row index : 0
Question       : أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
Gold chunk IDs : [2]

FAISS index vectors: 164,456
Query embedding shape: (1, 768)

======================================================================
TOP-5 RETRIEVED CHUNKS
======================================================================

Rank 1
----------------------------------------------------------------------
Vector index : 33508
Score        : 0.8562
Record ID    : 1398-3
Chunk index  : 3
Company      : شاشة المغرب
Domain       : streaming service
Country      : Morocco
Chunk text   : لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 2
----------------------------------------------------------------------
Vector index : 33501
Score        : 0.8562
Record ID    : 1398-2
Chunk index  : 3
Company      : شاشة المغرب
Domain       : streaming service
Country      : Morocco
Chunk text   : لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 3
----------------------------------------------------------------------
Vector index : 33494
Score        : 0.8562
Record ID    : 1398-1
Chunk index  : 3
Company      : شاشة المغرب
Domain       : streaming service
Country      : Morocco
Chunk text   : لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 4
----------------------------------------------------------------------
Vector index : 33487
Score        : 0.8562
Record ID    : 1398-0
Chunk index  : 3
Company      : شاشة المغرب
Domain       : streaming service
Country      : Morocco
Chunk text   : لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 5
----------------------------------------------------------------------
Vector index : 129954
Score        : 0.8545
Record ID    : 5427-3
Chunk index  : 5
Company      : فنادق لؤلؤة الخليج
Domain       : hotel chain
Country      : Bahrain
Chunk text   : لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.

======================================================================
SANITY CHECK
======================================================================

Gold pairs      : [('6875-0', 2)]
Retrieved pairs : [('1398-3', 3), ('1398-2', 3), ('1398-1', 3), ('1398-0', 3), ('5427-3', 5)]

Gold chunk found in Top-5: False

✓ STEP 5 RETRIEVAL SANITY TEST COMPLETED.

In [18]:
# STEP 5B — DIAGNOSE FAILED RETRIEVAL

import numpy as np
import faiss

print("=" * 70)
print("STEP 5B — DIAGNOSE FAILED RETRIEVAL")
print("=" * 70)

# --------------------------------------------------
# Same test example from Step 5
# --------------------------------------------------

test_idx = 0
test_row = test_df.iloc[test_idx]

test_id = test_row["id"]
gold_chunk_ids = np.asarray(
    test_row["gold_chunk_ids"],
    dtype=int
)

print("\nTEST RECORD")
print("-" * 70)
print(f"Test ID          : {test_id}")
print(f"Question         : {test_row['question']}")
print(f"Gold chunk IDs   : {gold_chunk_ids.tolist()}")

# --------------------------------------------------
# Get actual gold chunk text
# --------------------------------------------------

print("\n" + "=" * 70)
print("GOLD CHUNK")
print("=" * 70)

for gold_idx in gold_chunk_ids:
    gold_text = str(test_row["chunks"][gold_idx])

    print(f"\nGold chunk index: {gold_idx}")
    print(f"Gold text:\n{gold_text}")

# --------------------------------------------------
# Check whether the same record exists in TRAIN
# --------------------------------------------------

same_id_mask = train_chunks["id"].astype(str) == str(test_id)
same_id_chunks = train_chunks[same_id_mask]

print("\n" + "=" * 70)
print("TRAIN CORPUS CHECK")
print("=" * 70)

print(f"\nMatching train record ID count: {len(same_id_chunks)}")

if len(same_id_chunks) > 0:
    print("\n⚠️ Same test record ID exists in TRAIN:")
    print(
        same_id_chunks[
            ["id", "chunk_idx", "chunk_text"]
        ].to_string(index=False)
    )
else:
    print("\n✓ Test record ID is NOT present in TRAIN corpus.")

# --------------------------------------------------
# Exact gold text search in train corpus
# --------------------------------------------------

print("\n" + "=" * 70)
print("EXACT GOLD TEXT SEARCH")
print("=" * 70)

for gold_idx in gold_chunk_ids:

    gold_text = str(test_row["chunks"][gold_idx])

    exact_matches = train_chunks[
        train_chunks["chunk_text"].astype(str) == gold_text
    ]

    print(f"\nGold chunk {gold_idx}:")
    print(f"Exact matches in TRAIN: {len(exact_matches)}")

    if len(exact_matches) > 0:
        print(
            exact_matches[
                ["id", "chunk_idx", "company", "domain", "country"]
            ].head(20).to_string(index=False)
        )
    else:
        print("✓ Exact gold chunk does NOT exist in TRAIN.")

# --------------------------------------------------
# Embed gold chunk and search FAISS
# --------------------------------------------------

print("\n" + "=" * 70)
print("DIRECT GOLD-CHUNK SIMILARITY SEARCH")
print("=" * 70)

gold_texts = [
    "passage: " + str(test_row["chunks"][idx])
    for idx in gold_chunk_ids
]

gold_embeddings = model.encode(
    gold_texts,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=False
).astype(np.float32)

gold_scores, gold_indices = index.search(
    gold_embeddings,
    5
)

for gold_position, gold_idx in enumerate(gold_chunk_ids):

    print(f"\nGold chunk index: {gold_idx}")

    print("-" * 70)

    for rank, (vector_idx, score) in enumerate(
        zip(
            gold_indices[gold_position],
            gold_scores[gold_position]
        ),
        start=1
    ):
        chunk = train_chunks.iloc[int(vector_idx)]

        print(
            f"Rank {rank} | "
            f"Score {score:.4f} | "
            f"ID {chunk['id']} | "
            f"Chunk {chunk['chunk_idx']}"
        )

        print(f"Text: {chunk['chunk_text']}")

print("\n" + "=" * 70)
print("DIAGNOSIS COMPLETED")
print("=" * 70)

print("\n✓ No model/index changes were made.")
print("✓ No data was modified.")

======================================================================
STEP 5B — DIAGNOSE FAILED RETRIEVAL
======================================================================

TEST RECORD
----------------------------------------------------------------------
Test ID          : 6875-0
Question         : أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
Gold chunk IDs   : [2]

======================================================================
GOLD CHUNK
======================================================================

Gold chunk index: 2
Gold text:
يمكن للعملاء طلب إغلاق الحساب أو إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الشهر الجاري، مع سداد كافة المستحقات المتأخرة قبل إتمام عملية الإغلاق.

======================================================================
TRAIN CORPUS CHECK
======================================================================

Matching train record ID count: 0

✓ Test record ID is NOT present in TRAIN corpus.

======================================================================
EXACT GOLD TEXT SEARCH
======================================================================

Gold chunk 2:
Exact matches in TRAIN: 0
✓ Exact gold chunk does NOT exist in TRAIN.

======================================================================
DIRECT GOLD-CHUNK SIMILARITY SEARCH
======================================================================

Gold chunk index: 2
----------------------------------------------------------------------
Rank 1 | Score 0.9770 | ID 4356-3 | Chunk 4
Text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ الإلغاء المطلوب، ويتم رد المبالغ الفائضة في الحساب خلال 30 يوماً عمل من تاريخ إغلاق الحساب.
Rank 2 | Score 0.9770 | ID 4356-2 | Chunk 4
Text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ الإلغاء المطلوب، ويتم رد المبالغ الفائضة في الحساب خلال 30 يوماً عمل من تاريخ إغلاق الحساب.
Rank 3 | Score 0.9770 | ID 4356-1 | Chunk 4
Text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ الإلغاء المطلوب، ويتم رد المبالغ الفائضة في الحساب خلال 30 يوماً عمل من تاريخ إغلاق الحساب.
Rank 4 | Score 0.9770 | ID 4356-0 | Chunk 4
Text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ الإلغاء المطلوب، ويتم رد المبالغ الفائضة في الحساب خلال 30 يوماً عمل من تاريخ إغلاق الحساب.
Rank 5 | Score 0.9685 | ID 3120-3 | Chunk 2
Text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ انتهاء الشهر الجاري. يتم استرداد الرسوم المدفوعة مسبقاً عن الأيام غير المستخدمة بنسبة 80% من قيمتها.

======================================================================
DIAGNOSIS COMPLETED
======================================================================

✓ No model/index changes were made.
✓ No data was modified.

In [20]:
# STEP 5C — FIXED SEMANTIC RETRIEVAL ANALYSIS
# Handles unanswerable test examples with empty gold_chunk_ids

import numpy as np
import pandas as pd

TOP_K = 5
SAMPLE_SIZE = 10

print("=" * 70)
print("STEP 5C — FIXED TEST-TO-TRAIN SEMANTIC RETRIEVAL ANALYSIS")
print("=" * 70)

sample_test = test_df.head(SAMPLE_SIZE).copy()

analysis_results = []

for test_idx, (_, row) in enumerate(sample_test.iterrows()):

    question = str(row["question"])

    gold_chunk_ids = np.asarray(
        row["gold_chunk_ids"],
        dtype=int
    )

    print("\n" + "=" * 70)
    print(f"TEST EXAMPLE {test_idx + 1}")
    print("=" * 70)

    print(f"\nTest ID: {row['id']}")
    print(f"Question: {question}")
    print(f"Gold chunk IDs: {gold_chunk_ids.tolist()}")

    # --------------------------------------------------
    # Encode query
    # --------------------------------------------------

    query_embedding = model.encode(
        ["query: " + question],
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=False
    ).astype(np.float32)

    # Ensure correct shape for FAISS
    query_embedding = np.ascontiguousarray(
        query_embedding.reshape(1, -1),
        dtype=np.float32
    )

    # --------------------------------------------------
    # Retrieve Top-K
    # --------------------------------------------------

    scores, indices = index.search(
        query_embedding,
        TOP_K
    )

    scores = scores[0]
    indices = indices[0]

    print("\nTop-5 retrieved:")
    print("-" * 70)

    for rank, (vector_idx, score) in enumerate(
        zip(indices, scores),
        start=1
    ):
        chunk = train_chunks.iloc[int(vector_idx)]

        print(
            f"\nRank {rank} | "
            f"Score {score:.4f} | "
            f"ID {chunk['id']} | "
            f"Chunk {chunk['chunk_idx']}"
        )

        print(f"Text: {chunk['chunk_text']}")

    # --------------------------------------------------
    # Handle gold chunks
    # --------------------------------------------------

    if len(gold_chunk_ids) == 0:

        print("\n" + "-" * 70)
        print("GOLD CHUNK ANALYSIS")
        print("-" * 70)

        print("\n⚠️ No gold chunks for this example.")
        print("This is an unanswerable example.")
        print("Skipping direct gold semantic search.")

        analysis_results.append({
            "test_idx": test_idx,
            "test_id": row["id"],
            "answerable": bool(row["answerable"]),
            "gold_chunk_count": 0,
            "top1_score": float(scores[0]),
            "top5_score": float(scores[-1]),
            "nearest_train_similarity_to_gold": np.nan,
            "nearest_train_id": None,
            "nearest_train_chunk_idx": None
        })

        continue

    # --------------------------------------------------
    # Encode gold chunks
    # --------------------------------------------------

    gold_texts = [
        "passage: " + str(row["chunks"][gold_idx])
        for gold_idx in gold_chunk_ids
    ]

    gold_embeddings = model.encode(
        gold_texts,
        convert_to_numpy=True,
        normalize_embeddings=True,
        show_progress_bar=False
    ).astype(np.float32)

    # Force 2D shape
    gold_embeddings = np.ascontiguousarray(
        gold_embeddings.reshape(len(gold_texts), -1),
        dtype=np.float32
    )

    # --------------------------------------------------
    # Find nearest TRAIN chunk to each gold chunk
    # --------------------------------------------------

    gold_scores, gold_indices = index.search(
        gold_embeddings,
        1
    )

    best_position = int(
        np.argmax(gold_scores[:, 0])
    )

    best_gold_similarity = float(
        gold_scores[best_position, 0]
    )

    best_gold_vector_idx = int(
        gold_indices[best_position, 0]
    )

    nearest_gold_chunk = train_chunks.iloc[
        best_gold_vector_idx
    ]

    print("\n" + "-" * 70)
    print("NEAREST TRAIN SEMANTIC MATCH TO GOLD")
    print("-" * 70)

    print(
        f"\nBest similarity: "
        f"{best_gold_similarity:.4f}"
    )

    print(
        f"Train ID: "
        f"{nearest_gold_chunk['id']}"
    )

    print(
        f"Train chunk index: "
        f"{nearest_gold_chunk['chunk_idx']}"
    )

    print(
        f"Train chunk text: "
        f"{nearest_gold_chunk['chunk_text']}"
    )

    analysis_results.append({
        "test_idx": test_idx,
        "test_id": row["id"],
        "answerable": bool(row["answerable"]),
        "gold_chunk_count": len(gold_chunk_ids),
        "top1_score": float(scores[0]),
        "top5_score": float(scores[-1]),
        "nearest_train_similarity_to_gold": best_gold_similarity,
        "nearest_train_id": nearest_gold_chunk["id"],
        "nearest_train_chunk_idx": int(
            nearest_gold_chunk["chunk_idx"]
        )
    })

# --------------------------------------------------
# Summary
# --------------------------------------------------

analysis_df = pd.DataFrame(analysis_results)

print("\n" + "=" * 70)
print("STEP 5C SUMMARY")
print("=" * 70)

print(
    analysis_df[
        [
            "test_idx",
            "test_id",
            "answerable",
            "gold_chunk_count",
            "top1_score",
            "top5_score",
            "nearest_train_similarity_to_gold",
            "nearest_train_id",
            "nearest_train_chunk_idx"
        ]
    ].to_string(index=False)
)

print("\n✓ STEP 5C COMPLETED SUCCESSFULLY.")
print("✓ Unanswerable examples were handled correctly.")
print("✓ No model/index/data changes were made.")
print("✓ This remains diagnostic analysis — NOT official evaluation.")

======================================================================
STEP 5C — FIXED TEST-TO-TRAIN SEMANTIC RETRIEVAL ANALYSIS
======================================================================

======================================================================
TEST EXAMPLE 1
======================================================================

Test ID: 6875-0
Question: أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
Gold chunk IDs: [2]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8562 | ID 1398-3 | Chunk 3
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 2 | Score 0.8562 | ID 1398-2 | Chunk 3
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 3 | Score 0.8562 | ID 1398-1 | Chunk 3
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 4 | Score 0.8562 | ID 1398-0 | Chunk 3
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 5 | Score 0.8545 | ID 5427-3 | Chunk 5
Text: لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9770
Train ID: 4356-0
Train chunk index: 4
Train chunk text: يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ الإلغاء المطلوب، ويتم رد المبالغ الفائضة في الحساب خلال 30 يوماً عمل من تاريخ إغلاق الحساب.

======================================================================
TEST EXAMPLE 2
======================================================================

Test ID: 6875-1
Question: فاتورة زائدة. متر إضافي كم سعره؟
Gold chunk IDs: [1]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8650 | ID 3228-3 | Chunk 3
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 2 | Score 0.8650 | ID 3228-2 | Chunk 3
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 3 | Score 0.8650 | ID 3228-1 | Chunk 3
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 4 | Score 0.8650 | ID 3228-0 | Chunk 3
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 5 | Score 0.8597 | ID 0-1 | Chunk 1
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد المسموح به في الباقة، حيث يتم احتساب كل متر مكعب إضافي بسعر 0.700 ريال عماني. يتم تحصيل هذه الرسوم تلقائياً في فاتورة الشهر التالي وتظهر تحت بند 'تجاوز الاستهلاك'.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9453
Train ID: 3228-0
Train chunk index: 3
Train chunk text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

======================================================================
TEST EXAMPLE 3
======================================================================

Test ID: 6875-2
Question: السلام عليكم، أنا مشترك لديكم منذ فترة وأرغب في تحويل اشتراكي إلى خاصية الدفع التلقائي لضمان عدم التأخر في السداد، هل هناك أي ميزات أو خصومات عند تفعيل هذه الخاصية؟
Gold chunk IDs: [5]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8598 | ID 2494-3 | Chunk 5
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 2 | Score 0.8598 | ID 2494-2 | Chunk 5
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 3 | Score 0.8598 | ID 2494-1 | Chunk 5
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 4 | Score 0.8598 | ID 2494-0 | Chunk 5
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 5 | Score 0.8548 | ID 274-3 | Chunk 2
Text: لترقية الاشتراك، يمكن للمستخدم الانتقال من الباقة الأساسية إلى المتقدمة أو المميزة عبر قسم إدارة الحساب. يتم احتساب فرق السعر فقط للأيام المتبقية من الشهر الحالي، ويتم تفعيل المزايا الجديدة فور إتمام عملية الدفع بنجاح.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9742
Train ID: 1010-0
Train chunk index: 5
Train chunk text: تمنح الشركة خصماً بنسبة 15% على الفاتورة السنوية للعملاء الذين يسجلون في نظام الدفع التلقائي عبر البطاقة الائتمانية، على أن يتم سداد المستحقات في موعد لا يتجاوز الخامس من كل شهر ميلادي.

======================================================================
TEST EXAMPLE 4
======================================================================

Test ID: 6875-3
Question: تحية طيبة، أفكر في تغيير باقتي الحالية وأود معرفة الفرق بين الباقة الفضية والباقة الذهبية من حيث التكلفة الشهرية وكمية المياه المتاحة لكل منهما، وشكراً لكم.
Gold chunk IDs: [0]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8627 | ID 3970-3 | Chunk 1
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 2 | Score 0.8627 | ID 3970-2 | Chunk 1
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 3 | Score 0.8627 | ID 3970-1 | Chunk 1
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 4 | Score 0.8627 | ID 3970-0 | Chunk 1
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 5 | Score 0.8587 | ID 3289-3 | Chunk 5
Text: لترقية الباقة من الفضية إلى الذهبية، يجب دفع فارق السعر وهو 2500 ريال سعودي. يتم تفعيل التغطية الجديدة فوراً بعد سداد المبلغ، وتطبق الشروط والحدود الخاصة بالباقة الذهبية على جميع المطالبات اللاحقة لتاريخ الترقية.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9799
Train ID: 3391-0
Train chunk index: 0
Train chunk text: تقدم شركة سديم باقتين رئيسيتين للمنازل: الباقة الأساسية بسعر 45 دينار تونسي شهرياً وتوفر استهلاكاً حتى 20 متراً مكعباً، والباقة المميزة بسعر 80 دينار تونسي شهرياً وتوفر استهلاكاً حتى 50 متراً مكعباً مع خدمة صيانة سنوية مجانية واحدة.

======================================================================
TEST EXAMPLE 5
======================================================================

Test ID: 6876-0
Question: أنا غاضب جداً! لقد اشتريت خزانة ملابس وبها كسر في الرف السفلي، أريد استبدالها الآن فوراً، أين هي سياسة استبدال القطع التالفة بالتحديد؟
Gold chunk IDs: []

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8729 | ID 2116-2 | Chunk 3
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 2 | Score 0.8729 | ID 2116-1 | Chunk 3
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 3 | Score 0.8729 | ID 2116-0 | Chunk 3
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 4 | Score 0.8729 | ID 2116-3 | Chunk 3
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 5 | Score 0.8475 | ID 3999-0 | Chunk 4
Text: تتيح الشركة استبدال القطع التالفة خلال ١٤ يوماً من تاريخ الاستلام بشرط وجود الفاتورة الأصلية وأن يكون المنتج بحالته الأصلية. يتم الاستبدال مجاناً إذا كان التلف ناتجاً عن الشحن أو خطأ في التصنيع.

----------------------------------------------------------------------
GOLD CHUNK ANALYSIS
----------------------------------------------------------------------

⚠️ No gold chunks for this example.
This is an unanswerable example.
Skipping direct gold semantic search.

======================================================================
TEST EXAMPLE 6
======================================================================

Test ID: 6876-1
Question: طاولة رخام خدوش. ماذا أفعل؟
Gold chunk IDs: [2]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8164 | ID 1192-3 | Chunk 0
Text: تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد عيوب التصنيع.

Rank 2 | Score 0.8164 | ID 1192-2 | Chunk 0
Text: تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد عيوب التصنيع.

Rank 3 | Score 0.8164 | ID 1192-1 | Chunk 0
Text: تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد عيوب التصنيع.

Rank 4 | Score 0.8164 | ID 1192-0 | Chunk 0
Text: تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد عيوب التصنيع.

Rank 5 | Score 0.8112 | ID 4180-0 | Chunk 0
Text: تتوفر طاولة 'سديم' الخشبية بسعر 120 دينار كويتي، وهي مصنوعة من خشب الجوز الطبيعي بطول 180 سم وعرض 90 سم. أما طاولة 'أفق' الزجاجية فتباع بسعر 85 دينار كويتي، وتتميز بسطح من الزجاج المقسى ومقاساتها 120 سم في 70 سم.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9202
Train ID: 6776-1
Train chunk index: 2
Train chunk text: تتضمن طاولة 'مجان' للطعام سطحاً من الرخام الطبيعي وأرجلاً من خشب الزان، وتتسع لـ ٦ أشخاص، ويبلغ سعرها ٣٥٠ ريالاً عمانياً، مع خدمة تركيب مجانية عند الشراء.

======================================================================
TEST EXAMPLE 7
======================================================================

Test ID: 6876-2
Question: لقد انتظرت طويلاً ولم تصل غرفة النوم! أخبروني فوراً كم يستغرق التوصيل إلى محافظة ظفار وما هي التكلفة؟
Gold chunk IDs: [3]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8619 | ID 2657-3 | Chunk 1
Text: تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.

Rank 2 | Score 0.8619 | ID 2657-2 | Chunk 1
Text: تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.

Rank 3 | Score 0.8619 | ID 2657-1 | Chunk 1
Text: تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.

Rank 4 | Score 0.8619 | ID 2657-0 | Chunk 1
Text: تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.

Rank 5 | Score 0.8582 | ID 2579-3 | Chunk 2
Text: تكلفة خدمة التوصيل والتركيب داخل محافظة مسقط هي 15 ريال عماني فقط. أما بالنسبة للمحافظات الأخرى مثل صلالة أو صحار، فإن تكلفة التوصيل تبلغ 30 ريال عماني، ويتم التنفيذ خلال 3 إلى 7 أيام عمل من تاريخ تأكيد الطلب.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9629
Train ID: 5654-0
Train chunk index: 2
Train chunk text: تستغرق عملية توصيل الطلبات داخل محافظة مسقط مدة 24 ساعة عمل، بينما تستغرق التوصيلات إلى المحافظات الأخرى من 3 إلى 5 أيام عمل. تكلفة التوصيل الموحدة هي 2 ريال عماني لجميع الطلبات التي تقل قيمتها عن 20 ريالاً عمانياً.

======================================================================
TEST EXAMPLE 8
======================================================================

Test ID: 6876-3
Question: غرفة سلطان. موعد التركيب؟
Gold chunk IDs: [0]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8248 | ID 3068-3 | Chunk 3
Text: طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض الكريمي، والرمادي.

Rank 2 | Score 0.8248 | ID 3068-2 | Chunk 3
Text: طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض الكريمي، والرمادي.

Rank 3 | Score 0.8248 | ID 3068-1 | Chunk 3
Text: طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض الكريمي، والرمادي.

Rank 4 | Score 0.8248 | ID 3068-0 | Chunk 3
Text: طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض الكريمي، والرمادي.

Rank 5 | Score 0.8239 | ID 5505-0 | Chunk 0
Text: طقم غرفة المعيشة 'سلطان' يتكون من أريكة ثلاثية ومقعدين منفردين، مصنوع من خشب الزان الطبيعي والكتان الفاخر، وسعره 450 ديناراً بحرينياً. يتوفر هذا الطقم بثلاثة ألوان: البيج، الرمادي، والأزرق الداكن، مع ضمان شامل لمدة 5 سنوات ضد عيوب التصنيع.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9538
Train ID: 1248-0
Train chunk index: 0
Train chunk text: تقدم الشركة مجموعة 'سلطان' لغرف النوم بسعر ٤٥٠٠٠ جنيه مصري، وتتكون من سرير مقاس ١٨٠ سم وخزانة ملابس بعرض ٢٠٠ سم. تضمن الشركة جودة الخشب لمدة ٥ سنوات ضد عيوب التصنيع، مع توفير خدمة التركيب المجاني في القاهرة والجيزة.

======================================================================
TEST EXAMPLE 9
======================================================================

Test ID: 6877-0
Question: أريد معرفة الفرق بين نجم 10 ونجم 12 بسرعة! لماذا السعر مختلف بهذا الشكل وما هي سعة الذاكرة في كل منهما؟ أنا مستعجل جداً!
Gold chunk IDs: [0]

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8901 | ID 5269-3 | Chunk 2
Text: هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

Rank 2 | Score 0.8901 | ID 5269-2 | Chunk 2
Text: هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

Rank 3 | Score 0.8901 | ID 5269-1 | Chunk 2
Text: هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

Rank 4 | Score 0.8901 | ID 5269-0 | Chunk 2
Text: هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

Rank 5 | Score 0.8612 | ID 4285-3 | Chunk 0
Text: توفر شركة رفاه هاتف 'نجم 10' بسعر 450,000 دينار عراقي، ويتميز بذاكرة 128 جيجابايت وكاميرا بدقة 50 ميجابكسل. أما هاتف 'نجم 11' فيتوفر بسعر 600,000 دينار عراقي، ويأتي بذاكرة 256 جيجابايت وكاميرا بدقة 108 ميجابكسل.

----------------------------------------------------------------------
NEAREST TRAIN SEMANTIC MATCH TO GOLD
----------------------------------------------------------------------

Best similarity: 0.9623
Train ID: 5269-0
Train chunk index: 2
Train chunk text: هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

======================================================================
TEST EXAMPLE 10
======================================================================

Test ID: 6877-1
Question: تبديل منتج تالف. الشروط؟
Gold chunk IDs: []

Top-5 retrieved:
----------------------------------------------------------------------

Rank 1 | Score 0.8601 | ID 3914-2 | Chunk 5
Text: إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال 72 ساعة، ويتم استبدال القطعة التالفة مجاناً خلال 10 أيام عمل.

Rank 2 | Score 0.8601 | ID 3914-1 | Chunk 5
Text: إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال 72 ساعة، ويتم استبدال القطعة التالفة مجاناً خلال 10 أيام عمل.

Rank 3 | Score 0.8601 | ID 3914-0 | Chunk 5

In [21]:
# ============================================================
# STEP 6A — INDEPENDENT PROXY TARGET VALIDATION
# Exact Normalized Match + TF-IDF Character N-Gram Matching
# ============================================================

import re
import unicodedata
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel


print("=" * 70)
print("STEP 6A — INDEPENDENT PROXY TARGET VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Normalize Arabic text
# ------------------------------------------------------------

def normalize_arabic_text(text):
    """
    Conservative normalization for textual matching.
    Does NOT use E5 embeddings.
    """

    if pd.isna(text):
        return ""

    text = str(text)

    # Unicode normalization
    text = unicodedata.normalize("NFKC", text)

    # Remove Arabic diacritics / tashkeel
    text = re.sub(r"[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]", "", text)

    # Normalize common Arabic letter variants
    text = re.sub(r"[إأآٱ]", "ا", text)
    text = re.sub(r"ى", "ي", text)
    text = re.sub(r"ة", "ه", text)

    # Remove tatweel
    text = text.replace("ـ", "")

    # Normalize whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text


# ------------------------------------------------------------
# 2. Build Train chunk lookup
# ------------------------------------------------------------

print("\n[1/5] Preparing Train chunk lookup...")

train_chunk_texts = train_chunks["chunk_text"].fillna("").astype(str).tolist()

train_normalized = [
    normalize_arabic_text(x)
    for x in train_chunk_texts
]

# normalized text -> list of Train corpus positions
normalized_lookup = {}

for idx, text in enumerate(train_normalized):
    if text:
        normalized_lookup.setdefault(text, []).append(idx)

print(f"Train chunks: {len(train_chunk_texts):,}")
print(f"Unique normalized chunk texts: {len(normalized_lookup):,}")


# ------------------------------------------------------------
# 3. Collect Test gold chunks
# ------------------------------------------------------------

print("\n[2/5] Collecting Test gold chunks...")

gold_records = []

for row_idx, row in test_df.reset_index(drop=True).iterrows():

    gold_ids = row["gold_chunk_ids"]

    if gold_ids is None:
        continue

    if isinstance(gold_ids, float) and np.isnan(gold_ids):
        continue

    # Ensure list-like behavior
    if not isinstance(gold_ids, (list, tuple, np.ndarray)):
        continue

    chunks = row["chunks"]

    for chunk_idx in gold_ids:

        chunk_idx = int(chunk_idx)

        if chunk_idx < 0 or chunk_idx >= len(chunks):
            continue

        gold_records.append({
            "test_row_idx": row_idx,
            "test_id": row["id"],
            "gold_chunk_idx": chunk_idx,
            "gold_text": str(chunks[chunk_idx]),
        })


gold_df = pd.DataFrame(gold_records)

print(f"Answerable Test rows: {test_df['answerable'].sum():,}")
print(f"Test gold chunks collected: {len(gold_df):,}")


# ------------------------------------------------------------
# 4. Exact normalized matching
# ------------------------------------------------------------

print("\n[3/5] Checking normalized exact matches...")

gold_df["gold_normalized"] = gold_df["gold_text"].map(normalize_arabic_text)

gold_df["exact_match_count"] = gold_df["gold_normalized"].map(
    lambda x: len(normalized_lookup.get(x, []))
)

gold_df["has_exact_match"] = gold_df["exact_match_count"] > 0

exact_count = int(gold_df["has_exact_match"].sum())
total_gold = len(gold_df)

print(f"Exact normalized matches : {exact_count:,}/{total_gold:,}")

if total_gold > 0:
    print(f"Exact match coverage     : {exact_count / total_gold:.2%}")


# ------------------------------------------------------------
# 5. Independent lexical similarity using TF-IDF
# ------------------------------------------------------------

print("\n[4/5] Building independent TF-IDF character n-gram index...")

# Character n-grams are chosen because they are relatively robust
# to Arabic morphology, spacing and small spelling variations.
vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3, 5),
    min_df=2,
    max_features=300_000,
    sublinear_tf=True,
    dtype=np.float32
)

train_tfidf = vectorizer.fit_transform(train_normalized)

print(f"TF-IDF matrix shape: {train_tfidf.shape}")
print(f"TF-IDF matrix dtype : {train_tfidf.dtype}")


# ------------------------------------------------------------
# 6. Match each unique Test gold text independently
# ------------------------------------------------------------

print("\n[5/5] Finding top lexical matches...")

unique_gold = gold_df[
    ["gold_normalized"]
].drop_duplicates().reset_index(drop=True)

gold_tfidf = vectorizer.transform(
    unique_gold["gold_normalized"].tolist()
)

# Sparse matrix multiplication.
# This is lexical similarity only; E5 is NOT involved.
similarity_matrix = linear_kernel(
    gold_tfidf,
    train_tfidf,
    dense_output=True
)

top1_indices = similarity_matrix.argmax(axis=1)
top1_scores = similarity_matrix.max(axis=1)

unique_gold["lexical_top1_corpus_idx"] = top1_indices
unique_gold["lexical_top1_score"] = top1_scores


# Map back to gold_df
gold_df = gold_df.merge(
    unique_gold,
    on="gold_normalized",
    how="left"
)


# ------------------------------------------------------------
# 7. Recover metadata of top lexical Train matches
# ------------------------------------------------------------

gold_df["train_match_row_idx"] = gold_df["lexical_top1_corpus_idx"].map(
    lambda x: train_chunks.iloc[int(x)]["row_idx"]
)

gold_df["train_match_id"] = gold_df["lexical_top1_corpus_idx"].map(
    lambda x: train_chunks.iloc[int(x)]["id"]
)

gold_df["train_match_chunk_idx"] = gold_df["lexical_top1_corpus_idx"].map(
    lambda x: train_chunks.iloc[int(x)]["chunk_idx"]
)

gold_df["train_match_text"] = gold_df["lexical_top1_corpus_idx"].map(
    lambda x: train_chunks.iloc[int(x)]["chunk_text"]
)


# ------------------------------------------------------------
# 8. Diagnostic summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 6A DIAGNOSTIC SUMMARY")
print("=" * 70)

print(f"Total Test gold chunks       : {len(gold_df):,}")
print(f"Normalized exact matches     : {gold_df['has_exact_match'].sum():,}")

print(
    f"Exact normalized coverage    : "
    f"{gold_df['has_exact_match'].mean():.2%}"
)

print(
    f"TF-IDF top-1 mean similarity  : "
    f"{gold_df['lexical_top1_score'].mean():.4f}"
)

print(
    f"TF-IDF top-1 median similarity: "
    f"{gold_df['lexical_top1_score'].median():.4f}"
)

print(
    f"TF-IDF top-1 minimum          : "
    f"{gold_df['lexical_top1_score'].min():.4f}"
)

print(
    f"TF-IDF top-1 maximum          : "
    f"{gold_df['lexical_top1_score'].max():.4f}"
)


# ------------------------------------------------------------
# 9. Score distribution
# ------------------------------------------------------------

print("\nTF-IDF similarity quantiles:")

print(
    gold_df["lexical_top1_score"]
    .quantile([0.00, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 1.00])
    .round(4)
    .to_string()
)


# ------------------------------------------------------------
# 10. Show weakest lexical mappings
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LOWEST-CONFIDENCE LEXICAL MAPPINGS")
print("=" * 70)

weakest = (
    gold_df[
        [
            "test_id",
            "gold_chunk_idx",
            "lexical_top1_score",
            "gold_text",
            "train_match_id",
            "train_match_chunk_idx",
            "train_match_text"
        ]
    ]
    .sort_values("lexical_top1_score", ascending=True)
    .head(10)
)

pd.set_option("display.max_colwidth", 220)

for _, r in weakest.iterrows():

    print("\n" + "-" * 70)

    print(
        f"Test ID          : {r['test_id']}\n"
        f"Gold chunk       : {r['gold_chunk_idx']}\n"
        f"TF-IDF similarity : {r['lexical_top1_score']:.4f}\n"
        f"Train ID          : {r['train_match_id']}\n"
        f"Train chunk       : {r['train_match_chunk_idx']}"
    )

    print(f"\nTEST GOLD:\n{r['gold_text']}")

    print(f"\nTRAIN TOP-1:\n{r['train_match_text']}")


# ------------------------------------------------------------
# 11. Keep diagnostic dataframe available
# ------------------------------------------------------------

step6a_proxy_df = gold_df.copy()

print("\n" + "=" * 70)
print("Step 6A completed.")
print("Diagnostic dataframe: step6a_proxy_df")
print("NO official retrieval metrics calculated.")
print("=" * 70)

======================================================================
STEP 6A — INDEPENDENT PROXY TARGET VALIDATION
======================================================================

[1/5] Preparing Train chunk lookup...
Train chunks: 164,456
Unique normalized chunk texts: 41,179

[2/5] Collecting Test gold chunks...
Answerable Test rows: 446
Test gold chunks collected: 465

[3/5] Checking normalized exact matches...
Exact normalized matches : 0/465
Exact match coverage     : 0.00%

[4/5] Building independent TF-IDF character n-gram index...
TF-IDF matrix shape: (164456, 192451)
TF-IDF matrix dtype : float32

[5/5] Finding top lexical matches...

======================================================================
STEP 6A DIAGNOSTIC SUMMARY
======================================================================
Total Test gold chunks       : 465
Normalized exact matches     : 0
Exact normalized coverage    : 0.00%
TF-IDF top-1 mean similarity  : 0.5921
TF-IDF top-1 median similarity: 0.5954
TF-IDF top-1 minimum          : 0.1977
TF-IDF top-1 maximum          : 0.9645

TF-IDF similarity quantiles:
0.00    0.1977
0.05    0.3590
0.10    0.3934
0.25    0.4732
0.50    0.5954
0.75    0.6921
0.90    0.7919
0.95    0.8624
1.00    0.9645

======================================================================
LOWEST-CONFIDENCE LEXICAL MAPPINGS
======================================================================

----------------------------------------------------------------------
Test ID          : 6952-3
Gold chunk       : 3
TF-IDF similarity : 0.1977
Train ID          : 6432-0
Train chunk       : 2

TEST GOLD:
تطرح الشركة باقة 'تأثيث المنزل الكامل' بسعر 2500 دينار أردني، وتتضمن غرفة نوم رئيسية وطقم جلوس من 5 قطع وطاولة طعام. تمنح هذه الباقة العميل خصماً إضافياً بنسبة 5% عند الدفع النقدي الفوري.

TRAIN TOP-1:
تتوفر باقة 'التأثيث المتكامل' للمنازل الجديدة بسعر 25,000 درهم مغربي، وتشمل طقم أريكة من الجلد الطبيعي، وطاولة طعام خشبية لستة أشخاص، وسرير قياس 180*200 سم. يضمن هذا العرض توصيلاً وتركيباً مجانياً خلال 7 أيام عمل.

----------------------------------------------------------------------
Test ID          : 6914-2
Gold chunk       : 2
TF-IDF similarity : 0.2370
Train ID          : 4652-0
Train chunk       : 3

TEST GOLD:
توفر المجموعة خدمة 'التمريض المنزلي' بنظام الساعات، حيث تبلغ تكلفة الساعة الواحدة 25 دينار كويتي. يتم دفع الرسوم مسبقاً، وفي حال طلب الخدمة لمدة تزيد عن 10 ساعات أسبوعياً، يتم تقديم خصم إجمالي قدره 10% على قيمة الفاتورة الأسبوعية.

TRAIN TOP-1:
تتوفر خدمات التدريب الشخصي المكثف بنظام الساعات، حيث تبلغ تكلفة الساعة الواحدة 15 ريالاً عمانياً، ويتم حجز المواعيد مسبقاً قبل 24 ساعة على الأقل لضمان توفر المدرب المطلوب.

----------------------------------------------------------------------
Test ID          : 6876-1
Gold chunk       : 2
TF-IDF similarity : 0.2442
Train ID          : 5198-0
Train chunk       : 6

TEST GOLD:
يتوفر لدى المؤسسة طاولات طعام 'مزيون' الرخامية بسعر ٢٨٠ ريال عماني. تتسع الطاولة لـ٦ أشخاص وطولها ١٨٠ سم. في حال وجود خدوش في الرخام عند الاستلام، يجب إبلاغ خدمة العملاء خلال ٢٤ ساعة لترتيب عملية استبدال السطح الرخامي مجاناً.

TRAIN TOP-1:
تتوفر لدينا مجموعة من طاولات الطعام الرخامية بمقاسات مختلفة، حيث يبدأ سعر الطاولة الدائرية من 200 دينار بحريني، بينما تصل أسعار الطاولات المستطيلة الكبيرة إلى 600 دينار بحريني حسب نوع الرخام المستخدم.

----------------------------------------------------------------------
Test ID          : 6923-1
Gold chunk       : 2
TF-IDF similarity : 0.2720
Train ID          : 6874-0
Train chunk       : 2

TEST GOLD:
تتوفر باقة 'العطلة العائلية' بسعر 180 ريال عماني لليلتين. تتضمن الباقة غرفة واسعة بثلاثة أسرة، ودخولاً مجانياً لمدينة الألعاب المائية بالفندق، وخصماً بنسبة 15% على جميع وجبات الغداء والعشاء في مطعم الفندق الرئيسي.

TRAIN TOP-1:
تتضمن عضوية 'النخبة' الذهبية ميزات خاصة تشمل ترقية مجانية للغرفة عند التوفر، وخصماً بنسبة 15% على خدمات السبا والمساج، وخصماً بنسبة 10% على وجبات العشاء في مطعم الفندق الرئيسي، وتجدد العضوية سنوياً بمبلغ 50 ديناراً أردنياً.

----------------------------------------------------------------------
Test ID          : 6940-0
Gold chunk       : 3
TF-IDF similarity : 0.2887
Train ID          : 1245-0
Train chunk       : 4

TEST GOLD:
تطبق المجموعة سياسة استرداد الأموال للعمليات الجراحية الملغاة لأسباب طبية طارئة؛ حيث يتم استرجاع 90% من المبلغ المدفوع مسبقاً خلال 10 أيام عمل. أما الإلغاء لأسباب شخصية فيؤدي إلى استرداد 50% فقط من القيمة المالية خلال 15 يوماً عمل.

TRAIN TOP-1:
تطبق سياسة استرداد الأموال في حال تعذر تركيب الخدمة لأسباب تقنية، حيث يتم استرجاع 100% من الرسوم المدفوعة خلال 7 أيام عمل عبر التحويل البنكي.

----------------------------------------------------------------------
Test ID          : 6940-2
Gold chunk       : 4
TF-IDF similarity : 0.2932
Train ID          : 6759-0
Train chunk       : 0

TEST GOLD:
تتوفر خدمة التمريض المنزلي بنظام الباقات الشهرية؛ باقة 'العناية الأساسية' تبلغ تكلفتها 600 دينار تونسي شهرياً وتتضمن زيارتين أسبوعياً. باقة 'العناية المكثفة' تبلغ تكلفتها 1100 دينار تونسي شهرياً وتتضمن زيارة يومية طوال أيام الأسبوع.

TRAIN TOP-1:
تقدم مصحات الشفاء باقتين للرعاية الصحية المنزلية: الباقة الفضية بسعر 150 دينار تونسياً وتتضمن زيارتين طبيتين في الشهر، والباقة الذهبية بسعر 300 دينار تونسياً وتتضمن خمس زيارات طبية مع متابعة تمريضية يومية لمدة أسبوع.

----------------------------------------------------------------------
Test ID          : 6993-1
Gold chunk       : 1
TF-IDF similarity : 0.3031
Train ID          : 821-0
Train chunk       : 1

TEST GOLD:
تتضمن باقة 'الماسية' تغطية شاملة بنسبة ١٠٠٪ لجميع الخدمات الطبية، وتكلفتها السنوية ١٢,٠٠٠ جنيه مصري. تمنح هذه الباقة العميل إمكانية إجراء فحص طبي شامل مرتين في السنة مجاناً، وتغطي تكاليف الإقامة في المستشفيات دون سقف مالي محدد.

TRAIN TOP-1:
تقدم باقة 'الماسية الشاملة' أعلى سقف تغطية سنوي بقيمة ١٥٠,٠٠٠ جنيه مصري. تشمل هذه الباقة تغطية كاملة للأدوية بنسبة ١٠٠٪، وخدمة التوصيل المنزلي للأدوية المزمنة مجانًا، مع إمكانية إجراء الفحوصات الدورية الشاملة مرتين في العام الواحد.

----------------------------------------------------------------------
Test ID          : 6935-2
Gold chunk       : 1
TF-IDF similarity : 0.3063
Train ID          : 3486-0
Train chunk       : 0

TEST GOLD:
تتيح باقة 'أرزة الأساسية' تغطية بنسبة ٦٠٪ من المصاريف الطبية، بسقف سنوي قدره ٤٠ مليون ليرة لبنانية. تكلفة الاشتراك السنوي هي ٢ مليون ليرة لبنانية، وتشمل هذه الباقة تغطية محدودة للأدوية المزمنة بحد أقصى ٥٠٠ ألف ليرة لبنانية سنوياً.

TRAIN TOP-1:
تقدم باقة 'الرعاية الأساسية' تغطية صحية شاملة بسعر سنوي قدره ٥٠٠,٠٠٠ ليرة لبنانية. تشمل هذه الباقة زيارات غير محدودة لأطباء الأسرة، وتغطية بنسبة ٢٠٪ من تكاليف الأدوية الموصوفة، وحد أقصى للتعويض السنوي قدره ٢,٠٠٠,٠٠٠ ليرة لبنانية.

----------------------------------------------------------------------
Test ID          : 6945-1
Gold chunk       : 2
TF-IDF similarity : 0.3250
Train ID          : 1790-0
Train chunk       : 5

TEST GOLD:
تتوفر باقة الدعم الفني 'الذهبية' بسعر 150 درهماً سنوياً، وتوفر زيارتين منزلتين في السنة. أما باقة 'البلاتينية' فبسعر 300 درهم سنوياً وتوفر 5 زيارات منزلية في السنة.

TRAIN TOP-1:
تتوفر باقة الدعم التقني الذهبية بسعر 25 ريال عماني سنوياً، وتوفر زيارتين منزليتين للصيانة في العام الواحد. بينما توفر الباقة الفضية زيارة واحدة فقط بسعر 15 ريال عماني سنوياً.

----------------------------------------------------------------------
Test ID          : 6921-2
Gold chunk       : 3
TF-IDF similarity : 0.3274
Train ID          : 353-0
Train chunk       : 5

TEST GOLD:
لحل مشكلة تجميد الحساب بسبب إدخال كلمة المرور خاطئة 3 مرات متتالية، يجب على العميل تحديث بياناته عبر التطبيق باستخدام النفاذ الوطني الموحد، أو زيارة الفرع مع إبراز الهوية الوطنية لتفعيل الحساب خلال 24 ساعة.

TRAIN TOP-1:
لضمان أمن الحسابات، يتم تجميد أي محفظة إلكترونية في حال إدخال رمز المرور بشكل خاطئ 5 مرات متتالية، ويتطلب إلغاء التجميد زيارة أقرب مركز خدمة مع إبراز الهوية الوطنية.

======================================================================
Step 6A completed.
Diagnostic dataframe: step6a_proxy_df
NO official retrieval metrics calculated.
======================================================================

In [24]:
# ============================================================
# STEP 6B — FIXED FINAL VERSION
# Conservative Proxy Mapping Validation
# ============================================================

print("=" * 70)
print("STEP 6B — FIXED FINAL VERSION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Start from Step 6A output
# ------------------------------------------------------------

proxy = step6a_proxy_df.copy()

print(f"\nStep 6A records: {len(proxy):,}")


# ------------------------------------------------------------
# 2. Add Test metadata directly by row index
# ------------------------------------------------------------

test_meta = test_df.reset_index(drop=True)

proxy["test_domain"] = proxy["test_row_idx"].map(
    test_meta["domain"]
)

proxy["test_country"] = proxy["test_row_idx"].map(
    test_meta["country"]
)

proxy["test_question_type"] = proxy["test_row_idx"].map(
    test_meta["question_type"]
)

proxy["test_answerable"] = proxy["test_row_idx"].map(
    test_meta["answerable"]
)


# ------------------------------------------------------------
# 3. Build exact Train corpus lookup
# ------------------------------------------------------------

train_lookup = train_chunks.reset_index().rename(
    columns={"index": "corpus_idx"}
)[
    [
        "corpus_idx",
        "row_idx",
        "chunk_idx",
        "id",
        "domain",
        "country",
        "question",
        "chunk_text"
    ]
].copy()

train_lookup = train_lookup.rename(
    columns={
        "row_idx": "candidate_row_idx",
        "chunk_idx": "candidate_chunk_idx",
        "id": "candidate_id",
        "domain": "candidate_domain",
        "country": "candidate_country",
        "question": "candidate_question",
        "chunk_text": "candidate_text"
    }
)


# ------------------------------------------------------------
# 4. Remove old candidate metadata if present
# ------------------------------------------------------------

columns_to_remove = [
    "train_match_id",
    "train_match_chunk_idx",
    "train_match_row_idx",
    "train_domain",
    "train_country",
    "train_question",
    "train_match_text",
    "corpus_idx"
]

proxy = proxy.drop(
    columns=[
        c for c in columns_to_remove
        if c in proxy.columns
    ],
    errors="ignore"
)


# ------------------------------------------------------------
# 5. Attach exact candidate metadata
# ------------------------------------------------------------

proxy = proxy.merge(
    train_lookup,
    left_on="lexical_top1_corpus_idx",
    right_on="corpus_idx",
    how="left",
    validate="many_to_one"
)

print(f"Records after candidate lookup: {len(proxy):,}")

assert len(proxy) == len(step6a_proxy_df)

print("✓ Record count preserved: 465")


# ------------------------------------------------------------
# 6. Independent metadata consistency
# ------------------------------------------------------------

proxy["same_domain"] = (
    proxy["test_domain"] == proxy["candidate_domain"]
)

proxy["same_country"] = (
    proxy["test_country"] == proxy["candidate_country"]
)


# ------------------------------------------------------------
# 7. Conservative proxy reliability
# ------------------------------------------------------------

score = proxy["lexical_top1_score"]

proxy["proxy_reliable"] = (
    (score >= 0.85)
    |
    (
        (score >= 0.70)
        & proxy["same_domain"]
    )
    |
    (
        (score >= 0.50)
        & proxy["same_domain"]
        & proxy["same_country"]
    )
)


# ------------------------------------------------------------
# 8. Main summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("CONSERVATIVE PROXY SUMMARY")
print("=" * 70)

print(
    f"Total Test gold chunks          : "
    f"{len(proxy):,}"
)

print(
    f"Same domain                     : "
    f"{proxy['same_domain'].sum():,} "
    f"({proxy['same_domain'].mean():.2%})"
)

print(
    f"Same country                    : "
    f"{proxy['same_country'].sum():,} "
    f"({proxy['same_country'].mean():.2%})"
)

print(
    f"Conservative reliable mappings  : "
    f"{proxy['proxy_reliable'].sum():,} "
    f"({proxy['proxy_reliable'].mean():.2%})"
)


# ------------------------------------------------------------
# 9. Similarity bands
# ------------------------------------------------------------

proxy["similarity_band"] = pd.cut(
    proxy["lexical_top1_score"],
    bins=[
        -np.inf,
        0.30,
        0.40,
        0.50,
        0.60,
        0.70,
        0.80,
        0.90,
        np.inf
    ],
    labels=[
        "<0.30",
        "0.30-0.40",
        "0.40-0.50",
        "0.50-0.60",
        "0.60-0.70",
        "0.70-0.80",
        "0.80-0.90",
        ">=0.90"
    ]
)

band_summary = (
    proxy
    .groupby("similarity_band", observed=False)
    .agg(
        count=("lexical_top1_score", "size"),
        same_domain=("same_domain", "sum"),
        reliable=("proxy_reliable", "sum")
    )
)

band_summary["same_domain_pct"] = (
    band_summary["same_domain"]
    / band_summary["count"]
)

band_summary["reliable_pct"] = (
    band_summary["reliable"]
    / band_summary["count"]
)

print("\nSimilarity bands:")
print(
    band_summary.round(3).to_string()
)


# ------------------------------------------------------------
# 10. Strongest mappings
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STRONGEST MAPPINGS")
print("=" * 70)

strongest = (
    proxy[
        [
            "test_id",
            "gold_chunk_idx",
            "lexical_top1_score",
            "same_domain",
            "same_country",
            "candidate_id",
            "candidate_chunk_idx"
        ]
    ]
    .sort_values(
        "lexical_top1_score",
        ascending=False
    )
    .head(5)
)

print(
    strongest.to_string(index=False)
)


# ------------------------------------------------------------
# 11. Weakest mappings
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("WEAKEST MAPPINGS")
print("=" * 70)

weakest = (
    proxy[
        [
            "test_id",
            "gold_chunk_idx",
            "lexical_top1_score",
            "same_domain",
            "same_country",
            "candidate_id",
            "candidate_chunk_idx",
            "gold_text",
            "candidate_text"
        ]
    ]
    .sort_values(
        "lexical_top1_score",
        ascending=True
    )
    .head(5)
)

for _, r in weakest.iterrows():

    print("\n" + "-" * 70)

    print(
        f"Test ID          : {r['test_id']}\n"
        f"Gold chunk       : {r['gold_chunk_idx']}\n"
        f"TF-IDF similarity : {r['lexical_top1_score']:.4f}\n"
        f"Same domain       : {r['same_domain']}\n"
        f"Same country      : {r['same_country']}\n"
        f"Train ID          : {r['candidate_id']}\n"
        f"Train chunk       : {r['candidate_chunk_idx']}"
    )

    print(f"\nTEST GOLD:\n{r['gold_text']}")

    print(f"\nTRAIN CANDIDATE:\n{r['candidate_text']}")


# ------------------------------------------------------------
# 12. Save final Step 6B dataframe
# ------------------------------------------------------------

step6b_proxy_df = proxy.copy()

print("\n" + "=" * 70)
print("STEP 6B COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    "Diagnostic dataframe: step6b_proxy_df"
)

print(
    "NO official retrieval metrics calculated."
)

======================================================================
STEP 6B — FIXED FINAL VERSION
======================================================================

Step 6A records: 465
Records after candidate lookup: 465
✓ Record count preserved: 465

======================================================================
CONSERVATIVE PROXY SUMMARY
======================================================================
Total Test gold chunks          : 465
Same domain                     : 383 (82.37%)
Same country                    : 194 (41.72%)
Conservative reliable mappings  : 174 (37.42%)

Similarity bands:
                 count  same_domain  reliable  same_domain_pct  reliable_pct
similarity_band
<0.30                6            4         0            0.667         0.000
0.30-0.40           47           34         0            0.723         0.000
0.40-0.50           86           68         0            0.791         0.000
0.50-0.60          102           84        33            0.824         0.324
0.60-0.70          117           97        43            0.829         0.368
0.70-0.80           65           58        58            0.892         0.892
0.80-0.90           33           30        31            0.909         0.939
>=0.90               9            8         9            0.889         1.000

======================================================================
STRONGEST MAPPINGS
======================================================================
test_id  gold_chunk_idx  lexical_top1_score  same_domain  same_country candidate_id  candidate_chunk_idx
 6918-1               0            0.964533         True          True       4880-0                    0
 6949-3               2            0.957465         True         False       4978-0                    3
 6947-1               1            0.941770         True          True        121-0                    4
 6974-1               1            0.938649        False         False        815-0                    2
 6899-1               0            0.937311         True          True       3256-0                    0

======================================================================
WEAKEST MAPPINGS
======================================================================

----------------------------------------------------------------------
Test ID          : 6952-3
Gold chunk       : 3
TF-IDF similarity : 0.1977
Same domain       : True
Same country      : False
Train ID          : 6432-0
Train chunk       : 2

TEST GOLD:
تطرح الشركة باقة 'تأثيث المنزل الكامل' بسعر 2500 دينار أردني، وتتضمن غرفة نوم رئيسية وطقم جلوس من 5 قطع وطاولة طعام. تمنح هذه الباقة العميل خصماً إضافياً بنسبة 5% عند الدفع النقدي الفوري.

TRAIN CANDIDATE:
تتوفر باقة 'التأثيث المتكامل' للمنازل الجديدة بسعر 25,000 درهم مغربي، وتشمل طقم أريكة من الجلد الطبيعي، وطاولة طعام خشبية لستة أشخاص، وسرير قياس 180*200 سم. يضمن هذا العرض توصيلاً وتركيباً مجانياً خلال 7 أيام عمل.

----------------------------------------------------------------------
Test ID          : 6914-2
Gold chunk       : 2
TF-IDF similarity : 0.2370
Same domain       : False
Same country      : False
Train ID          : 4652-0
Train chunk       : 3

TEST GOLD:
توفر المجموعة خدمة 'التمريض المنزلي' بنظام الساعات، حيث تبلغ تكلفة الساعة الواحدة 25 دينار كويتي. يتم دفع الرسوم مسبقاً، وفي حال طلب الخدمة لمدة تزيد عن 10 ساعات أسبوعياً، يتم تقديم خصم إجمالي قدره 10% على قيمة الفاتورة الأسبوعية.

TRAIN CANDIDATE:
تتوفر خدمات التدريب الشخصي المكثف بنظام الساعات، حيث تبلغ تكلفة الساعة الواحدة 15 ريالاً عمانياً، ويتم حجز المواعيد مسبقاً قبل 24 ساعة على الأقل لضمان توفر المدرب المطلوب.

----------------------------------------------------------------------
Test ID          : 6876-1
Gold chunk       : 2
TF-IDF similarity : 0.2442
Same domain       : True
Same country      : False
Train ID          : 5198-0
Train chunk       : 6

TEST GOLD:
يتوفر لدى المؤسسة طاولات طعام 'مزيون' الرخامية بسعر ٢٨٠ ريال عماني. تتسع الطاولة لـ٦ أشخاص وطولها ١٨٠ سم. في حال وجود خدوش في الرخام عند الاستلام، يجب إبلاغ خدمة العملاء خلال ٢٤ ساعة لترتيب عملية استبدال السطح الرخامي مجاناً.

TRAIN CANDIDATE:
تتوفر لدينا مجموعة من طاولات الطعام الرخامية بمقاسات مختلفة، حيث يبدأ سعر الطاولة الدائرية من 200 دينار بحريني، بينما تصل أسعار الطاولات المستطيلة الكبيرة إلى 600 دينار بحريني حسب نوع الرخام المستخدم.

----------------------------------------------------------------------
Test ID          : 6923-1
Gold chunk       : 2
TF-IDF similarity : 0.2720
Same domain       : True
Same country      : False
Train ID          : 6874-0
Train chunk       : 2

TEST GOLD:
تتوفر باقة 'العطلة العائلية' بسعر 180 ريال عماني لليلتين. تتضمن الباقة غرفة واسعة بثلاثة أسرة، ودخولاً مجانياً لمدينة الألعاب المائية بالفندق، وخصماً بنسبة 15% على جميع وجبات الغداء والعشاء في مطعم الفندق الرئيسي.

TRAIN CANDIDATE:
تتضمن عضوية 'النخبة' الذهبية ميزات خاصة تشمل ترقية مجانية للغرفة عند التوفر، وخصماً بنسبة 15% على خدمات السبا والمساج، وخصماً بنسبة 10% على وجبات العشاء في مطعم الفندق الرئيسي، وتجدد العضوية سنوياً بمبلغ 50 ديناراً أردنياً.

----------------------------------------------------------------------
Test ID          : 6940-0
Gold chunk       : 3
TF-IDF similarity : 0.2887
Same domain       : False
Same country      : False
Train ID          : 1245-0
Train chunk       : 4

TEST GOLD:
تطبق المجموعة سياسة استرداد الأموال للعمليات الجراحية الملغاة لأسباب طبية طارئة؛ حيث يتم استرجاع 90% من المبلغ المدفوع مسبقاً خلال 10 أيام عمل. أما الإلغاء لأسباب شخصية فيؤدي إلى استرداد 50% فقط من القيمة المالية خلال 15 يوماً عمل.

TRAIN CANDIDATE:
تطبق سياسة استرداد الأموال في حال تعذر تركيب الخدمة لأسباب تقنية، حيث يتم استرجاع 100% من الرسوم المدفوعة خلال 7 أيام عمل عبر التحويل البنكي.

======================================================================
STEP 6B COMPLETED SUCCESSFULLY
======================================================================
Diagnostic dataframe: step6b_proxy_df
NO official retrieval metrics calculated.

In [25]:
# ============================================================
# STEP 6C — OFFICIAL RETRIEVAL EVALUATION
# Train-only FAISS + Test Queries
# ============================================================

import numpy as np
import pandas as pd
import time

print("=" * 70)
print("STEP 6C — OFFICIAL RETRIEVAL EVALUATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Validate required objects from previous steps
# ------------------------------------------------------------

assert "model" in globals(), "Embedding model is missing."
assert "index" in globals(), "FAISS index is missing."
assert "train_chunks" in globals(), "Train corpus is missing."
assert "test_df" in globals(), "Test dataframe is missing."

print("\n[1/5] Validating existing retrieval components...")

print(f"FAISS vectors : {index.ntotal:,}")
print(f"Train chunks  : {len(train_chunks):,}")
print(f"Test rows     : {len(test_df):,}")
print(f"Index dim     : {index.d}")

assert index.ntotal == len(train_chunks)
assert index.d == 768

print("✓ Existing model, corpus and FAISS index validated.")
print("✓ No rebuilding / re-embedding will be performed.")


# ------------------------------------------------------------
# 2. Prepare Test queries
# ------------------------------------------------------------

print("\n[2/5] Encoding Test queries...")

test_queries = (
    "query: " +
    test_df["question"].astype(str)
).tolist()

start_time = time.time()

test_query_embeddings = model.encode(
    test_queries,
    batch_size=32,
    convert_to_numpy=True,
    normalize_embeddings=True,
    show_progress_bar=True
)

elapsed = time.time() - start_time

print(f"\nQuery embedding shape: {test_query_embeddings.shape}")
print(f"Encoding time: {elapsed:.2f} seconds")

assert test_query_embeddings.shape == (len(test_df), 768)
assert test_query_embeddings.dtype == np.float32

query_norms = np.linalg.norm(test_query_embeddings, axis=1)

print(
    "Query norm range:",
    f"{query_norms.min():.4f} → {query_norms.max():.4f}"
)

assert np.allclose(query_norms, 1.0, atol=1e-5)

print("✓ Test queries encoded successfully.")
print("✓ Query embeddings are normalized.")


# ------------------------------------------------------------
# 3. Retrieve Top-K from TRAIN ONLY
# ------------------------------------------------------------

print("\n[3/5] Running Train-only FAISS retrieval...")

K = 10

start_time = time.time()

scores, indices = index.search(
    test_query_embeddings,
    K
)

elapsed = time.time() - start_time

print(f"Top-K: {K}")
print(f"Search time: {elapsed:.4f} seconds")
print(f"Score matrix shape: {scores.shape}")
print(f"Index matrix shape: {indices.shape}")

assert scores.shape == (len(test_df), K)
assert indices.shape == (len(test_df), K)

print("✓ Retrieval completed.")
print("✓ Only TRAIN vectors were searched.")


# ------------------------------------------------------------
# 4. Build evaluation dataframe
# ------------------------------------------------------------

print("\n[4/5] Building evaluation records...")

evaluation_records = []

for test_idx in range(len(test_df)):

    row = test_df.iloc[test_idx]

    retrieved_indices = indices[test_idx]
    retrieved_scores = scores[test_idx]

    retrieved_items = []

    for rank, (corpus_idx, score) in enumerate(
        zip(retrieved_indices, retrieved_scores),
        start=1
    ):

        corpus_idx = int(corpus_idx)

        if corpus_idx < 0:
            continue

        candidate = train_chunks.iloc[corpus_idx]

        retrieved_items.append({
            "rank": rank,
            "corpus_idx": corpus_idx,
            "score": float(score),
            "id": candidate["id"],
            "chunk_idx": int(candidate["chunk_idx"]),
            "row_idx": int(candidate["row_idx"]),
            "domain": candidate["domain"],
            "country": candidate["country"],
            "company": candidate["company"],
            "chunk_text": candidate["chunk_text"]
        })

    evaluation_records.append({
        "test_idx": test_idx,
        "test_id": row["id"],
        "question": row["question"],
        "answerable": bool(row["answerable"]),
        "gold_chunk_ids": list(row["gold_chunk_ids"]),
        "retrieved": retrieved_items
    })


# ------------------------------------------------------------
# 5. Official retrieval metrics
# ------------------------------------------------------------

print("\n[5/5] Calculating retrieval metrics...")


def unique_record_ids(retrieved):
    """
    Remove duplicated chunks belonging to the same record.
    This is important because the dataset contains repeated
    chunks across related records.
    """
    seen = set()
    result = []

    for item in retrieved:
        record_id = item["id"]

        if record_id not in seen:
            seen.add(record_id)
            result.append(item)

    return result


def evaluate_retrieval(records, k):
    """
    Evaluate retrieval against the Test question's gold chunk IDs.

    Important:
    Test gold chunks are NOT in the Train FAISS index.

    Therefore, exact gold-chunk Recall@K is structurally impossible
    under the Train-only setup.

    We instead report:
    - retrieval score statistics
    - answerable / unanswerable behavior
    - top-k semantic retrieval diagnostics

    No fabricated exact Recall is calculated.
    """

    answerable_records = [
        r for r in records if r["answerable"]
    ]

    unanswerable_records = [
        r for r in records if not r["answerable"]
    ]

    results = {
        "total": len(records),
        "answerable": len(answerable_records),
        "unanswerable": len(unanswerable_records)
    }

    for group_name, group in [
        ("all", records),
        ("answerable", answerable_records),
        ("unanswerable", unanswerable_records)
    ]:

        if len(group) == 0:
            continue

        top1_scores = [
            r["retrieved"][0]["score"]
            for r in group
            if len(r["retrieved"]) > 0
        ]

        topk_scores = [
            r["retrieved"][min(k, len(r["retrieved"])) - 1]["score"]
            for r in group
            if len(r["retrieved"]) > 0
        ]

        results[f"{group_name}_top1_mean"] = float(
            np.mean(top1_scores)
        )

        results[f"{group_name}_top1_median"] = float(
            np.median(top1_scores)
        )

        results[f"{group_name}_topk_mean"] = float(
            np.mean(topk_scores)
        )

    return results


metrics = evaluate_retrieval(
    evaluation_records,
    K
)


# ------------------------------------------------------------
# Print official diagnostic evaluation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 6C — RETRIEVAL EVALUATION RESULTS")
print("=" * 70)

print(
    f"\nTotal Test queries : {metrics['total']:,}"
)

print(
    f"Answerable queries : {metrics['answerable']:,}"
)

print(
    f"Unanswerable queries: {metrics['unanswerable']:,}"
)

print("\n" + "-" * 70)

for group_name in ["all", "answerable", "unanswerable"]:

    key = f"{group_name}_top1_mean"

    if key not in metrics:
        continue

    print(f"\n{group_name.upper()}")

    print(
        f"Top-1 mean score   : "
        f"{metrics[f'{group_name}_top1_mean']:.4f}"
    )

    print(
        f"Top-1 median score : "
        f"{metrics[f'{group_name}_top1_median']:.4f}"
    )

    print(
        f"Top-{K} boundary mean: "
        f"{metrics[f'{group_name}_topk_mean']:.4f}"
    )


# ------------------------------------------------------------
# Compare answerable vs unanswerable score distributions
# ------------------------------------------------------------

answerable_top1 = [
    r["retrieved"][0]["score"]
    for r in evaluation_records
    if r["answerable"] and r["retrieved"]
]

unanswerable_top1 = [
    r["retrieved"][0]["score"]
    for r in evaluation_records
    if not r["answerable"] and r["retrieved"]
]

print("\n" + "=" * 70)
print("ANSWERABLE vs UNANSWERABLE TOP-1 SCORE")
print("=" * 70)

print(
    f"\nAnswerable mean   : {np.mean(answerable_top1):.4f}"
)

print(
    f"Unanswerable mean : {np.mean(unanswerable_top1):.4f}"
)

print(
    f"Answerable median : {np.median(answerable_top1):.4f}"
)

print(
    f"Unanswerable median: {np.median(unanswerable_top1):.4f}"
)


# ------------------------------------------------------------
# Inspect first 5 Test queries
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE OFFICIAL RETRIEVAL RESULTS")
print("=" * 70)

for r in evaluation_records[:5]:

    print("\n" + "-" * 70)

    print(f"Test ID    : {r['test_id']}")
    print(f"Answerable : {r['answerable']}")
    print(f"Question   : {r['question']}")
    print(f"Gold IDs   : {r['gold_chunk_ids']}")

    print("\nTop-5 retrieved:")

    for item in r["retrieved"][:5]:

        print(
            f"\nRank {item['rank']} | "
            f"Score {item['score']:.4f} | "
            f"ID {item['id']} | "
            f"Chunk {item['chunk_idx']}"
        )

        print(
            f"Domain: {item['domain']} | "
            f"Country: {item['country']}"
        )

        print(
            f"Text: {item['chunk_text']}"
        )


# ------------------------------------------------------------
# Save results in memory
# ------------------------------------------------------------

step6c_evaluation = evaluation_records
step6c_metrics = metrics

print("\n" + "=" * 70)
print("STEP 6C COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6c_evaluation")
print("✓ step6c_metrics")

print(
    "\nIMPORTANT:"
    "\nExact Gold Recall@K is NOT reported here because "
    "Test gold chunks are absent from the Train-only index."
)

print(
    "\nNo data was modified."
    "\nNo model was changed."
    "\nNo FAISS index was rebuilt."
)

======================================================================
STEP 6C — OFFICIAL RETRIEVAL EVALUATION
======================================================================

[1/5] Validating existing retrieval components...
FAISS vectors : 164,456
Train chunks  : 164,456
Test rows     : 500
Index dim     : 768
✓ Existing model, corpus and FAISS index validated.
✓ No rebuilding / re-embedding will be performed.

[2/5] Encoding Test queries...

Batches:   0%|          | 0/16 [00:00<?, ?it/s]

Query embedding shape: (500, 768)
Encoding time: 1.26 seconds
Query norm range: 1.0000 → 1.0000
✓ Test queries encoded successfully.
✓ Query embeddings are normalized.

[3/5] Running Train-only FAISS retrieval...
Top-K: 10
Search time: 2.1557 seconds
Score matrix shape: (500, 10)
Index matrix shape: (500, 10)
✓ Retrieval completed.
✓ Only TRAIN vectors were searched.

[4/5] Building evaluation records...

[5/5] Calculating retrieval metrics...

======================================================================
STEP 6C — RETRIEVAL EVALUATION RESULTS
======================================================================

Total Test queries : 500
Answerable queries : 446
Unanswerable queries: 54

----------------------------------------------------------------------

ALL
Top-1 mean score   : 0.8667
Top-1 median score : 0.8671
Top-10 boundary mean: 0.8611

ANSWERABLE
Top-1 mean score   : 0.8679
Top-1 median score : 0.8690
Top-10 boundary mean: 0.8626

UNANSWERABLE
Top-1 mean score   : 0.8572
Top-1 median score : 0.8600
Top-10 boundary mean: 0.8494

======================================================================
ANSWERABLE vs UNANSWERABLE TOP-1 SCORE
======================================================================

Answerable mean   : 0.8679
Unanswerable mean : 0.8572
Answerable median : 0.8690
Unanswerable median: 0.8600

======================================================================
SAMPLE OFFICIAL RETRIEVAL RESULTS
======================================================================

----------------------------------------------------------------------
Test ID    : 6875-0
Answerable : True
Question   : أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
Gold IDs   : [np.int64(2)]

Top-5 retrieved:

Rank 1 | Score 0.8562 | ID 1398-3 | Chunk 3
Domain: streaming service | Country: Morocco
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 2 | Score 0.8562 | ID 1398-2 | Chunk 3
Domain: streaming service | Country: Morocco
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 3 | Score 0.8562 | ID 1398-1 | Chunk 3
Domain: streaming service | Country: Morocco
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 4 | Score 0.8562 | ID 1398-0 | Chunk 3
Domain: streaming service | Country: Morocco
Text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.

Rank 5 | Score 0.8545 | ID 5427-3 | Chunk 5
Domain: hotel chain | Country: Bahrain
Text: لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.

----------------------------------------------------------------------
Test ID    : 6875-1
Answerable : True
Question   : فاتورة زائدة. متر إضافي كم سعره؟
Gold IDs   : [np.int64(1)]

Top-5 retrieved:

Rank 1 | Score 0.8650 | ID 3228-3 | Chunk 3
Domain: water utility | Country: Egypt
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 2 | Score 0.8650 | ID 3228-0 | Chunk 3
Domain: water utility | Country: Egypt
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 3 | Score 0.8650 | ID 3228-2 | Chunk 3
Domain: water utility | Country: Egypt
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 4 | Score 0.8650 | ID 3228-1 | Chunk 3
Domain: water utility | Country: Egypt
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشهر التالي.

Rank 5 | Score 0.8597 | ID 0-1 | Chunk 1
Domain: water utility | Country: Oman
Text: تفرض الشركة رسوماً إضافية في حال تجاوز الحد المسموح به في الباقة، حيث يتم احتساب كل متر مكعب إضافي بسعر 0.700 ريال عماني. يتم تحصيل هذه الرسوم تلقائياً في فاتورة الشهر التالي وتظهر تحت بند 'تجاوز الاستهلاك'.

----------------------------------------------------------------------
Test ID    : 6875-2
Answerable : True
Question   : السلام عليكم، أنا مشترك لديكم منذ فترة وأرغب في تحويل اشتراكي إلى خاصية الدفع التلقائي لضمان عدم التأخر في السداد، هل هناك أي ميزات أو خصومات عند تفعيل هذه الخاصية؟
Gold IDs   : [np.int64(5)]

Top-5 retrieved:

Rank 1 | Score 0.8598 | ID 2494-2 | Chunk 5
Domain: gym / fitness club chain | Country: Iraq
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 2 | Score 0.8598 | ID 2494-1 | Chunk 5
Domain: gym / fitness club chain | Country: Iraq
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 3 | Score 0.8598 | ID 2494-3 | Chunk 5
Domain: gym / fitness club chain | Country: Iraq
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 4 | Score 0.8598 | ID 2494-0 | Chunk 5
Domain: gym / fitness club chain | Country: Iraq
Text: يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على الأقل.

Rank 5 | Score 0.8548 | ID 274-3 | Chunk 2
Domain: streaming service | Country: Qatar
Text: لترقية الاشتراك، يمكن للمستخدم الانتقال من الباقة الأساسية إلى المتقدمة أو المميزة عبر قسم إدارة الحساب. يتم احتساب فرق السعر فقط للأيام المتبقية من الشهر الحالي، ويتم تفعيل المزايا الجديدة فور إتمام عملية الدفع بنجاح.

----------------------------------------------------------------------
Test ID    : 6875-3
Answerable : True
Question   : تحية طيبة، أفكر في تغيير باقتي الحالية وأود معرفة الفرق بين الباقة الفضية والباقة الذهبية من حيث التكلفة الشهرية وكمية المياه المتاحة لكل منهما، وشكراً لكم.
Gold IDs   : [np.int64(0)]

Top-5 retrieved:

Rank 1 | Score 0.8627 | ID 3970-3 | Chunk 1
Domain: water utility | Country: Kuwait
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 2 | Score 0.8627 | ID 3970-2 | Chunk 1
Domain: water utility | Country: Kuwait
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 3 | Score 0.8627 | ID 3970-1 | Chunk 1
Domain: water utility | Country: Kuwait
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 4 | Score 0.8627 | ID 3970-0 | Chunk 1
Domain: water utility | Country: Kuwait
Text: تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

Rank 5 | Score 0.8587 | ID 3289-3 | Chunk 5
Domain: health insurance | Country: Saudi Arabia
Text: لترقية الباقة من الفضية إلى الذهبية، يجب دفع فارق السعر وهو 2500 ريال سعودي. يتم تفعيل التغطية الجديدة فوراً بعد سداد المبلغ، وتطبق الشروط والحدود الخاصة بالباقة الذهبية على جميع المطالبات اللاحقة لتاريخ الترقية.

----------------------------------------------------------------------
Test ID    : 6876-0
Answerable : False
Question   : أنا غاضب جداً! لقد اشتريت خزانة ملابس وبها كسر في الرف السفلي، أريد استبدالها الآن فوراً، أين هي سياسة استبدال القطع التالفة بالتحديد؟
Gold IDs   : []

Top-5 retrieved:

Rank 1 | Score 0.8729 | ID 2116-2 | Chunk 3
Domain: furniture store | Country: Bahrain
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 2 | Score 0.8729 | ID 2116-1 | Chunk 3
Domain: furniture store | Country: Bahrain
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 3 | Score 0.8729 | ID 2116-0 | Chunk 3
Domain: furniture store | Country: Bahrain
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 4 | Score 0.8729 | ID 2116-3 | Chunk 3
Domain: furniture store | Country: Bahrain
Text: تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي تكاليف إضافية على العميل.

Rank 5 | Score 0.8475 | ID 3999-3 | Chunk 4
Domain: furniture store | Country: Jordan
Text: تتيح الشركة استبدال القطع التالفة خلال ١٤ يوماً من تاريخ الاستلام بشرط وجود الفاتورة الأصلية وأن يكون المنتج بحالته الأصلية. يتم الاستبدال مجاناً إذا كان التلف ناتجاً عن الشحن أو خطأ في التصنيع.

======================================================================
STEP 6C COMPLETED
======================================================================

Saved objects:
✓ step6c_evaluation
✓ step6c_metrics

IMPORTANT:
Exact Gold Recall@K is NOT reported here because Test gold chunks are absent from the Train-only index.

No data was modified.
No model was changed.
No FAISS index was rebuilt.

In [26]:
# ============================================================
# STEP 6D — RETRIEVAL QUALITY & DUPLICATION ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6D — RETRIEVAL QUALITY & DUPLICATION ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Validate previous results
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert len(step6c_evaluation) == 500

print("\n[1/5] Previous evaluation validated.")
print(f"Test queries: {len(step6c_evaluation):,}")


# ------------------------------------------------------------
# 2. Analyze duplicate retrievals
# ------------------------------------------------------------

print("\n[2/5] Analyzing duplicate retrievals...")

dup_records = []

for r in step6c_evaluation:

    retrieved = r["retrieved"]

    record_ids = [item["id"] for item in retrieved]
    chunk_keys = [
        (item["id"], item["chunk_idx"])
        for item in retrieved
    ]

    unique_record_count = len(set(record_ids))
    unique_chunk_count = len(set(chunk_keys))

    dup_records.append({
        "test_id": r["test_id"],
        "answerable": r["answerable"],
        "top1_score": retrieved[0]["score"] if retrieved else np.nan,
        "unique_records_top10": unique_record_count,
        "unique_chunks_top10": unique_chunk_count,
        "duplicate_record_slots": len(record_ids) - unique_record_count,
        "duplicate_chunk_slots": len(chunk_keys) - unique_chunk_count
    })

dup_df = pd.DataFrame(dup_records)

print(
    f"Mean unique records in Top-10 : "
    f"{dup_df['unique_records_top10'].mean():.2f}"
)

print(
    f"Median unique records in Top-10 : "
    f"{dup_df['unique_records_top10'].median():.0f}"
)

print(
    f"Mean duplicate record slots : "
    f"{dup_df['duplicate_record_slots'].mean():.2f}"
)

print(
    f"Queries with duplicated records : "
    f"{(dup_df['duplicate_record_slots'] > 0).sum():,} "
    f"/ {len(dup_df):,}"
)


# ------------------------------------------------------------
# 3. Effective Top-K after record-level deduplication
# ------------------------------------------------------------

print("\n[3/5] Evaluating effective Top-K after deduplication...")

effective_k_values = [1, 3, 5, 10]

for k in effective_k_values:

    counts = []

    for r in step6c_evaluation:

        seen = set()
        unique_items = []

        for item in r["retrieved"]:

            record_id = item["id"]

            if record_id not in seen:
                seen.add(record_id)
                unique_items.append(item)

            if len(unique_items) >= k:
                break

        counts.append(len(unique_items))

    print(
        f"Effective unique records @ {k:2d}: "
        f"mean={np.mean(counts):.2f}, "
        f"median={np.median(counts):.0f}, "
        f"full={sum(x == k for x in counts):,}/{len(counts):,}"
    )


# ------------------------------------------------------------
# 4. Domain consistency of Top-10
# ------------------------------------------------------------

print("\n[4/5] Analyzing domain consistency...")

domain_stats = []

for r in step6c_evaluation:

    question_domain = test_df.iloc[r["test_idx"]]["domain"]

    retrieved_domains = [
        item["domain"]
        for item in r["retrieved"]
    ]

    same_domain_count = sum(
        d == question_domain
        for d in retrieved_domains
    )

    domain_stats.append({
        "test_id": r["test_id"],
        "answerable": r["answerable"],
        "question_domain": question_domain,
        "same_domain_top10": same_domain_count
    })

domain_df = pd.DataFrame(domain_stats)

print(
    f"Mean same-domain results in Top-10 : "
    f"{domain_df['same_domain_top10'].mean():.2f}"
)

print(
    f"Queries with Top-1 same domain : "
    f"{(domain_df['same_domain_top10'] >= 1).sum():,} "
    f"/ {len(domain_df):,}"
)

print(
    f"Queries with majority same domain : "
    f"{(domain_df['same_domain_top10'] >= 5).sum():,} "
    f"/ {len(domain_df):,}"
)


# ------------------------------------------------------------
# 5. Save analysis
# ------------------------------------------------------------

step6d_duplication = dup_df
step6d_domain = domain_df

print("\n" + "=" * 70)
print("STEP 6D COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6d_duplication")
print("✓ step6d_domain")

print("\nNo model changed.")
print("No embeddings recomputed.")
print("No FAISS index rebuilt.")

======================================================================
STEP 6D — RETRIEVAL QUALITY & DUPLICATION ANALYSIS
======================================================================

[1/5] Previous evaluation validated.
Test queries: 500

[2/5] Analyzing duplicate retrievals...
Mean unique records in Top-10 : 10.00
Median unique records in Top-10 : 10
Mean duplicate record slots : 0.00
Queries with duplicated records : 0 / 500

[3/5] Evaluating effective Top-K after deduplication...
Effective unique records @  1: mean=1.00, median=1, full=500/500
Effective unique records @  3: mean=3.00, median=3, full=500/500
Effective unique records @  5: mean=5.00, median=5, full=500/500
Effective unique records @ 10: mean=10.00, median=10, full=500/500

[4/5] Analyzing domain consistency...
Mean same-domain results in Top-10 : 5.14
Queries with Top-1 same domain : 329 / 500
Queries with majority same domain : 253 / 500

======================================================================
STEP 6D COMPLETED
======================================================================

Saved objects:
✓ step6d_duplication
✓ step6d_domain

No model changed.
No embeddings recomputed.
No FAISS index rebuilt.

In [27]:
# ============================================================
# STEP 6E — RETRIEVAL CONFIDENCE & THRESHOLD ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6E — RETRIEVAL CONFIDENCE & THRESHOLD ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Validate previous results
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert len(step6c_evaluation) == 500

print("\n[1/4] Validating previous retrieval results...")

threshold_records = []

for r in step6c_evaluation:

    if not r["retrieved"]:
        continue

    threshold_records.append({
        "test_id": r["test_id"],
        "answerable": r["answerable"],
        "top1_score": r["retrieved"][0]["score"],
        "top2_score": (
            r["retrieved"][1]["score"]
            if len(r["retrieved"]) > 1
            else np.nan
        ),
        "top5_score": (
            r["retrieved"][4]["score"]
            if len(r["retrieved"]) > 4
            else np.nan
        ),
        "top10_score": (
            r["retrieved"][9]["score"]
            if len(r["retrieved"]) > 9
            else np.nan
        )
    })

threshold_df = pd.DataFrame(threshold_records)

print(f"Queries analyzed: {len(threshold_df):,}")


# ------------------------------------------------------------
# 2. Score distribution
# ------------------------------------------------------------

print("\n[2/4] Top-1 score distribution...")

scores = threshold_df["top1_score"].values

quantiles = [0.00, 0.05, 0.10, 0.25, 0.50, 0.75, 0.90, 0.95, 1.00]

for q in quantiles:

    print(
        f"{q:>5.0%} percentile : "
        f"{np.quantile(scores, q):.4f}"
    )


# ------------------------------------------------------------
# 3. Threshold behavior
# ------------------------------------------------------------

print("\n[3/4] Threshold analysis...")

thresholds = [
    0.80,
    0.82,
    0.84,
    0.85,
    0.86,
    0.87,
    0.88,
    0.89,
    0.90
]

threshold_results = []

for threshold in thresholds:

    accepted = threshold_df[
        threshold_df["top1_score"] >= threshold
    ]

    answerable = threshold_df[
        threshold_df["answerable"]
    ]

    unanswerable = threshold_df[
        ~threshold_df["answerable"]
    ]

    accepted_answerable = answerable[
        answerable["top1_score"] >= threshold
    ]

    accepted_unanswerable = unanswerable[
        unanswerable["top1_score"] >= threshold
    ]

    coverage = len(accepted) / len(threshold_df)

    answerable_recall = (
        len(accepted_answerable) / len(answerable)
        if len(answerable) > 0
        else np.nan
    )

    unanswerable_accept_rate = (
        len(accepted_unanswerable) / len(unanswerable)
        if len(unanswerable) > 0
        else np.nan
    )

    precision_of_accepted = (
        len(accepted_answerable) / len(accepted)
        if len(accepted) > 0
        else np.nan
    )

    threshold_results.append({
        "threshold": threshold,
        "accepted": len(accepted),
        "coverage": coverage,
        "answerable_recall": answerable_recall,
        "unanswerable_accept_rate": unanswerable_accept_rate,
        "accepted_precision": precision_of_accepted
    })

threshold_results_df = pd.DataFrame(threshold_results)

print("\nThreshold | Accepted | Coverage | Answerable Recall | "
      "Unanswerable Accept | Accepted Precision")

print("-" * 90)

for _, row in threshold_results_df.iterrows():

    print(
        f"{row['threshold']:.2f}      | "
        f"{row['accepted']:>8} | "
        f"{row['coverage']:.3f}    | "
        f"{row['answerable_recall']:.3f}             | "
        f"{row['unanswerable_accept_rate']:.3f}              | "
        f"{row['accepted_precision']:.3f}"
    )


# ------------------------------------------------------------
# 4. Save results
# ------------------------------------------------------------

step6e_threshold_df = threshold_df
step6e_threshold_results = threshold_results_df

print("\n" + "=" * 70)
print("STEP 6E COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6e_threshold_df")
print("✓ step6e_threshold_results")

print("\nIMPORTANT:")
print("Threshold results are diagnostic.")
print("They do NOT represent retrieval Recall@K.")
print("No model, embeddings, or FAISS index were changed.")

======================================================================
STEP 6E — RETRIEVAL CONFIDENCE & THRESHOLD ANALYSIS
======================================================================

[1/4] Validating previous retrieval results...
Queries analyzed: 500

[2/4] Top-1 score distribution...
   0% percentile : 0.8046
   5% percentile : 0.8323
  10% percentile : 0.8403
  25% percentile : 0.8528
  50% percentile : 0.8671
  75% percentile : 0.8802
  90% percentile : 0.8918
  95% percentile : 0.8967
 100% percentile : 0.9324

[3/4] Threshold analysis...

Threshold | Accepted | Coverage | Answerable Recall | Unanswerable Accept | Accepted Precision
------------------------------------------------------------------------------------------
0.80      |    500.0 | 1.000    | 1.000             | 1.000              | 0.892
0.82      |    490.0 | 0.980    | 0.982             | 0.963              | 0.894
0.84      |    453.0 | 0.906    | 0.913             | 0.852              | 0.898
0.85      |    395.0 | 0.790    | 0.803             | 0.685              | 0.906
0.86      |    323.0 | 0.646    | 0.664             | 0.500              | 0.916
0.87      |    221.0 | 0.442    | 0.478             | 0.148              | 0.964
0.88      |    127.0 | 0.254    | 0.278             | 0.056              | 0.976
0.89      |     60.0 | 0.120    | 0.132             | 0.019              | 0.983
0.90      |     20.0 | 0.040    | 0.045             | 0.000              | 1.000

======================================================================
STEP 6E COMPLETED
======================================================================

Saved objects:
✓ step6e_threshold_df
✓ step6e_threshold_results

IMPORTANT:
Threshold results are diagnostic.
They do NOT represent retrieval Recall@K.
No model, embeddings, or FAISS index were changed.

In [29]:
# ============================================================
# STEP 6F-A — INSPECT EXISTING PROXY DATAFRAME
# ============================================================

print("=" * 70)
print("STEP 6F-A — INSPECT EXISTING PROXY DATAFRAME")
print("=" * 70)

assert "step6b_proxy_df" in globals()

print("\nShape:")
print(step6b_proxy_df.shape)

print("\nColumns:")
for i, col in enumerate(step6b_proxy_df.columns, start=1):
    print(f"{i:2d}. {col}")

print("\nFirst 3 rows:")
display(step6b_proxy_df.head(3))

print("\nData types:")
print(step6b_proxy_df.dtypes)

print("\n" + "=" * 70)
print("STEP 6F-A COMPLETED")
print("=" * 70)

======================================================================
STEP 6F-A — INSPECT EXISTING PROXY DATAFRAME
======================================================================

Shape:
(465, 25)

Columns:
 1. test_row_idx
 2. test_id
 3. gold_chunk_idx
 4. gold_text
 5. gold_normalized
 6. exact_match_count
 7. has_exact_match
 8. lexical_top1_corpus_idx
 9. lexical_top1_score
10. test_domain
11. test_country
12. test_question_type
13. test_answerable
14. corpus_idx
15. candidate_row_idx
16. candidate_chunk_idx
17. candidate_id
18. candidate_domain
19. candidate_country
20. candidate_question
21. candidate_text
22. same_domain
23. same_country
24. proxy_reliable
25. similarity_band

First 3 rows:

,test_row_idx,test_id,gold_chunk_idx,gold_text,gold_normalized,exact_match_count,has_exact_match,lexical_top1_corpus_idx,lexical_top1_score,test_domain,...,candidate_chunk_idx,candidate_id,candidate_domain,candidate_country,candidate_question,candidate_text,same_domain,same_country,proxy_reliable,similarity_band
0,0,6875-0,2,يمكن للعملاء طلب إغلاق الحساب أو إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الشهر الجاري، مع سداد كافة المستحقات المتأخرة قبل إتمام عملية الإغلاق.,يمكن للعملاء طلب اغلاق الحساب او الغاء الاشتراك في اي وقت، بشرط تقديم طلب كتابي قبل 15 يوما من تاريخ نهايه الشهر الجاري، مع سداد كافه المستحقات المتاخره قبل اتمام عمليه الاغلاق.,0,False,83623,0.526424,water utility,...,3,3493-0,internet service provider,Algeria,السلام عليكم، لقد لاحظت أن خدمة الإنترنت مقطوعة في منزلي منذ الصباح، وقد حاولت تفقد الأسلاك ولم أجد مشكلة، فكيف يمكنني حل هذه المشكلة؟,يمكن للعملاء طلب إلغاء الاشتراك في أي وقت، بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الدورة الشهرية. يتم استرداد الرسوم المدفوعة مسبقاً بنسبة 70% من قيمة الشهر المتبقي.,False,False,False,0.50-0.60
1,1,6875-1,1,في حال تجاوز الاستهلاك السعة المحددة في الباقة، يتم احتساب كل متر مكعب إضافي بسعر 3 دينارات تونسية، وتضاف هذه الرسوم تلقائياً إلى فاتورة الشهر التالي دون الحاجة إلى إشعار مسبق.,في حال تجاوز الاستهلاك السعه المحدده في الباقه، يتم احتساب كل متر مكعب اضافي بسعر 3 دينارات تونسيه، وتضاف هذه الرسوم تلقائيا الي فاتوره الشهر التالي دون الحاجه الي اشعار مسبق.,0,False,20190,0.531419,water utility,...,2,843-0,water utility,Lebanon,تحية طيبة، أنا مشترك في باقتكم منذ عام، وقد لاحظت في فاتورة هذا الشهر وجود مبلغ إضافي لم أكن أتوقعه رغم أن استهلاكي كان طبيعياً. هل يمكنكم إرشادي إلى كيفية تصحيح هذا الخطأ المالي؟,"تفرض الشركة رسوماً إضافية على استهلاك المياه التي تتجاوز سعة الباقة المختارة، حيث يتم احتساب كل متر مكعب إضافي بسعر 5,000 ليرة لبنانية، وتضاف هذه الرسوم تلقائياً إلى فاتورة الدورة الشهرية التالية.",True,False,False,0.50-0.60
2,2,6875-2,5,تمنح الشركة خصماً قدره 15% على الفاتورة السنوية للعملاء الذين يقومون بتفعيل خاصية الدفع التلقائي عبر البطاقة البنكية، ويتم تطبيق هذا الخصم في نهاية كل سنة تعاقدية.,تمنح الشركه خصما قدره 15% علي الفاتوره السنويه للعملاء الذين يقومون بتفعيل خاصيه الدفع التلقائي عبر البطاقه البنكيه، ويتم تطبيق هذا الخصم في نهايه كل سنه تعاقديه.,0,False,49107,0.620166,water utility,...,5,2048-0,water utility,Egypt,المنزلية أم العائلية؟,تمنح الشركة خصماً بنسبة 15% على إجمالي الفاتورة السنوية للعملاء الذين يقومون بتفعيل خاصية الدفع التلقائي عبر البطاقات الائتمانية. يتم تطبيق هذا الخصم في شهر يناير من كل عام ميلادي بعد مراجعة سجل السداد.,True,False,False,0.60-0.70

Data types:
test_row_idx                  int64
test_id                         str
gold_chunk_idx                int64
gold_text                       str
gold_normalized                 str
exact_match_count             int64
has_exact_match                bool
lexical_top1_corpus_idx       int64
lexical_top1_score          float32
test_domain                     str
test_country                    str
test_question_type              str
test_answerable                bool
corpus_idx                    int64
candidate_row_idx             int64
candidate_chunk_idx           int64
candidate_id                    str
candidate_domain                str
candidate_country               str
candidate_question              str
candidate_text                  str
same_domain                    bool
same_country                   bool
proxy_reliable                 bool
similarity_band            category
dtype: object

======================================================================
STEP 6F-A COMPLETED
======================================================================

In [30]:
# ============================================================
# STEP 6F — CONSERVATIVE PROXY RETRIEVAL EVALUATION
# Corrected for existing step6b_proxy_df schema
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6F — CONSERVATIVE PROXY RETRIEVAL EVALUATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing proxy data
# ------------------------------------------------------------

print("\n[1/5] Validating existing proxy mappings...")

assert "step6b_proxy_df" in globals()
assert "step6c_evaluation" in globals()

proxy_df = step6b_proxy_df.copy()

required_columns = [
    "test_row_idx",
    "test_id",
    "gold_chunk_idx",
    "corpus_idx",
    "proxy_reliable"
]

for col in required_columns:
    assert col in proxy_df.columns, f"Missing column: {col}"

print(f"Total Test gold chunks : {len(proxy_df):,}")

reliable_proxy = proxy_df[
    proxy_df["proxy_reliable"] == True
].copy()

print(
    f"Reliable proxy mappings: "
    f"{len(reliable_proxy):,}"
)

print(
    f"Reliable mapping rate  : "
    f"{len(reliable_proxy) / len(proxy_df):.2%}"
)


# ------------------------------------------------------------
# 2. Build proxy lookup
# ------------------------------------------------------------

print("\n[2/5] Building proxy target lookup...")

proxy_lookup = {}

for _, row in reliable_proxy.iterrows():

    test_row_idx = int(row["test_row_idx"])
    gold_chunk_idx = int(row["gold_chunk_idx"])
    proxy_corpus_idx = int(row["corpus_idx"])

    key = (
        test_row_idx,
        gold_chunk_idx
    )

    proxy_lookup[key] = proxy_corpus_idx

print(
    f"Proxy lookup entries: "
    f"{len(proxy_lookup):,}"
)


# ------------------------------------------------------------
# 3. Match proxy targets against Top-10 retrieval
# ------------------------------------------------------------

print("\n[3/5] Checking proxy targets in Top-10 retrieval...")

evaluation_rows = []

for r in step6c_evaluation:

    test_row_idx = int(r["test_idx"])

    for gold_chunk_id in r["gold_chunk_ids"]:

        gold_chunk_idx = int(gold_chunk_id)

        key = (
            test_row_idx,
            gold_chunk_idx
        )

        if key not in proxy_lookup:
            continue

        proxy_corpus_idx = proxy_lookup[key]

        retrieved_indices = [
            int(item["corpus_idx"])
            for item in r["retrieved"]
        ]

        found_rank = None

        for rank, retrieved_idx in enumerate(
            retrieved_indices,
            start=1
        ):

            if retrieved_idx == proxy_corpus_idx:
                found_rank = rank
                break

        evaluation_rows.append({
            "test_row_idx": test_row_idx,
            "test_id": r["test_id"],
            "gold_chunk_idx": gold_chunk_idx,
            "proxy_corpus_idx": proxy_corpus_idx,
            "found_rank": found_rank,
            "found_at_1": (
                found_rank is not None
                and found_rank <= 1
            ),
            "found_at_3": (
                found_rank is not None
                and found_rank <= 3
            ),
            "found_at_5": (
                found_rank is not None
                and found_rank <= 5
            ),
            "found_at_10": (
                found_rank is not None
                and found_rank <= 10
            )
        })


proxy_eval_df = pd.DataFrame(evaluation_rows)

print(
    f"Reliable proxy targets evaluated: "
    f"{len(proxy_eval_df):,}"
)

assert len(proxy_eval_df) == len(reliable_proxy)


# ------------------------------------------------------------
# 4. Calculate proxy retrieval metrics
# ------------------------------------------------------------

print("\n[4/5] Calculating proxy retrieval metrics...")

proxy_metrics = {
    "evaluated_targets": len(proxy_eval_df),

    "proxy_recall_at_1": float(
        proxy_eval_df["found_at_1"].mean()
    ),

    "proxy_recall_at_3": float(
        proxy_eval_df["found_at_3"].mean()
    ),

    "proxy_recall_at_5": float(
        proxy_eval_df["found_at_5"].mean()
    ),

    "proxy_recall_at_10": float(
        proxy_eval_df["found_at_10"].mean()
    )
}


print("\n" + "-" * 70)

print(
    f"Proxy Recall@1  : "
    f"{proxy_metrics['proxy_recall_at_1']:.4f}"
)

print(
    f"Proxy Recall@3  : "
    f"{proxy_metrics['proxy_recall_at_3']:.4f}"
)

print(
    f"Proxy Recall@5  : "
    f"{proxy_metrics['proxy_recall_at_5']:.4f}"
)

print(
    f"Proxy Recall@10 : "
    f"{proxy_metrics['proxy_recall_at_10']:.4f}"
)


# ------------------------------------------------------------
# 5. Save results
# ------------------------------------------------------------

step6f_proxy_eval = proxy_eval_df
step6f_proxy_metrics = proxy_metrics

print("\n" + "=" * 70)
print("STEP 6F COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6f_proxy_eval")
print("✓ step6f_proxy_metrics")

print("\nMETHODOLOGICAL NOTE:")
print(
    "These are CONSERVATIVE PROXY retrieval metrics, "
    "not official Gold Recall@K."
)

print(
    "Only reliable proxy mappings are evaluated."
)

print(
    "The proxy targets were constructed independently "
    "using lexical similarity + domain/country constraints."
)

print(
    "No Test chunks were added to the TRAIN FAISS index."
)

print(
    "No model, embeddings, or FAISS index were changed."
)

======================================================================
STEP 6F — CONSERVATIVE PROXY RETRIEVAL EVALUATION
======================================================================

[1/5] Validating existing proxy mappings...
Total Test gold chunks : 465
Reliable proxy mappings: 174
Reliable mapping rate  : 37.42%

[2/5] Building proxy target lookup...
Proxy lookup entries: 174

[3/5] Checking proxy targets in Top-10 retrieval...
Reliable proxy targets evaluated: 174

[4/5] Calculating proxy retrieval metrics...

----------------------------------------------------------------------
Proxy Recall@1  : 0.0000
Proxy Recall@3  : 0.0000
Proxy Recall@5  : 0.0230
Proxy Recall@10 : 0.0402

======================================================================
STEP 6F COMPLETED
======================================================================

Saved objects:
✓ step6f_proxy_eval
✓ step6f_proxy_metrics

METHODOLOGICAL NOTE:
These are CONSERVATIVE PROXY retrieval metrics, not official Gold Recall@K.
Only reliable proxy mappings are evaluated.
The proxy targets were constructed independently using lexical similarity + domain/country constraints.
No Test chunks were added to the TRAIN FAISS index.
No model, embeddings, or FAISS index were changed.

In [31]:
# ============================================================
# STEP 6G — PROXY vs E5 RETRIEVAL DISAGREEMENT ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6G — PROXY vs E5 RETRIEVAL DISAGREEMENT ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate previous objects
# ------------------------------------------------------------

print("\n[1/5] Validating previous results...")

assert "step6b_proxy_df" in globals()
assert "step6c_evaluation" in globals()
assert "step6f_proxy_eval" in globals()

reliable_proxy = step6b_proxy_df[
    step6b_proxy_df["proxy_reliable"] == True
].copy()

print(
    f"Reliable proxy mappings: "
    f"{len(reliable_proxy):,}"
)

assert len(reliable_proxy) == 174


# ------------------------------------------------------------
# 2. Analyze every reliable proxy target
# ------------------------------------------------------------

print("\n[2/5] Comparing proxy targets against E5 Top-10...")

analysis_rows = []

for _, proxy_row in reliable_proxy.iterrows():

    test_row_idx = int(proxy_row["test_row_idx"])
    gold_chunk_idx = int(proxy_row["gold_chunk_idx"])

    proxy_corpus_idx = int(proxy_row["corpus_idx"])

    # Find corresponding Test evaluation
    evaluation = step6c_evaluation[test_row_idx]

    retrieved = evaluation["retrieved"]

    retrieved_indices = [
        int(item["corpus_idx"])
        for item in retrieved
    ]

    # --------------------------------------------------------
    # Find proxy target rank
    # --------------------------------------------------------

    proxy_rank = None
    proxy_score = None

    for rank, item in enumerate(retrieved, start=1):

        if int(item["corpus_idx"]) == proxy_corpus_idx:

            proxy_rank = rank
            proxy_score = float(item["score"])

            break

    # --------------------------------------------------------
    # Best E5 result
    # --------------------------------------------------------

    top1 = retrieved[0]

    # --------------------------------------------------------
    # Compare metadata
    # --------------------------------------------------------

    analysis_rows.append({

        "test_row_idx":
            test_row_idx,

        "test_id":
            proxy_row["test_id"],

        "gold_chunk_idx":
            gold_chunk_idx,

        "proxy_corpus_idx":
            proxy_corpus_idx,

        "proxy_score_e5":
            proxy_score,

        "proxy_rank_e5":
            proxy_rank,

        "proxy_similarity_tf_idf":
            float(proxy_row["lexical_top1_score"]),

        "test_domain":
            proxy_row["test_domain"],

        "proxy_domain":
            proxy_row["candidate_domain"],

        "proxy_country":
            proxy_row["candidate_country"],

        "proxy_same_domain":
            bool(proxy_row["same_domain"]),

        "proxy_same_country":
            bool(proxy_row["same_country"]),

        "e5_top1_corpus_idx":
            int(top1["corpus_idx"]),

        "e5_top1_id":
            top1["id"],

        "e5_top1_score":
            float(top1["score"]),

        "e5_top1_domain":
            top1["domain"],

        "e5_top1_country":
            top1["country"],

        "e5_top1_same_domain":
            top1["domain"] == proxy_row["test_domain"],

        "e5_top1_same_country":
            top1["country"] == proxy_row["test_country"],

        "proxy_found_top10":
            proxy_rank is not None
    })


disagreement_df = pd.DataFrame(analysis_rows)


# ------------------------------------------------------------
# 3. Summary of disagreement
# ------------------------------------------------------------

print("\n[3/5] Summarizing proxy vs E5 disagreement...")

proxy_found = disagreement_df[
    disagreement_df["proxy_found_top10"]
]

proxy_not_found = disagreement_df[
    ~disagreement_df["proxy_found_top10"]
]

print(
    f"\nProxy found in E5 Top-10 : "
    f"{len(proxy_found):,} / {len(disagreement_df):,}"
)

print(
    f"Proxy NOT found in Top-10: "
    f"{len(proxy_not_found):,} / {len(disagreement_df):,}"
)

print(
    f"Proxy Top-10 agreement rate: "
    f"{len(proxy_found) / len(disagreement_df):.2%}"
)

print(
    f"\nE5 Top-1 same domain: "
    f"{disagreement_df['e5_top1_same_domain'].mean():.2%}"
)

print(
    f"E5 Top-1 same country: "
    f"{disagreement_df['e5_top1_same_country'].mean():.2%}"
)


# ------------------------------------------------------------
# 4. Compare scores
# ------------------------------------------------------------

print("\n[4/5] Comparing E5 scores...")

if len(proxy_found) > 0:

    print(
        f"\nProxy E5 score when found:"
        f" mean={proxy_found['proxy_score_e5'].mean():.4f},"
        f" median={proxy_found['proxy_score_e5'].median():.4f}"
    )

    print(
        f"Mean E5 rank of found proxy:"
        f" {proxy_found['proxy_rank_e5'].mean():.2f}"
    )

print(
    f"\nE5 Top-1 score:"
    f" mean={disagreement_df['e5_top1_score'].mean():.4f},"
    f" median={disagreement_df['e5_top1_score'].median():.4f}"
)


# ------------------------------------------------------------
# 5. Inspect representative disagreements
# ------------------------------------------------------------

print("\n[5/5] Representative proxy disagreements...")

print("\n" + "=" * 70)
print("SAMPLE CASES WHERE TF-IDF PROXY WAS NOT IN E5 TOP-10")
print("=" * 70)

sample_failures = proxy_not_found.head(10)

for _, row in sample_failures.iterrows():

    test_row_idx = int(row["test_row_idx"])

    evaluation = step6c_evaluation[test_row_idx]

    proxy_source = reliable_proxy[
        (reliable_proxy["test_row_idx"] == test_row_idx)
        &
        (reliable_proxy["gold_chunk_idx"] == row["gold_chunk_idx"])
    ].iloc[0]

    print("\n" + "-" * 70)

    print(f"Test ID       : {row['test_id']}")
    print(f"Gold chunk    : {row['gold_chunk_idx']}")

    print(
        f"TF-IDF score  : "
        f"{row['proxy_similarity_tf_idf']:.4f}"
    )

    print(
        f"Proxy domain  : "
        f"{row['proxy_domain']}"
    )

    print(
        f"Proxy country : "
        f"{row['proxy_country']}"
    )

    print("\nTF-IDF Proxy Text:")
    print(proxy_source["candidate_text"])

    print("\nE5 Top-1:")
    print(
        f"Score  : {row['e5_top1_score']:.4f}"
    )

    print(
        f"ID     : {row['e5_top1_id']}"
    )

    print(
        f"Domain : {row['e5_top1_domain']}"
    )

    print(
        f"Country: {row['e5_top1_country']}"
    )

    print(
        f"Text   : "
        f"{evaluation['retrieved'][0]['chunk_text']}"
    )


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6g_disagreement = disagreement_df

print("\n" + "=" * 70)
print("STEP 6G COMPLETED")
print("=" * 70)

print("\nSaved object:")
print("✓ step6g_disagreement")

print("\nIMPORTANT:")
print(
    "This analysis diagnoses disagreement between "
    "an independent TF-IDF proxy and E5 semantic retrieval."
)

print(
    "It does NOT treat TF-IDF proxy agreement as ground-truth."
)

print(
    "No model, embeddings, FAISS index, or dataset was changed."
)

======================================================================
STEP 6G — PROXY vs E5 RETRIEVAL DISAGREEMENT ANALYSIS
======================================================================

[1/5] Validating previous results...
Reliable proxy mappings: 174

[2/5] Comparing proxy targets against E5 Top-10...

[3/5] Summarizing proxy vs E5 disagreement...

Proxy found in E5 Top-10 : 7 / 174
Proxy NOT found in Top-10: 167 / 174
Proxy Top-10 agreement rate: 4.02%

E5 Top-1 same domain: 57.47%
E5 Top-1 same country: 18.39%

[4/5] Comparing E5 scores...

Proxy E5 score when found: mean=0.8846, median=0.8817
Mean E5 rank of found proxy: 5.43

E5 Top-1 score: mean=0.8718, median=0.8739

[5/5] Representative proxy disagreements...

======================================================================
SAMPLE CASES WHERE TF-IDF PROXY WAS NOT IN E5 TOP-10
======================================================================

----------------------------------------------------------------------
Test ID       : 6875-3
Gold chunk    : 0
TF-IDF score  : 0.6921
Proxy domain  : water utility
Proxy country : Tunisia

TF-IDF Proxy Text:
تقدم شركة سديم باقتين رئيسيتين للمنازل: الباقة الأساسية بسعر 45 دينار تونسي شهرياً وتوفر استهلاكاً حتى 20 متراً مكعباً، والباقة المميزة بسعر 80 دينار تونسي شهرياً وتوفر استهلاكاً حتى 50 متراً مكعباً مع خدمة صيانة سنوية مجانية واحدة.

E5 Top-1:
Score  : 0.8627
ID     : 3970-3
Domain : water utility
Country: Kuwait
Text   : تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة 10% عند التجديد السنوي المسبق.

----------------------------------------------------------------------
Test ID       : 6877-0
Gold chunk    : 0
TF-IDF score  : 0.6308
Proxy domain  : online electronics store
Proxy country : Algeria

TF-IDF Proxy Text:
توفر الشركة هاتف 'سديم X1' بسعر 45,000 دينار جزائري، ويتميز بذاكرة 128 جيجابايت وبطارية 5000 مللي أمبير. أما هاتف 'سديم X2' فيأتي بسعر 60,000 دينار جزائري، مع ذاكرة 256 جيجابايت وشاشة بدقة 4K.

E5 Top-1:
Score  : 0.8901
ID     : 5269-3
Domain : online electronics store
Country: Algeria
Text   : هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره 92000 دينار جزائري، وكلاهما بضمان لمدة عامين.

----------------------------------------------------------------------
Test ID       : 6878-2
Gold chunk    : 0
TF-IDF score  : 0.6044
Proxy domain  : car insurance
Proxy country : Lebanon

TF-IDF Proxy Text:
تقدم شركة أرزة باقة التأمين الأساسية بسعر 500,000 ليرة لبنانية سنوياً، وتغطي هذه الباقة الحوادث المرورية البسيطة والسرقة الجزئية، بينما تبلغ تكلفة باقة التأمين الذهبية 1,200,000 ليرة لبنانية سنوياً لتشمل تغطية كاملة ضد الحريق والسرقة الكلية.

E5 Top-1:
Score  : 0.8520
ID     : 6787-3
Domain : car insurance
Country: Oman
Text   : تقدم الشركة باقة 'التأمين الأساسي' بسعر 45 ريالاً عمانياً سنوياً، وتغطي الأضرار المادية للطرف الثالث فقط. أما باقة 'التأمين الشامل' فتبدأ من 120 ريالاً عمانياً سنوياً، وتغطي الحوادث، والسرقة، والحرائق، مع تحمل العميل مبلغ 50 ريالاً عمانياً كنسبة مقتطعة عند كل مطالبة.

----------------------------------------------------------------------
Test ID       : 6879-3
Gold chunk    : 0
TF-IDF score  : 0.6853
Proxy domain  : retail bank
Proxy country : Egypt

TF-IDF Proxy Text:
يقدم بنك النماء حساب التوفير الذهبي بعائد سنوي قدره 12% يصرف شهرياً. الحد الأدنى لفتح الحساب هو 5000 جنيه مصري. يتم فرض رسوم إدارية قدرها 100 جنيه مصري يتم خصمها كل 3 أشهر من رصيد الحساب.

E5 Top-1:
Score  : 0.8808
ID     : 5703-3
Domain : retail bank
Country: Iraq
Text   : يقدم المصرف حساب التوفير الذهبي بعائد سنوي قدره 4%. يتطلب فتح الحساب إيداعاً أولياً بقيمة 250,000 دينار عراقي. يتم تحويل الأرباح إلى الحساب بشكل ربع سنوي، ويسمح العميل بسحب مبلغ 1,000,000 دينار شهرياً دون قيود.

----------------------------------------------------------------------
Test ID       : 6881-2
Gold chunk    : 2
TF-IDF score  : 0.5970
Proxy domain  : furniture store
Proxy country : Saudi Arabia

TF-IDF Proxy Text:
يمكن للعملاء الاشتراك في 'عضوية النخبة' السنوية مقابل 300 ريال سعودي. تمنح هذه العضوية خصماً ثابتاً بنسبة 10% على جميع المشتريات، بالإضافة إلى أولوية في التوصيل خلال 48 ساعة فقط من تاريخ الطلب.

E5 Top-1:
Score  : 0.8936
ID     : 1446-3
Domain : furniture store
Country: Egypt
Text   : يمكن للعملاء الاشتراك في 'عضوية التميز' السنوية مقابل ٥٠٠ جنيه مصري. تمنح هذه العضوية صاحبها خصمًا بنسبة ١٠٪ على جميع المشتريات وتوصيلاً مجانياً لعدد ٣ طلبات في السنة. يتم تجديد الاشتراك تلقائياً كل ٣٦٥ يوماً عبر البطاقة الائتمانية المسجلة.

----------------------------------------------------------------------
Test ID       : 6882-2
Gold chunk    : 1
TF-IDF score  : 0.7714
Proxy domain  : hotel chain
Proxy country : Tunisia

TF-IDF Proxy Text:
سياسة الإلغاء: يمكن للعملاء إلغاء الحجز مجاناً قبل موعد الوصول بـ 48 ساعة. في حال الإلغاء خلال أقل من 48 ساعة من موعد الوصول، يتم خصم قيمة الليلة الأولى من المبلغ المسترد. يتم تحويل المبالغ المستردة إلى الحساب البنكي للعميل خلال 7 أيام عمل.

E5 Top-1:
Score  : 0.8474
ID     : 5688-2
Domain : ride-hailing app
Country: Qatar
Text   : لحل مشكلات الدفع، يرجى الدخول إلى قائمة الإعدادات ثم اختيار 'الدعم الفني' وإرسال لقطة شاشة للمشكلة. يتم مراجعة طلبات استرداد المبالغ الخاطئة خلال 48 ساعة عمل من تاريخ تقديم الطلب.

----------------------------------------------------------------------
Test ID       : 6883-0
Gold chunk    : 2
TF-IDF score  : 0.6439
Proxy domain  : internet service provider
Proxy country : Egypt

TF-IDF Proxy Text:
في حال تعطل خدمة الإنترنت، يجب على العميل أولاً إعادة تشغيل جهاز الراوتر والانتظار لمدة 5 دقائق. إذا استمرت المشكلة، يرجى التحقق من إضاءة مصباح 'DSL'؛ فإذا كان أحمر اللون، فهذا يشير إلى وجود عطل في الكابل الأرضي يتطلب تدخل الفني.

E5 Top-1:
Score  : 0.8870
ID     : 5822-2
Domain : telecom / mobile network
Country: Lebanon
Text   : في حال تعذر الاتصال بالإنترنت، يرجى أولاً التأكد من إضاءة مصباح 'DSL' باللون الأخضر الثابت. إذا كان المصباح يومض باللون الأحمر، يجب إعادة تشغيل الجهاز لمدة 60 ثانية. في حال استمرار المشكلة، يرجى الاتصال بالدعم الفني على الرقم 1010.

----------------------------------------------------------------------
Test ID       : 6883-1
Gold chunk    : 3
TF-IDF score  : 0.7243
Proxy domain  : internet service provider
Proxy country : Algeria

TF-IDF Proxy Text:
يمكن للعملاء ترقية باقتهم الحالية من خلال تطبيق أفق أو الموقع الإلكتروني. يتم تفعيل الترقية في غضون 24 ساعة من تأكيد الدفع، ويتم احتساب فرق السعر بنسبة تناسبية بناءً على الأيام المتبقية في الشهر الحالي.

E5 Top-1:
Score  : 0.8765
ID     : 5203-3
Domain : telecom / mobile network
Country: Morocco
Text   : لتحديث الباقة من 'الاقتصاد' إلى 'الرائد'، يجب على العميل تفعيل الخدمة عبر إرسال كلمة 'ترقية' في رسالة نصية إلى الرقم 123. يتم خصم فرق السعر من الرصيد الحالي فوراً وتفعيل المزايا الجديدة خلال 24 ساعة.

----------------------------------------------------------------------
Test ID       : 6883-2
Gold chunk    : 2
TF-IDF score  : 0.6439
Proxy domain  : internet service provider
Proxy country : Egypt

TF-IDF Proxy Text:
في حال تعطل خدمة الإنترنت، يجب على العميل أولاً إعادة تشغيل جهاز الراوتر والانتظار لمدة 5 دقائق. إذا استمرت المشكلة، يرجى التحقق من إضاءة مصباح 'DSL'؛ فإذا كان أحمر اللون، فهذا يشير إلى وجود عطل في الكابل الأرضي يتطلب تدخل الفني.

E5 Top-1:
Score  : 0.8674
ID     : 3359-3
Domain : telecom / mobile network
Country: Saudi Arabia
Text   : في حال انقطاع خدمة الإنترنت، يرجى أولاً إعادة تشغيل الجهاز والتحقق من تفعيل وضع الطيران ثم إلغاؤه. إذا استمرت المشكلة، يجب التحقق من إعدادات نقطة الوصول (APN) والتأكد من أنها مضبوطه على 'alathir.net.sa'. إذا لم يتم الحل، يرجى الاتصال بالدعم الفني.

----------------------------------------------------------------------
Test ID       : 6883-3
Gold chunk    : 0
TF-IDF score  : 0.7382
Proxy domain  : internet service provider
Proxy country : Egypt

TF-IDF Proxy Text:
تقدم شركة سحاب باقة 'السرعة القصوى' بسعر 450 جنيهاً مصرياً شهرياً، وتوفر سرعة تحميل تصل إلى 100 ميجابت في الثانية وسعة تحميل 600 جيجابايت. تتضمن هذه الباقة جهاز راوتر حديث مجاناً عند التعاقد لمدة 12 شهراً.

E5 Top-1:
Score  : 0.8768
ID     : 5918-3
Domain : internet service provider
Country: Lebanon
Text   : تقدم باقة 'السرعة القصوى' إنترنت منزلي بسرعة 100 ميجابت في الثانية بتكلفة شهرية قدرها 1,200,000 ليرة لبنانية، بينما توفر باقة 'الاقتصادية' سرعة 30 ميجابت في الثانية بتكلفة 500,000 ليرة لبنانية شهرياً. تشمل جميع الباقات سعة تحميل غير محدودة وتفعيل الخدمة مجاناً للمشتركين الجدد.

======================================================================
STEP 6G COMPLETED
======================================================================

Saved object:
✓ step6g_disagreement

IMPORTANT:
This analysis diagnoses disagreement between an independent TF-IDF proxy and E5 semantic retrieval.
It does NOT treat TF-IDF proxy agreement as ground-truth.
No model, embeddings, FAISS index, or dataset was changed.

In [32]:
# ============================================================
# STEP 6H — TOP-K SEMANTIC RETRIEVAL QUALITY ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6H — TOP-K SEMANTIC RETRIEVAL QUALITY ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing retrieval
# ------------------------------------------------------------

print("\n[1/4] Validating existing retrieval results...")

assert "step6c_evaluation" in globals()
assert len(step6c_evaluation) == 500

print(f"Test queries: {len(step6c_evaluation):,}")
print("Using existing E5 + FAISS results.")
print("No re-embedding.")
print("No FAISS rebuild.")


# ------------------------------------------------------------
# 2. Calculate score gaps
# ------------------------------------------------------------

print("\n[2/4] Calculating Top-K score gaps...")

gap_records = []

for r in step6c_evaluation:

    retrieved = r["retrieved"]

    if len(retrieved) < 2:
        continue

    top1 = retrieved[0]["score"]
    top2 = retrieved[1]["score"]

    top5 = (
        retrieved[4]["score"]
        if len(retrieved) >= 5
        else np.nan
    )

    top10 = (
        retrieved[9]["score"]
        if len(retrieved) >= 10
        else np.nan
    )

    gap_records.append({
        "test_id": r["test_id"],
        "answerable": r["answerable"],
        "top1_score": top1,
        "top2_score": top2,
        "top5_score": top5,
        "top10_score": top10,
        "top1_top2_gap": top1 - top2,
        "top1_top5_gap": top1 - top5,
        "top1_top10_gap": top1 - top10
    })

gap_df = pd.DataFrame(gap_records)


# ------------------------------------------------------------
# 3. Analyze score gaps
# ------------------------------------------------------------

print("\n[3/4] Score-gap analysis...")

for group_name, mask in [
    ("ALL", np.ones(len(gap_df), dtype=bool)),
    ("ANSWERABLE", gap_df["answerable"].values),
    ("UNANSWERABLE", ~gap_df["answerable"].values)
]:

    group = gap_df[mask]

    print("\n" + "-" * 70)
    print(group_name)

    print(
        f"Top1 → Top2 gap mean   : "
        f"{group['top1_top2_gap'].mean():.4f}"
    )

    print(
        f"Top1 → Top2 gap median : "
        f"{group['top1_top2_gap'].median():.4f}"
    )

    print(
        f"Top1 → Top5 gap mean   : "
        f"{group['top1_top5_gap'].mean():.4f}"
    )

    print(
        f"Top1 → Top10 gap mean  : "
        f"{group['top1_top10_gap'].mean():.4f}"
    )


# ------------------------------------------------------------
# 4. Identify ambiguous vs confident retrievals
# ------------------------------------------------------------

print("\n[4/4] Identifying retrieval confidence groups...")

gap_df["confidence_group"] = pd.cut(
    gap_df["top1_top2_gap"],
    bins=[
        -np.inf,
        0.005,
        0.010,
        0.020,
        0.050,
        np.inf
    ],
    labels=[
        "very_ambiguous",
        "ambiguous",
        "moderate",
        "clear",
        "very_clear"
    ]
)

print("\nConfidence-group distribution:")

print(
    gap_df["confidence_group"]
    .value_counts()
    .sort_index()
)

print("\nAnswerable rate by confidence group:")

confidence_summary = (
    gap_df
    .groupby(
        "confidence_group",
        observed=False
    )["answerable"]
    .agg(
        ["count", "mean"]
    )
)

confidence_summary["answerable_rate"] = (
    confidence_summary["mean"]
)

display(confidence_summary)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6h_gap_analysis = gap_df

print("\n" + "=" * 70)
print("STEP 6H COMPLETED")
print("=" * 70)

print("\nSaved object:")
print("✓ step6h_gap_analysis")

print("\nIMPORTANT:")
print(
    "Score gaps are confidence diagnostics, "
    "not retrieval accuracy or Recall@K."
)

print(
    "No model, embeddings, FAISS index, or dataset was changed."
)

======================================================================
STEP 6H — TOP-K SEMANTIC RETRIEVAL QUALITY ANALYSIS
======================================================================

[1/4] Validating existing retrieval results...
Test queries: 500
Using existing E5 + FAISS results.
No re-embedding.
No FAISS rebuild.

[2/4] Calculating Top-K score gaps...

[3/4] Score-gap analysis...

----------------------------------------------------------------------
ALL
Top1 → Top2 gap mean   : 0.0000
Top1 → Top2 gap median : 0.0000
Top1 → Top5 gap mean   : 0.0035
Top1 → Top10 gap mean  : 0.0056

----------------------------------------------------------------------
ANSWERABLE
Top1 → Top2 gap mean   : 0.0000
Top1 → Top2 gap median : 0.0000
Top1 → Top5 gap mean   : 0.0032
Top1 → Top10 gap mean  : 0.0053

----------------------------------------------------------------------
UNANSWERABLE
Top1 → Top2 gap mean   : 0.0000
Top1 → Top2 gap median : 0.0000
Top1 → Top5 gap mean   : 0.0057
Top1 → Top10 gap mean  : 0.0078

[4/4] Identifying retrieval confidence groups...

Confidence-group distribution:
confidence_group
very_ambiguous    500
ambiguous           0
moderate            0
clear               0
very_clear          0
Name: count, dtype: int64

Answerable rate by confidence group:

                  count   mean  answerable_rate
confidence_group
very_ambiguous      500  0.892            0.892
ambiguous             0    NaN              NaN
moderate              0    NaN              NaN
clear                 0    NaN              NaN
very_clear            0    NaN              NaN

======================================================================
STEP 6H COMPLETED
======================================================================

Saved object:
✓ step6h_gap_analysis

IMPORTANT:
Score gaps are confidence diagnostics, not retrieval accuracy or Recall@K.
No model, embeddings, FAISS index, or dataset was changed.

In [33]:
# ============================================================
# STEP 6I — TOP-K SCORE TIE & TEXT DUPLICATION DIAGNOSTIC
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6I — TOP-K SCORE TIE & TEXT DUPLICATION DIAGNOSTIC")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing retrieval
# ------------------------------------------------------------

print("\n[1/4] Validating existing retrieval objects...")

assert "step6c_evaluation" in globals()
assert len(step6c_evaluation) == 500

print(f"Test queries: {len(step6c_evaluation):,}")
print("Using existing retrieval results only.")
print("No re-embedding.")
print("No FAISS rebuild.")


# ------------------------------------------------------------
# 2. Inspect retrieval structure
# ------------------------------------------------------------

print("\n[2/4] Inspecting Top-K score ties...")

tie_records = []

for r in step6c_evaluation:

    retrieved = r["retrieved"]

    if len(retrieved) < 2:
        continue

    scores = np.array(
        [item["score"] for item in retrieved],
        dtype=np.float64
    )

    top1 = scores[0]

    # Exact floating-point equality
    exact_top1_top2_tie = (
        scores[0] == scores[1]
    )

    # Very small numerical difference
    near_top1_top2_tie = (
        abs(scores[0] - scores[1]) < 1e-6
    )

    # Count how many Top-K scores are effectively tied
    near_tie_count = int(
        np.sum(np.abs(scores - top1) < 1e-6)
    )

    # Unique scores after rounding
    unique_scores_6dp = len(
        np.unique(np.round(scores, 6))
    )

    tie_records.append({
        "test_id": r["test_id"],
        "answerable": r["answerable"],
        "top1_score": scores[0],
        "top2_score": scores[1],
        "top1_top2_gap": scores[0] - scores[1],
        "exact_top1_top2_tie": exact_top1_top2_tie,
        "near_top1_top2_tie": near_top1_top2_tie,
        "near_tie_count_top10": near_tie_count,
        "unique_scores_top10_6dp": unique_scores_6dp
    })

tie_df = pd.DataFrame(tie_records)


# ------------------------------------------------------------
# 3. Summary of score ties
# ------------------------------------------------------------

print("\n[3/4] Score-tie summary...")

exact_ties = tie_df["exact_top1_top2_tie"].sum()
near_ties = tie_df["near_top1_top2_tie"].sum()

print(
    f"Exact Top1=Top2 ties      : "
    f"{exact_ties:,}/{len(tie_df):,}"
)

print(
    f"Near Top1≈Top2 ties (<1e-6): "
    f"{near_ties:,}/{len(tie_df):,}"
)

print(
    f"Mean near-tied results "
    f"inside Top-10           : "
    f"{tie_df['near_tie_count_top10'].mean():.2f}"
)

print(
    f"Median near-tied results "
    f"inside Top-10           : "
    f"{tie_df['near_tie_count_top10'].median():.0f}"
)

print(
    f"Mean unique scores "
    f"inside Top-10 (6 decimals): "
    f"{tie_df['unique_scores_top10_6dp'].mean():.2f}"
)


# ------------------------------------------------------------
# 4. Inspect representative tied queries
# ------------------------------------------------------------

print("\n[4/4] Representative Top-K ties...")

tied_ids = tie_df[
    tie_df["near_top1_top2_tie"]
].head(10)["test_id"].tolist()

for test_id in tied_ids:

    row = next(
        r for r in step6c_evaluation
        if r["test_id"] == test_id
    )

    print("\n" + "-" * 70)
    print(f"Test ID     : {row['test_id']}")
    print(f"Question    : {row['question']}")
    print(f"Answerable  : {row['answerable']}")

    print("\nTop-5 retrieved:")

    for rank, item in enumerate(
        row["retrieved"][:5],
        start=1
    ):

        print(
            f"{rank}. "
            f"ID={item.get('id')} | "
            f"chunk={item.get('chunk_idx')} | "
            f"score={item.get('score'):.8f}"
        )

        if "text" in item:
            print(
                f"   text={item['text'][:180]}"
            )
        elif "chunk_text" in item:
            print(
                f"   text={item['chunk_text'][:180]}"
            )


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6i_tie_diagnostic = tie_df

print("\n" + "=" * 70)
print("STEP 6I COMPLETED")
print("=" * 70)

print("\nSaved object:")
print("✓ step6i_tie_diagnostic")

print("\nIMPORTANT:")
print(
    "This step diagnoses score ties and Top-K behavior only."
)

print(
    "It does NOT measure retrieval accuracy or Recall@K."
)

print(
    "No model, embeddings, FAISS index, or dataset was changed."
)

======================================================================
STEP 6I — TOP-K SCORE TIE & TEXT DUPLICATION DIAGNOSTIC
======================================================================

[1/4] Validating existing retrieval objects...
Test queries: 500
Using existing retrieval results only.
No re-embedding.
No FAISS rebuild.

[2/4] Inspecting Top-K score ties...

[3/4] Score-tie summary...
Exact Top1=Top2 ties      : 427/500
Near Top1≈Top2 ties (<1e-6): 500/500
Mean near-tied results inside Top-10           : 3.99
Median near-tied results inside Top-10           : 4
Mean unique scores inside Top-10 (6 decimals): 3.14

[4/4] Representative Top-K ties...

----------------------------------------------------------------------
Test ID     : 6875-0
Question    : أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
Answerable  : True

Top-5 retrieved:
1. ID=1398-3 | chunk=3 | score=0.85624039
   text=لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد
2. ID=1398-2 | chunk=3 | score=0.85624039
   text=لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد
3. ID=1398-1 | chunk=3 | score=0.85624039
   text=لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد
4. ID=1398-0 | chunk=3 | score=0.85624039
   text=لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد
5. ID=5427-3 | chunk=5 | score=0.85445118
   text=لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.

----------------------------------------------------------------------
Test ID     : 6875-1
Question    : فاتورة زائدة. متر إضافي كم سعره؟
Answerable  : True

Top-5 retrieved:
1. ID=3228-3 | chunk=3 | score=0.86500394
   text=تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشه
2. ID=3228-0 | chunk=3 | score=0.86500394
   text=تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشه
3. ID=3228-2 | chunk=3 | score=0.86500382
   text=تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشه
4. ID=3228-1 | chunk=3 | score=0.86500382
   text=تفرض الشركة رسوماً إضافية في حال تجاوز الحد الأقصى للاستهلاك المحدد في الباقة؛ حيث يتم احتساب كل متر مكعب إضافي بسعر 12 جنيهاً مصرياً. يتم إضافة هذه الرسوم تلقائياً إلى فاتورة الشه
5. ID=0-1 | chunk=1 | score=0.85968667
   text=تفرض الشركة رسوماً إضافية في حال تجاوز الحد المسموح به في الباقة، حيث يتم احتساب كل متر مكعب إضافي بسعر 0.700 ريال عماني. يتم تحصيل هذه الرسوم تلقائياً في فاتورة الشهر التالي وتظهر

----------------------------------------------------------------------
Test ID     : 6875-2
Question    : السلام عليكم، أنا مشترك لديكم منذ فترة وأرغب في تحويل اشتراكي إلى خاصية الدفع التلقائي لضمان عدم التأخر في السداد، هل هناك أي ميزات أو خصومات عند تفعيل هذه الخاصية؟
Answerable  : True

Top-5 retrieved:
1. ID=2494-2 | chunk=5 | score=0.85984558
   text=يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على
2. ID=2494-1 | chunk=5 | score=0.85984558
   text=يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على
3. ID=2494-3 | chunk=5 | score=0.85984540
   text=يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على
4. ID=2494-0 | chunk=5 | score=0.85984540
   text=يتم تجديد الاشتراكات السنوية تلقائياً بخصم ١٥٪ من القيمة الإجمالية إذا تم تفعيل خاصية الدفع التلقائي. يمكن إلغاء التجديد التلقائي من إعدادات الحساب قبل موعد التجديد بـ ٤٨ ساعة على
5. ID=274-3 | chunk=2 | score=0.85483962
   text=لترقية الاشتراك، يمكن للمستخدم الانتقال من الباقة الأساسية إلى المتقدمة أو المميزة عبر قسم إدارة الحساب. يتم احتساب فرق السعر فقط للأيام المتبقية من الشهر الحالي، ويتم تفعيل المزاي

----------------------------------------------------------------------
Test ID     : 6875-3
Question    : تحية طيبة، أفكر في تغيير باقتي الحالية وأود معرفة الفرق بين الباقة الفضية والباقة الذهبية من حيث التكلفة الشهرية وكمية المياه المتاحة لكل منهما، وشكراً لكم.
Answerable  : True

Top-5 retrieved:
1. ID=3970-3 | chunk=1 | score=0.86274379
   text=تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة
2. ID=3970-2 | chunk=1 | score=0.86274379
   text=تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة
3. ID=3970-1 | chunk=1 | score=0.86274379
   text=تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة
4. ID=3970-0 | chunk=1 | score=0.86274379
   text=تتوفر باقتان أساسيتان: الباقة الفضية وتوفر 20 قارورة شهرياً بسعر 15 دينار كويتي، والباقة الذهبية وتوفر 50 قارورة شهرياً بسعر 30 دينار كويتي. تمنح الباقة الذهبية العميل خصماً بنسبة
5. ID=3289-3 | chunk=5 | score=0.85871577
   text=لترقية الباقة من الفضية إلى الذهبية، يجب دفع فارق السعر وهو 2500 ريال سعودي. يتم تفعيل التغطية الجديدة فوراً بعد سداد المبلغ، وتطبق الشروط والحدود الخاصة بالباقة الذهبية على جميع ا

----------------------------------------------------------------------
Test ID     : 6876-0
Question    : أنا غاضب جداً! لقد اشتريت خزانة ملابس وبها كسر في الرف السفلي، أريد استبدالها الآن فوراً، أين هي سياسة استبدال القطع التالفة بالتحديد؟
Answerable  : False

Top-5 retrieved:
1. ID=2116-2 | chunk=3 | score=0.87289822
   text=تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي
2. ID=2116-1 | chunk=3 | score=0.87289822
   text=تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي
3. ID=2116-0 | chunk=3 | score=0.87289822
   text=تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي
4. ID=2116-3 | chunk=3 | score=0.87289810
   text=تطبق سياسة الاستبدال على قطع الأثاث التالفة عند الاستلام فقط، ويجب الإبلاغ عن التلف في غضون 24 ساعة من وصول الشحنة. يتم استبدال القطعة بقطعة جديدة مطابقة للمواصفات مجاناً وبدون أي
5. ID=3999-3 | chunk=4 | score=0.84751141
   text=تتيح الشركة استبدال القطع التالفة خلال ١٤ يوماً من تاريخ الاستلام بشرط وجود الفاتورة الأصلية وأن يكون المنتج بحالته الأصلية. يتم الاستبدال مجاناً إذا كان التلف ناتجاً عن الشحن أو خ

----------------------------------------------------------------------
Test ID     : 6876-1
Question    : طاولة رخام خدوش. ماذا أفعل؟
Answerable  : True

Top-5 retrieved:
1. ID=1192-0 | chunk=0 | score=0.81640327
   text=تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد
2. ID=1192-3 | chunk=0 | score=0.81640315
   text=تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد
3. ID=1192-2 | chunk=0 | score=0.81640315
   text=تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد
4. ID=1192-1 | chunk=0 | score=0.81640315
   text=تتوفر لدينا طاولة 'سديم' الخشبية بسعر 1200 ريال سعودي وبأبعاد 180×90 سم، بينما تتوفر طاولة 'أفق' الرخامية بسعر 2500 ريال سعودي وبأبعاد 200×100 سم. كلاهما يأتي مع ضمان لمدة سنتين ضد
5. ID=4180-3 | chunk=0 | score=0.81116593
   text=تتوفر طاولة 'سديم' الخشبية بسعر 120 دينار كويتي، وهي مصنوعة من خشب الجوز الطبيعي بطول 180 سم وعرض 90 سم. أما طاولة 'أفق' الزجاجية فتباع بسعر 85 دينار كويتي، وتتميز بسطح من الزجاج ا

----------------------------------------------------------------------
Test ID     : 6876-2
Question    : لقد انتظرت طويلاً ولم تصل غرفة النوم! أخبروني فوراً كم يستغرق التوصيل إلى محافظة ظفار وما هي التكلفة؟
Answerable  : True

Top-5 retrieved:
1. ID=2657-3 | chunk=1 | score=0.86188316
   text=تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.
2. ID=2657-1 | chunk=1 | score=0.86188316
   text=تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.
3. ID=2657-0 | chunk=1 | score=0.86188316
   text=تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.
4. ID=2657-2 | chunk=1 | score=0.86188310
   text=تغطي خدماتنا كافة ولايات محافظة مسقط ومحافظة ظفار. يستغرق التوصيل عادةً ما بين 30 إلى 50 دقيقة، بينما قد يمتد إلى 75 دقيقة في أوقات الذروة أو الظروف الجوية القاسية.
5. ID=2579-3 | chunk=2 | score=0.85819447
   text=تكلفة خدمة التوصيل والتركيب داخل محافظة مسقط هي 15 ريال عماني فقط. أما بالنسبة للمحافظات الأخرى مثل صلالة أو صحار، فإن تكلفة التوصيل تبلغ 30 ريال عماني، ويتم التنفيذ خلال 3 إلى 7 أ

----------------------------------------------------------------------
Test ID     : 6876-3
Question    : غرفة سلطان. موعد التركيب؟
Answerable  : True

Top-5 retrieved:
1. ID=3068-3 | chunk=3 | score=0.82483047
   text=طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض
2. ID=3068-2 | chunk=3 | score=0.82483047
   text=طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض
3. ID=3068-1 | chunk=3 | score=0.82483047
   text=طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض
4. ID=3068-0 | chunk=3 | score=0.82483047
   text=طقم غرفة النوم 'السلطان' يتكون من سرير مقاس ٢٠٠*١٨٠ سم وخزانة ملابس بـ ٤ أبواب، وسعره ١٢٠٠ ريال عماني. يتم تصنيعه من خشب الزان الطبيعي ويأتي بـ ٣ ألوان متوفرة: البني الداكن، الأبيض
5. ID=5505-3 | chunk=0 | score=0.82385707
   text=طقم غرفة المعيشة 'سلطان' يتكون من أريكة ثلاثية ومقعدين منفردين، مصنوع من خشب الزان الطبيعي والكتان الفاخر، وسعره 450 ديناراً بحرينياً. يتوفر هذا الطقم بثلاثة ألوان: البيج، الرمادي،

----------------------------------------------------------------------
Test ID     : 6877-0
Question    : أريد معرفة الفرق بين نجم 10 ونجم 12 بسرعة! لماذا السعر مختلف بهذا الشكل وما هي سعة الذاكرة في كل منهما؟ أنا مستعجل جداً!
Answerable  : True

Top-5 retrieved:
1. ID=5269-3 | chunk=2 | score=0.89014626
   text=هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره
2. ID=5269-2 | chunk=2 | score=0.89014626
   text=هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره
3. ID=5269-1 | chunk=2 | score=0.89014626
   text=هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره
4. ID=5269-0 | chunk=2 | score=0.89014626
   text=هاتف 'نجم 10' يأتي بذاكرة عشوائية 8 جيجابايت ومساحة تخزين 256 جيجابايت وسعره 65000 دينار جزائري. أما هاتف 'نجم 12' فيتميز بذاكرة عشوائية 12 جيجابايت ومساحة تخزين 512 جيجابايت وسعره
5. ID=4285-3 | chunk=0 | score=0.86120796
   text=توفر شركة رفاه هاتف 'نجم 10' بسعر 450,000 دينار عراقي، ويتميز بذاكرة 128 جيجابايت وكاميرا بدقة 50 ميجابكسل. أما هاتف 'نجم 11' فيتوفر بسعر 600,000 دينار عراقي، ويأتي بذاكرة 256 جيجا

----------------------------------------------------------------------
Test ID     : 6877-1
Question    : تبديل منتج تالف. الشروط؟
Answerable  : False

Top-5 retrieved:
1. ID=3914-2 | chunk=5 | score=0.86009461
   text=إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال
2. ID=3914-1 | chunk=5 | score=0.86009455
   text=إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال
3. ID=3914-0 | chunk=5 | score=0.86009455
   text=إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال
4. ID=3914-3 | chunk=5 | score=0.86009443
   text=إجراءات معالجة التلف: في حال وصول المنتج تالفاً، يجب على العميل تصوير التلف وإرسال الصور عبر البريد الإلكتروني خلال 48 ساعة من الاستلام. ستقوم الشركة بإرسال فريق فني للمعاينة خلال
5. ID=3999-3 | chunk=4 | score=0.85006988
   text=تتيح الشركة استبدال القطع التالفة خلال ١٤ يوماً من تاريخ الاستلام بشرط وجود الفاتورة الأصلية وأن يكون المنتج بحالته الأصلية. يتم الاستبدال مجاناً إذا كان التلف ناتجاً عن الشحن أو خ

======================================================================
STEP 6I COMPLETED
======================================================================

Saved object:
✓ step6i_tie_diagnostic

IMPORTANT:
This step diagnoses score ties and Top-K behavior only.
It does NOT measure retrieval accuracy or Recall@K.
No model, embeddings, FAISS index, or dataset was changed.

In [36]:
# ============================================================
# STEP 6J — RESTORE TRAIN CORPUS + DUPLICATION ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6J — RESTORE TRAIN CORPUS + DUPLICATION ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Restore train corpus if missing
# ------------------------------------------------------------

print("\n[1/5] Checking train corpus...")

if "train_corpus" not in globals():

    print("train_corpus not found.")
    print("Restoring from existing train_df...")

    assert "train_df" in globals(), (
        "train_df is also missing. "
        "Please load the existing train.parquet first."
    )

    def build_chunk_corpus(df):

        records = []

        for row_idx, row in df.iterrows():

            chunks = row["chunks"]

            for chunk_idx, chunk_text in enumerate(chunks):

                records.append({
                    "row_idx": row_idx,
                    "id": row["id"],
                    "company_id": row["company_id"],
                    "company": row["company"],
                    "domain": row["domain"],
                    "country": row["country"],
                    "chunk_idx": chunk_idx,
                    "chunk_text": chunk_text,
                    "question": row["question"],
                    "answer": row["answer"],
                    "answerable": row["answerable"]
                })

        return pd.DataFrame(records)

    train_corpus = build_chunk_corpus(train_df)

    print(
        f"✓ train_corpus restored: "
        f"{len(train_corpus):,} chunks"
    )

else:

    print(
        f"✓ train_corpus already exists: "
        f"{len(train_corpus):,} chunks"
    )


# ------------------------------------------------------------
# 2. Exact text duplication
# ------------------------------------------------------------

print("\n[2/5] Checking exact chunk-text duplication...")

text_series = (
    train_corpus["chunk_text"]
    .fillna("")
    .astype(str)
    .str.strip()
)

total_chunks = len(text_series)

unique_text_count = text_series.nunique()

duplicate_chunk_count = (
    total_chunks - unique_text_count
)

text_counts = text_series.value_counts()

duplicated_text_values = text_counts[
    text_counts > 1
]

print(
    f"Total chunk slots       : "
    f"{total_chunks:,}"
)

print(
    f"Unique chunk texts      : "
    f"{unique_text_count:,}"
)

print(
    f"Duplicate chunk slots   : "
    f"{duplicate_chunk_count:,}"
)

print(
    f"Duplicated text patterns: "
    f"{len(duplicated_text_values):,}"
)

print(
    f"Duplication slot rate   : "
    f"{duplicate_chunk_count / total_chunks:.2%}"
)


# ------------------------------------------------------------
# 3. Cross-ID duplication
# ------------------------------------------------------------

print("\n[3/5] Analyzing duplication across different IDs...")

dup_texts = set(
    duplicated_text_values.index
)

dup_mask = text_series.isin(dup_texts)

dup_corpus = train_corpus.loc[
    dup_mask,
    ["id", "chunk_idx", "chunk_text"]
].copy()

cross_id_stats = []

for text, group in dup_corpus.groupby(
    "chunk_text",
    sort=False
):

    unique_ids = group["id"].nunique()
    total_slots = len(group)

    cross_id_stats.append({
        "chunk_text": text,
        "total_slots": total_slots,
        "unique_ids": unique_ids,
        "cross_id_duplicate": unique_ids > 1
    })

cross_id_df = pd.DataFrame(cross_id_stats)

if len(cross_id_df) > 0:

    cross_id_patterns = int(
        cross_id_df["cross_id_duplicate"].sum()
    )

    cross_id_slots = int(
        cross_id_df.loc[
            cross_id_df["cross_id_duplicate"],
            "total_slots"
        ].sum()
    )

else:

    cross_id_patterns = 0
    cross_id_slots = 0


print(
    f"Duplicated patterns across different IDs : "
    f"{cross_id_patterns:,}"
)

print(
    f"Chunk slots in cross-ID duplicates       : "
    f"{cross_id_slots:,}"
)


# ------------------------------------------------------------
# 4. Duplication statistics
# ------------------------------------------------------------

print("\n[4/5] Duplication statistics...")

if len(duplicated_text_values) > 0:

    print(
        f"Mean copies per duplicated text   : "
        f"{duplicated_text_values.mean():.2f}"
    )

    print(
        f"Median copies per duplicated text : "
        f"{duplicated_text_values.median():.0f}"
    )

    print(
        f"Maximum copies of one text        : "
        f"{duplicated_text_values.max():,}"
    )


# ------------------------------------------------------------
# 5. Most duplicated examples
# ------------------------------------------------------------

print("\n[5/5] Most duplicated chunk texts...")

for rank, (text, count) in enumerate(
    duplicated_text_values.head(10).items(),
    start=1
):

    matching = train_corpus[
        train_corpus["chunk_text"].astype(str).str.strip() == text
    ]

    print("\n" + "-" * 70)

    print(f"Rank       : {rank}")
    print(f"Copies     : {count}")
    print(f"Unique IDs : {matching['id'].nunique()}")

    print(
        f"IDs        : "
        f"{matching['id'].tolist()[:10]}"
    )

    print(
        f"Chunks     : "
        f"{matching['chunk_idx'].tolist()[:10]}"
    )

    print(
        f"Text       : "
        f"{text[:300]}"
    )


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6j_duplication_analysis = {
    "total_chunks": total_chunks,
    "unique_chunk_texts": unique_text_count,
    "duplicate_chunk_slots": duplicate_chunk_count,
    "duplicated_text_patterns": len(duplicated_text_values),
    "duplication_slot_rate": duplicate_chunk_count / total_chunks,
    "cross_id_duplicate_patterns": cross_id_patterns,
    "cross_id_duplicate_slots": cross_id_slots,
    "duplicate_text_counts": duplicated_text_values,
    "cross_id_details": cross_id_df
}

print("\n" + "=" * 70)
print("STEP 6J COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ train_corpus")
print("✓ step6j_duplication_analysis")

print("\nIMPORTANT:")
print("No embeddings were recomputed.")
print("No FAISS index was rebuilt.")
print("No dataset rows or chunks were modified.")

======================================================================
STEP 6J — RESTORE TRAIN CORPUS + DUPLICATION ANALYSIS
======================================================================

[1/5] Checking train corpus...
train_corpus not found.
Restoring from existing train_df...
✓ train_corpus restored: 164,456 chunks

[2/5] Checking exact chunk-text duplication...
Total chunk slots       : 164,456
Unique chunk texts      : 41,179
Duplicate chunk slots   : 123,277
Duplicated text patterns: 41,179
Duplication slot rate   : 74.96%

[3/5] Analyzing duplication across different IDs...
Duplicated patterns across different IDs : 41,179
Chunk slots in cross-ID duplicates       : 164,456

[4/5] Duplication statistics...
Mean copies per duplicated text   : 3.99
Median copies per duplicated text : 4
Maximum copies of one text        : 12

[5/5] Most duplicated chunk texts...

----------------------------------------------------------------------
Rank       : 1
Copies     : 12
Unique IDs : 12
IDs        : ['141-0', '141-1', '141-2', '141-3', '192-0', '192-1', '192-2', '192-3', '4289-0', '4289-1']
Chunks     : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Text       : تتيح سياسة الإلغاء استرداد المبلغ كاملاً بنسبة 100% إذا تم إلغاء الحجز قبل موعد الوصول بـ 48 ساعة على الأقل. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى من المبلغ المسترد كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Rank       : 2
Copies     : 12
Unique IDs : 12
IDs        : ['858-0', '858-1', '858-2', '858-3', '2828-0', '2828-1', '2828-2', '2828-3', '2944-0', '2944-1']
Chunks     : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Text       : تسمح سياسة الإلغاء باسترداد كامل المبلغ بنسبة 100% إذا تم إلغاء الحجز قبل موعد الوصول بـ 48 ساعة على الأقل. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى من المبلغ المسترد كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Rank       : 3
Copies     : 12
Unique IDs : 12
IDs        : ['3598-0', '3598-1', '3598-2', '3598-3', '3624-0', '3624-1', '3624-2', '3624-3', '5903-0', '5903-1']
Chunks     : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
Text       : تسمح سياسة الإلغاء باسترداد كامل المبلغ بنسبة 100% إذا تم إلغاء الحجز قبل 48 ساعة من موعد الوصول. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم 50% من قيمة الليلة الأولى كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Rank       : 4
Copies     : 8
Unique IDs : 8
IDs        : ['329-0', '329-1', '329-2', '329-3', '5221-0', '5221-1', '5221-2', '5221-3']
Chunks     : [2, 2, 2, 2, 1, 1, 1, 1]
Text       : سياسة الإلغاء: يمكن للعميل إلغاء الحجز مجاناً قبل 48 ساعة من موعد الوصول. في حال الإلغاء خلال أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى بنسبة 100% من المبلغ المسترد. يتم تحويل المبالغ المستردة إلى الحساب البنكي خلال 7 أيام عمل.

----------------------------------------------------------------------
Rank       : 5
Copies     : 8
Unique IDs : 8
IDs        : ['509-0', '509-1', '509-2', '509-3', '1325-0', '1325-1', '1325-2', '1325-3']
Chunks     : [5, 5, 5, 5, 4, 4, 4, 4]
Text       : تتطلب الخدمة سرعة إنترنت لا تقل عن 5 ميجابت في الثانية للباقة الفضية، و25 ميجابت في الثانية للباقة الذهبية لضمان استقرار البث ومنع التقطيع أثناء المشاهدة بدقة عالية.

----------------------------------------------------------------------
Rank       : 6
Copies     : 8
Unique IDs : 8
IDs        : ['591-0', '591-1', '591-2', '591-3', '3069-0', '3069-1', '3069-2', '3069-3']
Chunks     : [3, 3, 3, 3, 1, 1, 1, 1]
Text       : تسمح سياسة الإلغاء باسترداد كامل المبلغ بنسبة 100% إذا تم إلغاء الحجز قبل موعد الوصول بـ 48 ساعة على الأقل. في حال الإلغاء خلال أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى من المبلغ المسترد، ولا يمكن استرداد أي مبالغ في حال عدم الحضور.

----------------------------------------------------------------------
Rank       : 7
Copies     : 8
Unique IDs : 8
IDs        : ['739-0', '739-1', '739-2', '739-3', '6398-0', '6398-1', '6398-2', '6398-3']
Chunks     : [3, 3, 3, 3, 4, 4, 4, 4]
Text       : تضمن الشركة جميع الأجهزة الإلكترونية لمدة ٢٤ شهراً ضد عيوب التصنيع. لا يشمل الضمان الكسور الناتجة عن سوء الاستخدام أو التعرض للسوائل، ويجب تقديم الفاتورة الأصلية عند طلب الصيانة.

----------------------------------------------------------------------
Rank       : 8
Copies     : 8
Unique IDs : 8
IDs        : ['823-0', '823-1', '823-2', '823-3', '4912-0', '4912-1', '4912-2', '4912-3']
Chunks     : [4, 4, 4, 4, 5, 5, 5, 5]
Text       : تتطلب الخدمة سرعة إنترنت لا تقل عن 5 ميجابت في الثانية للباقة الأساسية، و25 ميجابت في الثانية للباقة المميزة لضمان جودة البث دون انقطاع.

----------------------------------------------------------------------
Rank       : 9
Copies     : 8
Unique IDs : 8
IDs        : ['1016-0', '1016-1', '1016-2', '1016-3', '5291-0', '5291-1', '5291-2', '5291-3']
Chunks     : [4, 4, 4, 4, 4, 4, 4, 4]
Text       : تضمن الشركة جميع الأجهزة الإلكترونية لمدة 12 شهراً ضد عيوب التصنيع، ولا يشمل الضمان الكسور الناتجة عن سوء الاستخدام أو التعرض للسوائل.

----------------------------------------------------------------------
Rank       : 10
Copies     : 8
Unique IDs : 8
IDs        : ['1073-0', '1073-1', '1073-2', '1073-3', '2039-0', '2039-1', '2039-2', '2039-3']
Chunks     : [2, 2, 2, 2, 2, 2, 2, 2]
Text       : سياسة الإلغاء: يمكن للعميل إلغاء الحجز واسترداد المبلغ كاملاً بنسبة 100% إذا تم الإلغاء قبل 48 ساعة من موعد الاستلام. إذا تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم 20% من قيمة اليوم الأول كرسوم إدارية.

======================================================================
STEP 6J COMPLETED
======================================================================

Saved objects:
✓ train_corpus
✓ step6j_duplication_analysis

IMPORTANT:
No embeddings were recomputed.
No FAISS index was rebuilt.
No dataset rows or chunks were modified.

In [37]:
# ============================================================
# STEP 6K — DUPLICATE CONTENT METADATA ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6K — DUPLICATE CONTENT METADATA ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate restored corpus
# ------------------------------------------------------------

print("\n[1/5] Validating train corpus...")

assert "train_corpus" in globals()
assert "step6j_duplication_analysis" in globals()

print(
    f"Train corpus chunks: "
    f"{len(train_corpus):,}"
)


# ------------------------------------------------------------
# 2. Select duplicated texts only
# ------------------------------------------------------------

print("\n[2/5] Building duplicated-content groups...")

text_series = (
    train_corpus["chunk_text"]
    .fillna("")
    .astype(str)
    .str.strip()
)

text_counts = text_series.value_counts()

duplicated_texts = set(
    text_counts[text_counts > 1].index
)

dup_corpus = train_corpus[
    text_series.isin(duplicated_texts)
].copy()

print(
    f"Duplicated text patterns: "
    f"{len(duplicated_texts):,}"
)

print(
    f"Chunk slots involved    : "
    f"{len(dup_corpus):,}"
)


# ------------------------------------------------------------
# 3. Analyze metadata diversity per duplicated text
# ------------------------------------------------------------

print("\n[3/5] Measuring metadata diversity...")

group_records = []

for text, group in dup_corpus.groupby(
    "chunk_text",
    sort=False
):

    group_records.append({

        "chunk_text": text,

        "copies": len(group),

        "unique_ids":
            group["id"].nunique(),

        "unique_company_ids":
            group["company_id"].nunique(),

        "unique_companies":
            group["company"].nunique(),

        "unique_domains":
            group["domain"].nunique(),

        "unique_countries":
            group["country"].nunique(),

        "same_domain":
            group["domain"].nunique() == 1,

        "same_country":
            group["country"].nunique() == 1,

        "same_company":
            group["company_id"].nunique() == 1
    })


duplicate_groups_df = pd.DataFrame(
    group_records
)


# ------------------------------------------------------------
# 4. Summary
# ------------------------------------------------------------

print("\n[4/5] Duplicate-group summary...")

print(
    f"Mean unique IDs per duplicated text      : "
    f"{duplicate_groups_df['unique_ids'].mean():.2f}"
)

print(
    f"Mean unique companies per duplicated text: "
    f"{duplicate_groups_df['unique_companies'].mean():.2f}"
)

print(
    f"Mean unique domains per duplicated text  : "
    f"{duplicate_groups_df['unique_domains'].mean():.2f}"
)

print(
    f"Mean unique countries per duplicated text: "
    f"{duplicate_groups_df['unique_countries'].mean():.2f}"
)

print(
    f"Same-company duplicated groups : "
    f"{duplicate_groups_df['same_company'].sum():,}"
)

print(
    f"Same-domain duplicated groups  : "
    f"{duplicate_groups_df['same_domain'].sum():,}"
)

print(
    f"Same-country duplicated groups : "
    f"{duplicate_groups_df['same_country'].sum():,}"
)

print(
    f"Cross-domain duplicated groups : "
    f"{(~duplicate_groups_df['same_domain']).sum():,}"
)

print(
    f"Cross-country duplicated groups: "
    f"{(~duplicate_groups_df['same_country']).sum():,}"
)


# ------------------------------------------------------------
# 5. Representative cross-metadata duplicates
# ------------------------------------------------------------

print("\n[5/5] Representative cross-metadata duplicates...")

cross_domain = duplicate_groups_df[
    ~duplicate_groups_df["same_domain"]
].sort_values(
    ["copies", "unique_domains"],
    ascending=False
)

cross_country = duplicate_groups_df[
    ~duplicate_groups_df["same_country"]
].sort_values(
    ["copies", "unique_countries"],
    ascending=False
)


print("\nCross-domain duplicate examples:")

for rank, row in enumerate(
    cross_domain.head(5).itertuples(index=False),
    start=1
):

    matching = dup_corpus[
        dup_corpus["chunk_text"] == row.chunk_text
    ]

    print("\n" + "-" * 70)
    print(f"Example {rank}")
    print(f"Copies   : {row.copies}")
    print(
        f"Domains  : "
        f"{matching['domain'].unique().tolist()}"
    )
    print(
        f"Countries: "
        f"{matching['country'].unique().tolist()}"
    )
    print(
        f"IDs      : "
        f"{matching['id'].tolist()[:12]}"
    )
    print(
        f"Text     : "
        f"{row.chunk_text[:300]}"
    )


print("\nCross-country duplicate examples:")

for rank, row in enumerate(
    cross_country.head(5).itertuples(index=False),
    start=1
):

    matching = dup_corpus[
        dup_corpus["chunk_text"] == row.chunk_text
    ]

    print("\n" + "-" * 70)
    print(f"Example {rank}")
    print(f"Copies   : {row.copies}")
    print(
        f"Domains  : "
        f"{matching['domain'].unique().tolist()}"
    )
    print(
        f"Countries: "
        f"{matching['country'].unique().tolist()}"
    )
    print(
        f"IDs      : "
        f"{matching['id'].tolist()[:12]}"
    )
    print(
        f"Text     : "
        f"{row.chunk_text[:300]}"
    )


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6k_duplicate_groups = duplicate_groups_df

print("\n" + "=" * 70)
print("STEP 6K COMPLETED")
print("=" * 70)

print("\nSaved object:")
print("✓ step6k_duplicate_groups")

print("\nIMPORTANT:")
print(
    "This step only analyzes metadata diversity "
    "inside duplicated chunk groups."
)

print(
    "No chunks were removed."
)

print(
    "No embeddings were recomputed."
)

print(
    "No FAISS index was rebuilt."
)

======================================================================
STEP 6K — DUPLICATE CONTENT METADATA ANALYSIS
======================================================================

[1/5] Validating train corpus...
Train corpus chunks: 164,456

[2/5] Building duplicated-content groups...
Duplicated text patterns: 41,179
Chunk slots involved    : 164,456

[3/5] Measuring metadata diversity...

[4/5] Duplicate-group summary...
Mean unique IDs per duplicated text      : 3.99
Mean unique companies per duplicated text: 1.00
Mean unique domains per duplicated text  : 1.00
Mean unique countries per duplicated text: 1.00
Same-company duplicated groups : 41,155
Same-domain duplicated groups  : 41,179
Same-country duplicated groups : 41,158
Cross-domain duplicated groups : 0
Cross-country duplicated groups: 21

[5/5] Representative cross-metadata duplicates...

Cross-domain duplicate examples:

Cross-country duplicate examples:

----------------------------------------------------------------------
Example 1
Copies   : 12
Domains  : ['hotel chain']
Countries: ['Morocco', 'Kuwait', 'Bahrain']
IDs      : ['141-0', '141-1', '141-2', '141-3', '192-0', '192-1', '192-2', '192-3', '4289-0', '4289-1', '4289-2', '4289-3']
Text     : تتيح سياسة الإلغاء استرداد المبلغ كاملاً بنسبة 100% إذا تم إلغاء الحجز قبل موعد الوصول بـ 48 ساعة على الأقل. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى من المبلغ المسترد كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Example 2
Copies   : 12
Domains  : ['hotel chain']
Countries: ['Algeria', 'Bahrain']
IDs      : ['858-0', '858-1', '858-2', '858-3', '2828-0', '2828-1', '2828-2', '2828-3', '2944-0', '2944-1', '2944-2', '2944-3']
Text     : تسمح سياسة الإلغاء باسترداد كامل المبلغ بنسبة 100% إذا تم إلغاء الحجز قبل موعد الوصول بـ 48 ساعة على الأقل. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى من المبلغ المسترد كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Example 3
Copies   : 12
Domains  : ['hotel chain']
Countries: ['Algeria', 'Lebanon']
IDs      : ['3598-0', '3598-1', '3598-2', '3598-3', '3624-0', '3624-1', '3624-2', '3624-3', '5903-0', '5903-1', '5903-2', '5903-3']
Text     : تسمح سياسة الإلغاء باسترداد كامل المبلغ بنسبة 100% إذا تم إلغاء الحجز قبل 48 ساعة من موعد الوصول. في حال تم الإلغاء خلال فترة أقل من 48 ساعة، يتم خصم 50% من قيمة الليلة الأولى كرسوم إلغاء إدارية.

----------------------------------------------------------------------
Example 4
Copies   : 8
Domains  : ['hotel chain']
Countries: ['Jordan', 'Lebanon']
IDs      : ['329-0', '329-1', '329-2', '329-3', '5221-0', '5221-1', '5221-2', '5221-3']
Text     : سياسة الإلغاء: يمكن للعميل إلغاء الحجز مجاناً قبل 48 ساعة من موعد الوصول. في حال الإلغاء خلال أقل من 48 ساعة، يتم خصم قيمة الليلة الأولى بنسبة 100% من المبلغ المسترد. يتم تحويل المبالغ المستردة إلى الحساب البنكي خلال 7 أيام عمل.

----------------------------------------------------------------------
Example 5
Copies   : 8
Domains  : ['streaming service']
Countries: ['Lebanon', 'Iraq']
IDs      : ['509-0', '509-1', '509-2', '509-3', '1325-0', '1325-1', '1325-2', '1325-3']
Text     : تتطلب الخدمة سرعة إنترنت لا تقل عن 5 ميجابت في الثانية للباقة الفضية، و25 ميجابت في الثانية للباقة الذهبية لضمان استقرار البث ومنع التقطيع أثناء المشاهدة بدقة عالية.

======================================================================
STEP 6K COMPLETED
======================================================================

Saved object:
✓ step6k_duplicate_groups

IMPORTANT:
This step only analyzes metadata diversity inside duplicated chunk groups.
No chunks were removed.
No embeddings were recomputed.
No FAISS index was rebuilt.

In [38]:
# ============================================================
# STEP 6L — BUILD UNIQUE CONTENT MAPPING
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6L — BUILD UNIQUE CONTENT MAPPING")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing corpus
# ------------------------------------------------------------

print("\n[1/5] Validating train corpus...")

assert "train_corpus" in globals()

print(
    f"Original train chunks: "
    f"{len(train_corpus):,}"
)


# ------------------------------------------------------------
# 2. Build unique-content table
# ------------------------------------------------------------

print("\n[2/5] Building unique-content table...")

corpus = train_corpus.copy()

corpus["chunk_text"] = (
    corpus["chunk_text"]
    .fillna("")
    .astype(str)
    .str.strip()
)

# First occurrence of every unique text
unique_mask = ~corpus["chunk_text"].duplicated(
    keep="first"
)

unique_corpus = corpus.loc[
    unique_mask
].copy()

unique_corpus = unique_corpus.reset_index(
    drop=False
)

unique_corpus = unique_corpus.rename(
    columns={"index": "original_corpus_idx"}
)

unique_corpus["unique_content_id"] = (
    np.arange(len(unique_corpus))
)

print(
    f"Unique content records: "
    f"{len(unique_corpus):,}"
)

print(
    f"Compression ratio: "
    f"{len(unique_corpus) / len(corpus):.4f}"
)

print(
    f"Reduction: "
    f"{1 - len(unique_corpus) / len(corpus):.2%}"
)


# ------------------------------------------------------------
# 3. Build original → unique mapping
# ------------------------------------------------------------

print("\n[3/5] Building original-to-unique mapping...")

text_to_unique_id = pd.Series(
    unique_corpus["unique_content_id"].values,
    index=unique_corpus["chunk_text"]
).to_dict()

corpus_to_unique = (
    corpus["chunk_text"]
    .map(text_to_unique_id)
    .astype("int64")
)

print(
    f"Original → unique mappings: "
    f"{len(corpus_to_unique):,}"
)

print(
    f"Unique IDs generated: "
    f"{corpus_to_unique.nunique():,}"
)


# ------------------------------------------------------------
# 4. Validate mapping integrity
# ------------------------------------------------------------

print("\n[4/5] Validating mapping integrity...")

assert (
    corpus_to_unique.nunique()
    == unique_corpus["unique_content_id"].nunique()
)

assert (
    corpus_to_unique.min() == 0
)

assert (
    corpus_to_unique.max()
    == len(unique_corpus) - 1
)

# Every original chunk must map to exactly one unique content ID
assert (
    corpus_to_unique.notna().all()
)

# Unique records must have unique texts
assert (
    unique_corpus["chunk_text"].nunique()
    == len(unique_corpus)
)

print("✓ Every original chunk maps to exactly one unique content ID.")
print("✓ Every unique content ID maps to exactly one unique text.")
print("✓ No text-to-ID mapping collisions.")


# ------------------------------------------------------------
# 5. Distribution of copies per unique content
# ------------------------------------------------------------

print("\n[5/5] Copy-count distribution...")

copy_counts = (
    corpus_to_unique
    .value_counts()
    .sort_index()
)

print(
    f"Mean copies per unique content : "
    f"{copy_counts.mean():.2f}"
)

print(
    f"Median copies per unique content: "
    f"{copy_counts.median():.0f}"
)

print(
    f"Minimum copies                 : "
    f"{copy_counts.min()}"
)

print(
    f"Maximum copies                 : "
    f"{copy_counts.max()}"
)

print("\nCopy-count distribution:")

print(
    copy_counts
    .value_counts()
    .sort_index()
    .to_string()
)


# ------------------------------------------------------------
# Save objects
# ------------------------------------------------------------

unique_corpus_mapping = pd.DataFrame({
    "original_corpus_idx": np.arange(len(corpus)),
    "unique_content_id": corpus_to_unique.values
})

unique_content_corpus = unique_corpus[
    [
        "unique_content_id",
        "original_corpus_idx",
        "id",
        "company_id",
        "company",
        "domain",
        "country",
        "chunk_idx",
        "chunk_text",
        "question",
        "answer",
        "answerable"
    ]
].copy()

step6l_unique_content = unique_content_corpus
step6l_original_to_unique = unique_corpus_mapping
step6l_copy_counts = copy_counts


print("\n" + "=" * 70)
print("STEP 6L COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6l_unique_content")
print("✓ step6l_original_to_unique")
print("✓ step6l_copy_counts")

print("\nIMPORTANT:")
print(
    "This creates a deduplication mapping only."
)

print(
    "No embeddings were recomputed."
)

print(
    "No FAISS index was modified."
)

print(
    "The original 164,456-chunk corpus remains intact."
)

======================================================================
STEP 6L — BUILD UNIQUE CONTENT MAPPING
======================================================================

[1/5] Validating train corpus...
Original train chunks: 164,456

[2/5] Building unique-content table...
Unique content records: 41,179
Compression ratio: 0.2504
Reduction: 74.96%

[3/5] Building original-to-unique mapping...
Original → unique mappings: 164,456
Unique IDs generated: 41,179

[4/5] Validating mapping integrity...
✓ Every original chunk maps to exactly one unique content ID.
✓ Every unique content ID maps to exactly one unique text.
✓ No text-to-ID mapping collisions.

[5/5] Copy-count distribution...
Mean copies per unique content : 3.99
Median copies per unique content: 4
Minimum copies                 : 2
Maximum copies                 : 12

Copy-count distribution:
count
2        14
3       339
4     40802
7         1
8        20
12        3

======================================================================
STEP 6L COMPLETED
======================================================================

Saved objects:
✓ step6l_unique_content
✓ step6l_original_to_unique
✓ step6l_copy_counts

IMPORTANT:
This creates a deduplication mapping only.
No embeddings were recomputed.
No FAISS index was modified.
The original 164,456-chunk corpus remains intact.

In [41]:
# ============================================================
# STEP 6M — INSPECT RETRIEVED STRUCTURE
# ============================================================

print("=" * 70)
print("STEP 6M — INSPECT RETRIEVED STRUCTURE")
print("=" * 70)

first_item = step6c_evaluation[0]

print("\nTest ID:")
print(first_item["test_id"])

print("\nQuestion:")
print(first_item["question"])

print("\nRetrieved object type:")
print(type(first_item["retrieved"]).__name__)

print("\nRetrieved object:")
print(first_item["retrieved"])

print("\n" + "=" * 70)
print("INSPECTION COMPLETED")
print("=" * 70)

======================================================================
STEP 6M — INSPECT RETRIEVED STRUCTURE
======================================================================

Test ID:
6875-0

Question:
أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!

Retrieved object type:
list

Retrieved object:
[{'rank': 1, 'corpus_idx': 33508, 'score': 0.8562403917312622, 'id': '1398-3', 'chunk_idx': 3, 'row_idx': 5580, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 2, 'corpus_idx': 33501, 'score': 0.8562403917312622, 'id': '1398-2', 'chunk_idx': 3, 'row_idx': 5579, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 3, 'corpus_idx': 33494, 'score': 0.8562403917312622, 'id': '1398-1', 'chunk_idx': 3, 'row_idx': 5578, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 4, 'corpus_idx': 33487, 'score': 0.8562403917312622, 'id': '1398-0', 'chunk_idx': 3, 'row_idx': 5577, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 5, 'corpus_idx': 129954, 'score': 0.8544511795043945, 'id': '5427-3', 'chunk_idx': 5, 'row_idx': 21655, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 6, 'corpus_idx': 129947, 'score': 0.8544511795043945, 'id': '5427-2', 'chunk_idx': 5, 'row_idx': 21654, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 7, 'corpus_idx': 129940, 'score': 0.8544511795043945, 'id': '5427-1', 'chunk_idx': 5, 'row_idx': 21653, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 8, 'corpus_idx': 129933, 'score': 0.8544511795043945, 'id': '5427-0', 'chunk_idx': 5, 'row_idx': 21652, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 9, 'corpus_idx': 41754, 'score': 0.8533371686935425, 'id': '1740-3', 'chunk_idx': 4, 'row_idx': 6945, 'domain': 'food delivery app', 'country': 'Lebanon', 'company': 'سريع-لقمة', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب إرسال طلب عبر البريد الإلكتروني للدعم الفني. يستغرق معالجة طلب إغلاق الحساب 48 ساعة عمل، وسيتم حذف كافة البيانات الشخصية وسجل الطلبات من خوادمنا بشكل نهائي.'}, {'rank': 10, 'corpus_idx': 41747, 'score': 0.8533371686935425, 'id': '1740-2', 'chunk_idx': 4, 'row_idx': 6944, 'domain': 'food delivery app', 'country': 'Lebanon', 'company': 'سريع-لقمة', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب إرسال طلب عبر البريد الإلكتروني للدعم الفني. يستغرق معالجة طلب إغلاق الحساب 48 ساعة عمل، وسيتم حذف كافة البيانات الشخصية وسجل الطلبات من خوادمنا بشكل نهائي.'}]

======================================================================
INSPECTION COMPLETED
======================================================================

In [42]:
# ============================================================
# STEP 6M — DEDUPLICATION-AWARE RETRIEVAL ANALYSIS
# ============================================================

import numpy as np
import pandas as pd

print("=" * 70)
print("STEP 6M — DEDUPLICATION-AWARE RETRIEVAL ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate required objects
# ------------------------------------------------------------

print("\n[1/5] Validating required objects...")

assert "step6c_evaluation" in globals()
assert "step6l_original_to_unique" in globals()
assert "step6l_unique_content" in globals()

evaluation = step6c_evaluation

assert len(evaluation) == 500

print(f"Evaluation queries : {len(evaluation):,}")


# ------------------------------------------------------------
# 2. Prepare original → unique mapping
# ------------------------------------------------------------

print("\n[2/5] Preparing original → unique mapping...")

original_to_unique = (
    step6l_original_to_unique
    .set_index("original_corpus_idx")["unique_content_id"]
    .to_dict()
)

print(
    f"Original corpus mappings : "
    f"{len(original_to_unique):,}"
)

print(
    f"Unique content records   : "
    f"{step6l_unique_content['unique_content_id'].nunique():,}"
)


# ------------------------------------------------------------
# 3. Deduplicate every retrieved Top-K
# ------------------------------------------------------------

print("\n[3/5] Deduplicating Top-K results...")

results = []

for item in evaluation:

    retrieved = item["retrieved"]

    assert len(retrieved) == 10

    corpus_indices = [
        int(result["corpus_idx"])
        for result in retrieved
    ]

    unique_ids = [
        original_to_unique[idx]
        for idx in corpus_indices
    ]

    results.append({
        "test_idx": item["test_idx"],
        "test_id": item["test_id"],
        "answerable": item["answerable"],

        "raw_top1_corpus_idx":
            corpus_indices[0],

        "raw_top1_unique_id":
            unique_ids[0],

        "unique_count_at_3":
            len(set(unique_ids[:3])),

        "unique_count_at_5":
            len(set(unique_ids[:5])),

        "unique_count_at_10":
            len(set(unique_ids[:10])),

        "raw_count_at_10":
            10,

        "duplicate_slots_at_10":
            10 - len(set(unique_ids[:10])),

        "unique_ids_top10":
            unique_ids
    })


dedup_eval = pd.DataFrame(results)


# ------------------------------------------------------------
# 4. Summary statistics
# ------------------------------------------------------------

print("\n[4/5] Summary statistics...")

for k in [3, 5, 10]:

    col = f"unique_count_at_{k}"

    print(f"\nUnique content @ {k}:")

    print(
        f"  Mean   : "
        f"{dedup_eval[col].mean():.2f}"
    )

    print(
        f"  Median : "
        f"{dedup_eval[col].median():.0f}"
    )

    print(
        f"  Min    : "
        f"{dedup_eval[col].min()}"
    )

    print(
        f"  Max    : "
        f"{dedup_eval[col].max()}"
    )


print("\nTop-10 duplication impact:")

print(
    f"  Mean duplicate slots   : "
    f"{dedup_eval['duplicate_slots_at_10'].mean():.2f}"
)

print(
    f"  Median duplicate slots : "
    f"{dedup_eval['duplicate_slots_at_10'].median():.0f}"
)

print(
    f"  Queries with duplicates: "
    f"{(dedup_eval['duplicate_slots_at_10'] > 0).sum():,}"
    f"/{len(dedup_eval):,}"
)


# ------------------------------------------------------------
# 5. Distribution
# ------------------------------------------------------------

print("\n[5/5] Unique-content distributions...")

for k in [3, 5, 10]:

    col = f"unique_count_at_{k}"

    distribution = (
        dedup_eval[col]
        .value_counts()
        .sort_index()
    )

    print(
        f"\nUnique content count @ {k}:"
    )

    print(
        distribution.to_string()
    )


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6m_dedup_eval = dedup_eval


print("\n" + "=" * 70)
print("STEP 6M COMPLETED")
print("=" * 70)

print("\nSaved object:")
print("✓ step6m_dedup_eval")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("Original retrieval results remain unchanged.")

======================================================================
STEP 6M — DEDUPLICATION-AWARE RETRIEVAL ANALYSIS
======================================================================

[1/5] Validating required objects...
Evaluation queries : 500

[2/5] Preparing original → unique mapping...
Original corpus mappings : 164,456
Unique content records   : 41,179

[3/5] Deduplicating Top-K results...

[4/5] Summary statistics...

Unique content @ 3:
  Mean   : 1.00
  Median : 1
  Min    : 1
  Max    : 1

Unique content @ 5:
  Mean   : 2.00
  Median : 2
  Min    : 2
  Max    : 2

Unique content @ 10:
  Mean   : 3.00
  Median : 3
  Min    : 3
  Max    : 3

Top-10 duplication impact:
  Mean duplicate slots   : 7.00
  Median duplicate slots : 7
  Queries with duplicates: 500/500

[5/5] Unique-content distributions...

Unique content count @ 3:
unique_count_at_3
1    500

Unique content count @ 5:
unique_count_at_5
2    500

Unique content count @ 10:
unique_count_at_10
3    500

======================================================================
STEP 6M COMPLETED
======================================================================

Saved object:
✓ step6m_dedup_eval

No embeddings were recomputed.
No FAISS index was modified.
Original retrieval results remain unchanged.

In [43]:
# ============================================================
# STEP 6N — UNIQUE CONTENT RETRIEVAL PROFILE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6N — UNIQUE CONTENT RETRIEVAL PROFILE")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing results
# ------------------------------------------------------------

print("\n[1/4] Validating existing retrieval results...")

assert "step6c_evaluation" in globals()
assert "step6m_dedup_eval" in globals()
assert "train_corpus" in globals()

evaluation = step6c_evaluation

assert len(evaluation) == 500

print(f"Queries: {len(evaluation):,}")


# ------------------------------------------------------------
# 2. Build unique-content retrieval records
# ------------------------------------------------------------

print("\n[2/4] Building unique-content profiles...")

profiles = []

for item in evaluation:

    retrieved = item["retrieved"]

    seen = set()
    unique_results = []

    for result in retrieved:

        corpus_idx = int(result["corpus_idx"])

        unique_id = (
            step6l_original_to_unique
            .loc[
                step6l_original_to_unique["original_corpus_idx"]
                == corpus_idx,
                "unique_content_id"
            ]
            .iloc[0]
        )

        if unique_id in seen:
            continue

        seen.add(unique_id)

        unique_results.append({
            "unique_content_id": int(unique_id),
            "first_rank": int(result["rank"]),
            "score": float(result["score"]),
            "corpus_idx": corpus_idx,
            "id": result["id"],
            "chunk_idx": result["chunk_idx"],
            "domain": result["domain"],
            "country": result["country"],
            "company": result["company"],
            "chunk_text": result["chunk_text"],
            "copy_count": int(
                (
                    step6l_original_to_unique[
                        "unique_content_id"
                    ] == unique_id
                ).sum()
            )
        })

    profiles.append({
        "test_idx": item["test_idx"],
        "test_id": item["test_id"],
        "answerable": item["answerable"],
        "unique_results": unique_results
    })


# ------------------------------------------------------------
# 3. Analyze number of unique contents and ranks
# ------------------------------------------------------------

print("\n[3/4] Analyzing unique-content ranking...")

profile_rows = []

for profile in profiles:

    for position, result in enumerate(
        profile["unique_results"],
        start=1
    ):

        profile_rows.append({

            "test_idx":
                profile["test_idx"],

            "test_id":
                profile["test_id"],

            "answerable":
                profile["answerable"],

            "unique_position":
                position,

            "first_rank":
                result["first_rank"],

            "unique_content_id":
                result["unique_content_id"],

            "score":
                result["score"],

            "corpus_idx":
                result["corpus_idx"],

            "id":
                result["id"],

            "chunk_idx":
                result["chunk_idx"],

            "domain":
                result["domain"],

            "country":
                result["country"],

            "company":
                result["company"],

            "copy_count":
                result["copy_count"],

            "chunk_text":
                result["chunk_text"]
        })


unique_profile_df = pd.DataFrame(profile_rows)


print(
    f"Total unique-content retrieval records: "
    f"{len(unique_profile_df):,}"
)

print(
    f"Mean unique contents per query: "
    f"{unique_profile_df.groupby('test_id').size().mean():.2f}"
)

print(
    f"Unique-content positions observed: "
    f"{sorted(unique_profile_df['unique_position'].unique().tolist())}"
)


# ------------------------------------------------------------
# 4. Summary by unique position
# ------------------------------------------------------------

print("\n[4/4] Summary by unique-content position...")

position_summary = (
    unique_profile_df
    .groupby("unique_position")
    .agg(
        queries=("test_id", "count"),
        mean_score=("score", "mean"),
        median_score=("score", "median"),
        mean_first_rank=("first_rank", "mean"),
        mean_copy_count=("copy_count", "mean")
    )
    .reset_index()
)

print(
    position_summary.to_string(index=False)
)


# ------------------------------------------------------------
# Save objects
# ------------------------------------------------------------

step6n_unique_profile = unique_profile_df
step6n_position_summary = position_summary


print("\n" + "=" * 70)
print("STEP 6N COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6n_unique_profile")
print("✓ step6n_position_summary")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6N — UNIQUE CONTENT RETRIEVAL PROFILE
======================================================================

[1/4] Validating existing retrieval results...
Queries: 500

[2/4] Building unique-content profiles...

[3/4] Analyzing unique-content ranking...
Total unique-content retrieval records: 1,500
Mean unique contents per query: 3.00
Unique-content positions observed: [1, 2, 3]

[4/4] Summary by unique-content position...
 unique_position  queries  mean_score  median_score  mean_first_rank  mean_copy_count
               1      500    0.866702      0.867077            1.000            3.986
               2      500    0.863205      0.863671            4.986            3.998
               3      500    0.861133      0.861777            8.984            3.996

======================================================================
STEP 6N COMPLETED
======================================================================

Saved objects:
✓ step6n_unique_profile
✓ step6n_position_summary

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [44]:
# ============================================================
# STEP 6O — UNIQUE CONTENT DIVERSITY ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6O — UNIQUE CONTENT DIVERSITY ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing results
# ------------------------------------------------------------

print("\n[1/5] Validating existing objects...")

assert "step6n_unique_profile" in globals()
assert "step6n_position_summary" in globals()

df = step6n_unique_profile.copy()

assert len(df) == 1500
assert df["unique_position"].isin([1, 2, 3]).all()

print(f"Unique retrieval records: {len(df):,}")
print(f"Queries: {df['test_id'].nunique():,}")


# ------------------------------------------------------------
# 2. Domain diversity per query
# ------------------------------------------------------------

print("\n[2/5] Calculating domain diversity...")

domain_diversity = (
    df.groupby("test_id")
    .agg(
        unique_domains=("domain", "nunique"),
        unique_countries=("country", "nunique"),
        unique_companies=("company", "nunique"),
        answerable=("answerable", "first")
    )
    .reset_index()
)

print("\nOverall diversity:")

print(
    f"Mean unique domains    : "
    f"{domain_diversity['unique_domains'].mean():.2f}"
)

print(
    f"Median unique domains  : "
    f"{domain_diversity['unique_domains'].median():.0f}"
)

print(
    f"Mean unique countries  : "
    f"{domain_diversity['unique_countries'].mean():.2f}"
)

print(
    f"Mean unique companies  : "
    f"{domain_diversity['unique_companies'].mean():.2f}"
)


# ------------------------------------------------------------
# 3. Diversity distribution
# ------------------------------------------------------------

print("\n[3/5] Diversity distributions...")

for column, label in [
    ("unique_domains", "domains"),
    ("unique_countries", "countries"),
    ("unique_companies", "companies")
]:

    print(f"\nUnique {label} per query:")

    print(
        domain_diversity[column]
        .value_counts()
        .sort_index()
        .to_string()
    )


# ------------------------------------------------------------
# 4. Answerable vs unanswerable
# ------------------------------------------------------------

print("\n[4/5] Answerable vs unanswerable diversity...")

group_summary = (
    domain_diversity
    .groupby("answerable")
    .agg(
        queries=("test_id", "count"),
        mean_domains=("unique_domains", "mean"),
        mean_countries=("unique_countries", "mean"),
        mean_companies=("unique_companies", "mean")
    )
    .reset_index()
)

print(
    group_summary.to_string(index=False)
)


# ------------------------------------------------------------
# 5. Position-wise domain/country/company changes
# ------------------------------------------------------------

print("\n[5/5] Position-wise diversity...")

position_diversity = (
    df.groupby("unique_position")
    .agg(
        unique_domains=("domain", "nunique"),
        unique_countries=("country", "nunique"),
        unique_companies=("company", "nunique"),
        mean_score=("score", "mean")
    )
    .reset_index()
)

print(
    position_diversity.to_string(index=False)
)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6o_domain_diversity = domain_diversity
step6o_group_summary = group_summary
step6o_position_diversity = position_diversity


print("\n" + "=" * 70)
print("STEP 6O COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6o_domain_diversity")
print("✓ step6o_group_summary")
print("✓ step6o_position_diversity")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6O — UNIQUE CONTENT DIVERSITY ANALYSIS
======================================================================

[1/5] Validating existing objects...
Unique retrieval records: 1,500
Queries: 500

[2/5] Calculating domain diversity...

Overall diversity:
Mean unique domains    : 1.78
Median unique domains  : 2
Mean unique countries  : 2.54
Mean unique companies  : 2.82

[3/5] Diversity distributions...

Unique domains per query:
unique_domains
1    223
2    165
3    112

Unique countries per query:
unique_countries
1     37
2    156
3    307

Unique companies per query:
unique_companies
1      3
2     84
3    413

[4/5] Answerable vs unanswerable diversity...
 answerable  queries  mean_domains  mean_countries  mean_companies
      False       54      2.000000        2.444444        2.870370
       True      446      1.751121        2.551570        2.813901

[5/5] Position-wise diversity...
 unique_position  unique_domains  unique_countries  unique_companies  mean_score
               1              20                13               292    0.866702
               2              20                13               272    0.863205
               3              20                13               279    0.861133

======================================================================
STEP 6O COMPLETED
======================================================================

Saved objects:
✓ step6o_domain_diversity
✓ step6o_group_summary
✓ step6o_position_diversity

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [45]:
# ============================================================
# STEP 6P — TOP-1 RETRIEVAL ALIGNMENT ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6P — TOP-1 RETRIEVAL ALIGNMENT ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

print("\n[1/5] Validating existing objects...")

assert "step6c_evaluation" in globals()
assert "step6n_unique_profile" in globals()
assert "test_df" in globals()

evaluation = step6c_evaluation
unique_profile = step6n_unique_profile

assert len(evaluation) == 500
assert len(unique_profile) == 1500

print(f"Evaluation queries : {len(evaluation):,}")


# ------------------------------------------------------------
# 2. Build Top-1 alignment table
# ------------------------------------------------------------

print("\n[2/5] Building Top-1 alignment table...")

rows = []

for item in evaluation:

    test_idx = int(item["test_idx"])

    test_row = test_df.iloc[test_idx]

    top1 = item["retrieved"][0]

    rows.append({
        "test_idx":
            test_idx,

        "test_id":
            item["test_id"],

        "answerable":
            bool(item["answerable"]),

        "test_domain":
            test_row["domain"],

        "test_country":
            test_row["country"],

        "retrieved_domain":
            top1["domain"],

        "retrieved_country":
            top1["country"],

        "retrieved_company":
            top1["company"],

        "score":
            float(top1["score"]),

        "same_domain":
            test_row["domain"] == top1["domain"],

        "same_country":
            test_row["country"] == top1["country"]
    })


top1_alignment = pd.DataFrame(rows)


# ------------------------------------------------------------
# 3. Overall alignment
# ------------------------------------------------------------

print("\n[3/5] Overall Top-1 alignment...")

print(
    f"Top-1 same domain : "
    f"{top1_alignment['same_domain'].sum():,}/"
    f"{len(top1_alignment):,}"
    f" = "
    f"{top1_alignment['same_domain'].mean():.2%}"
)

print(
    f"Top-1 same country: "
    f"{top1_alignment['same_country'].sum():,}/"
    f"{len(top1_alignment):,}"
    f" = "
    f"{top1_alignment['same_country'].mean():.2%}"
)

print(
    f"Top-1 mean score  : "
    f"{top1_alignment['score'].mean():.4f}"
)

print(
    f"Top-1 median score: "
    f"{top1_alignment['score'].median():.4f}"
)


# ------------------------------------------------------------
# 4. Answerable vs unanswerable
# ------------------------------------------------------------

print("\n[4/5] Alignment by answerability...")

answerability_alignment = (
    top1_alignment
    .groupby("answerable")
    .agg(
        queries=("test_id", "count"),

        same_domain_count=("same_domain", "sum"),
        same_domain_rate=("same_domain", "mean"),

        same_country_count=("same_country", "sum"),
        same_country_rate=("same_country", "mean"),

        mean_score=("score", "mean"),
        median_score=("score", "median")
    )
    .reset_index()
)

print(
    answerability_alignment.to_string(index=False)
)


# ------------------------------------------------------------
# 5. Alignment combinations
# ------------------------------------------------------------

print("\n[5/5] Top-1 alignment combinations...")

top1_alignment["alignment_type"] = np.select(
    [
        top1_alignment["same_domain"]
        & top1_alignment["same_country"],

        top1_alignment["same_domain"]
        & ~top1_alignment["same_country"],

        ~top1_alignment["same_domain"]
        & top1_alignment["same_country"]
    ],
    [
        "same_domain_and_country",
        "same_domain_only",
        "same_country_only"
    ],
    default="different_domain_and_country"
)

alignment_distribution = (
    top1_alignment["alignment_type"]
    .value_counts()
    .sort_index()
)

print(
    alignment_distribution.to_string()
)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6p_top1_alignment = top1_alignment
step6p_answerability_alignment = answerability_alignment
step6p_alignment_distribution = alignment_distribution


print("\n" + "=" * 70)
print("STEP 6P COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6p_top1_alignment")
print("✓ step6p_answerability_alignment")
print("✓ step6p_alignment_distribution")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6P — TOP-1 RETRIEVAL ALIGNMENT ANALYSIS
======================================================================

[1/5] Validating existing objects...
Evaluation queries : 500

[2/5] Building Top-1 alignment table...

[3/5] Overall Top-1 alignment...
Top-1 same domain : 265/500 = 53.00%
Top-1 same country: 92/500 = 18.40%
Top-1 mean score  : 0.8667
Top-1 median score: 0.8671

[4/5] Alignment by answerability...
 answerable  queries  same_domain_count  same_domain_rate  same_country_count  same_country_rate  mean_score  median_score
      False       54                 18          0.333333                  14           0.259259    0.857178      0.859954
       True      446                247          0.553812                  78           0.174888    0.867856      0.868965

[5/5] Top-1 alignment combinations...
alignment_type
different_domain_and_country    183
same_country_only                52
same_domain_and_country          40
same_domain_only                225

======================================================================
STEP 6P COMPLETED
======================================================================

Saved objects:
✓ step6p_top1_alignment
✓ step6p_answerability_alignment
✓ step6p_alignment_distribution

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [46]:
# ============================================================
# STEP 6Q — TOP-1 DOMAIN ERROR ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6Q — TOP-1 DOMAIN ERROR ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

print("\n[1/4] Validating existing objects...")

assert "step6p_top1_alignment" in globals()
assert "test_df" in globals()

df = step6p_top1_alignment.copy()

assert len(df) == 500

print(f"Total queries: {len(df):,}")


# ------------------------------------------------------------
# 2. Select domain-mismatch cases
# ------------------------------------------------------------

print("\n[2/4] Selecting Top-1 domain mismatches...")

domain_mismatch = (
    df[df["same_domain"] == False]
    .copy()
    .sort_values(
        ["answerable", "score"],
        ascending=[False, True]
    )
)

print(
    f"Domain mismatch cases: "
    f"{len(domain_mismatch):,}/"
    f"{len(df):,}"
    f" = "
    f"{len(domain_mismatch) / len(df):.2%}"
)


# ------------------------------------------------------------
# 3. Add question + retrieved text
# ------------------------------------------------------------

print("\n[3/4] Attaching question and retrieved content...")

questions = (
    test_df[
        ["id", "question", "domain", "country"]
    ]
    .copy()
)

questions = questions.rename(
    columns={
        "id": "test_id"
    }
)

questions["test_id"] = questions["test_id"].astype(str)

domain_mismatch["test_id"] = (
    domain_mismatch["test_id"]
    .astype(str)
)

domain_mismatch = domain_mismatch.merge(
    questions[
        [
            "test_id",
            "question"
        ]
    ],
    on="test_id",
    how="left"
)

# Retrieve the exact Top-1 text from the existing evaluation
retrieved_text_map = {}

for item in step6c_evaluation:

    retrieved_text_map[
        str(item["test_id"])
    ] = item["retrieved"][0]["chunk_text"]


domain_mismatch["retrieved_text"] = (
    domain_mismatch["test_id"]
    .map(retrieved_text_map)
)


# ------------------------------------------------------------
# 4. Show representative errors
# ------------------------------------------------------------

print("\n[4/4] Representative domain mismatches...")

display_columns = [
    "test_id",
    "answerable",
    "score",
    "test_domain",
    "test_country",
    "retrieved_domain",
    "retrieved_country",
    "retrieved_company",
    "question",
    "retrieved_text"
]

representative = (
    domain_mismatch[
        display_columns
    ]
    .head(20)
    .reset_index(drop=True)
)

print(
    representative.to_string(index=False)
)


# ------------------------------------------------------------
# Save result
# ------------------------------------------------------------

step6q_domain_mismatch = domain_mismatch
step6q_representative = representative


print("\n" + "=" * 70)
print("STEP 6Q COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6q_domain_mismatch")
print("✓ step6q_representative")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6Q — TOP-1 DOMAIN ERROR ANALYSIS
======================================================================

[1/4] Validating existing objects...
Total queries: 500

[2/4] Selecting Top-1 domain mismatches...
Domain mismatch cases: 235/500 = 47.00%

[3/4] Attaching question and retrieved content...

[4/4] Representative domain mismatches...
test_id  answerable    score               test_domain             test_country             retrieved_domain retrieved_country                      retrieved_company                                                                                                                                             question                                                                                                                                                                                                                                          retrieved_text
 6982-3        True 0.811899         streaming service                   Jordan     gym / fitness club chain           Tunisia                      نادي جسور اللياقة                                                                                                             الأساسية أم المميزة؟ من حيث عدد الأجهزة.                  باقة 'التميز' الشهرية تبلغ تكلفتها 120 ديناراً تونسياً، وتمنح العضو وصولاً كاملاً لصالة الأجهزة والسباحة. أما باقة 'الأساسية' فتبلغ تكلفتها 60 ديناراً تونسياً وتقتصر على استخدام الأجهزة الرياضية فقط من الساعة 8 صباحاً حتى 4 مساءً.
 6946-3        True 0.813676          health insurance                    Egypt     gym / fitness club chain           Algeria              نادي القمة للياقة البدنية                                                                                      لقد مر وقت طويل ولم أستلم بطاقتي حتى الآن، هذا إهمال غير مقبول!                                 تنص سياسة الإلغاء على أنه يحق للعضو إلغاء الاشتراك واسترداد 50% من قيمة الرسوم المتبقية بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الشهر الحالي. لا يتم استرداد أي مبالغ بعد مرور 30 يوماً من تاريخ بدء الاشتراك.
 6906-3        True 0.814437  online electronics store                  Tunisia    internet service provider              Iraq           شركة أثير الرافدين للاتصالات                                                                                            ما الفرق بين سريع 1 وسريع 2؟ لا أريد تضييع وقتي في البحث!       باقة 'سريع' توفر سرعة تحميل تصل إلى 20 ميجابت في الثانية بسعر 25,000 دينار عراقي شهرياً، بينما توفر باقة 'فائق' سرعة تحميل تصل إلى 50 ميجابت في الثانية بسعر 45,000 دينار عراقي شهرياً. تلتزم الشركة بتوفير سرعة لا تقل عن 80% من السرعة المعلنة.
 6896-2        True 0.818783          ride-hailing app             Saudi Arabia    internet service provider           Bahrain            شركة أثير البحرين للاتصالات                                                                                            لقد تم خصم مبلغ إضافي من رحلتي الأخيرة وأرغب في استعادته.                                                 في حال الرغبة في إلغاء الاشتراك، يجب تقديم الطلب قبل 15 يوماً من تاريخ تجديد الفاتورة. يتم استرداد الرسوم المتبقية من الشهر الحالي بنسبة 70% من القيمة، بينما يتم خصم 30% كرسوم إدارية لمعالجة الإلغاء.
 6923-0        True 0.822589               hotel chain                     Oman              furniture store              Oman            مؤسسة ركائز الأثاث العمانية                                                                                                                                محتويات جناح السلطان؟                        تتوفر مجموعة 'سلطان' للغرف الرئيسية بسعر 850 ريال عماني، وتتضمن سريراً خشبياً من خشب الجوز، وخزانتين جانبيتين، وخزانة ملابس بـ 6 أبواب. جميع قطع هذه المجموعة تأتي مع ضمان شامل ضد عيوب التصنيع لمدة 24 شهراً من تاريخ الاستلام.
 6906-1        True 0.822709  online electronics store                  Tunisia            food delivery app           Lebanon                              سريع-لقمة                                                                                أريد إغلاق اشتراك 'نور بلس' فوراً، لقد سئمت من هذه الإجراءات المعقدة!                                                                 لإغلاق الحساب نهائياً، يجب إرسال طلب عبر البريد الإلكتروني للدعم الفني. يستغرق معالجة طلب إغلاق الحساب 48 ساعة عمل، وسيتم حذف كافة البيانات الشخصية وسجل الطلبات من خوادمنا بشكل نهائي.
 6884-2        True 0.826035  gym / fitness club chain                  Lebanon                  hotel chain      Saudi Arabia                    فنادق المدار الذهبي                                                                                                                               تفاصيل الباقة الذهبية.                                                   تتوفر 'الباقة الذهبية' الفاخرة بسعر 800 ريال سعودي لليلة الواحدة. تتضمن جناحاً ملكياً يطل على المدينة، ووجبة إفطار وعشاء فاخرة، وخدمة نقل مجانية من وإلى المطار، بالإضافة إلى دخول خاص للمسبح والسبا.
 6936-0        True 0.828818 courier / parcel delivery                   Kuwait     gym / fitness club chain      Saudi Arabia                       نادي صرح اللياقة                                                                                                                           الفرق بين الفضية والذهبية؟ تتضمن الباقة الفضية وصولاً كاملاً لصالة الأجهزة الرياضية و٣ حصص تدريب جماعي شهرياً بسعر ١٥٠ ريال سعودي شهرياً. أما الباقة الذهبية فتشمل جميع مزايا الفضية بالإضافة إلى دخول غير محدود للمسبح والساونا و٥ جلسات تدليك شهرياً بسعر ٣٠٠ ريال سعودي شهرياً.
 6953-1        True 0.828818          health insurance                     Iraq     gym / fitness club chain      Saudi Arabia                       نادي صرح اللياقة                                                                                                                           الفرق بين الفضية والذهبية؟ تتضمن الباقة الفضية وصولاً كاملاً لصالة الأجهزة الرياضية و٣ حصص تدريب جماعي شهرياً بسعر ١٥٠ ريال سعودي شهرياً. أما الباقة الذهبية فتشمل جميع مزايا الفضية بالإضافة إلى دخول غير محدود للمسبح والساونا و٥ جلسات تدليك شهرياً بسعر ٣٠٠ ريال سعودي شهرياً.
 6935-1        True 0.830061          health insurance                  Lebanon                water utility              Iraq   شركة الرافدين لتدبير المياه والخدمات تحية طيبة، لقد لاحظت وجود مبلغ مخصوم من حسابي لم أكن أتوقعه بخصوص مطالبتي الأخيرة، وأود الاستفسار عن الإجراء المتبع للاعتراض على هذه القيمة المالية.                                                                               في حال الرغبة في إلغاء الاشتراك، يجب تقديم طلب كتابي قبل 15 يوماً من تاريخ نهاية الشهر الحالي، ويتم استرداد 50% من قيمة الرصيد المتبقي في الحساب بعد خصم الرسوم الإدارية.
 6888-2        True 0.830168           furniture store                  Lebanon       private hospital group           Algeria مجموعة الشفاء المتكاملة للخدمات الطبية                                                                                    لماذا تم خصم مبلغ من قيمة استرجاعي؟ أنا مستاء جداً من هذا التصرف!                                                      في حال إلغاء الموعد قبل 24 ساعة من الموعد المحدد، يتم استرداد المبلغ كاملاً بنسبة 100%. أما إذا تم الإلغاء في فترة أقل من 24 ساعة، يتم خصم رسوم إدارية قدرها 2,000 دينار جزائري من المبلغ المسترد.
 6973-1        True 0.830690         streaming service                  Bahrain                car insurance           Tunisia        شركة تونس للأمان الشامل للتأمين                                                                                لقد تم خصم مبلغ إضافي من حسابي وأرغب في تقديم اعتراض على هذه العملية.                                                                في حال وجود خطأ في الفوترة أو خصم مبالغ إضافية، يجب تقديم اعتراض كتابي خلال 30 يوماً من تاريخ الخصم. تقوم الشركة بمراجعة الطلب ورد المبالغ الزائدة خلال 14 يوماً من تاريخ قبول الاعتراض.
 6934-2        True 0.831350             water utility                  Lebanon                  hotel chain           Morocco                      فنادق أطلس الزمرد                                                                                                                               ترقية للاشتراك الذهبي.                       يمكن للعملاء ترقية عضويتهم من الفئة الفضية إلى الفئة الذهبية عبر تطبيقنا من خلال دفع رسوم ترقية لمرة واحدة قدرها 500 درهم مغربي. تمنح العضوية الذهبية صاحبها خصماً ثابتاً بنسبة 15% على جميع الحجوزات المستقبلية في أي من فروعنا.
 6882-1        True 0.832372               hotel chain the United Arab Emirates    internet service provider            Jordan                    شركة سحاب للاتصالات                                                               أنا مستاء جداً، الإنترنت في الغرفة مقطوع تماماً ولا يمكنني إنجاز عملي! ماذا أفعل الآن؟                                          في حال انقطاع الخدمة، يرجى أولاً التأكد من إطفاء جهاز المودم لمدة 60 ثانية ثم إعادة تشغيله. إذا استمرت المشكلة، يجب التحقق من أن ضوء 'Internet' باللون الأخضر؛ وإذا كان أحمر، يرجى الاتصال بالدعم الفني فوراً.
 6880-3        True 0.833153             water utility                     Oman     online electronics store           Bahrain     شركة التقنية المتقدمة للإلكترونيات                                                                              لقد تم احتساب مبالغ إضافية في فاتورتي وهذا خطأ فادح! كيف أستعيد أموالي؟                            في حال وجود خطأ في الفوترة أو احتساب مبلغ إضافي، يجب تقديم طلب اعتراض عبر الموقع خلال 30 يوماً من تاريخ الفاتورة. تقوم الشركة بمراجعة العملية المالية واسترداد المبالغ الزائدة بنسبة 100% في غضون 5 أيام عمل من تأكيد الخطأ.
 6946-0        True 0.835513          health insurance                    Egypt mobile wallet / payments app           Lebanon                               سريع-دفع                                                                          أريد معرفة الفرق بين الباقة الأساسية والمتميزة فوراً، لقد سئمت من الانتظار!    يوفر تطبيق سريع-دفع باقة 'الأساسية' مجانًا وبدون رسوم شهرية، بينما توفر باقة 'المتميزة' ميزات إضافية مقابل 15,000 ليرة لبنانية شهريًا. تتيح الباقة المتميزة إجراء تحويلات مالية غير محدودة، بينما تقتصر الباقة الأساسية على 5 تحويلات مجانية شهريًا.
 6988-2        True 0.835606  telecom / mobile network                  Algeria    internet service provider           Tunisia                    شركة سديم للاتصالات                                                                                                       لقد انتظرت طويلاً! متى سيصل المودم الذي طلبته؟                                                          يتم تركيب أجهزة المودم وتفعيل الخدمة المنزلية في غضون 48 ساعة عمل من تاريخ تقديم الطلب وتأكيد العنوان. تلتزم الشركة بزيارة الفني للمنزل لضمان جودة الإشارة قبل تسليم الجهاز للعميل بشكل نهائي.
 6959-0        True 0.836156               hotel chain                   Jordan     online electronics store            Jordan                      سديم للإلكترونيات                                                                                                                     خصم 120 ديناراً غير مبرر. لماذا؟                                                                                     تمنح الشركة خصماً بنسبة 10% للطلبات التي تتجاوز قيمتها 200 دينار أردني، ويطبق هذا الخصم تلقائياً عند الدفع. لا يمكن دمج هذا العرض مع كوبونات الخصم الموسمية الأخرى.
 6945-1        True 0.836529  online electronics store                  Morocco             health insurance           Tunisia                شركة تونسيا لضمان الصحة                                                                 أريد معرفة الفرق بين الباقة الذهبية والبلاتينية فوراً، لا وقت لدي للمراسلات الطويلة!                                                              تتطلب عملية تحديث البيانات الشخصية أو ترقية الباقة تقديم طلب عبر البوابة الإلكترونية. يتم تفعيل الترقية من الباقة الأساسية إلى الذهبية في غضون 48 ساعة عمل من تاريخ دفع فرق السعر المطلوب.
 6982-2        True 0.837801         streaming service                   Jordan             health insurance           Tunisia                شركة نماء للتأمين الصحي                                                               أريد استعادة أموالي الآن! لقد اشتركت بالخطأ قبل ساعات قليلة وهذا أمر غير مقبول تماماً!                                                  في حال تعذر الدخول إلى البوابة الإلكترونية، يجب على المستخدم مسح ملفات تعريف الارتباط (Cookies) ثم إعادة تشغيل المتصفح. إذا استمرت المشكلة، يرجى إرسال لقطة شاشة للخطأ إلى البريد التقني خلال 24 ساعة.

======================================================================
STEP 6Q COMPLETED
======================================================================

Saved objects:
✓ step6q_domain_mismatch
✓ step6q_representative

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [47]:
# ============================================================
# STEP 6R — INTENT / QUESTION-TYPE RETRIEVAL ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6R — INTENT / QUESTION-TYPE RETRIEVAL ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

print("\n[1/5] Validating existing objects...")

assert "step6p_top1_alignment" in globals()
assert "test_df" in globals()

alignment = step6p_top1_alignment.copy()

assert len(alignment) == 500

print(f"Queries: {len(alignment):,}")


# ------------------------------------------------------------
# 2. Attach question_type from Test
# ------------------------------------------------------------

print("\n[2/5] Attaching question types...")

test_meta = (
    test_df[
        ["id", "question_type"]
    ]
    .copy()
)

test_meta["id"] = test_meta["id"].astype(str)

alignment["test_id"] = (
    alignment["test_id"]
    .astype(str)
)

alignment = alignment.merge(
    test_meta.rename(
        columns={
            "id": "test_id"
        }
    ),
    on="test_id",
    how="left"
)

assert alignment["question_type"].notna().all()

print(
    f"Question types found: "
    f"{alignment['question_type'].nunique()}"
)

print("\nQuestion-type distribution:")

print(
    alignment["question_type"]
    .value_counts()
    .sort_index()
    .to_string()
)


# ------------------------------------------------------------
# 3. Analyze retrieval by question type
# ------------------------------------------------------------

print("\n[3/5] Retrieval performance by question type...")

type_summary = (
    alignment
    .groupby("question_type")
    .agg(
        queries=("test_id", "count"),

        answerable_rate=("answerable", "mean"),

        mean_score=("score", "mean"),
        median_score=("score", "median"),

        same_domain_rate=("same_domain", "mean"),
        same_country_rate=("same_country", "mean")
    )
    .reset_index()
    .sort_values(
        "mean_score",
        ascending=False
    )
)

print(
    type_summary.to_string(index=False)
)


# ------------------------------------------------------------
# 4. Compare answerable vs unanswerable within each type
# ------------------------------------------------------------

print("\n[4/5] Answerable vs unanswerable by question type...")

answerability_by_type = (
    alignment
    .groupby(
        ["question_type", "answerable"]
    )
    .agg(
        queries=("test_id", "count"),

        mean_score=("score", "mean"),
        median_score=("score", "median"),

        same_domain_rate=("same_domain", "mean"),
        same_country_rate=("same_country", "mean")
    )
    .reset_index()
)

print(
    answerability_by_type.to_string(index=False)
)


# ------------------------------------------------------------
# 5. Identify weakest question types
# ------------------------------------------------------------

print("\n[5/5] Weakest question types...")

weakest = (
    type_summary[
        [
            "question_type",
            "queries",
            "mean_score",
            "same_domain_rate",
            "same_country_rate"
        ]
    ]
    .sort_values(
        [
            "same_domain_rate",
            "mean_score"
        ],
        ascending=[
            True,
            True
        ]
    )
    .head(10)
)

print(
    weakest.to_string(index=False)
)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6r_type_analysis = alignment
step6r_type_summary = type_summary
step6r_answerability_by_type = answerability_by_type
step6r_weakest_types = weakest


print("\n" + "=" * 70)
print("STEP 6R COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6r_type_analysis")
print("✓ step6r_type_summary")
print("✓ step6r_answerability_by_type")
print("✓ step6r_weakest_types")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6R — INTENT / QUESTION-TYPE RETRIEVAL ANALYSIS
======================================================================

[1/5] Validating existing objects...
Queries: 500

[2/5] Attaching question types...
Question types found: 8

Question-type distribution:
question_type
account or subscription management (upgrade, renewal, closing)    64
availability, coverage or delivery time                           60
billing dispute or a charge on the account                        64
comparison between two products or plans                          66
policy (refund, cancellation, warranty, exchange)                 66
pricing or fees                                                   55
product or plan details (specs, what is included)                 59
troubleshooting a problem with the product or service             66

[3/5] Retrieval performance by question type...
                                                 question_type  queries  answerable_rate  mean_score  median_score  same_domain_rate  same_country_rate
                                               pricing or fees       55         0.909091    0.874926      0.874296          0.618182           0.145455
             policy (refund, cancellation, warranty, exchange)       66         0.863636    0.872851      0.873247          0.575758           0.121212
                       availability, coverage or delivery time       60         0.816667    0.871493      0.870224          0.600000           0.300000
             product or plan details (specs, what is included)       59         0.932203    0.868100      0.868274          0.745763           0.237288
account or subscription management (upgrade, renewal, closing)       64         0.875000    0.866317      0.869672          0.265625           0.109375
                      comparison between two products or plans       66         0.924242    0.863636      0.868251          0.575758           0.212121
         troubleshooting a problem with the product or service       66         0.893939    0.863385      0.865742          0.621212           0.106061
                    billing dispute or a charge on the account       64         0.921875    0.854484      0.856941          0.265625           0.250000

[4/5] Answerable vs unanswerable by question type...
                                                 question_type  answerable  queries  mean_score  median_score  same_domain_rate  same_country_rate
account or subscription management (upgrade, renewal, closing)       False        8    0.863151      0.869760          0.125000           0.000000
account or subscription management (upgrade, renewal, closing)        True       56    0.866769      0.869599          0.285714           0.125000
                       availability, coverage or delivery time       False       11    0.849309      0.850805          0.545455           0.363636
                       availability, coverage or delivery time        True       49    0.876473      0.874286          0.612245           0.285714
                    billing dispute or a charge on the account       False        5    0.858620      0.859708          0.000000           0.200000
                    billing dispute or a charge on the account        True       59    0.854133      0.854724          0.288136           0.254237
                      comparison between two products or plans       False        5    0.854264      0.850577          0.400000           0.400000
                      comparison between two products or plans        True       61    0.864405      0.871614          0.590164           0.196721
             policy (refund, cancellation, warranty, exchange)       False        9    0.866874      0.865096          0.333333           0.222222
             policy (refund, cancellation, warranty, exchange)        True       57    0.873795      0.873915          0.614035           0.105263
                                               pricing or fees       False        5    0.855577      0.865090          0.200000           0.200000
                                               pricing or fees        True       50    0.876860      0.875755          0.660000           0.140000
             product or plan details (specs, what is included)       False        4    0.836405      0.841274          0.500000           0.500000
             product or plan details (specs, what is included)        True       55    0.870405      0.871810          0.763636           0.218182
         troubleshooting a problem with the product or service       False        7    0.864320      0.864595          0.428571           0.285714
         troubleshooting a problem with the product or service        True       59    0.863274      0.866117          0.644068           0.084746

[5/5] Weakest question types...
                                                 question_type  queries  mean_score  same_domain_rate  same_country_rate
                    billing dispute or a charge on the account       64    0.854484          0.265625           0.250000
account or subscription management (upgrade, renewal, closing)       64    0.866317          0.265625           0.109375
                      comparison between two products or plans       66    0.863636          0.575758           0.212121
             policy (refund, cancellation, warranty, exchange)       66    0.872851          0.575758           0.121212
                       availability, coverage or delivery time       60    0.871493          0.600000           0.300000
                                               pricing or fees       55    0.874926          0.618182           0.145455
         troubleshooting a problem with the product or service       66    0.863385          0.621212           0.106061
             product or plan details (specs, what is included)       59    0.868100          0.745763           0.237288

======================================================================
STEP 6R COMPLETED
======================================================================

Saved objects:
✓ step6r_type_analysis
✓ step6r_type_summary
✓ step6r_answerability_by_type
✓ step6r_weakest_types

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [48]:
# ============================================================
# STEP 6S — TOP-3 UNIQUE DOMAIN COVERAGE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6S — TOP-3 UNIQUE DOMAIN COVERAGE")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

print("\n[1/4] Validating existing objects...")

assert "step6c_evaluation" in globals()
assert "test_df" in globals()
assert "step6l_original_to_unique" in globals()

evaluation = step6c_evaluation

assert len(evaluation) == 500

original_to_unique = (
    step6l_original_to_unique
    .set_index("original_corpus_idx")["unique_content_id"]
    .to_dict()
)

print(f"Queries: {len(evaluation):,}")


# ------------------------------------------------------------
# 2. Build Top-3 unique-content domain coverage
# ------------------------------------------------------------

print("\n[2/4] Calculating Top-3 unique domain coverage...")

rows = []

for item in evaluation:

    test_idx = int(item["test_idx"])
    test_row = test_df.iloc[test_idx]

    retrieved = item["retrieved"]

    seen_unique = set()
    unique_results = []

    for result in retrieved:

        corpus_idx = int(result["corpus_idx"])
        unique_id = original_to_unique[corpus_idx]

        if unique_id in seen_unique:
            continue

        seen_unique.add(unique_id)
        unique_results.append(result)

        if len(unique_results) == 3:
            break

    assert len(unique_results) == 3

    retrieved_domains = [
        r["domain"]
        for r in unique_results
    ]

    retrieved_countries = [
        r["country"]
        for r in unique_results
    ]

    same_domain_flags = [
        r["domain"] == test_row["domain"]
        for r in unique_results
    ]

    same_country_flags = [
        r["country"] == test_row["country"]
        for r in unique_results
    ]

    rows.append({
        "test_idx": test_idx,
        "test_id": item["test_id"],
        "answerable": bool(item["answerable"]),

        "test_domain": test_row["domain"],
        "test_country": test_row["country"],

        "top1_same_domain":
            same_domain_flags[0],

        "top2_same_domain":
            same_domain_flags[1],

        "top3_same_domain":
            same_domain_flags[2],

        "top3_has_same_domain":
            any(same_domain_flags),

        "top3_domain_count":
            sum(same_domain_flags),

        "top3_has_same_country":
            any(same_country_flags),

        "top3_country_count":
            sum(same_country_flags),

        "unique_domains":
            len(set(retrieved_domains)),

        "unique_countries":
            len(set(retrieved_countries)),

        "top1_score":
            float(unique_results[0]["score"]),

        "top2_score":
            float(unique_results[1]["score"]),

        "top3_score":
            float(unique_results[2]["score"])
    })


top3_coverage = pd.DataFrame(rows)


# ------------------------------------------------------------
# 3. Overall Top-3 coverage
# ------------------------------------------------------------

print("\n[3/4] Overall Top-3 coverage...")

print(
    f"Top-1 same-domain rate      : "
    f"{top3_coverage['top1_same_domain'].mean():.2%}"
)

print(
    f"Top-3 contains same-domain  : "
    f"{top3_coverage['top3_has_same_domain'].mean():.2%}"
)

print(
    f"Mean same-domain results    : "
    f"{top3_coverage['top3_domain_count'].mean():.2f}/3"
)

print(
    f"Top-3 contains same-country : "
    f"{top3_coverage['top3_has_same_country'].mean():.2%}"
)

print(
    f"Mean same-country results   : "
    f"{top3_coverage['top3_country_count'].mean():.2f}/3"
)


# ------------------------------------------------------------
# 4. Coverage by answerability
# ------------------------------------------------------------

print("\n[4/4] Top-3 coverage by answerability...")

coverage_by_answerability = (
    top3_coverage
    .groupby("answerable")
    .agg(
        queries=("test_id", "count"),

        top1_same_domain_rate=(
            "top1_same_domain",
            "mean"
        ),

        top3_same_domain_coverage=(
            "top3_has_same_domain",
            "mean"
        ),

        mean_same_domain_results=(
            "top3_domain_count",
            "mean"
        ),

        top3_same_country_coverage=(
            "top3_has_same_country",
            "mean"
        ),

        mean_top3_score=(
            "top3_score",
            "mean"
        )
    )
    .reset_index()
)

print(
    coverage_by_answerability.to_string(index=False)
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6s_top3_coverage = top3_coverage
step6s_coverage_by_answerability = coverage_by_answerability


print("\n" + "=" * 70)
print("STEP 6S COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6s_top3_coverage")
print("✓ step6s_coverage_by_answerability")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6S — TOP-3 UNIQUE DOMAIN COVERAGE
======================================================================

[1/4] Validating existing objects...
Queries: 500

[2/4] Calculating Top-3 unique domain coverage...

[3/4] Overall Top-3 coverage...
Top-1 same-domain rate      : 53.00%
Top-3 contains same-domain  : 65.80%
Mean same-domain results    : 1.53/3
Top-3 contains same-country : 34.00%
Mean same-country results   : 0.51/3

[4/4] Top-3 coverage by answerability...
 answerable  queries  top1_same_domain_rate  top3_same_domain_coverage  mean_same_domain_results  top3_same_country_coverage  mean_top3_score
      False       54               0.333333                   0.462963                  0.944444                    0.407407         0.849390
       True      446               0.553812                   0.681614                  1.605381                    0.331839         0.862555

======================================================================
STEP 6S COMPLETED
======================================================================

Saved objects:
✓ step6s_top3_coverage
✓ step6s_coverage_by_answerability

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [49]:
# ============================================================
# STEP 6T — TOP-3 DOMAIN COVERAGE BY QUESTION TYPE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6T — TOP-3 DOMAIN COVERAGE BY QUESTION TYPE")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

print("\n[1/4] Validating existing objects...")

assert "step6s_top3_coverage" in globals()
assert "test_df" in globals()

coverage = step6s_top3_coverage.copy()

test_meta = (
    test_df[
        ["id", "question_type"]
    ]
    .copy()
)

test_meta["id"] = test_meta["id"].astype(str)
coverage["test_id"] = coverage["test_id"].astype(str)

coverage = coverage.merge(
    test_meta.rename(
        columns={"id": "test_id"}
    ),
    on="test_id",
    how="left"
)

assert coverage["question_type"].notna().all()

print(f"Queries: {len(coverage):,}")


# ------------------------------------------------------------
# 2. Top-3 coverage by question type
# ------------------------------------------------------------

print("\n[2/4] Calculating coverage by question type...")

type_top3 = (
    coverage
    .groupby("question_type")
    .agg(
        queries=("test_id", "count"),

        answerable_rate=("answerable", "mean"),

        top1_same_domain_rate=(
            "top1_same_domain",
            "mean"
        ),

        top3_domain_coverage=(
            "top3_has_same_domain",
            "mean"
        ),

        mean_same_domain_results=(
            "top3_domain_count",
            "mean"
        ),

        top3_country_coverage=(
            "top3_has_same_country",
            "mean"
        ),

        mean_top3_score=(
            "top3_score",
            "mean"
        )
    )
    .reset_index()
)

type_top3["top3_gain_vs_top1"] = (
    type_top3["top3_domain_coverage"]
    - type_top3["top1_same_domain_rate"]
)

type_top3 = type_top3.sort_values(
    "top3_domain_coverage",
    ascending=False
)


print(
    type_top3.to_string(index=False)
)


# ------------------------------------------------------------
# 3. Identify where Top-3 helps the most
# ------------------------------------------------------------

print("\n[3/4] Question types with largest Top-3 gain...")

largest_gain = (
    type_top3[
        [
            "question_type",
            "queries",
            "top1_same_domain_rate",
            "top3_domain_coverage",
            "top3_gain_vs_top1"
        ]
    ]
    .sort_values(
        "top3_gain_vs_top1",
        ascending=False
    )
)

print(
    largest_gain.to_string(index=False)
)


# ------------------------------------------------------------
# 4. Identify persistent weak intents
# ------------------------------------------------------------

print("\n[4/4] Persistent weak question types...")

persistent_weak = (
    type_top3[
        [
            "question_type",
            "queries",
            "top1_same_domain_rate",
            "top3_domain_coverage",
            "top3_gain_vs_top1",
            "mean_top3_score"
        ]
    ]
    .sort_values(
        [
            "top3_domain_coverage",
            "mean_top3_score"
        ],
        ascending=[
            True,
            True
        ]
    )
    .head(5)
)

print(
    persistent_weak.to_string(index=False)
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6t_type_top3 = type_top3
step6t_largest_gain = largest_gain
step6t_persistent_weak = persistent_weak


print("\n" + "=" * 70)
print("STEP 6T COMPLETED")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6t_type_top3")
print("✓ step6t_largest_gain")
print("✓ step6t_persistent_weak")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6T — TOP-3 DOMAIN COVERAGE BY QUESTION TYPE
======================================================================

[1/4] Validating existing objects...
Queries: 500

[2/4] Calculating coverage by question type...
                                                 question_type  queries  answerable_rate  top1_same_domain_rate  top3_domain_coverage  mean_same_domain_results  top3_country_coverage  mean_top3_score  top3_gain_vs_top1
             product or plan details (specs, what is included)       59         0.932203               0.745763              0.898305                  2.271186               0.508475         0.862271           0.152542
                                               pricing or fees       55         0.909091               0.618182              0.818182                  1.963636               0.254545         0.867873           0.200000
         troubleshooting a problem with the product or service       66         0.893939               0.621212              0.742424                  1.772727               0.227273         0.858527           0.121212
                       availability, coverage or delivery time       60         0.816667               0.600000              0.716667                  1.616667               0.533333         0.864163           0.116667
             policy (refund, cancellation, warranty, exchange)       66         0.863636               0.575758              0.681818                  1.590909               0.257576         0.868719           0.106061
                      comparison between two products or plans       66         0.924242               0.575758              0.666667                  1.636364               0.378788         0.856731           0.090909
account or subscription management (upgrade, renewal, closing)       64         0.875000               0.265625              0.421875                  0.796875               0.203125         0.861447           0.156250
                    billing dispute or a charge on the account       64         0.921875               0.265625              0.359375                  0.734375               0.375000         0.850543           0.093750

[3/4] Question types with largest Top-3 gain...
                                                 question_type  queries  top1_same_domain_rate  top3_domain_coverage  top3_gain_vs_top1
                                               pricing or fees       55               0.618182              0.818182           0.200000
account or subscription management (upgrade, renewal, closing)       64               0.265625              0.421875           0.156250
             product or plan details (specs, what is included)       59               0.745763              0.898305           0.152542
         troubleshooting a problem with the product or service       66               0.621212              0.742424           0.121212
                       availability, coverage or delivery time       60               0.600000              0.716667           0.116667
             policy (refund, cancellation, warranty, exchange)       66               0.575758              0.681818           0.106061
                    billing dispute or a charge on the account       64               0.265625              0.359375           0.093750
                      comparison between two products or plans       66               0.575758              0.666667           0.090909

[4/4] Persistent weak question types...
                                                 question_type  queries  top1_same_domain_rate  top3_domain_coverage  top3_gain_vs_top1  mean_top3_score
                    billing dispute or a charge on the account       64               0.265625              0.359375           0.093750         0.850543
account or subscription management (upgrade, renewal, closing)       64               0.265625              0.421875           0.156250         0.861447
                      comparison between two products or plans       66               0.575758              0.666667           0.090909         0.856731
             policy (refund, cancellation, warranty, exchange)       66               0.575758              0.681818           0.106061         0.868719
                       availability, coverage or delivery time       60               0.600000              0.716667           0.116667         0.864163

======================================================================
STEP 6T COMPLETED
======================================================================

Saved objects:
✓ step6t_type_top3
✓ step6t_largest_gain
✓ step6t_persistent_weak

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [51]:
# ============================================================
# STEP 6U — FIXED INTENT ALIGNMENT ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6U — FIXED INTENT ALIGNMENT ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing retrieval data
# ------------------------------------------------------------

print("\n[1/4] Validating existing objects...")

assert "intent_alignment" in globals()

assert len(intent_alignment) == 1500
assert "same_question_type" in intent_alignment.columns
assert "position" in intent_alignment.columns

print(
    f"Unique retrieval records: "
    f"{len(intent_alignment):,}"
)


# ------------------------------------------------------------
# 2. Intent alignment by Top-3 position
# ------------------------------------------------------------

print("\n[2/4] Intent alignment by position...")

position_summary = (
    intent_alignment
    .groupby("position")
    .agg(
        queries=("test_id", "count"),

        same_intent_rate=(
            "same_question_type",
            "mean"
        ),

        mean_score=("score", "mean"),
        median_score=("score", "median")
    )
    .reset_index()
)

print(
    position_summary.to_string(index=False)
)


# ------------------------------------------------------------
# 3. Query-level Top-1 / Top-3 intent coverage
# ------------------------------------------------------------

print("\n[3/4] Overall intent coverage...")

query_intent = (
    intent_alignment
    .groupby(
        ["test_id", "test_question_type"]
    )
    .agg(
        top1_same_intent=(
            "same_question_type",
            "first"
        ),

        top3_has_same_intent=(
            "same_question_type",
            "max"
        ),

        top3_intent_count=(
            "same_question_type",
            "sum"
        )
    )
    .reset_index()
)

print(
    f"Top-1 same-intent rate: "
    f"{query_intent['top1_same_intent'].mean():.2%}"
)

print(
    f"Top-3 contains same intent: "
    f"{query_intent['top3_has_same_intent'].mean():.2%}"
)

print(
    f"Mean same-intent results in Top-3: "
    f"{query_intent['top3_intent_count'].mean():.2f}/3"
)


# ------------------------------------------------------------
# 4. Intent coverage by question type
# ------------------------------------------------------------

print("\n[4/4] Intent coverage by question type...")

type_intent = (
    query_intent
    .groupby("test_question_type")
    .agg(
        queries=("test_id", "count"),

        top1_same_intent_rate=(
            "top1_same_intent",
            "mean"
        ),

        top3_intent_coverage=(
            "top3_has_same_intent",
            "mean"
        ),

        mean_same_intent_results=(
            "top3_intent_count",
            "mean"
        )
    )
    .reset_index()
)

type_intent["top3_gain_vs_top1"] = (
    type_intent["top3_intent_coverage"]
    - type_intent["top1_same_intent_rate"]
)

type_intent = type_intent.sort_values(
    "top3_intent_coverage",
    ascending=False
)

print(
    type_intent.to_string(index=False)
)


# ------------------------------------------------------------
# Save results
# ------------------------------------------------------------

step6u_intent_alignment = intent_alignment
step6u_position_summary = position_summary
step6u_query_intent = query_intent
step6u_type_intent = type_intent


print("\n" + "=" * 70)
print("STEP 6U COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6u_intent_alignment")
print("✓ step6u_position_summary")
print("✓ step6u_query_intent")
print("✓ step6u_type_intent")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6U — FIXED INTENT ALIGNMENT ANALYSIS
======================================================================

[1/4] Validating existing objects...
Unique retrieval records: 1,500

[2/4] Intent alignment by position...
 position  queries  same_intent_rate  mean_score  median_score
        1      500             0.218    0.866702      0.867077
        2      500             0.188    0.863205      0.863671
        3      500             0.194    0.861133      0.861777

[3/4] Overall intent coverage...
Top-1 same-intent rate: 21.80%
Top-3 contains same intent: 46.60%
Mean same-intent results in Top-3: 0.60/3

[4/4] Intent coverage by question type...
                                            test_question_type  queries  top1_same_intent_rate  top3_intent_coverage  mean_same_intent_results  top3_gain_vs_top1
account or subscription management (upgrade, renewal, closing)       64               0.406250              0.640625                  0.953125           0.234375
                      comparison between two products or plans       66               0.212121              0.530303                  0.621212           0.318182
                       availability, coverage or delivery time       60               0.183333              0.466667                  0.616667           0.283333
         troubleshooting a problem with the product or service       66               0.196970              0.454545                  0.560606           0.257576
                    billing dispute or a charge on the account       64               0.218750              0.437500                  0.578125           0.218750
                                               pricing or fees       55               0.200000              0.436364                  0.527273           0.236364
             product or plan details (specs, what is included)       59               0.203390              0.406780                  0.508475           0.203390
             policy (refund, cancellation, warranty, exchange)       66               0.121212              0.348485                  0.424242           0.227273

======================================================================
STEP 6U COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step6u_intent_alignment
✓ step6u_position_summary
✓ step6u_query_intent
✓ step6u_type_intent

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [56]:
# ============================================================
# STEP 6V — INSPECT ACTUAL AUDIT SCHEMA
# ============================================================

print("=" * 70)
print("STEP 6V — INSPECT ACTUAL AUDIT SCHEMA")
print("=" * 70)

assert "audit" in globals()

print("\nAudit shape:")
print(audit.shape)

print("\nAudit columns:")
for i, col in enumerate(audit.columns, start=1):
    print(f"{i:02d}. {col}")

print("\nRelevant columns:")
relevant = [
    col for col in audit.columns
    if (
        "question" in col.lower()
        or "retriev" in col.lower()
        or "candidate" in col.lower()
        or "domain" in col.lower()
        or "country" in col.lower()
        or "intent" in col.lower()
    )
]

for col in relevant:
    print(f"✓ {col}")

print("\nFirst audit row:")
print(
    audit.iloc[0][relevant].to_string()
)

print("\n" + "=" * 70)
print("SCHEMA INSPECTION COMPLETED")
print("=" * 70)

======================================================================
STEP 6V — INSPECT ACTUAL AUDIT SCHEMA
======================================================================

Audit shape:
(801, 14)

Audit columns:
01. test_id
02. test_idx
03. answerable
04. test_question_type
05. position
06. retrieved_id
07. retrieved_domain
08. retrieved_country
09. retrieved_question_type
10. score
11. same_question_type
12. question
13. test_domain
14. test_country

Relevant columns:
✓ test_question_type
✓ retrieved_id
✓ retrieved_domain
✓ retrieved_country
✓ retrieved_question_type
✓ same_question_type
✓ question
✓ test_domain
✓ test_country

First audit row:
test_question_type                                 account or subscription management (upgrade, renewal, closing)
retrieved_id                                                                                               1398-3
retrieved_domain                                                                                streaming service
retrieved_country                                                                                         Morocco
retrieved_question_type                                         product or plan details (specs, what is included)
same_question_type                                                                                          False
question                   أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!
test_domain                                                                                         water utility
test_country                                                                                              Tunisia

======================================================================
SCHEMA INSPECTION COMPLETED
======================================================================

In [57]:
# ============================================================
# STEP 6V — FINAL CLEAN HARD-MISS AUDIT
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6V — FINAL CLEAN HARD-MISS AUDIT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

assert "audit" in globals()
assert "hard_misses" in globals()

assert len(audit) == 801
assert len(hard_misses) == 267

print("\n[1/3] Validation")
print(f"Hard Top-3 intent misses : {len(hard_misses):,}")
print(f"Audit records            : {len(audit):,}")


# ------------------------------------------------------------
# 2. Build representative queries
# ------------------------------------------------------------

print("\n[2/3] Building representative hard misses...")

query_meta = (
    audit[
        [
            "test_id",
            "answerable",
            "test_question_type",
            "test_domain",
            "test_country",
            "question"
        ]
    ]
    .drop_duplicates("test_id")
    .copy()
)

top1_scores = (
    audit[
        audit["position"] == 1
    ][
        [
            "test_id",
            "score"
        ]
    ]
    .rename(
        columns={
            "score": "top1_score"
        }
    )
)

representative = (
    query_meta
    .merge(
        top1_scores,
        on="test_id",
        how="left"
    )
    .sort_values(
        [
            "answerable",
            "top1_score"
        ],
        ascending=[
            False,
            True
        ]
    )
    .head(20)
    .copy()
)

print(f"Representative queries: {len(representative)}")


# ------------------------------------------------------------
# 3. Print hard-miss audit
# ------------------------------------------------------------

print("\n[3/3] Hard-miss retrieval audit")

for _, row in representative.iterrows():

    print("\n" + "-" * 70)

    print(f"Test ID       : {row['test_id']}")
    print(f"Answerable    : {row['answerable']}")
    print(f"Question Type : {row['test_question_type']}")
    print(f"Domain        : {row['test_domain']}")
    print(f"Country       : {row['test_country']}")
    print(f"Question      : {row['question']}")
    print(f"Top-1 Score   : {row['top1_score']:.4f}")

    print("\nTop-3 Retrieved:")

    query_rows = (
        audit[
            audit["test_id"] == row["test_id"]
        ]
        .sort_values("position")
    )

    for _, r in query_rows.iterrows():

        print(
            f"\n  Rank {int(r['position'])}"
        )

        print(
            f"  Score         : {r['score']:.4f}"
        )

        print(
            f"  ID            : {r['retrieved_id']}"
        )

        print(
            f"  Domain        : {r['retrieved_domain']}"
        )

        print(
            f"  Country       : {r['retrieved_country']}"
        )

        print(
            f"  Question Type : "
            f"{r['retrieved_question_type']}"
        )

        print(
            f"  Same Intent   : "
            f"{r['same_question_type']}"
        )


# ------------------------------------------------------------
# Save final Step 6V artifacts
# ------------------------------------------------------------

step6v_hard_misses = hard_misses.copy()
step6v_audit = audit.copy()
step6v_representative = representative.copy()


print("\n" + "=" * 70)
print("STEP 6V COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6v_hard_misses")
print("✓ step6v_audit")
print("✓ step6v_representative")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6V — FINAL CLEAN HARD-MISS AUDIT
======================================================================

[1/3] Validation
Hard Top-3 intent misses : 267
Audit records            : 801

[2/3] Building representative hard misses...
Representative queries: 20

[3/3] Hard-miss retrieval audit

----------------------------------------------------------------------
Test ID       : 6938-2
Answerable    : True
Question Type : comparison between two products or plans
Domain        : mobile wallet / payments app
Country       : Egypt
Question      : الفرق بين الأساسية والمميزة؟
Top-1 Score   : 0.8074

Top-3 Retrieved:

  Rank 1
  Score         : 0.8074
  ID            : 4437-3
  Domain        : mobile wallet / payments app
  Country       : Morocco
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

  Rank 2
  Score         : 0.8043
  ID            : 429-2
  Domain        : mobile wallet / payments app
  Country       : Morocco
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

  Rank 3
  Score         : 0.8037
  ID            : 1595-3
  Domain        : mobile wallet / payments app
  Country       : Morocco
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6980-0
Answerable    : True
Question Type : comparison between two products or plans
Domain        : car insurance
Country       : Qatar
Question      : الفرق بين الأساسي والشامل؟
Top-1 Score   : 0.8117

Top-3 Retrieved:

  Rank 1
  Score         : 0.8117
  ID            : 6067-3
  Domain        : car insurance
  Country       : Saudi Arabia
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

  Rank 2
  Score         : 0.8006
  ID            : 1643-2
  Domain        : car insurance
  Country       : Saudi Arabia
  Question Type : pricing or fees
  Same Intent   : False

  Rank 3
  Score         : 0.8005
  ID            : 3216-2
  Domain        : car insurance
  Country       : Tunisia
  Question Type : account or subscription management (upgrade, renewal, closing)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6946-3
Answerable    : True
Question Type : troubleshooting a problem with the product or service
Domain        : health insurance
Country       : Egypt
Question      : لقد مر وقت طويل ولم أستلم بطاقتي حتى الآن، هذا إهمال غير مقبول!
Top-1 Score   : 0.8137

Top-3 Retrieved:

  Rank 1
  Score         : 0.8137
  ID            : 3136-3
  Domain        : gym / fitness club chain
  Country       : Algeria
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

  Rank 2
  Score         : 0.8133
  ID            : 6823-3
  Domain        : hotel chain
  Country       : Kuwait
  Question Type : comparison between two products or plans
  Same Intent   : False

  Rank 3
  Score         : 0.8125
  ID            : 1740-3
  Domain        : food delivery app
  Country       : Lebanon
  Question Type : comparison between two products or plans
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6906-3
Answerable    : True
Question Type : comparison between two products or plans
Domain        : online electronics store
Country       : Tunisia
Question      : ما الفرق بين سريع 1 وسريع 2؟ لا أريد تضييع وقتي في البحث!
Top-1 Score   : 0.8144

Top-3 Retrieved:

  Rank 1
  Score         : 0.8144
  ID            : 3185-2
  Domain        : internet service provider
  Country       : Iraq
  Question Type : pricing or fees
  Same Intent   : False

  Rank 2
  Score         : 0.8039
  ID            : 3891-3
  Domain        : internet service provider
  Country       : Egypt
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

  Rank 3
  Score         : 0.8035
  ID            : 5733-1
  Domain        : ride-hailing app
  Country       : Saudi Arabia
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6876-1
Answerable    : True
Question Type : troubleshooting a problem with the product or service
Domain        : furniture store
Country       : Oman
Question      : طاولة رخام خدوش. ماذا أفعل؟
Top-1 Score   : 0.8164

Top-3 Retrieved:

  Rank 1
  Score         : 0.8164
  ID            : 1192-0
  Domain        : furniture store
  Country       : Saudi Arabia
  Question Type : comparison between two products or plans
  Same Intent   : False

  Rank 2
  Score         : 0.8112
  ID            : 4180-3
  Domain        : furniture store
  Country       : Kuwait
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

  Rank 3
  Score         : 0.8102
  ID            : 4765-1
  Domain        : furniture store
  Country       : Algeria
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6896-2
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : ride-hailing app
Country       : Saudi Arabia
Question      : لقد تم خصم مبلغ إضافي من رحلتي الأخيرة وأرغب في استعادته.
Top-1 Score   : 0.8188

Top-3 Retrieved:

  Rank 1
  Score         : 0.8188
  ID            : 3320-3
  Domain        : internet service provider
  Country       : Bahrain
  Question Type : pricing or fees
  Same Intent   : False

  Rank 2
  Score         : 0.8185
  ID            : 6538-2
  Domain        : airline
  Country       : Oman
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

  Rank 3
  Score         : 0.8171
  ID            : 270-3
  Domain        : water utility
  Country       : Bahrain
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6906-1
Answerable    : True
Question Type : account or subscription management (upgrade, renewal, closing)
Domain        : online electronics store
Country       : Tunisia
Question      : أريد إغلاق اشتراك 'نور بلس' فوراً، لقد سئمت من هذه الإجراءات المعقدة!
Top-1 Score   : 0.8227

Top-3 Retrieved:

  Rank 1
  Score         : 0.8227
  ID            : 1740-3
  Domain        : food delivery app
  Country       : Lebanon
  Question Type : comparison between two products or plans
  Same Intent   : False

  Rank 2
  Score         : 0.8218
  ID            : 5427-3
  Domain        : hotel chain
  Country       : Bahrain
  Question Type : pricing or fees
  Same Intent   : False

  Rank 3
  Score         : 0.8179
  ID            : 1398-3
  Domain        : streaming service
  Country       : Morocco
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6945-0
Answerable    : True
Question Type : comparison between two products or plans
Domain        : online electronics store
Country       : Morocco
Question      : الفرق بين أطلس X وأطلس برو؟
Top-1 Score   : 0.8247

Top-3 Retrieved:

  Rank 1
  Score         : 0.8247
  ID            : 630-0
  Domain        : online electronics store
  Country       : Algeria
  Question Type : account or subscription management (upgrade, renewal, closing)
  Same Intent   : False

  Rank 2
  Score         : 0.8212
  ID            : 3984-3
  Domain        : online electronics store
  Country       : Algeria
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 3
  Score         : 0.8208
  ID            : 5067-1
  Domain        : online electronics store
  Country       : Morocco
  Question Type : billing dispute or a charge on the account
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6936-0
Answerable    : True
Question Type : comparison between two products or plans
Domain        : courier / parcel delivery
Country       : Kuwait
Question      : الفرق بين الفضية والذهبية؟
Top-1 Score   : 0.8288

Top-3 Retrieved:

  Rank 1
  Score         : 0.8288
  ID            : 6644-3
  Domain        : gym / fitness club chain
  Country       : Saudi Arabia
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8285
  ID            : 2038-3
  Domain        : streaming service
  Country       : Bahrain
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

  Rank 3
  Score         : 0.8248
  ID            : 3860-1
  Domain        : mobile wallet / payments app
  Country       : Egypt
  Question Type : pricing or fees
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6953-1
Answerable    : True
Question Type : comparison between two products or plans
Domain        : health insurance
Country       : Iraq
Question      : الفرق بين الفضية والذهبية؟
Top-1 Score   : 0.8288

Top-3 Retrieved:

  Rank 1
  Score         : 0.8288
  ID            : 6644-3
  Domain        : gym / fitness club chain
  Country       : Saudi Arabia
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8285
  ID            : 2038-3
  Domain        : streaming service
  Country       : Bahrain
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

  Rank 3
  Score         : 0.8248
  ID            : 3860-1
  Domain        : mobile wallet / payments app
  Country       : Egypt
  Question Type : pricing or fees
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6935-1
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : health insurance
Country       : Lebanon
Question      : تحية طيبة، لقد لاحظت وجود مبلغ مخصوم من حسابي لم أكن أتوقعه بخصوص مطالبتي الأخيرة، وأود الاستفسار عن الإجراء المتبع للاعتراض على هذه القيمة المالية.
Top-1 Score   : 0.8301

Top-3 Retrieved:

  Rank 1
  Score         : 0.8301
  ID            : 1282-1
  Domain        : water utility
  Country       : Iraq
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8292
  ID            : 6653-3
  Domain        : health insurance
  Country       : Algeria
  Question Type : availability, coverage or delivery time
  Same Intent   : False

  Rank 3
  Score         : 0.8287
  ID            : 5399-3
  Domain        : health insurance
  Country       : Algeria
  Question Type : pricing or fees
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6920-1
Answerable    : True
Question Type : troubleshooting a problem with the product or service
Domain        : mobile wallet / payments app
Country       : the United Arab Emirates
Question      : الرصيد لا يتحدث. ماذا أفعل؟
Top-1 Score   : 0.8306

Top-3 Retrieved:

  Rank 1
  Score         : 0.8306
  ID            : 3982-3
  Domain        : mobile wallet / payments app
  Country       : Oman
  Question Type : account or subscription management (upgrade, renewal, closing)
  Same Intent   : False

  Rank 2
  Score         : 0.8295
  ID            : 5887-3
  Domain        : retail bank
  Country       : Egypt
  Question Type : availability, coverage or delivery time
  Same Intent   : False

  Rank 3
  Score         : 0.8289
  ID            : 1428-2
  Domain        : telecom / mobile network
  Country       : Tunisia
  Question Type : availability, coverage or delivery time
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6973-1
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : streaming service
Country       : Bahrain
Question      : لقد تم خصم مبلغ إضافي من حسابي وأرغب في تقديم اعتراض على هذه العملية.
Top-1 Score   : 0.8307

Top-3 Retrieved:

  Rank 1
  Score         : 0.8307
  ID            : 1748-3
  Domain        : car insurance
  Country       : Tunisia
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8294
  ID            : 291-3
  Domain        : gym / fitness club chain
  Country       : Saudi Arabia
  Question Type : account or subscription management (upgrade, renewal, closing)
  Same Intent   : False

  Rank 3
  Score         : 0.8278
  ID            : 5871-1
  Domain        : gym / fitness club chain
  Country       : Lebanon
  Question Type : comparison between two products or plans
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6934-2
Answerable    : True
Question Type : account or subscription management (upgrade, renewal, closing)
Domain        : water utility
Country       : Lebanon
Question      : ترقية للاشتراك الذهبي.
Top-1 Score   : 0.8314

Top-3 Retrieved:

  Rank 1
  Score         : 0.8314
  ID            : 2989-0
  Domain        : hotel chain
  Country       : Morocco
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8282
  ID            : 4112-2
  Domain        : streaming service
  Country       : Egypt
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

  Rank 3
  Score         : 0.8276
  ID            : 3395-3
  Domain        : health insurance
  Country       : Saudi Arabia
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6880-3
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : water utility
Country       : Oman
Question      : لقد تم احتساب مبالغ إضافية في فاتورتي وهذا خطأ فادح! كيف أستعيد أموالي؟
Top-1 Score   : 0.8332

Top-3 Retrieved:

  Rank 1
  Score         : 0.8332
  ID            : 2232-0
  Domain        : online electronics store
  Country       : Bahrain
  Question Type : availability, coverage or delivery time
  Same Intent   : False

  Rank 2
  Score         : 0.8319
  ID            : 3790-3
  Domain        : furniture store
  Country       : Bahrain
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 3
  Score         : 0.8306
  ID            : 963-3
  Domain        : e-commerce marketplace
  Country       : Tunisia
  Question Type : pricing or fees
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6946-0
Answerable    : True
Question Type : comparison between two products or plans
Domain        : health insurance
Country       : Egypt
Question      : أريد معرفة الفرق بين الباقة الأساسية والمتميزة فوراً، لقد سئمت من الانتظار!
Top-1 Score   : 0.8355

Top-3 Retrieved:

  Rank 1
  Score         : 0.8355
  ID            : 4005-3
  Domain        : mobile wallet / payments app
  Country       : Lebanon
  Question Type : pricing or fees
  Same Intent   : False

  Rank 2
  Score         : 0.8354
  ID            : 2034-2
  Domain        : water utility
  Country       : Egypt
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

  Rank 3
  Score         : 0.8346
  ID            : 3849-3
  Domain        : streaming service
  Country       : Kuwait
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6939-3
Answerable    : True
Question Type : troubleshooting a problem with the product or service
Domain        : courier / parcel delivery
Country       : Kuwait
Question      : لقد دفعت مبلغاً إضافياً لخدمة إكسبريس ولكن الطرد لم يصل في الوقت المحدد، هذا غير مقبول!
Top-1 Score   : 0.8356

Top-3 Retrieved:

  Rank 1
  Score         : 0.8356
  ID            : 5255-3
  Domain        : courier / parcel delivery
  Country       : Lebanon
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8338
  ID            : 310-3
  Domain        : electricity utility
  Country       : the United Arab Emirates
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 3
  Score         : 0.8328
  ID            : 1864-3
  Domain        : courier / parcel delivery
  Country       : Algeria
  Question Type : pricing or fees
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6959-0
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : hotel chain
Country       : Jordan
Question      : خصم 120 ديناراً غير مبرر. لماذا؟
Top-1 Score   : 0.8362

Top-3 Retrieved:

  Rank 1
  Score         : 0.8362
  ID            : 2960-3
  Domain        : online electronics store
  Country       : Jordan
  Question Type : availability, coverage or delivery time
  Same Intent   : False

  Rank 2
  Score         : 0.8340
  ID            : 3622-2
  Domain        : furniture store
  Country       : Kuwait
  Question Type : pricing or fees
  Same Intent   : False

  Rank 3
  Score         : 0.8313
  ID            : 719-3
  Domain        : furniture store
  Country       : Jordan
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6945-1
Answerable    : True
Question Type : comparison between two products or plans
Domain        : online electronics store
Country       : Morocco
Question      : أريد معرفة الفرق بين الباقة الذهبية والبلاتينية فوراً، لا وقت لدي للمراسلات الطويلة!
Top-1 Score   : 0.8365

Top-3 Retrieved:

  Rank 1
  Score         : 0.8365
  ID            : 3808-1
  Domain        : health insurance
  Country       : Tunisia
  Question Type : product or plan details (specs, what is included)
  Same Intent   : False

  Rank 2
  Score         : 0.8335
  ID            : 6514-3
  Domain        : water utility
  Country       : Algeria
  Question Type : policy (refund, cancellation, warranty, exchange)
  Same Intent   : False

  Rank 3
  Score         : 0.8318
  ID            : 2546-3
  Domain        : water utility
  Country       : Morocco
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

----------------------------------------------------------------------
Test ID       : 6977-0
Answerable    : True
Question Type : billing dispute or a charge on the account
Domain        : private hospital group
Country       : Tunisia
Question      : السلام عليكم، لقد قمت بإجراء استشارة طبية يوم الأحد الماضي، وعند مراجعة فاتورتي وجدت مبلغاً إضافياً قدره 50 ديناراً لم أكن أعلم به، هل يمكنكم توضيح سبب هذا الرسم؟
Top-1 Score   : 0.8366

Top-3 Retrieved:

  Rank 1
  Score         : 0.8366
  ID            : 3693-2
  Domain        : private hospital group
  Country       : Kuwait
  Question Type : comparison between two products or plans
  Same Intent   : False

  Rank 2
  Score         : 0.8355
  ID            : 5279-3
  Domain        : internet service provider
  Country       : Iraq
  Question Type : troubleshooting a problem with the product or service
  Same Intent   : False

  Rank 3
  Score         : 0.8340
  ID            : 2191-2
  Domain        : private hospital group
  Country       : Iraq

In [58]:
# ============================================================
# STEP 6W — HARD-MISS ROOT CAUSE CLASSIFICATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6W — HARD-MISS ROOT CAUSE CLASSIFICATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6v_audit" in globals()
assert "step6v_hard_misses" in globals()

audit_w = step6v_audit.copy()

assert len(audit_w) == 801

print("\n[1/4] Input validation")
print(f"Hard-miss audit records: {len(audit_w):,}")


# ------------------------------------------------------------
# 2. Use Top-1 only for root-cause classification
# ------------------------------------------------------------

print("\n[2/4] Classifying Top-1 root cause...")

top1 = (
    audit_w[
        audit_w["position"] == 1
    ][
        [
            "test_id",
            "answerable",
            "test_question_type",
            "test_domain",
            "test_country",
            "retrieved_id",
            "retrieved_domain",
            "retrieved_country",
            "retrieved_question_type",
            "score"
        ]
    ]
    .copy()
)

assert len(top1) == 267
assert top1["test_id"].nunique() == 267


# ------------------------------------------------------------
# 3. Root-cause categories
# ------------------------------------------------------------

top1["same_domain"] = (
    top1["test_domain"]
    == top1["retrieved_domain"]
)

top1["same_intent"] = (
    top1["test_question_type"]
    == top1["retrieved_question_type"]
)

def classify_root_cause(row):

    domain = bool(row["same_domain"])
    intent = bool(row["same_intent"])

    if domain and intent:
        return "domain + intent correct"

    if domain and not intent:
        return "domain correct / intent wrong"

    if not domain and intent:
        return "domain wrong / intent correct"

    return "domain + intent wrong"


top1["root_cause"] = (
    top1.apply(
        classify_root_cause,
        axis=1
    )
)


# ------------------------------------------------------------
# 4. Summary
# ------------------------------------------------------------

print("\n[3/4] Overall root-cause distribution")

root_summary = (
    top1["root_cause"]
    .value_counts()
    .rename_axis("root_cause")
    .reset_index(name="count")
)

root_summary["percentage"] = (
    root_summary["count"]
    / len(top1)
    * 100
)

print(
    root_summary.to_string(
        index=False,
        formatters={
            "percentage": "{:.2f}%".format
        }
    )
)


# ------------------------------------------------------------
# 5. Breakdown by Question Type
# ------------------------------------------------------------

print("\n[4/4] Root cause by Question Type")

type_root = (
    top1
    .groupby(
        [
            "test_question_type",
            "root_cause"
        ],
        dropna=False
    )
    .size()
    .reset_index(name="count")
)

type_totals = (
    top1
    .groupby("test_question_type")
    .size()
    .rename("total")
    .reset_index()
)

type_root = type_root.merge(
    type_totals,
    on="test_question_type",
    how="left"
)

type_root["percentage"] = (
    type_root["count"]
    / type_root["total"]
    * 100
)

type_root = (
    type_root
    .sort_values(
        [
            "test_question_type",
            "count"
        ],
        ascending=[
            True,
            False
        ]
    )
)

print(
    type_root.to_string(
        index=False,
        formatters={
            "percentage": "{:.2f}%".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6w_root_cause = top1
step6w_root_summary = root_summary
step6w_type_root = type_root


print("\n" + "=" * 70)
print("STEP 6W COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6w_root_cause")
print("✓ step6w_root_summary")
print("✓ step6w_type_root")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6W — HARD-MISS ROOT CAUSE CLASSIFICATION
======================================================================

[1/4] Input validation
Hard-miss audit records: 801

[2/4] Classifying Top-1 root cause...

[3/4] Overall root-cause distribution
                   root_cause  count percentage
domain correct / intent wrong    143     53.56%
        domain + intent wrong    124     46.44%

[4/4] Root cause by Question Type
                                            test_question_type                    root_cause  count  total percentage
account or subscription management (upgrade, renewal, closing)         domain + intent wrong     21     23     91.30%
account or subscription management (upgrade, renewal, closing) domain correct / intent wrong      2     23      8.70%
                       availability, coverage or delivery time domain correct / intent wrong     20     32     62.50%
                       availability, coverage or delivery time         domain + intent wrong     12     32     37.50%
                    billing dispute or a charge on the account         domain + intent wrong     27     36     75.00%
                    billing dispute or a charge on the account domain correct / intent wrong      9     36     25.00%
                      comparison between two products or plans domain correct / intent wrong     18     31     58.06%
                      comparison between two products or plans         domain + intent wrong     13     31     41.94%
             policy (refund, cancellation, warranty, exchange) domain correct / intent wrong     26     43     60.47%
             policy (refund, cancellation, warranty, exchange)         domain + intent wrong     17     43     39.53%
                                               pricing or fees domain correct / intent wrong     20     31     64.52%
                                               pricing or fees         domain + intent wrong     11     31     35.48%
             product or plan details (specs, what is included) domain correct / intent wrong     29     35     82.86%
             product or plan details (specs, what is included)         domain + intent wrong      6     35     17.14%
         troubleshooting a problem with the product or service domain correct / intent wrong     19     36     52.78%
         troubleshooting a problem with the product or service         domain + intent wrong     17     36     47.22%

======================================================================
STEP 6W COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step6w_root_cause
✓ step6w_root_summary
✓ step6w_type_root

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [59]:
# ============================================================
# STEP 6X — HARD-MISS RECOVERY BY TOP-K
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6X — HARD-MISS RECOVERY BY TOP-K")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate input
# ------------------------------------------------------------

assert "step6v_audit" in globals()
assert "step6v_hard_misses" in globals()

audit_x = step6v_audit.copy()

assert len(audit_x) == 801
assert len(step6v_hard_misses) == 267

print("\n[1/4] Input validation")
print(f"Hard-miss queries: {len(step6v_hard_misses):,}")
print(f"Audit records    : {len(audit_x):,}")


# ------------------------------------------------------------
# 2. Keep only Top-3
# ------------------------------------------------------------

print("\n[2/4] Evaluating Top-3 recovery...")

top3 = (
    audit_x[
        audit_x["position"] <= 3
    ]
    .copy()
)

assert len(top3) == 801


# ------------------------------------------------------------
# 3. Per-query recovery signals
# ------------------------------------------------------------

records = []

for test_id, group in top3.groupby("test_id"):

    test_domain = group["test_domain"].iloc[0]
    test_intent = group["test_question_type"].iloc[0]

    same_domain = (
        group["retrieved_domain"]
        == test_domain
    )

    same_intent = (
        group["retrieved_question_type"]
        == test_intent
    )

    both = (
        same_domain
        & same_intent
    )

    records.append(
        {
            "test_id": test_id,

            "answerable":
                group["answerable"].iloc[0],

            "question_type":
                test_intent,

            "test_domain":
                test_domain,

            "top3_has_same_domain":
                bool(same_domain.any()),

            "top3_has_same_intent":
                bool(same_intent.any()),

            "top3_has_same_domain_and_intent":
                bool(both.any()),

            "same_domain_count":
                int(same_domain.sum()),

            "same_intent_count":
                int(same_intent.sum()),

            "same_domain_and_intent_count":
                int(both.sum()),

            "best_score":
                float(group["score"].max())
        }
    )


recovery = pd.DataFrame(records)

assert len(recovery) == 267


# ------------------------------------------------------------
# 4. Overall recovery summary
# ------------------------------------------------------------

print("\n[3/4] Overall Top-3 recovery")

summary = pd.DataFrame(
    {
        "metric": [
            "Top-3 has same domain",
            "Top-3 has same intent",
            "Top-3 has same domain + intent",
        ],
        "count": [
            recovery["top3_has_same_domain"].sum(),
            recovery["top3_has_same_intent"].sum(),
            recovery["top3_has_same_domain_and_intent"].sum(),
        ]
    }
)

summary["percentage"] = (
    summary["count"]
    / len(recovery)
    * 100
)

print(
    summary.to_string(
        index=False,
        formatters={
            "percentage": "{:.2f}%".format
        }
    )
)


# ------------------------------------------------------------
# 5. Recovery by Question Type
# ------------------------------------------------------------

print("\n[4/4] Recovery by Question Type")

type_recovery = (
    recovery
    .groupby("question_type")
    .agg(
        queries=("test_id", "count"),

        top3_same_domain=(
            "top3_has_same_domain",
            "sum"
        ),

        top3_same_intent=(
            "top3_has_same_intent",
            "sum"
        ),

        top3_same_domain_intent=(
            "top3_has_same_domain_and_intent",
            "sum"
        )
    )
    .reset_index()
)

type_recovery["domain_%"] = (
    type_recovery["top3_same_domain"]
    / type_recovery["queries"]
    * 100
)

type_recovery["intent_%"] = (
    type_recovery["top3_same_intent"]
    / type_recovery["queries"]
    * 100
)

type_recovery["domain_intent_%"] = (
    type_recovery["top3_same_domain_intent"]
    / type_recovery["queries"]
    * 100
)

print(
    type_recovery.to_string(
        index=False,
        formatters={
            "domain_%": "{:.2f}%".format,
            "intent_%": "{:.2f}%".format,
            "domain_intent_%": "{:.2f}%".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6x_recovery = recovery
step6x_summary = summary
step6x_type_recovery = type_recovery


print("\n" + "=" * 70)
print("STEP 6X COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6x_recovery")
print("✓ step6x_summary")
print("✓ step6x_type_recovery")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6X — HARD-MISS RECOVERY BY TOP-K
======================================================================

[1/4] Input validation
Hard-miss queries: 267
Audit records    : 801

[2/4] Evaluating Top-3 recovery...

[3/4] Overall Top-3 recovery
                        metric  count percentage
         Top-3 has same domain    180     67.42%
         Top-3 has same intent      0      0.00%
Top-3 has same domain + intent      0      0.00%

[4/4] Recovery by Question Type
                                                 question_type  queries  top3_same_domain  top3_same_intent  top3_same_domain_intent domain_% intent_% domain_intent_%
account or subscription management (upgrade, renewal, closing)       23                 6                 0                        0   26.09%    0.00%           0.00%
                       availability, coverage or delivery time       32                24                 0                        0   75.00%    0.00%           0.00%
                    billing dispute or a charge on the account       36                13                 0                        0   36.11%    0.00%           0.00%
                      comparison between two products or plans       31                20                 0                        0   64.52%    0.00%           0.00%
             policy (refund, cancellation, warranty, exchange)       43                33                 0                        0   76.74%    0.00%           0.00%
                                               pricing or fees       31                26                 0                        0   83.87%    0.00%           0.00%
             product or plan details (specs, what is included)       35                32                 0                        0   91.43%    0.00%           0.00%
         troubleshooting a problem with the product or service       36                26                 0                        0   72.22%    0.00%           0.00%

======================================================================
STEP 6X COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step6x_recovery
✓ step6x_summary
✓ step6x_type_recovery

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [62]:
# ============================================================
# STEP 6Y — FIXED HARD-MISS GOLD / PROXY AVAILABILITY
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 6Y — FIXED HARD-MISS GOLD / PROXY AVAILABILITY")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

assert "step6v_hard_misses" in globals()
assert "step6v_audit" in globals()
assert "step6b_proxy_df" in globals()

audit_y = step6v_audit.copy()
proxy_y = step6b_proxy_df.copy()

print("\n[1/4] Input validation")

print(
    f"Hard misses             : "
    f"{audit_y['test_id'].nunique():,}"
)

print(
    f"Test gold chunks        : "
    f"{len(proxy_y):,}"
)

print(
    f"Reliable proxy mappings : "
    f"{proxy_y['proxy_reliable'].sum():,}"
)


# ------------------------------------------------------------
# 2. Get hard-miss query IDs
# ------------------------------------------------------------

print("\n[2/4] Building hard-miss query metadata...")

hard_ids = (
    step6v_hard_misses["test_id"]
    .astype(str)
    .unique()
)

hard_ids = set(hard_ids)

query_meta = (
    audit_y[
        audit_y["test_id"].astype(str).isin(hard_ids)
    ][
        [
            "test_id",
            "answerable",
            "test_question_type",
            "test_domain",
            "test_country"
        ]
    ]
    .drop_duplicates("test_id")
    .copy()
)

query_meta["test_id"] = (
    query_meta["test_id"].astype(str)
)

assert len(query_meta) == 267


# ------------------------------------------------------------
# 3. Match proxy availability
# ------------------------------------------------------------

print("\n[3/4] Matching hard misses to proxy availability...")

proxy_hard = (
    proxy_y[
        proxy_y["test_id"]
        .astype(str)
        .isin(hard_ids)
    ]
    .copy()
)

proxy_hard["test_id"] = (
    proxy_hard["test_id"].astype(str)
)

proxy_query = (
    proxy_hard
    .groupby("test_id")
    .agg(
        gold_chunks=(
            "gold_chunk_idx",
            "count"
        ),

        reliable_proxy=(
            "proxy_reliable",
            "any"
        ),

        best_proxy_score=(
            "lexical_top1_score",
            "max"
        )
    )
    .reset_index()
)

analysis_y = (
    query_meta
    .merge(
        proxy_query,
        on="test_id",
        how="left"
    )
)

analysis_y["reliable_proxy"] = (
    analysis_y["reliable_proxy"]
    .fillna(False)
    .astype(bool)
)

analysis_y["has_reliable_proxy"] = (
    analysis_y["reliable_proxy"]
)

analysis_y["gold_chunks"] = (
    analysis_y["gold_chunks"]
    .fillna(0)
    .astype(int)
)

analysis_y["best_proxy_score"] = (
    analysis_y["best_proxy_score"]
    .fillna(0.0)
)

assert len(analysis_y) == 267


# ------------------------------------------------------------
# 4. Overall + type analysis
# ------------------------------------------------------------

print("\n[4/4] Proxy availability results")

availability_summary = pd.DataFrame(
    {
        "metric": [
            "Hard-miss queries",
            "Queries with reliable proxy",
            "Queries without reliable proxy"
        ],

        "count": [
            len(analysis_y),

            int(
                analysis_y[
                    "has_reliable_proxy"
                ].sum()
            ),

            int(
                (
                    ~analysis_y[
                        "has_reliable_proxy"
                    ]
                ).sum()
            )
        ]
    }
)

availability_summary["percentage"] = (
    availability_summary["count"]
    / len(analysis_y)
    * 100
)

print(
    "\nOverall:"
)

print(
    availability_summary.to_string(
        index=False,
        formatters={
            "percentage": "{:.2f}%".format
        }
    )
)


print(
    "\nBy Question Type:"
)

type_availability = (
    analysis_y
    .groupby("test_question_type")
    .agg(
        queries=(
            "test_id",
            "count"
        ),

        reliable_proxy=(
            "has_reliable_proxy",
            "sum"
        ),

        mean_best_proxy_score=(
            "best_proxy_score",
            "mean"
        )
    )
    .reset_index()
)

type_availability["reliable_proxy_%"] = (
    type_availability["reliable_proxy"]
    / type_availability["queries"]
    * 100
)

type_availability = (
    type_availability
    .sort_values(
        "reliable_proxy_%",
        ascending=False
    )
)

print(
    type_availability.to_string(
        index=False,
        formatters={
            "reliable_proxy_%":
                "{:.2f}%".format,

            "mean_best_proxy_score":
                "{:.4f}".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step6y_proxy_availability = analysis_y
step6y_availability_summary = availability_summary
step6y_type_availability = type_availability


print("\n" + "=" * 70)
print("STEP 6Y COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step6y_proxy_availability")
print("✓ step6y_availability_summary")
print("✓ step6y_type_availability")

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")
print("No dataset was changed.")

======================================================================
STEP 6Y — FIXED HARD-MISS GOLD / PROXY AVAILABILITY
======================================================================

[1/4] Input validation
Hard misses             : 267
Test gold chunks        : 465
Reliable proxy mappings : 174

[2/4] Building hard-miss query metadata...

[3/4] Matching hard misses to proxy availability...

[4/4] Proxy availability results

Overall:
                        metric  count percentage
             Hard-miss queries    267    100.00%
   Queries with reliable proxy     94     35.21%
Queries without reliable proxy    173     64.79%

By Question Type:
                                            test_question_type  queries  reliable_proxy mean_best_proxy_score reliable_proxy_%
             product or plan details (specs, what is included)       35              21                0.5889           60.00%
                      comparison between two products or plans       31              13                0.5390           41.94%
             policy (refund, cancellation, warranty, exchange)       43              18                0.5905           41.86%
                    billing dispute or a charge on the account       36              15                0.5952           41.67%
                                               pricing or fees       31              10                0.4881           32.26%
                       availability, coverage or delivery time       32               8                0.4239           25.00%
         troubleshooting a problem with the product or service       36               7                0.5167           19.44%
account or subscription management (upgrade, renewal, closing)       23               2                0.4938            8.70%

======================================================================
STEP 6Y COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step6y_proxy_availability
✓ step6y_availability_summary
✓ step6y_type_availability

No embeddings were recomputed.
No FAISS index was modified.
No dataset was changed.

In [63]:
# ============================================================
# STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
# PART 1: VERIFY EXISTING RETRIEVAL ARTIFACTS
# ============================================================

print("=" * 70)
print("STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT")
print("PART 1 — VERIFY EXISTING RETRIEVAL ARTIFACTS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Required objects
# ------------------------------------------------------------

required_objects = [
    "step6c_evaluation",
    "step6c_metrics",
    "step6v_audit",
    "step6y_proxy_availability",
    "train_corpus",
    "train_df",
    "test_df",
    "index"
]

print("\n[1/3] Checking required objects...")

for obj_name in required_objects:

    exists = obj_name in globals()

    print(
        f"{'✓' if exists else '✗'} "
        f"{obj_name}"
    )

    assert exists, (
        f"Required object missing: {obj_name}"
    )


# ------------------------------------------------------------
# 2. Inspect baseline retrieval structure
# ------------------------------------------------------------

print("\n[2/3] Inspecting baseline retrieval...")

assert isinstance(
    step6c_evaluation,
    list
)

print(
    f"Test queries          : "
    f"{len(step6c_evaluation):,}"
)

first_eval = step6c_evaluation[0]

print(
    "\nEvaluation fields:"
)

for key in first_eval.keys():
    print(f"✓ {key}")


print(
    "\nRetrieved candidate fields:"
)

first_candidate = (
    first_eval["retrieved"][0]
)

for key in first_candidate.keys():
    print(f"✓ {key}")


# ------------------------------------------------------------
# 3. Candidate coverage check
# ------------------------------------------------------------

print("\n[3/3] Checking candidate coverage...")

retrieval_sizes = [
    len(item["retrieved"])
    for item in step6c_evaluation
]

print(
    f"Min candidates/query : "
    f"{min(retrieval_sizes)}"
)

print(
    f"Max candidates/query : "
    f"{max(retrieval_sizes)}"
)

print(
    f"Mean candidates/query: "
    f"{np.mean(retrieval_sizes):.2f}"
)

assert min(retrieval_sizes) >= 10


print("\nSample baseline candidate:")

sample = step6c_evaluation[0]["retrieved"][0]

for key, value in sample.items():

    if key == "chunk_text":
        value = str(value)[:250] + "..."

    print(
        f"{key}: {value}"
    )


print("\n" + "=" * 70)
print("STEP 7A PART 1 COMPLETED")
print("=" * 70)

print(
    "\nReady for controlled reranking experiment."
)

print(
    "No embeddings were recomputed."
)

print(
    "No FAISS index was modified."
)

======================================================================
STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
PART 1 — VERIFY EXISTING RETRIEVAL ARTIFACTS
======================================================================

[1/3] Checking required objects...
✓ step6c_evaluation
✓ step6c_metrics
✓ step6v_audit
✓ step6y_proxy_availability
✓ train_corpus
✓ train_df
✓ test_df
✓ index

[2/3] Inspecting baseline retrieval...
Test queries          : 500

Evaluation fields:
✓ test_idx
✓ test_id
✓ question
✓ answerable
✓ gold_chunk_ids
✓ retrieved

Retrieved candidate fields:
✓ rank
✓ corpus_idx
✓ score
✓ id
✓ chunk_idx
✓ row_idx
✓ domain
✓ country
✓ company
✓ chunk_text

[3/3] Checking candidate coverage...
Min candidates/query : 10
Max candidates/query : 10
Mean candidates/query: 10.00

Sample baseline candidate:
rank: 1
corpus_idx: 33508
score: 0.8562403917312622
id: 1398-3
chunk_idx: 3
row_idx: 5580
domain: streaming service
country: Morocco
company: شاشة المغرب
chunk_text: لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب....

======================================================================
STEP 7A PART 1 COMPLETED
======================================================================

Ready for controlled reranking experiment.
No embeddings were recomputed.
No FAISS index was modified.

In [64]:
# ============================================================
# STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
# PART 2 — LOAD MULTILINGUAL RERANKER + SANITY TEST
# ============================================================

import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

print("=" * 70)
print("STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT")
print("PART 2 — MULTILINGUAL RERANKER")
print("=" * 70)


# ------------------------------------------------------------
# 1. Configuration
# ------------------------------------------------------------

RERANKER_NAME = "BAAI/bge-reranker-v2-m3"

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("\n[1/4] Configuration")

print(f"Model  : {RERANKER_NAME}")
print(f"Device : {device}")

if torch.cuda.is_available():
    print(
        f"GPU    : "
        f"{torch.cuda.get_device_name(0)}"
    )


# ------------------------------------------------------------
# 2. Load tokenizer
# ------------------------------------------------------------

print("\n[2/4] Loading tokenizer...")

reranker_tokenizer = AutoTokenizer.from_pretrained(
    RERANKER_NAME
)

print("✓ Tokenizer loaded")


# ------------------------------------------------------------
# 3. Load model
# ------------------------------------------------------------

print("\n[3/4] Loading reranker model...")

reranker_model = (
    AutoModelForSequenceClassification
    .from_pretrained(
        RERANKER_NAME
    )
    .to(device)
)

reranker_model.eval()

print("✓ Reranker loaded")
print(
    f"Parameters: "
    f"{sum(p.numel() for p in reranker_model.parameters()):,}"
)


# ------------------------------------------------------------
# 4. Single-query sanity test
# ------------------------------------------------------------

print("\n[4/4] Running single-query sanity test...")

sample_eval = step6c_evaluation[0]

query = sample_eval["question"]

candidates = sample_eval["retrieved"]

texts = [
    candidate["chunk_text"]
    for candidate in candidates
]

inputs = reranker_tokenizer(
    [query] * len(texts),
    texts,
    padding=True,
    truncation=True,
    max_length=512,
    return_tensors="pt"
)

inputs = {
    key: value.to(device)
    for key, value in inputs.items()
}

with torch.no_grad():

    outputs = reranker_model(
        **inputs
    )

    logits = outputs.logits.view(-1)

scores = logits.detach().cpu().numpy()


# ------------------------------------------------------------
# Display sanity result
# ------------------------------------------------------------

print(
    f"\nQuery:"
)

print(query)

print(
    "\nReranker scores:"
)

for rank, score in enumerate(scores, start=1):

    print(
        f"Candidate {rank:2d} | "
        f"score = {score:.6f}"
    )


# ------------------------------------------------------------
# Validation
# ------------------------------------------------------------

assert len(scores) == 10
assert np.isfinite(scores).all()

print("\n" + "=" * 70)
print("STEP 7A PART 2 COMPLETED")
print("=" * 70)

print(
    "\n✓ Reranker is loaded successfully."
)

print(
    "✓ 10/10 candidates scored successfully."
)

print(
    "✓ No embeddings were recomputed."
)

print(
    "✓ FAISS index was not modified."
)

print(
    "\nNext: apply reranking to all 500 × Top-10 candidates."
)

======================================================================
STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
PART 2 — MULTILINGUAL RERANKER
======================================================================

[1/4] Configuration
Model  : BAAI/bge-reranker-v2-m3
Device : cuda
GPU    : Tesla T4

[2/4] Loading tokenizer...

config.json:   0%|          | 0.00/795 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.17k [00:00<?, ?B/s]

sentencepiece.bpe.model: reconstructing file:   0%|          |  0.00B / 5.07MB

sentencepiece.bpe.model: downloading bytes:           |  0.00B

tokenizer.json: reconstructing file:   0%|          |  0.00B / 17.1MB

tokenizer.json: downloading bytes:           |  0.00B

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

✓ Tokenizer loaded

[3/4] Loading reranker model...

model.safetensors: reconstructing file:   0%|          |  0.00B / 2.27GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

✓ Reranker loaded
Parameters: 567,755,777

[4/4] Running single-query sanity test...

Query:
أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!

Reranker scores:
Candidate  1 | score = 1.458237
Candidate  2 | score = 1.458237
Candidate  3 | score = 1.458237
Candidate  4 | score = 1.458237
Candidate  5 | score = 0.107621
Candidate  6 | score = 0.107621
Candidate  7 | score = 0.107621
Candidate  8 | score = 0.107621
Candidate  9 | score = 0.491474
Candidate 10 | score = 0.491474

======================================================================
STEP 7A PART 2 COMPLETED
======================================================================

✓ Reranker is loaded successfully.
✓ 10/10 candidates scored successfully.
✓ No embeddings were recomputed.
✓ FAISS index was not modified.

Next: apply reranking to all 500 × Top-10 candidates.

In [65]:
# ============================================================
# STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
# PART 3 — RERANK ALL 500 × TOP-10 CANDIDATES
# ============================================================

import time
import numpy as np
import pandas as pd
import torch

print("=" * 70)
print("STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT")
print("PART 3 — FULL TOP-10 RERANKING")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "reranker_tokenizer" in globals()
assert "reranker_model" in globals()

assert len(step6c_evaluation) == 500

print("\n[1/5] Input validation")
print("✓ Test queries       : 500")
print("✓ Candidates/query   : 10")
print("✓ Total pairs        : 5,000")
print("✓ Reranker           : BAAI/bge-reranker-v2-m3")
print("✓ Device             :", device)


# ------------------------------------------------------------
# 2. Prepare all query-document pairs
# ------------------------------------------------------------

print("\n[2/5] Preparing query-document pairs...")

all_queries = []
all_texts = []

for evaluation in step6c_evaluation:

    query = evaluation["question"]

    for candidate in evaluation["retrieved"]:

        all_queries.append(query)
        all_texts.append(candidate["chunk_text"])

assert len(all_queries) == 5000
assert len(all_texts) == 5000

print(
    f"✓ Prepared {len(all_queries):,} query-document pairs"
)


# ------------------------------------------------------------
# 3. Batch reranking
# ------------------------------------------------------------

print("\n[3/5] Running reranker...")

BATCH_SIZE = 16

all_scores = []

start_time = time.time()

for start_idx in range(
    0,
    len(all_queries),
    BATCH_SIZE
):

    end_idx = min(
        start_idx + BATCH_SIZE,
        len(all_queries)
    )

    batch_queries = all_queries[
        start_idx:end_idx
    ]

    batch_texts = all_texts[
        start_idx:end_idx
    ]

    inputs = reranker_tokenizer(
        batch_queries,
        batch_texts,
        padding=True,
        truncation=True,
        max_length=512,
        return_tensors="pt"
    )

    inputs = {
        key: value.to(device)
        for key, value in inputs.items()
    }

    with torch.no_grad():

        outputs = reranker_model(
            **inputs
        )

        batch_scores = (
            outputs.logits
            .view(-1)
            .detach()
            .cpu()
            .numpy()
        )

    all_scores.extend(
        batch_scores.tolist()
    )

    if (
        (end_idx % 500 == 0)
        or
        (end_idx == len(all_queries))
    ):

        elapsed = time.time() - start_time

        print(
            f"Processed "
            f"{end_idx:>5,}/5,000 "
            f"pairs | "
            f"Elapsed: {elapsed:.1f}s"
        )


elapsed = time.time() - start_time


# ------------------------------------------------------------
# 4. Attach reranker scores
# ------------------------------------------------------------

print("\n[4/5] Building reranked results...")

assert len(all_scores) == 5000
assert np.isfinite(all_scores).all()

reranked_evaluation = []

pair_idx = 0

for evaluation in step6c_evaluation:

    reranked_candidates = []

    for candidate in evaluation["retrieved"]:

        candidate_copy = candidate.copy()

        candidate_copy[
            "reranker_score"
        ] = float(
            all_scores[pair_idx]
        )

        reranked_candidates.append(
            candidate_copy
        )

        pair_idx += 1


    # Sort by reranker score
    reranked_candidates = sorted(
        reranked_candidates,
        key=lambda x: x["reranker_score"],
        reverse=True
    )


    # Reassign rank
    for new_rank, candidate in enumerate(
        reranked_candidates,
        start=1
    ):

        candidate["rerank_rank"] = new_rank


    reranked_evaluation.append(
        {
            "test_idx": evaluation["test_idx"],
            "test_id": evaluation["test_id"],
            "question": evaluation["question"],
            "answerable": evaluation["answerable"],
            "gold_chunk_ids": evaluation[
                "gold_chunk_ids"
            ],
            "retrieved": reranked_candidates
        }
    )


assert len(reranked_evaluation) == 500


# ------------------------------------------------------------
# 5. Sanity checks
# ------------------------------------------------------------

print("\n[5/5] Sanity checks...")

candidate_counts = [
    len(item["retrieved"])
    for item in reranked_evaluation
]

assert min(candidate_counts) == 10
assert max(candidate_counts) == 10

# Verify ranking order
for item in reranked_evaluation:

    scores = [
        candidate["reranker_score"]
        for candidate in item["retrieved"]
    ]

    assert all(
        scores[i] >= scores[i + 1]
        for i in range(len(scores) - 1)
    )


# ------------------------------------------------------------
# Display first query before/after
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("FIRST QUERY — BASELINE vs RERANKED")
print("-" * 70)

first_baseline = step6c_evaluation[0]
first_reranked = reranked_evaluation[0]

print("\nQuery:")
print(first_baseline["question"])


print("\nBASELINE E5 TOP-5:")

for candidate in first_baseline["retrieved"][:5]:

    print(
        f"Rank {candidate['rank']:>2} | "
        f"E5 = {candidate['score']:.6f} | "
        f"{candidate['id']} | "
        f"chunk {candidate['chunk_idx']}"
    )


print("\nRERANKED TOP-5:")

for candidate in first_reranked["retrieved"][:5]:

    print(
        f"Rank {candidate['rerank_rank']:>2} | "
        f"Reranker = "
        f"{candidate['reranker_score']:.6f} | "
        f"E5 = {candidate['score']:.6f} | "
        f"{candidate['id']} | "
        f"chunk {candidate['chunk_idx']}"
    )


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7a_reranked_evaluation = reranked_evaluation

print("\n" + "=" * 70)
print("STEP 7A PART 3 COMPLETED SUCCESSFULLY")
print("=" * 70)

print(
    f"\nTotal pairs reranked : {len(all_scores):,}"
)

print(
    f"Total queries        : "
    f"{len(reranked_evaluation):,}"
)

print(
    f"Elapsed time         : "
    f"{elapsed:.2f} sec"
)

print(
    "\n✓ Baseline results preserved."
)

print(
    "✓ Reranked results saved as:"
)

print(
    "  step7a_reranked_evaluation"
)

print(
    "\nNo embeddings were recomputed."
)

print(
    "No FAISS index was modified."
)

======================================================================
STEP 7A — CONTROLLED RETRIEVAL IMPROVEMENT
PART 3 — FULL TOP-10 RERANKING
======================================================================

[1/5] Input validation
✓ Test queries       : 500
✓ Candidates/query   : 10
✓ Total pairs        : 5,000
✓ Reranker           : BAAI/bge-reranker-v2-m3
✓ Device             : cuda

[2/5] Preparing query-document pairs...
✓ Prepared 5,000 query-document pairs

[3/5] Running reranker...
Processed 2,000/5,000 pairs | Elapsed: 35.9s
Processed 4,000/5,000 pairs | Elapsed: 73.1s
Processed 5,000/5,000 pairs | Elapsed: 92.2s

[4/5] Building reranked results...

[5/5] Sanity checks...

----------------------------------------------------------------------
FIRST QUERY — BASELINE vs RERANKED
----------------------------------------------------------------------

Query:
أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!

BASELINE E5 TOP-5:
Rank  1 | E5 = 0.856240 | 1398-3 | chunk 3
Rank  2 | E5 = 0.856240 | 1398-2 | chunk 3
Rank  3 | E5 = 0.856240 | 1398-1 | chunk 3
Rank  4 | E5 = 0.856240 | 1398-0 | chunk 3
Rank  5 | E5 = 0.854451 | 5427-3 | chunk 5

RERANKED TOP-5:
Rank  1 | Reranker = 1.458237 | E5 = 0.856240 | 1398-3 | chunk 3
Rank  2 | Reranker = 1.458237 | E5 = 0.856240 | 1398-2 | chunk 3
Rank  3 | Reranker = 1.458237 | E5 = 0.856240 | 1398-1 | chunk 3
Rank  4 | Reranker = 1.458237 | E5 = 0.856240 | 1398-0 | chunk 3
Rank  5 | Reranker = 0.491474 | E5 = 0.853337 | 1740-3 | chunk 4

======================================================================
STEP 7A PART 3 COMPLETED SUCCESSFULLY
======================================================================

Total pairs reranked : 5,000
Total queries        : 500
Elapsed time         : 92.23 sec

✓ Baseline results preserved.
✓ Reranked results saved as:
  step7a_reranked_evaluation

No embeddings were recomputed.
No FAISS index was modified.

In [67]:
# ============================================================
# STEP 7B — DEBUG METADATA MISMATCH
# ============================================================

print("=" * 70)
print("STEP 7B — DEBUG METADATA MISMATCH")
print("=" * 70)


# ------------------------------------------------------------
# 1. Inspect audit IDs
# ------------------------------------------------------------

print("\n[1/3] step6v_audit")

print(
    "Rows:",
    len(step6v_audit)
)

print(
    "Unique test IDs:",
    step6v_audit["test_id"].nunique()
)

print(
    "First 10 IDs:"
)

print(
    step6v_audit["test_id"]
    .astype(str)
    .unique()[:10]
)


# ------------------------------------------------------------
# 2. Inspect test_df
# ------------------------------------------------------------

print("\n[2/3] test_df")

print(
    "Shape:",
    test_df.shape
)

print(
    "Columns:"
)

for col in test_df.columns:
    print(f"✓ {col}")


# ------------------------------------------------------------
# 3. Check ID availability
# ------------------------------------------------------------

print("\n[3/3] ID consistency")

audit_ids = set(
    step6v_audit["test_id"]
    .astype(str)
)

test_ids = set(
    test_df["id"]
    .astype(str)
)

print(
    "IDs in test_df:",
    len(test_ids)
)

print(
    "IDs in audit:",
    len(audit_ids)
)

print(
    "Test IDs missing from audit:",
    len(test_ids - audit_ids)
)

print(
    "Audit IDs not in test_df:",
    len(audit_ids - test_ids)
)

print("\n" + "=" * 70)
print("DEBUG COMPLETED")
print("=" * 70)

======================================================================
STEP 7B — DEBUG METADATA MISMATCH
======================================================================

[1/3] step6v_audit
Rows: 801
Unique test IDs: 267
First 10 IDs:
<ArrowStringArray>
['6875-0', '6875-1', '6875-2', '6876-1', '6876-2', '6877-0', '6877-3',
 '6878-1', '6878-2', '6879-1']
Length: 10, dtype: str

[2/3] test_df
Shape: (500, 15)
Columns:
✓ id
✓ company_id
✓ company
✓ domain
✓ country
✓ chunks
✓ question
✓ answer
✓ answerable
✓ gold_chunk_ids
✓ question_type
✓ tone
✓ n_tokens
✓ question_chars
✓ answer_chars

[3/3] ID consistency
IDs in test_df: 500
IDs in audit: 267
Test IDs missing from audit: 233
Audit IDs not in test_df: 0

======================================================================
DEBUG COMPLETED
======================================================================

In [68]:
# ============================================================
# STEP 7B — BASELINE vs RERANKED RETRIEVAL COMPARISON
# FIXED METADATA SOURCE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7B — BASELINE vs RERANKED RETRIEVAL COMPARISON")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "step7a_reranked_evaluation" in globals()
assert "test_df" in globals()

assert len(step6c_evaluation) == 500
assert len(step7a_reranked_evaluation) == 500
assert len(test_df) == 500

print("\n[1/5] Input validation")
print("✓ Baseline queries : 500")
print("✓ Reranked queries : 500")
print("✓ Test metadata    : 500")


# ------------------------------------------------------------
# 2. Build metadata directly from test_df
# ------------------------------------------------------------

print("\n[2/5] Loading complete test metadata...")

test_meta = (
    test_df[
        [
            "id",
            "question_type",
            "domain",
            "country"
        ]
    ]
    .copy()
)

test_meta = test_meta.rename(
    columns={
        "id": "test_id",
        "question_type": "test_question_type",
        "domain": "test_domain",
        "country": "test_country"
    }
)

test_meta["test_id"] = (
    test_meta["test_id"].astype(str)
)

assert len(test_meta) == 500
assert test_meta["test_id"].nunique() == 500

print("✓ Complete metadata loaded")


# ------------------------------------------------------------
# 3. Helper function
# ------------------------------------------------------------

def evaluate_ranking(
    evaluation,
    metadata,
    method_name
):

    records = []

    metadata_lookup = (
        metadata
        .set_index("test_id")
    )

    for item in evaluation:

        test_id = str(item["test_id"])

        assert test_id in metadata_lookup.index

        meta = metadata_lookup.loc[test_id]

        test_domain = meta["test_domain"]
        test_question_type = (
            meta["test_question_type"]
        )
        test_country = meta["test_country"]


        candidates = item["retrieved"]


        # ----------------------------------------------------
        # Top-1
        # ----------------------------------------------------

        top1 = candidates[0]

        top1_same_domain = (
            top1["domain"] == test_domain
        )

        top1_same_intent = (
            top1.get("question_type")
            == test_question_type
        )


        # ----------------------------------------------------
        # Top-3
        # ----------------------------------------------------

        top3 = candidates[:3]

        top3_same_domain = any(
            candidate["domain"] == test_domain
            for candidate in top3
        )

        top3_same_intent = any(
            candidate.get("question_type")
            == test_question_type
            for candidate in top3
        )


        # ----------------------------------------------------
        # Unique-content aware ranking
        # ----------------------------------------------------

        unique_contents = []
        seen_texts = set()

        for candidate in candidates:

            text = candidate["chunk_text"]

            if text not in seen_texts:

                seen_texts.add(text)
                unique_contents.append(candidate)

            if len(unique_contents) == 3:
                break


        assert len(unique_contents) == 3

        unique_top1 = unique_contents[0]
        unique_top3 = unique_contents[:3]


        unique_top1_same_domain = (
            unique_top1["domain"]
            == test_domain
        )

        unique_top1_same_intent = (
            unique_top1.get("question_type")
            == test_question_type
        )

        unique_top3_same_domain = any(
            candidate["domain"] == test_domain
            for candidate in unique_top3
        )

        unique_top3_same_intent = any(
            candidate.get("question_type")
            == test_question_type
            for candidate in unique_top3
        )


        # ----------------------------------------------------
        # Save record
        # ----------------------------------------------------

        records.append(
            {
                "test_id": test_id,
                "method": method_name,

                "top1_same_domain":
                    top1_same_domain,

                "top3_same_domain":
                    top3_same_domain,

                "top1_same_intent":
                    top1_same_intent,

                "top3_same_intent":
                    top3_same_intent,

                "unique_top1_same_domain":
                    unique_top1_same_domain,

                "unique_top3_same_domain":
                    unique_top3_same_domain,

                "unique_top1_same_intent":
                    unique_top1_same_intent,

                "unique_top3_same_intent":
                    unique_top3_same_intent,

                "top1_score":
                    float(
                        top1.get(
                            "score",
                            np.nan
                        )
                    ),

                "test_question_type":
                    test_question_type,

                "test_domain":
                    test_domain,

                "test_country":
                    test_country
            }
        )


    return pd.DataFrame(records)


# ------------------------------------------------------------
# 4. Evaluate baseline
# ------------------------------------------------------------

print("\n[3/5] Evaluating E5 baseline...")

baseline_eval_7b = evaluate_ranking(
    step6c_evaluation,
    test_meta,
    "E5_Baseline"
)

assert len(baseline_eval_7b) == 500

print("✓ Baseline evaluated")


# ------------------------------------------------------------
# 5. Evaluate reranked
# ------------------------------------------------------------

print("\n[4/5] Evaluating E5 + BGE Reranker...")

reranked_eval_7b = evaluate_ranking(
    step7a_reranked_evaluation,
    test_meta,
    "E5_plus_BGE_Reranker"
)

assert len(reranked_eval_7b) == 500

print("✓ Reranked results evaluated")


# ------------------------------------------------------------
# 6. Comparison
# ------------------------------------------------------------

print("\n[5/5] Computing comparison...")

comparison_metrics = []

metric_columns = [
    "top1_same_domain",
    "top3_same_domain",
    "top1_same_intent",
    "top3_same_intent",
    "unique_top1_same_domain",
    "unique_top3_same_domain",
    "unique_top1_same_intent",
    "unique_top3_same_intent"
]

metric_labels = {
    "top1_same_domain":
        "Top-1 Same Domain",

    "top3_same_domain":
        "Top-3 Domain Coverage",

    "top1_same_intent":
        "Top-1 Same Intent",

    "top3_same_intent":
        "Top-3 Intent Coverage",

    "unique_top1_same_domain":
        "Unique Top-1 Same Domain",

    "unique_top3_same_domain":
        "Unique Top-3 Domain Coverage",

    "unique_top1_same_intent":
        "Unique Top-1 Same Intent",

    "unique_top3_same_intent":
        "Unique Top-3 Intent Coverage"
}


for column in metric_columns:

    baseline_value = (
        baseline_eval_7b[column]
        .mean()
        * 100
    )

    reranked_value = (
        reranked_eval_7b[column]
        .mean()
        * 100
    )

    comparison_metrics.append(
        {
            "metric":
                metric_labels[column],

            "baseline_%":
                baseline_value,

            "reranked_%":
                reranked_value,

            "change_pp":
                reranked_value
                - baseline_value
        }
    )


step7b_comparison = pd.DataFrame(
    comparison_metrics
)


# ------------------------------------------------------------
# Display results
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BASELINE vs RERANKED")
print("-" * 70)

print(
    step7b_comparison.to_string(
        index=False,
        formatters={
            "baseline_%":
                "{:.2f}".format,

            "reranked_%":
                "{:.2f}".format,

            "change_pp":
                "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7b_baseline_eval = baseline_eval_7b
step7b_reranked_eval = reranked_eval_7b

print("\n" + "=" * 70)
print("STEP 7B COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7b_baseline_eval")
print("✓ step7b_reranked_eval")
print("✓ step7b_comparison")

print("\nMethodological note:")
print(
    "These are retrieval alignment diagnostics "
    "using test metadata."
)

print(
    "They are NOT official Gold Recall@K, "
    "because Test and Train are company-disjoint."
)

print("\nNo embeddings were recomputed.")
print("No FAISS index was modified.")

======================================================================
STEP 7B — BASELINE vs RERANKED RETRIEVAL COMPARISON
======================================================================

[1/5] Input validation
✓ Baseline queries : 500
✓ Reranked queries : 500
✓ Test metadata    : 500

[2/5] Loading complete test metadata...
✓ Complete metadata loaded

[3/5] Evaluating E5 baseline...
✓ Baseline evaluated

[4/5] Evaluating E5 + BGE Reranker...
✓ Reranked results evaluated

[5/5] Computing comparison...

----------------------------------------------------------------------
BASELINE vs RERANKED
----------------------------------------------------------------------
                      metric baseline_% reranked_% change_pp
           Top-1 Same Domain      53.00      53.20     +0.20
       Top-3 Domain Coverage      53.00      55.80     +2.80
           Top-1 Same Intent       0.00       0.00     +0.00
       Top-3 Intent Coverage       0.00       0.00     +0.00
    Unique Top-1 Same Domain      53.00      53.20     +0.20
Unique Top-3 Domain Coverage      65.80      65.80     +0.00
    Unique Top-1 Same Intent       0.00       0.00     +0.00
Unique Top-3 Intent Coverage       0.00       0.00     +0.00

======================================================================
STEP 7B COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7b_baseline_eval
✓ step7b_reranked_eval
✓ step7b_comparison

Methodological note:
These are retrieval alignment diagnostics using test metadata.
They are NOT official Gold Recall@K, because Test and Train are company-disjoint.

No embeddings were recomputed.
No FAISS index was modified.

In [69]:
# ============================================================
# STEP 7B — PART 2
# FIX INTENT METADATA + RE-EVALUATE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7B — PART 2")
print("FIX INTENT METADATA + RE-EVALUATE")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate existing objects
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "step7a_reranked_evaluation" in globals()
assert "test_df" in globals()
assert "train_df" in globals()

print("\n[1/4] Input validation")
print("✓ Baseline retrieval available")
print("✓ Reranked retrieval available")
print("✓ Train metadata available")
print("✓ Test metadata available")


# ------------------------------------------------------------
# 2. Build candidate question-type lookup
# ------------------------------------------------------------

print("\n[2/4] Building candidate intent lookup...")

# Candidate row_idx points to the original train_df row.
train_intent_lookup = (
    train_df[
        [
            "question_type"
        ]
    ]
    .reset_index(drop=True)
)

print(
    f"Train rows available: "
    f"{len(train_intent_lookup):,}"
)

assert len(train_intent_lookup) == len(train_df)


# ------------------------------------------------------------
# 3. Evaluation function
# ------------------------------------------------------------

def get_candidate_intent(candidate):

    row_idx = int(
        candidate["row_idx"]
    )

    assert 0 <= row_idx < len(
        train_intent_lookup
    )

    return train_intent_lookup.iloc[
        row_idx
    ]["question_type"]


def evaluate_ranking_fixed(
    evaluation,
    metadata,
    method_name
):

    records = []

    metadata_lookup = (
        metadata
        .set_index("test_id")
    )

    for item in evaluation:

        test_id = str(
            item["test_id"]
        )

        assert test_id in metadata_lookup.index

        meta = metadata_lookup.loc[
            test_id
        ]

        test_domain = meta[
            "test_domain"
        ]

        test_question_type = meta[
            "test_question_type"
        ]

        test_country = meta[
            "test_country"
        ]


        candidates = item[
            "retrieved"
        ]

        assert len(candidates) == 10


        # ----------------------------------------------------
        # Attach candidate intent
        # ----------------------------------------------------

        enriched_candidates = []

        for candidate in candidates:

            candidate_copy = candidate.copy()

            candidate_copy[
                "question_type"
            ] = get_candidate_intent(
                candidate
            )

            enriched_candidates.append(
                candidate_copy
            )


        # ----------------------------------------------------
        # Top-1
        # ----------------------------------------------------

        top1 = enriched_candidates[0]

        top1_same_domain = (
            top1["domain"]
            == test_domain
        )

        top1_same_intent = (
            top1["question_type"]
            == test_question_type
        )


        # ----------------------------------------------------
        # Top-3
        # ----------------------------------------------------

        top3 = enriched_candidates[:3]

        top3_same_domain = any(
            candidate["domain"]
            == test_domain
            for candidate in top3
        )

        top3_same_intent = any(
            candidate["question_type"]
            == test_question_type
            for candidate in top3
        )


        # ----------------------------------------------------
        # Unique-content Top-3
        # ----------------------------------------------------

        unique_contents = []

        seen_texts = set()

        for candidate in enriched_candidates:

            text = candidate[
                "chunk_text"
            ]

            if text not in seen_texts:

                seen_texts.add(text)

                unique_contents.append(
                    candidate
                )

            if len(unique_contents) == 3:
                break


        assert len(unique_contents) == 3

        unique_top1 = (
            unique_contents[0]
        )

        unique_top3 = (
            unique_contents[:3]
        )


        unique_top1_same_domain = (
            unique_top1["domain"]
            == test_domain
        )

        unique_top1_same_intent = (
            unique_top1["question_type"]
            == test_question_type
        )

        unique_top3_same_domain = any(
            candidate["domain"]
            == test_domain
            for candidate in unique_top3
        )

        unique_top3_same_intent = any(
            candidate["question_type"]
            == test_question_type
            for candidate in unique_top3
        )


        # ----------------------------------------------------
        # Store
        # ----------------------------------------------------

        records.append(
            {
                "test_id":
                    test_id,

                "method":
                    method_name,

                "top1_same_domain":
                    top1_same_domain,

                "top3_same_domain":
                    top3_same_domain,

                "top1_same_intent":
                    top1_same_intent,

                "top3_same_intent":
                    top3_same_intent,

                "unique_top1_same_domain":
                    unique_top1_same_domain,

                "unique_top3_same_domain":
                    unique_top3_same_domain,

                "unique_top1_same_intent":
                    unique_top1_same_intent,

                "unique_top3_same_intent":
                    unique_top3_same_intent,

                "top1_score":
                    float(
                        top1.get(
                            "score",
                            np.nan
                        )
                    ),

                "test_question_type":
                    test_question_type,

                "test_domain":
                    test_domain,

                "test_country":
                    test_country
            }
        )


    return pd.DataFrame(records)


# ------------------------------------------------------------
# 4. Build complete test metadata
# ------------------------------------------------------------

print("\n[3/4] Building test metadata...")

test_meta_fixed = (
    test_df[
        [
            "id",
            "question_type",
            "domain",
            "country"
        ]
    ]
    .copy()
    .rename(
        columns={
            "id":
                "test_id",

            "question_type":
                "test_question_type",

            "domain":
                "test_domain",

            "country":
                "test_country"
        }
    )
)

test_meta_fixed["test_id"] = (
    test_meta_fixed["test_id"]
    .astype(str)
)

assert len(test_meta_fixed) == 500
assert (
    test_meta_fixed["test_id"]
    .nunique()
    == 500
)


# ------------------------------------------------------------
# 5. Re-evaluate both methods
# ------------------------------------------------------------

print(
    "\n[4/4] Re-evaluating baseline "
    "and reranked results..."
)

baseline_eval_7b_fixed = (
    evaluate_ranking_fixed(
        step6c_evaluation,
        test_meta_fixed,
        "E5_Baseline"
    )
)

reranked_eval_7b_fixed = (
    evaluate_ranking_fixed(
        step7a_reranked_evaluation,
        test_meta_fixed,
        "E5_plus_BGE_Reranker"
    )
)

assert len(
    baseline_eval_7b_fixed
) == 500

assert len(
    reranked_eval_7b_fixed
) == 500


# ------------------------------------------------------------
# 6. Calculate comparison
# ------------------------------------------------------------

metrics = [
    (
        "Top-1 Same Domain",
        "top1_same_domain"
    ),

    (
        "Top-3 Domain Coverage",
        "top3_same_domain"
    ),

    (
        "Top-1 Same Intent",
        "top1_same_intent"
    ),

    (
        "Top-3 Intent Coverage",
        "top3_same_intent"
    ),

    (
        "Unique Top-1 Same Domain",
        "unique_top1_same_domain"
    ),

    (
        "Unique Top-3 Domain Coverage",
        "unique_top3_same_domain"
    ),

    (
        "Unique Top-1 Same Intent",
        "unique_top1_same_intent"
    ),

    (
        "Unique Top-3 Intent Coverage",
        "unique_top3_same_intent"
    )
]


comparison_rows = []

for label, column in metrics:

    baseline = (
        baseline_eval_7b_fixed[
            column
        ]
        .mean()
        * 100
    )

    reranked = (
        reranked_eval_7b_fixed[
            column
        ]
        .mean()
        * 100
    )

    comparison_rows.append(
        {
            "metric":
                label,

            "baseline_%":
                baseline,

            "reranked_%":
                reranked,

            "change_pp":
                reranked - baseline
        }
    )


step7b_comparison_fixed = (
    pd.DataFrame(
        comparison_rows
    )
)


# ------------------------------------------------------------
# 7. Verify baseline against known Step 6U
# ------------------------------------------------------------

baseline_intent_top1 = (
    baseline_eval_7b_fixed[
        "top1_same_intent"
    ]
    .mean()
    * 100
)

baseline_intent_top3 = (
    baseline_eval_7b_fixed[
        "top3_same_intent"
    ]
    .mean()
    * 100
)

print("\n" + "-" * 70)
print("BASELINE VALIDATION")
print("-" * 70)

print(
    f"Baseline Top-1 Intent : "
    f"{baseline_intent_top1:.2f}%"
)

print(
    f"Baseline Top-3 Intent : "
    f"{baseline_intent_top3:.2f}%"
)

print(
    "\nExpected from Step 6U:"
)

print(
    "Top-1 Intent = 21.80%"
)

print(
    "Top-3 Intent = 46.60%"
)


# ------------------------------------------------------------
# 8. Final comparison
# ------------------------------------------------------------

print("\n" + "-" * 70)
print("BASELINE vs RERANKED — FIXED")
print("-" * 70)

print(
    step7b_comparison_fixed.to_string(
        index=False,
        formatters={
            "baseline_%":
                "{:.2f}".format,

            "reranked_%":
                "{:.2f}".format,

            "change_pp":
                "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save corrected objects
# ------------------------------------------------------------

step7b_baseline_eval = (
    baseline_eval_7b_fixed
)

step7b_reranked_eval = (
    reranked_eval_7b_fixed
)

step7b_comparison = (
    step7b_comparison_fixed
)


print("\n" + "=" * 70)
print("STEP 7B PART 2 COMPLETED")
print("=" * 70)

print("\nCorrected objects saved:")
print("✓ step7b_baseline_eval")
print("✓ step7b_reranked_eval")
print("✓ step7b_comparison")

print(
    "\n✓ No reranking was repeated."
)

print(
    "✓ No embeddings were recomputed."
)

print(
    "✓ FAISS index was not modified."
)

======================================================================
STEP 7B — PART 2
FIX INTENT METADATA + RE-EVALUATE
======================================================================

[1/4] Input validation
✓ Baseline retrieval available
✓ Reranked retrieval available
✓ Train metadata available
✓ Test metadata available

[2/4] Building candidate intent lookup...
Train rows available: 27,427

[3/4] Building test metadata...

[4/4] Re-evaluating baseline and reranked results...

----------------------------------------------------------------------
BASELINE VALIDATION
----------------------------------------------------------------------
Baseline Top-1 Intent : 21.80%
Baseline Top-3 Intent : 55.00%

Expected from Step 6U:
Top-1 Intent = 21.80%
Top-3 Intent = 46.60%

----------------------------------------------------------------------
BASELINE vs RERANKED — FIXED
----------------------------------------------------------------------
                      metric baseline_% reranked_% change_pp
           Top-1 Same Domain      53.00      53.20     +0.20
       Top-3 Domain Coverage      53.00      55.80     +2.80
           Top-1 Same Intent      21.80      21.80     +0.00
       Top-3 Intent Coverage      55.00      56.20     +1.20
    Unique Top-1 Same Domain      53.00      53.20     +0.20
Unique Top-3 Domain Coverage      65.80      65.80     +0.00
    Unique Top-1 Same Intent      21.80      21.80     +0.00
Unique Top-3 Intent Coverage      46.60      47.60     +1.00

======================================================================
STEP 7B PART 2 COMPLETED
======================================================================

Corrected objects saved:
✓ step7b_baseline_eval
✓ step7b_reranked_eval
✓ step7b_comparison

✓ No reranking was repeated.
✓ No embeddings were recomputed.
✓ FAISS index was not modified.

In [70]:
# ============================================================
# STEP 7C — RERANKER IMPACT ANALYSIS
# QUERY-LEVEL + QUESTION-TYPE ANALYSIS
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7C — RERANKER IMPACT ANALYSIS")
print("QUERY-LEVEL + QUESTION-TYPE ANALYSIS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step7b_baseline_eval" in globals()
assert "step7b_reranked_eval" in globals()

baseline = step7b_baseline_eval.copy()
reranked = step7b_reranked_eval.copy()

assert len(baseline) == 500
assert len(reranked) == 500

print("\n[1/4] Input validation")
print("✓ Baseline : 500")
print("✓ Reranked : 500")


# ------------------------------------------------------------
# 2. Merge paired query results
# ------------------------------------------------------------

print("\n[2/4] Building paired query comparison...")

paired = baseline.merge(
    reranked,
    on="test_id",
    suffixes=(
        "_baseline",
        "_reranked"
    ),
    validate="one_to_one"
)

assert len(paired) == 500


# ------------------------------------------------------------
# 3. Query-level changes
# ------------------------------------------------------------

print("\n[3/4] Computing query-level changes...")

paired["intent_top1_change"] = (
    paired["top1_same_intent_reranked"].astype(int)
    -
    paired["top1_same_intent_baseline"].astype(int)
)

paired["intent_top3_change"] = (
    paired["top3_same_intent_reranked"].astype(int)
    -
    paired["top3_same_intent_baseline"].astype(int)
)

paired["unique_intent_top3_change"] = (
    paired[
        "unique_top3_same_intent_reranked"
    ].astype(int)
    -
    paired[
        "unique_top3_same_intent_baseline"
    ].astype(int)
)

paired["domain_top1_change"] = (
    paired["top1_same_domain_reranked"].astype(int)
    -
    paired["top1_same_domain_baseline"].astype(int)
)

paired["domain_top3_change"] = (
    paired["top3_same_domain_reranked"].astype(int)
    -
    paired["top3_same_domain_baseline"].astype(int)
)

paired["unique_domain_top3_change"] = (
    paired[
        "unique_top3_same_domain_reranked"
    ].astype(int)
    -
    paired[
        "unique_top3_same_domain_baseline"
    ].astype(int)
)


# ------------------------------------------------------------
# Helper
# ------------------------------------------------------------

def summarize_change(series):

    improved = int(
        (series > 0).sum()
    )

    unchanged = int(
        (series == 0).sum()
    )

    worsened = int(
        (series < 0).sum()
    )

    return (
        improved,
        unchanged,
        worsened
    )


# ------------------------------------------------------------
# Overall query-level impact
# ------------------------------------------------------------

impact_rows = []

impact_metrics = [
    (
        "Top-1 Intent",
        "intent_top1_change"
    ),

    (
        "Top-3 Intent",
        "intent_top3_change"
    ),

    (
        "Unique Top-3 Intent",
        "unique_intent_top3_change"
    ),

    (
        "Top-1 Domain",
        "domain_top1_change"
    ),

    (
        "Top-3 Domain",
        "domain_top3_change"
    ),

    (
        "Unique Top-3 Domain",
        "unique_domain_top3_change"
    )
]


for label, column in impact_metrics:

    improved, unchanged, worsened = (
        summarize_change(
            paired[column]
        )
    )

    impact_rows.append(
        {
            "metric": label,
            "improved": improved,
            "unchanged": unchanged,
            "worsened": worsened,
            "net_change":
                improved - worsened
        }
    )


step7c_query_impact = pd.DataFrame(
    impact_rows
)


print("\nOverall Query-Level Impact:")

print(
    step7c_query_impact.to_string(
        index=False
    )
)


# ------------------------------------------------------------
# 4. Question-type analysis
# ------------------------------------------------------------

print("\n[4/4] Analyzing impact by question type...")

type_rows = []

for question_type, group in paired.groupby(
    "test_question_type_baseline"
):

    n = len(group)

    row = {
        "test_question_type":
            question_type,

        "queries":
            n
    }


    # ----------------------------------------
    # Unique Top-3 Intent
    # ----------------------------------------

    change = group[
        "unique_intent_top3_change"
    ]

    row[
        "intent_top3_improved"
    ] = int((change > 0).sum())

    row[
        "intent_top3_unchanged"
    ] = int((change == 0).sum())

    row[
        "intent_top3_worsened"
    ] = int((change < 0).sum())

    row[
        "intent_top3_net"
    ] = int(
        (change > 0).sum()
        -
        (change < 0).sum()
    )

    row[
        "baseline_unique_top3_intent_%"
    ] = (
        group[
            "unique_top3_same_intent_baseline"
        ]
        .mean()
        * 100
    )

    row[
        "reranked_unique_top3_intent_%"
    ] = (
        group[
            "unique_top3_same_intent_reranked"
        ]
        .mean()
        * 100
    )

    row[
        "intent_top3_change_pp"
    ] = (
        row[
            "reranked_unique_top3_intent_%"
        ]
        -
        row[
            "baseline_unique_top3_intent_%"
        ]
    )


    # ----------------------------------------
    # Top-1 Intent
    # ----------------------------------------

    row[
        "baseline_top1_intent_%"
    ] = (
        group[
            "top1_same_intent_baseline"
        ]
        .mean()
        * 100
    )

    row[
        "reranked_top1_intent_%"
    ] = (
        group[
            "top1_same_intent_reranked"
        ]
        .mean()
        * 100
    )

    row[
        "top1_intent_change_pp"
    ] = (
        row[
            "reranked_top1_intent_%"
        ]
        -
        row[
            "baseline_top1_intent_%"
        ]
    )


    type_rows.append(row)


step7c_type_impact = pd.DataFrame(
    type_rows
)

step7c_type_impact = (
    step7c_type_impact
    .sort_values(
        "intent_top3_change_pp",
        ascending=False
    )
)


print(
    "\nQuestion-Type Impact:"
)

print(
    step7c_type_impact.to_string(
        index=False,
        formatters={
            "baseline_unique_top3_intent_%":
                "{:.2f}".format,

            "reranked_unique_top3_intent_%":
                "{:.2f}".format,

            "intent_top3_change_pp":
                "{:+.2f}".format,

            "baseline_top1_intent_%":
                "{:.2f}".format,

            "reranked_top1_intent_%":
                "{:.2f}".format,

            "top1_intent_change_pp":
                "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7c_paired = paired
step7c_query_impact = step7c_query_impact
step7c_type_impact = step7c_type_impact


print("\n" + "=" * 70)
print("STEP 7C COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7c_paired")
print("✓ step7c_query_impact")
print("✓ step7c_type_impact")

print("\nNo reranking was repeated.")
print("No embeddings were recomputed.")
print("No FAISS index was modified.")

======================================================================
STEP 7C — RERANKER IMPACT ANALYSIS
QUERY-LEVEL + QUESTION-TYPE ANALYSIS
======================================================================

[1/4] Input validation
✓ Baseline : 500
✓ Reranked : 500

[2/4] Building paired query comparison...

[3/4] Computing query-level changes...

Overall Query-Level Impact:
             metric  improved  unchanged  worsened  net_change
       Top-1 Intent        47        406        47           0
       Top-3 Intent        56        394        50           6
Unique Top-3 Intent         7        491         2           5
       Top-1 Domain        27        447        26           1
       Top-3 Domain        29        456        15          14
Unique Top-3 Domain         0        500         0           0

[4/4] Analyzing impact by question type...

Question-Type Impact:
                                            test_question_type  queries  intent_top3_improved  intent_top3_unchanged  intent_top3_worsened  intent_top3_net baseline_unique_top3_intent_% reranked_unique_top3_intent_% intent_top3_change_pp baseline_top1_intent_% reranked_top1_intent_% top1_intent_change_pp
                                               pricing or fees       55                     2                     53                     0                2                         43.64                         47.27                 +3.64                  20.00                  23.64                 +3.64
             product or plan details (specs, what is included)       59                     2                     57                     0                2                         40.68                         44.07                 +3.39                  20.34                  15.25                 -5.08
                       availability, coverage or delivery time       60                     2                     58                     0                2                         46.67                         50.00                 +3.33                  18.33                  23.33                 +5.00
account or subscription management (upgrade, renewal, closing)       64                     0                     64                     0                0                         64.06                         64.06                 +0.00                  40.62                  32.81                 -7.81
             policy (refund, cancellation, warranty, exchange)       66                     0                     66                     0                0                         34.85                         34.85                 +0.00                  12.12                  16.67                 +4.55
                    billing dispute or a charge on the account       64                     0                     64                     0                0                         43.75                         43.75                 +0.00                  21.88                  17.19                 -4.69
         troubleshooting a problem with the product or service       66                     1                     64                     1                0                         45.45                         45.45                 +0.00                  19.70                  22.73                 +3.03
                      comparison between two products or plans       66                     0                     65                     1               -1                         53.03                         51.52                 -1.52                  21.21                  22.73                 +1.52

======================================================================
STEP 7C COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7c_paired
✓ step7c_query_impact
✓ step7c_type_impact

No reranking was repeated.
No embeddings were recomputed.
No FAISS index was modified.

In [71]:
# ============================================================
# STEP 7D — INTENT AVAILABILITY IN E5 CANDIDATES
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7D — INTENT AVAILABILITY IN E5 CANDIDATES")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "test_df" in globals()
assert "train_df" in globals()

assert len(step6c_evaluation) == 500

print("\n[1/4] Input validation")
print("✓ E5 retrieval results : 500 queries")
print("✓ Train metadata       :", len(train_df))
print("✓ Test metadata        :", len(test_df))


# ------------------------------------------------------------
# 2. Build metadata lookup
# ------------------------------------------------------------

print("\n[2/4] Building intent lookup...")

test_meta = (
    test_df[
        [
            "id",
            "question_type"
        ]
    ]
    .copy()
)

test_meta["id"] = (
    test_meta["id"].astype(str)
)

test_intent_lookup = (
    test_meta
    .set_index("id")["question_type"]
    .to_dict()
)


train_intent = (
    train_df[
        "question_type"
    ]
    .reset_index(drop=True)
)

print(
    "✓ Test intent lookup:",
    len(test_intent_lookup)
)

print(
    "✓ Train intent lookup:",
    len(train_intent)
)


# ------------------------------------------------------------
# 3. Analyze intent availability
# ------------------------------------------------------------

print("\n[3/4] Analyzing intent availability...")

records = []

for item in step6c_evaluation:

    test_id = str(
        item["test_id"]
    )

    test_intent = (
        test_intent_lookup[test_id]
    )

    candidates = item[
        "retrieved"
    ]

    candidate_intents = []

    for candidate in candidates:

        row_idx = int(
            candidate["row_idx"]
        )

        assert (
            0 <= row_idx < len(train_intent)
        )

        candidate_intent = (
            train_intent.iloc[row_idx]
        )

        candidate_intents.append(
            candidate_intent
        )


    # --------------------------------------------------------
    # Intent presence by K
    # --------------------------------------------------------

    same_intent_positions = [
        idx + 1
        for idx, intent
        in enumerate(candidate_intents)
        if intent == test_intent
    ]


    has_top1 = (
        1 in same_intent_positions
    )

    has_top3 = any(
        position <= 3
        for position
        in same_intent_positions
    )

    has_top5 = any(
        position <= 5
        for position
        in same_intent_positions
    )

    has_top10 = (
        len(same_intent_positions) > 0
    )


    # --------------------------------------------------------
    # Unique-content Top-3
    # --------------------------------------------------------

    unique_contents = []

    seen_texts = set()

    for candidate, intent in zip(
        candidates,
        candidate_intents
    ):

        text = candidate[
            "chunk_text"
        ]

        if text not in seen_texts:

            seen_texts.add(text)

            unique_contents.append(
                (
                    candidate,
                    intent
                )
            )

        if len(unique_contents) == 3:
            break


    unique_top3_same_intent = any(
        intent == test_intent
        for _, intent
        in unique_contents
    )


    # --------------------------------------------------------
    # Best same-intent rank
    # --------------------------------------------------------

    best_same_intent_rank = (
        min(same_intent_positions)
        if same_intent_positions
        else np.nan
    )


    records.append(
        {
            "test_id":
                test_id,

            "test_intent":
                test_intent,

            "has_top1_intent":
                has_top1,

            "has_top3_intent":
                has_top3,

            "has_top5_intent":
                has_top5,

            "has_top10_intent":
                has_top10,

            "unique_top3_intent":
                unique_top3_same_intent,

            "same_intent_count_top10":
                len(same_intent_positions),

            "best_same_intent_rank":
                best_same_intent_rank
        }
    )


step7d_intent_availability = (
    pd.DataFrame(records)
)

assert len(
    step7d_intent_availability
) == 500


# ------------------------------------------------------------
# 4. Summary
# ------------------------------------------------------------

print("\n[4/4] Computing summary...")

summary = pd.DataFrame(
    {
        "metric": [
            "Same intent at Top-1",
            "Same intent available in Top-3",
            "Same intent available in Top-5",
            "Same intent available in Top-10",
            "Same intent in Unique Top-3"
        ],

        "count": [
            int(
                step7d_intent_availability[
                    "has_top1_intent"
                ].sum()
            ),

            int(
                step7d_intent_availability[
                    "has_top3_intent"
                ].sum()
            ),

            int(
                step7d_intent_availability[
                    "has_top5_intent"
                ].sum()
            ),

            int(
                step7d_intent_availability[
                    "has_top10_intent"
                ].sum()
            ),

            int(
                step7d_intent_availability[
                    "unique_top3_intent"
                ].sum()
            )
        ]
    }
)

summary["percentage"] = (
    summary["count"]
    / 500
    * 100
)


print(
    "\nIntent Availability:"
)

print(
    summary.to_string(
        index=False,
        formatters={
            "percentage":
                "{:.2f}%".format
        }
    )
)


print(
    "\nBest same-intent rank distribution:"
)

rank_distribution = (
    step7d_intent_availability[
        "best_same_intent_rank"
    ]
    .value_counts()
    .sort_index()
)

print(
    rank_distribution.to_string()
)


print(
    "\nQueries with NO same-intent candidate "
    "in Top-10:"
)

no_intent = (
    ~step7d_intent_availability[
        "has_top10_intent"
    ]
)

print(
    f"{no_intent.sum():,} / 500 "
    f"({no_intent.mean() * 100:.2f}%)"
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7d_summary = summary
step7d_rank_distribution = rank_distribution

print("\n" + "=" * 70)
print("STEP 7D COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7d_intent_availability")
print("✓ step7d_summary")
print("✓ step7d_rank_distribution")

print("\nNo model inference was performed.")
print("No embeddings were recomputed.")
print("No FAISS index was modified.")

======================================================================
STEP 7D — INTENT AVAILABILITY IN E5 CANDIDATES
======================================================================

[1/4] Input validation
✓ E5 retrieval results : 500 queries
✓ Train metadata       : 27427
✓ Test metadata        : 500

[2/4] Building intent lookup...
✓ Test intent lookup: 500
✓ Train intent lookup: 27427

[3/4] Analyzing intent availability...

[4/4] Computing summary...

Intent Availability:
                         metric  count percentage
           Same intent at Top-1    109     21.80%
 Same intent available in Top-3    275     55.00%
 Same intent available in Top-5    348     69.60%
Same intent available in Top-10    426     85.20%
    Same intent in Unique Top-3    233     46.60%

Best same-intent rank distribution:
best_same_intent_rank
1.0     109
2.0      93
3.0      73
4.0      55
5.0      18
6.0      22
7.0      15
8.0      19
9.0      11
10.0     11

Queries with NO same-intent candidate in Top-10:
74 / 500 (14.80%)

======================================================================
STEP 7D COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7d_intent_availability
✓ step7d_summary
✓ step7d_rank_distribution

No model inference was performed.
No embeddings were recomputed.
No FAISS index was modified.

In [73]:
# ============================================================
# STEP 7E — INTENT-AWARE RERANKING EXPERIMENT
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7E — INTENT-AWARE RERANKING EXPERIMENT")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "test_df" in globals()
assert "train_df" in globals()

assert len(step6c_evaluation) == 500

print("\n[1/5] Input validation")
print("✓ Queries          : 500")
print("✓ E5 candidates    : Top-10")
print("✓ Train metadata   :", len(train_df))
print("✓ Test metadata    :", len(test_df))


# ------------------------------------------------------------
# 2. Build metadata lookups
# ------------------------------------------------------------

print("\n[2/5] Building metadata lookups...")

test_meta = test_df[
    ["id", "question_type"]
].copy()

test_meta["id"] = test_meta["id"].astype(str)

test_intent_lookup = (
    test_meta
    .set_index("id")["question_type"]
    .to_dict()
)

train_intent_lookup = (
    train_df["question_type"]
    .reset_index(drop=True)
)

print("✓ Test intents :", len(test_intent_lookup))
print("✓ Train intents:", len(train_intent_lookup))


# ------------------------------------------------------------
# 3. Prepare candidate records
# ------------------------------------------------------------

print("\n[3/5] Preparing candidate records...")

records = []

for item in step6c_evaluation:

    test_id = str(item["test_id"])

    test_intent = test_intent_lookup[test_id]

    for candidate in item["retrieved"]:

        row_idx = int(candidate["row_idx"])

        assert 0 <= row_idx < len(train_intent_lookup)

        candidate_intent = (
            train_intent_lookup.iloc[row_idx]
        )

        records.append({
            "test_id": test_id,
            "test_intent": test_intent,
            "corpus_idx": candidate["corpus_idx"],
            "original_rank": candidate["rank"],
            "e5_score": float(candidate["score"]),
            "candidate_intent": candidate_intent,
            "intent_match": int(
                candidate_intent == test_intent
            ),
            "chunk_text": candidate["chunk_text"]
        })


candidate_df_7e = pd.DataFrame(records)

assert len(candidate_df_7e) == 5000

print(
    f"✓ Candidate records: {len(candidate_df_7e):,}"
)


# ------------------------------------------------------------
# 4. Evaluate intent bonus weights
# ------------------------------------------------------------

print("\n[4/5] Testing intent bonus weights...")

ALPHAS = [
    0.00,
    0.01,
    0.02,
    0.03,
    0.05,
    0.10
]

alpha_results = []

for alpha in ALPHAS:

    query_results = []

    for test_id, group in candidate_df_7e.groupby(
        "test_id",
        sort=False
    ):

        group = group.copy()

        # ----------------------------------------------------
        # Intent-aware score
        # ----------------------------------------------------

        group["final_score"] = (
            group["e5_score"]
            +
            alpha * group["intent_match"]
        )

        ranked = (
            group
            .sort_values(
                ["final_score", "e5_score"],
                ascending=False
            )
        )

        # ----------------------------------------------------
        # Raw Top-1 / Top-3
        # ----------------------------------------------------

        top3 = ranked.head(3)

        raw_top1_intent = int(
            top3.iloc[0]["intent_match"]
        )

        raw_top3_intent = int(
            top3["intent_match"].any()
        )

        # ----------------------------------------------------
        # Unique-content Top-3
        # ----------------------------------------------------

        unique_rows = []
        seen_texts = set()

        for _, row in ranked.iterrows():

            text = row["chunk_text"]

            if text not in seen_texts:

                seen_texts.add(text)
                unique_rows.append(row)

            if len(unique_rows) == 3:
                break

        unique_df = pd.DataFrame(unique_rows)

        assert len(unique_df) == 3

        unique_top1_intent = int(
            unique_df.iloc[0]["intent_match"]
        )

        unique_top3_intent = int(
            unique_df["intent_match"].any()
        )

        query_results.append({
            "test_id": test_id,
            "top1_intent": raw_top1_intent,
            "top3_intent": raw_top3_intent,
            "unique_top1_intent": unique_top1_intent,
            "unique_top3_intent": unique_top3_intent
        })

    query_results_df = pd.DataFrame(query_results)

    alpha_results.append({
        "alpha": alpha,

        "top1_intent_%": (
            query_results_df["top1_intent"].mean() * 100
        ),

        "top3_intent_%": (
            query_results_df["top3_intent"].mean() * 100
        ),

        "unique_top1_intent_%": (
            query_results_df["unique_top1_intent"].mean() * 100
        ),

        "unique_top3_intent_%": (
            query_results_df["unique_top3_intent"].mean() * 100
        )
    })


step7e_alpha_results = pd.DataFrame(alpha_results)


# ------------------------------------------------------------
# 5. Calculate changes relative to baseline
# ------------------------------------------------------------

print("\n[5/5] Final results...")

baseline_unique_top1 = (
    step7e_alpha_results.iloc[0]["unique_top1_intent_%"]
)

baseline_unique_top3 = (
    step7e_alpha_results.iloc[0]["unique_top3_intent_%"]
)

step7e_alpha_results["unique_top1_change_pp"] = (
    step7e_alpha_results["unique_top1_intent_%"]
    - baseline_unique_top1
)

step7e_alpha_results["unique_top3_change_pp"] = (
    step7e_alpha_results["unique_top3_intent_%"]
    - baseline_unique_top3
)


print("\nIntent Bonus Experiment:")

print(
    step7e_alpha_results.to_string(
        index=False,
        formatters={
            "top1_intent_%": "{:.2f}".format,
            "top3_intent_%": "{:.2f}".format,
            "unique_top1_intent_%": "{:.2f}".format,
            "unique_top3_intent_%": "{:.2f}".format,
            "unique_top1_change_pp": "{:+.2f}".format,
            "unique_top3_change_pp": "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7e_candidate_df = candidate_df_7e

print("\n" + "=" * 70)
print("STEP 7E COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7e_candidate_df")
print("✓ step7e_alpha_results")

print("\nNo model inference was performed.")
print("No embeddings were recomputed.")
print("No FAISS index was modified.")

======================================================================
STEP 7E — INTENT-AWARE RERANKING EXPERIMENT
======================================================================

[1/5] Input validation
✓ Queries          : 500
✓ E5 candidates    : Top-10
✓ Train metadata   : 27427
✓ Test metadata    : 500

[2/5] Building metadata lookups...
✓ Test intents : 500
✓ Train intents: 27427

[3/5] Preparing candidate records...
✓ Candidate records: 5,000

[4/5] Testing intent bonus weights...

[5/5] Final results...

Intent Bonus Experiment:
 alpha top1_intent_% top3_intent_% unique_top1_intent_% unique_top3_intent_% unique_top1_change_pp unique_top3_change_pp
  0.00         21.80         55.00                21.80                46.60                 +0.00                 +0.00
  0.01         83.00         83.00                83.00                85.20                +61.20                +38.60
  0.02         85.00         85.00                85.00                85.20                +63.20                +38.60
  0.03         85.20         85.20                85.20                85.20                +63.40                +38.60
  0.05         85.20         85.20                85.20                85.20                +63.40                +38.60
  0.10         85.20         85.20                85.20                85.20                +63.40                +38.60

======================================================================
STEP 7E COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7e_candidate_df
✓ step7e_alpha_results

No model inference was performed.
No embeddings were recomputed.
No FAISS index was modified.

In [74]:
# ============================================================
# STEP 7F — QUESTION-TYPE CLASSIFIER
# TRAIN-ONLY SUPERVISED INTENT PREDICTION
# ============================================================

import pandas as pd
import numpy as np

from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

print("=" * 70)
print("STEP 7F — QUESTION-TYPE CLASSIFIER")
print("TRAIN-ONLY SUPERVISED INTENT PREDICTION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate data
# ------------------------------------------------------------

assert "train_df" in globals()
assert "test_df" in globals()

assert "question" in train_df.columns
assert "question_type" in train_df.columns

assert "question" in test_df.columns
assert "question_type" in test_df.columns

print("\n[1/5] Dataset validation")

print("✓ Train rows:", len(train_df))
print("✓ Test rows :", len(test_df))

print(
    "✓ Intent classes:",
    train_df["question_type"].nunique()
)


# ------------------------------------------------------------
# 2. Prepare train/test data
# ------------------------------------------------------------

print("\n[2/5] Preparing text and labels...")

X_train = (
    train_df["question"]
    .fillna("")
    .astype(str)
)

y_train = (
    train_df["question_type"]
    .astype(str)
)

X_test = (
    test_df["question"]
    .fillna("")
    .astype(str)
)

y_test = (
    test_df["question_type"]
    .astype(str)
)


print("\nTrain class distribution:")

print(
    y_train.value_counts()
    .sort_index()
    .to_string()
)


# ------------------------------------------------------------
# 3. Build classifier
# ------------------------------------------------------------

print("\n[3/5] Building TF-IDF + LinearSVC classifier...")

intent_classifier = Pipeline(
    [
        (
            "tfidf",
            TfidfVectorizer(
                analyzer="char",
                ngram_range=(3, 5),
                min_df=2,
                max_features=300000,
                sublinear_tf=True
            )
        ),

        (
            "classifier",
            LinearSVC(
                C=1.0
            )
        )
    ]
)


# ------------------------------------------------------------
# 4. Train
# ------------------------------------------------------------

print("\n[4/5] Training...")

intent_classifier.fit(
    X_train,
    y_train
)

print("✓ Training completed")


# ------------------------------------------------------------
# 5. Test evaluation
# ------------------------------------------------------------

print("\n[5/5] Evaluating on held-out Test...")

y_pred = intent_classifier.predict(
    X_test
)

accuracy = accuracy_score(
    y_test,
    y_pred
)

macro_f1 = f1_score(
    y_test,
    y_pred,
    average="macro"
)

weighted_f1 = f1_score(
    y_test,
    y_pred,
    average="weighted"
)


print("\n" + "-" * 70)
print("INTENT CLASSIFIER RESULTS")
print("-" * 70)

print(
    f"Accuracy    : {accuracy:.4f} "
    f"({accuracy * 100:.2f}%)"
)

print(
    f"Macro F1    : {macro_f1:.4f} "
    f"({macro_f1 * 100:.2f}%)"
)

print(
    f"Weighted F1 : {weighted_f1:.4f} "
    f"({weighted_f1 * 100:.2f}%)"
)


# ------------------------------------------------------------
# Classification report
# ------------------------------------------------------------

print("\nClassification Report:")

print(
    classification_report(
        y_test,
        y_pred,
        digits=4
    )
)


# ------------------------------------------------------------
# Confusion Matrix
# ------------------------------------------------------------

labels = sorted(
    y_test.unique()
)

cm = confusion_matrix(
    y_test,
    y_pred,
    labels=labels
)

step7f_confusion_matrix = pd.DataFrame(
    cm,
    index=[
        f"true: {label}"
        for label in labels
    ],
    columns=[
        f"pred: {label}"
        for label in labels
    ]
)

print("\nConfusion Matrix:")

print(
    step7f_confusion_matrix.to_string()
)


# ------------------------------------------------------------
# Save predictions
# ------------------------------------------------------------

step7f_predictions = pd.DataFrame(
    {
        "test_id":
            test_df["id"].astype(str),

        "question":
            X_test,

        "true_question_type":
            y_test,

        "predicted_question_type":
            y_pred,

        "correct":
            y_test.values == y_pred
    }
)


step7f_metrics = {
    "accuracy": accuracy,
    "macro_f1": macro_f1,
    "weighted_f1": weighted_f1
}

step7f_classifier = intent_classifier


print("\n" + "=" * 70)
print("STEP 7F COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7f_classifier")
print("✓ step7f_predictions")
print("✓ step7f_metrics")
print("✓ step7f_confusion_matrix")

print("\nImportant:")
print("✓ Test labels were NOT used for prediction.")
print("✓ No E5 embeddings were recomputed.")
print("✓ No FAISS index was modified.")
print("✓ This classifier uses question text only.")

======================================================================
STEP 7F — QUESTION-TYPE CLASSIFIER
TRAIN-ONLY SUPERVISED INTENT PREDICTION
======================================================================

[1/5] Dataset validation
✓ Train rows: 27427
✓ Test rows : 500
✓ Intent classes: 8

[2/5] Preparing text and labels...

Train class distribution:
question_type
account or subscription management (upgrade, renewal, closing)    3429
availability, coverage or delivery time                           3408
billing dispute or a charge on the account                        3446
comparison between two products or plans                          3387
policy (refund, cancellation, warranty, exchange)                 3425
pricing or fees                                                   3414
product or plan details (specs, what is included)                 3474
troubleshooting a problem with the product or service             3444

[3/5] Building TF-IDF + LinearSVC classifier...

[4/5] Training...
✓ Training completed

[5/5] Evaluating on held-out Test...

----------------------------------------------------------------------
INTENT CLASSIFIER RESULTS
----------------------------------------------------------------------
Accuracy    : 0.8960 (89.60%)
Macro F1    : 0.8946 (89.46%)
Weighted F1 : 0.8965 (89.65%)

Classification Report:
                                                                precision    recall  f1-score   support

account or subscription management (upgrade, renewal, closing)     0.9365    0.9219    0.9291        64
                       availability, coverage or delivery time     0.8730    0.9167    0.8943        60
                    billing dispute or a charge on the account     0.9677    0.9375    0.9524        64
                      comparison between two products or plans     0.9846    0.9697    0.9771        66
             policy (refund, cancellation, warranty, exchange)     0.8310    0.8939    0.8613        66
                                               pricing or fees     0.7778    0.8909    0.8305        55
             product or plan details (specs, what is included)     0.8868    0.7966    0.8393        59
         troubleshooting a problem with the product or service     0.9167    0.8333    0.8730        66

                                                      accuracy                         0.8960       500
                                                     macro avg     0.8968    0.8951    0.8946       500
                                                  weighted avg     0.8994    0.8960    0.8965       500


Confusion Matrix:
                                                                      pred: account or subscription management (upgrade, renewal, closing)  pred: availability, coverage or delivery time  pred: billing dispute or a charge on the account  pred: comparison between two products or plans  pred: policy (refund, cancellation, warranty, exchange)  pred: pricing or fees  pred: product or plan details (specs, what is included)  pred: troubleshooting a problem with the product or service
true: account or subscription management (upgrade, renewal, closing)                                                                    59                                              0                                                 0                                               0                                                        3                      0                                                        2                                                            0
true: availability, coverage or delivery time                                                                                            0                                             55                                                 0                                               0                                                        0                      3                                                        1                                                            1
true: billing dispute or a charge on the account                                                                                         0                                              0                                                60                                               0                                                        1                      2                                                        0                                                            1
true: comparison between two products or plans                                                                                           1                                              0                                                 0                                              64                                                        0                      1                                                        0                                                            0
true: policy (refund, cancellation, warranty, exchange)                                                                                  1                                              1                                                 1                                               0                                                       59                      1                                                        1                                                            2
true: pricing or fees                                                                                                                    1                                              1                                                 1                                               0                                                        2                     49                                                        1                                                            0
true: product or plan details (specs, what is included)                                                                                  1                                              2                                                 0                                               1                                                        3                      4                                                       47                                                            1
true: troubleshooting a problem with the product or service                                                                              0                                              4                                                 0                                               0                                                        3                      3                                                        1                                                           55

======================================================================
STEP 7F COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7f_classifier
✓ step7f_predictions
✓ step7f_metrics
✓ step7f_confusion_matrix

Important:
✓ Test labels were NOT used for prediction.
✓ No E5 embeddings were recomputed.
✓ No FAISS index was modified.
✓ This classifier uses question text only.

In [75]:
# ============================================================
# STEP 7G — PREDICTED-INTENT RERANKING
# NO TEST-LABEL LEAKAGE
# ============================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 7G — PREDICTED-INTENT RERANKING")
print("NO TEST-LABEL LEAKAGE")
print("=" * 70)


# ------------------------------------------------------------
# 1. Validate inputs
# ------------------------------------------------------------

assert "step6c_evaluation" in globals()
assert "step7f_classifier" in globals()
assert "step7f_predictions" in globals()
assert "test_df" in globals()
assert "train_df" in globals()

assert len(step6c_evaluation) == 500
assert len(step7f_predictions) == 500

print("\n[1/6] Input validation")
print("✓ E5 queries       : 500")
print("✓ Intent model     : trained on Train only")
print("✓ Intent predictions:", len(step7f_predictions))


# ------------------------------------------------------------
# 2. Build predicted-intent lookup
# ------------------------------------------------------------

print("\n[2/6] Building predicted-intent lookup...")

predicted_intent_lookup = (
    step7f_predictions[
        [
            "test_id",
            "predicted_question_type"
        ]
    ]
    .copy()
)

predicted_intent_lookup["test_id"] = (
    predicted_intent_lookup["test_id"]
    .astype(str)
)

predicted_intent_lookup = (
    predicted_intent_lookup
    .set_index("test_id")[
        "predicted_question_type"
    ]
    .to_dict()
)

assert len(predicted_intent_lookup) == 500

print(
    "✓ Predicted intents:",
    len(predicted_intent_lookup)
)


# ------------------------------------------------------------
# 3. Prepare E5 Top-10 candidates
# ------------------------------------------------------------

print("\n[3/6] Preparing E5 candidates...")

train_intent_lookup = (
    train_df["question_type"]
    .reset_index(drop=True)
)

records = []

for item in step6c_evaluation:

    test_id = str(
        item["test_id"]
    )

    predicted_intent = (
        predicted_intent_lookup[test_id]
    )

    for candidate in item["retrieved"]:

        row_idx = int(
            candidate["row_idx"]
        )

        candidate_intent = (
            train_intent_lookup.iloc[row_idx]
        )

        records.append(
            {
                "test_id":
                    test_id,

                "predicted_intent":
                    predicted_intent,

                "candidate_intent":
                    candidate_intent,

                "intent_match":
                    int(
                        candidate_intent
                        == predicted_intent
                    ),

                "e5_score":
                    float(candidate["score"]),

                "corpus_idx":
                    candidate["corpus_idx"],

                "original_rank":
                    candidate["rank"],

                "chunk_text":
                    candidate["chunk_text"]
            }
        )


candidate_df_7g = pd.DataFrame(
    records
)

assert len(candidate_df_7g) == 5000

print(
    f"✓ Candidate records: {len(candidate_df_7g):,}"
)


# ------------------------------------------------------------
# 4. Test intent bonus weights
# ------------------------------------------------------------

print("\n[4/6] Testing predicted-intent bonus weights...")

ALPHAS = [
    0.00,
    0.01,
    0.02,
    0.03,
    0.05,
    0.10
]

alpha_results = []

for alpha in ALPHAS:

    query_results = []

    for test_id, group in candidate_df_7g.groupby(
        "test_id",
        sort=False
    ):

        group = group.copy()

        # ----------------------------------------------------
        # Reranking score
        # ----------------------------------------------------

        group["final_score"] = (
            group["e5_score"]
            +
            alpha * group["intent_match"]
        )

        ranked = (
            group
            .sort_values(
                [
                    "final_score",
                    "e5_score"
                ],
                ascending=False
            )
        )

        # ----------------------------------------------------
        # Raw Top-1 / Top-3
        # ----------------------------------------------------

        top3 = ranked.head(3)

        # IMPORTANT:
        # Evaluation uses TRUE test intent here ONLY
        # after ranking, not for producing the ranking.
        test_record = (
            test_df[
                test_df["id"].astype(str) == test_id
            ]
        )

        true_intent = (
            test_record.iloc[0]["question_type"]
        )

        raw_top1_intent = int(
            top3.iloc[0]["candidate_intent"]
            == true_intent
        )

        raw_top3_intent = int(
            (
                top3["candidate_intent"]
                == true_intent
            ).any()
        )

        # ----------------------------------------------------
        # Unique-content Top-3
        # ----------------------------------------------------

        unique_rows = []
        seen_texts = set()

        for _, row in ranked.iterrows():

            text = row["chunk_text"]

            if text not in seen_texts:

                seen_texts.add(text)
                unique_rows.append(row)

            if len(unique_rows) == 3:
                break

        unique_df = pd.DataFrame(
            unique_rows
        )

        assert len(unique_df) == 3

        unique_top1_intent = int(
            unique_df.iloc[0]["candidate_intent"]
            == true_intent
        )

        unique_top3_intent = int(
            (
                unique_df["candidate_intent"]
                == true_intent
            ).any()
        )

        query_results.append(
            {
                "test_id":
                    test_id,

                "true_intent":
                    true_intent,

                "predicted_intent":
                    predicted_intent_lookup[
                        test_id
                    ],

                "top1_intent":
                    raw_top1_intent,

                "top3_intent":
                    raw_top3_intent,

                "unique_top1_intent":
                    unique_top1_intent,

                "unique_top3_intent":
                    unique_top3_intent
            }
        )


    query_results_df = pd.DataFrame(
        query_results
    )

    alpha_results.append(
        {
            "alpha":
                alpha,

            "top1_intent_%":
                query_results_df[
                    "top1_intent"
                ].mean() * 100,

            "top3_intent_%":
                query_results_df[
                    "top3_intent"
                ].mean() * 100,

            "unique_top1_intent_%":
                query_results_df[
                    "unique_top1_intent"
                ].mean() * 100,

            "unique_top3_intent_%":
                query_results_df[
                    "unique_top3_intent"
                ].mean() * 100
        }
    )


step7g_alpha_results = pd.DataFrame(
    alpha_results
)


# ------------------------------------------------------------
# 5. Calculate baseline changes
# ------------------------------------------------------------

print("\n[5/6] Calculating changes...")

baseline_unique_top1 = (
    step7g_alpha_results.iloc[0][
        "unique_top1_intent_%"
    ]
)

baseline_unique_top3 = (
    step7g_alpha_results.iloc[0][
        "unique_top3_intent_%"
    ]
)

step7g_alpha_results[
    "unique_top1_change_pp"
] = (
    step7g_alpha_results[
        "unique_top1_intent_%"
    ]
    - baseline_unique_top1
)

step7g_alpha_results[
    "unique_top3_change_pp"
] = (
    step7g_alpha_results[
        "unique_top3_intent_%"
    ]
    - baseline_unique_top3
)


# ------------------------------------------------------------
# 6. Print results
# ------------------------------------------------------------

print("\n[6/6] Final results")

print(
    "\nPredicted-Intent Reranking:"
)

print(
    step7g_alpha_results.to_string(
        index=False,
        formatters={
            "top1_intent_%":
                "{:.2f}".format,

            "top3_intent_%":
                "{:.2f}".format,

            "unique_top1_intent_%":
                "{:.2f}".format,

            "unique_top3_intent_%":
                "{:.2f}".format,

            "unique_top1_change_pp":
                "{:+.2f}".format,

            "unique_top3_change_pp":
                "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save
# ------------------------------------------------------------

step7g_candidate_df = candidate_df_7g

print("\n" + "=" * 70)
print("STEP 7G COMPLETED SUCCESSFULLY")
print("=" * 70)

print("\nSaved objects:")
print("✓ step7g_candidate_df")
print("✓ step7g_alpha_results")

print("\nRanking used predicted intent only.")
print("True Test intent was used for evaluation only.")
print("No label leakage into ranking.")
print("No embeddings were recomputed.")
print("No FAISS index was modified.")

======================================================================
STEP 7G — PREDICTED-INTENT RERANKING
NO TEST-LABEL LEAKAGE
======================================================================

[1/6] Input validation
✓ E5 queries       : 500
✓ Intent model     : trained on Train only
✓ Intent predictions: 500

[2/6] Building predicted-intent lookup...
✓ Predicted intents: 500

[3/6] Preparing E5 candidates...
✓ Candidate records: 5,000

[4/6] Testing predicted-intent bonus weights...

[5/6] Calculating changes...

[6/6] Final results

Predicted-Intent Reranking:
 alpha top1_intent_% top3_intent_% unique_top1_intent_% unique_top3_intent_% unique_top1_change_pp unique_top3_change_pp
  0.00         21.80         55.00                21.80                46.60                 +0.00                 +0.00
  0.01         76.00         78.20                76.00                79.80                +54.20                +33.20
  0.02         77.80         79.60                77.80                79.80                +56.00                +33.20
  0.03         78.00         79.80                78.00                79.80                +56.20                +33.20
  0.05         78.00         79.80                78.00                79.80                +56.20                +33.20
  0.10         78.00         79.80                78.00                79.80                +56.20                +33.20

======================================================================
STEP 7G COMPLETED SUCCESSFULLY
======================================================================

Saved objects:
✓ step7g_candidate_df
✓ step7g_alpha_results

Ranking used predicted intent only.
True Test intent was used for evaluation only.
No label leakage into ranking.
No embeddings were recomputed.
No FAISS index was modified.

In [77]:
print("step7g_candidate_df columns:")
print(step7g_candidate_df.columns.tolist())

print("\nShape:")
print(step7g_candidate_df.shape)

print("\nFirst row:")
print(step7g_candidate_df.iloc[0].to_dict())

step7g_candidate_df columns:
['test_id', 'predicted_intent', 'candidate_intent', 'intent_match', 'e5_score', 'corpus_idx', 'original_rank', 'chunk_text']

Shape:
(5000, 8)

First row:
{'test_id': '6875-0', 'predicted_intent': 'account or subscription management (upgrade, renewal, closing)', 'candidate_intent': 'product or plan details (specs, what is included)', 'intent_match': 0, 'e5_score': 0.8562403917312622, 'corpus_idx': 33508, 'original_rank': 1, 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}

In [79]:
print("train_corpus columns:")
print(train_corpus.columns.tolist())

print("\nrow_idx exists:", "row_idx" in train_corpus.columns)

print("\nFirst corpus row:")
print(train_corpus.iloc[0].to_dict())

train_corpus columns:
['row_idx', 'id', 'company_id', 'company', 'domain', 'country', 'chunk_idx', 'chunk_text', 'question', 'answer', 'answerable']

row_idx exists: True

First corpus row:
{'row_idx': 0, 'id': '0-0', 'company_id': 0, 'company': 'شركة نماء للمياه المتكاملة', 'domain': 'water utility', 'country': 'Oman', 'chunk_idx': 0, 'chunk_text': "تعتمد باقة 'المنزل الأساسية' على استهلاك شهري يصل إلى 20 متكعباً من المياه بسعر 12 ريالاً عمانياً، بينما توفر باقة 'المنزل المطور' استهلاكاً يصل إلى 50 متكعباً بسعر 25 ريالاً عمانياً، وتتضمن الأخيرة خدمة صيانة دورية مجانية كل 6 أشهر.", 'question': 'ألاحظ وجود مبلغ إضافي في فاتورتي لهذا الشهر، أرجو توضيح سبب هذه الرسوم.', 'answer': "تفرض الشركة رسوماً إضافية في حال تجاوز الحد المسموح به في الباقة، حيث يتم احتساب كل متر مكعب إضافي بسعر 0.700 ريال عماني وتظهر تحت بند 'تجاوز الاستهلاك'.", 'answerable': True}

In [81]:
# ============================================================
# STEP 7H — FIX MERGE ONLY
# ============================================================

print("=" * 70)
print("STEP 7H — FIXING CANDIDATE METADATA MERGE")
print("=" * 70)

# Rebuild candidate metadata with a different column name
# to avoid collision with the existing candidate_intent column.

row_to_intent = (
    train_df["question_type"]
    .reset_index(drop=True)
    .to_dict()
)

candidate_meta = train_corpus[
    [
        "row_idx",
        "domain",
        "country"
    ]
].copy()

candidate_meta["mapped_intent"] = (
    candidate_meta["row_idx"].map(row_to_intent)
)

assert candidate_meta["mapped_intent"].notna().all()

candidate_meta = candidate_meta.reset_index()

candidate_meta = candidate_meta.rename(
    columns={"index": "corpus_idx"}
)


# Merge only domain/country + mapped intent
candidates = step7g_candidate_df.merge(
    candidate_meta[
        [
            "corpus_idx",
            "domain",
            "country",
            "mapped_intent"
        ]
    ],
    on="corpus_idx",
    how="left",
    validate="many_to_one"
)

assert len(candidates) == 5000
assert candidates["domain"].notna().all()
assert candidates["mapped_intent"].notna().all()


# The existing candidate_intent from Step 7G
# should be identical to mapped_intent.
intent_consistency = (
    candidates["candidate_intent"]
    ==
    candidates["mapped_intent"]
).mean()

print("\n✓ Candidates:", len(candidates))
print("✓ Domain coverage: 100%")
print("✓ Intent coverage: 100%")
print(
    f"✓ Existing vs mapped candidate intent agreement: "
    f"{intent_consistency * 100:.2f}%"
)

print("\nCandidate columns:")
print(candidates.columns.tolist())

print("\nFirst candidate:")
print(candidates.iloc[0].to_dict())

======================================================================
STEP 7H — FIXING CANDIDATE METADATA MERGE
======================================================================

✓ Candidates: 5000
✓ Domain coverage: 100%
✓ Intent coverage: 100%
✓ Existing vs mapped candidate intent agreement: 100.00%

Candidate columns:
['test_id', 'predicted_intent', 'candidate_intent', 'intent_match', 'e5_score', 'corpus_idx', 'original_rank', 'chunk_text', 'domain', 'country', 'mapped_intent']

First candidate:
{'test_id': '6875-0', 'predicted_intent': 'account or subscription management (upgrade, renewal, closing)', 'candidate_intent': 'product or plan details (specs, what is included)', 'intent_match': 0, 'e5_score': 0.8562403917312622, 'corpus_idx': 33508, 'original_rank': 1, 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.', 'domain': 'streaming service', 'country': 'Morocco', 'mapped_intent': 'product or plan details (specs, what is included)'}

In [82]:
# ============================================================
# STEP 7H — PER-INTENT IMPACT ANALYSIS
# FINAL EXECUTION
# ============================================================

print("=" * 70)
print("STEP 7H — PER-INTENT IMPACT ANALYSIS")
print("BASELINE vs PREDICTED-INTENT RERANKING")
print("=" * 70)

ALPHA = 0.03


# ------------------------------------------------------------
# 1. Prepare Test metadata
# ------------------------------------------------------------

print("\n[1/4] Preparing Test metadata...")

test_meta = (
    test_df[
        [
            "id",
            "question_type",
            "domain",
            "answerable"
        ]
    ]
    .copy()
)

test_meta["id"] = test_meta["id"].astype(str)

test_lookup = (
    test_meta
    .set_index("id")
    .to_dict("index")
)

assert len(test_lookup) == 500

print("✓ Test metadata ready")


# ------------------------------------------------------------
# 2. Evaluate baseline vs reranked
# ------------------------------------------------------------

print("\n[2/4] Evaluating baseline vs reranked...")

results = []


for test_id, group in candidates.groupby(
    "test_id",
    sort=False
):

    test_id = str(test_id)

    meta = test_lookup[test_id]

    true_intent = meta["question_type"]
    true_domain = meta["domain"]


    # ========================================================
    # BASELINE
    # ========================================================

    baseline = (
        group
        .sort_values(
            "original_rank",
            ascending=True
        )
        .reset_index(drop=True)
    )


    # ========================================================
    # PREDICTED-INTENT RERANKING
    # ========================================================

    reranked = group.copy()

    reranked["final_score"] = (
        reranked["e5_score"]
        +
        ALPHA * reranked["intent_match"]
    )

    reranked = (
        reranked
        .sort_values(
            [
                "final_score",
                "e5_score",
                "original_rank"
            ],
            ascending=False
        )
        .reset_index(drop=True)
    )


    # ========================================================
    # Evaluation function
    # ========================================================

    def evaluate(df):

        # -------------------------
        # Raw Top-1
        # -------------------------

        top1 = df.iloc[0]

        top1_intent = int(
            top1["candidate_intent"]
            == true_intent
        )

        top1_domain = int(
            top1["domain"]
            == true_domain
        )


        # -------------------------
        # Raw Top-3
        # -------------------------

        top3 = df.head(3)

        top3_intent = int(
            (
                top3["candidate_intent"]
                == true_intent
            ).any()
        )

        top3_domain = int(
            (
                top3["domain"]
                == true_domain
            ).any()
        )


        # -------------------------
        # Unique-content Top-3
        # -------------------------

        unique_rows = []
        seen_texts = set()

        for _, row in df.iterrows():

            text = row["chunk_text"]

            if text not in seen_texts:

                seen_texts.add(text)
                unique_rows.append(row)

            if len(unique_rows) == 3:
                break


        unique_df = pd.DataFrame(
            unique_rows
        )

        assert len(unique_df) == 3


        unique_top1_intent = int(
            unique_df.iloc[0]["candidate_intent"]
            == true_intent
        )

        unique_top3_intent = int(
            (
                unique_df["candidate_intent"]
                == true_intent
            ).any()
        )

        unique_top3_domain = int(
            (
                unique_df["domain"]
                == true_domain
            ).any()
        )


        return {
            "top1_intent":
                top1_intent,

            "top3_intent":
                top3_intent,

            "unique_top1_intent":
                unique_top1_intent,

            "unique_top3_intent":
                unique_top3_intent,

            "top1_domain":
                top1_domain,

            "top3_domain":
                top3_domain,

            "unique_top3_domain":
                unique_top3_domain
        }


    b = evaluate(baseline)
    r = evaluate(reranked)


    results.append(
        {
            "test_id":
                test_id,

            "true_intent":
                true_intent,

            "predicted_intent":
                group[
                    "predicted_intent"
                ].iloc[0],

            "classifier_correct":
                int(
                    true_intent
                    ==
                    group[
                        "predicted_intent"
                    ].iloc[0]
                ),

            "answerable":
                meta["answerable"],

            "domain":
                true_domain,

            # Baseline
            "baseline_top1_intent":
                b["top1_intent"],

            "baseline_top3_intent":
                b["top3_intent"],

            "baseline_unique_top1_intent":
                b["unique_top1_intent"],

            "baseline_unique_top3_intent":
                b["unique_top3_intent"],

            "baseline_top1_domain":
                b["top1_domain"],

            "baseline_top3_domain":
                b["top3_domain"],

            "baseline_unique_top3_domain":
                b["unique_top3_domain"],

            # Reranked
            "reranked_top1_intent":
                r["top1_intent"],

            "reranked_top3_intent":
                r["top3_intent"],

            "reranked_unique_top1_intent":
                r["unique_top1_intent"],

            "reranked_unique_top3_intent":
                r["unique_top3_intent"],

            "reranked_top1_domain":
                r["top1_domain"],

            "reranked_top3_domain":
                r["top3_domain"],

            "reranked_unique_top3_domain":
                r["unique_top3_domain"]
        }
    )


step7h_query = pd.DataFrame(results)

assert len(step7h_query) == 500

print("✓ Evaluated 500 Test queries")


# ------------------------------------------------------------
# 3. Calculate changes
# ------------------------------------------------------------

print("\n[3/4] Calculating impact...")

step7h_query["unique_top3_change"] = (
    step7h_query[
        "reranked_unique_top3_intent"
    ]
    -
    step7h_query[
        "baseline_unique_top3_intent"
    ]
)

step7h_query["top1_change"] = (
    step7h_query[
        "reranked_top1_intent"
    ]
    -
    step7h_query[
        "baseline_top1_intent"
    ]
)


# ------------------------------------------------------------
# 4. Per-intent analysis
# ------------------------------------------------------------

print("\n[4/4] Computing per-question-type impact...")

rows = []


for intent, g in step7h_query.groupby(
    "true_intent",
    sort=False
):

    baseline_u3 = (
        g[
            "baseline_unique_top3_intent"
        ].mean()
        * 100
    )

    reranked_u3 = (
        g[
            "reranked_unique_top3_intent"
        ].mean()
        * 100
    )

    baseline_t1 = (
        g[
            "baseline_top1_intent"
        ].mean()
        * 100
    )

    reranked_t1 = (
        g[
            "reranked_top1_intent"
        ].mean()
        * 100
    )


    rows.append(
        {
            "question_type":
                intent,

            "queries":
                len(g),

            "classifier_accuracy_%":
                g[
                    "classifier_correct"
                ].mean() * 100,

            "baseline_unique_top3_%":
                baseline_u3,

            "reranked_unique_top3_%":
                reranked_u3,

            "unique_top3_change_pp":
                reranked_u3 - baseline_u3,

            "baseline_top1_%":
                baseline_t1,

            "reranked_top1_%":
                reranked_t1,

            "top1_change_pp":
                reranked_t1 - baseline_t1,

            "improved_unique_top3":
                int(
                    (
                        g[
                            "unique_top3_change"
                        ] > 0
                    ).sum()
                ),

            "unchanged_unique_top3":
                int(
                    (
                        g[
                            "unique_top3_change"
                        ] == 0
                    ).sum()
                ),

            "worsened_unique_top3":
                int(
                    (
                        g[
                            "unique_top3_change"
                        ] < 0
                    ).sum()
                )
        }
    )


step7h_type = pd.DataFrame(rows)

step7h_type = (
    step7h_type
    .sort_values(
        "unique_top3_change_pp",
        ascending=False
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# Classifier correct vs wrong
# ------------------------------------------------------------

correct = step7h_query[
    step7h_query[
        "classifier_correct"
    ] == 1
]

wrong = step7h_query[
    step7h_query[
        "classifier_correct"
    ] == 0
]


step7h_summary = pd.DataFrame(
    {
        "group": [
            "Classifier Correct",
            "Classifier Wrong"
        ],

        "queries": [
            len(correct),
            len(wrong)
        ],

        "baseline_unique_top3_%": [
            correct[
                "baseline_unique_top3_intent"
            ].mean() * 100,

            wrong[
                "baseline_unique_top3_intent"
            ].mean() * 100
        ],

        "reranked_unique_top3_%": [
            correct[
                "reranked_unique_top3_intent"
            ].mean() * 100,

            wrong[
                "reranked_unique_top3_intent"
            ].mean() * 100
        ]
    }
)

step7h_summary["change_pp"] = (
    step7h_summary[
        "reranked_unique_top3_%"
    ]
    -
    step7h_summary[
        "baseline_unique_top3_%"
    ]
)


# ------------------------------------------------------------
# Display
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("PER-INTENT IMPACT — α = 0.03")
print("=" * 70)

print(
    step7h_type.to_string(
        index=False,
        formatters={
            "classifier_accuracy_%":
                "{:.2f}".format,

            "baseline_unique_top3_%":
                "{:.2f}".format,

            "reranked_unique_top3_%":
                "{:.2f}".format,

            "unique_top3_change_pp":
                "{:+.2f}".format,

            "baseline_top1_%":
                "{:.2f}".format,

            "reranked_top1_%":
                "{:.2f}".format,

            "top1_change_pp":
                "{:+.2f}".format
        }
    )
)


print("\n" + "=" * 70)
print("CLASSIFIER CORRECT vs WRONG")
print("=" * 70)

print(
    step7h_summary.to_string(
        index=False,
        formatters={
            "baseline_unique_top3_%":
                "{:.2f}".format,

            "reranked_unique_top3_%":
                "{:.2f}".format,

            "change_pp":
                "{:+.2f}".format
        }
    )
)


print("\n" + "=" * 70)
print("STEP 7H COMPLETED SUCCESSFULLY")
print("=" * 70)

print("✓ step7h_query")
print("✓ step7h_type")
print("✓ step7h_summary")

print("\nNo new model inference.")
print("No embeddings recomputed.")
print("No FAISS changes.")

======================================================================
STEP 7H — PER-INTENT IMPACT ANALYSIS
BASELINE vs PREDICTED-INTENT RERANKING
======================================================================

[1/4] Preparing Test metadata...
✓ Test metadata ready

[2/4] Evaluating baseline vs reranked...
✓ Evaluated 500 Test queries

[3/4] Calculating impact...

[4/4] Computing per-question-type impact...

======================================================================
PER-INTENT IMPACT — α = 0.03
======================================================================
                                                 question_type  queries classifier_accuracy_% baseline_unique_top3_% reranked_unique_top3_% unique_top3_change_pp baseline_top1_% reranked_top1_% top1_change_pp  improved_unique_top3  unchanged_unique_top3  worsened_unique_top3
         troubleshooting a problem with the product or service       66                 83.33                  45.45                  90.91                +45.45           19.70           80.30         +60.61                    30                     36                     0
                       availability, coverage or delivery time       60                 91.67                  46.67                  90.00                +43.33           18.33           85.00         +66.67                    26                     34                     0
                    billing dispute or a charge on the account       64                 93.75                  43.75                  79.69                +35.94           21.88           79.69         +57.81                    23                     41                     0
                      comparison between two products or plans       66                 96.97                  53.03                  87.88                +34.85           21.21           87.88         +66.67                    24                     41                     1
             policy (refund, cancellation, warranty, exchange)       66                 89.39                  34.85                  68.18                +33.33           12.12           63.64         +51.52                    22                     44                     0
                                               pricing or fees       55                 89.09                  43.64                  72.73                +29.09           20.00           70.91         +50.91                    16                     39                     0
account or subscription management (upgrade, renewal, closing)       64                 92.19                  64.06                  92.19                +28.12           40.62           92.19         +51.56                    20                     42                     2
             product or plan details (specs, what is included)       59                 79.66                  40.68                  64.41                +23.73           20.34           61.02         +40.68                    18                     37                     4

======================================================================
CLASSIFIER CORRECT vs WRONG
======================================================================
             group  queries baseline_unique_top3_% reranked_unique_top3_% change_pp
Classifier Correct      448                  48.21                  86.38    +38.17
  Classifier Wrong       52                  32.69                  34.62     +1.92

======================================================================
STEP 7H COMPLETED SUCCESSFULLY
======================================================================
✓ step7h_query
✓ step7h_type
✓ step7h_summary

No new model inference.
No embeddings recomputed.
No FAISS changes.

In [84]:
# ============================================================
# STEP 7I — FINAL STRATEGY COMPARISON
# ============================================================

import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 7I — FINAL STRATEGY COMPARISON")
print("=" * 75)


# ------------------------------------------------------------
# 1. Validate all existing artifacts
# ------------------------------------------------------------

print("\n[1/5] Validating existing evaluation artifacts...")

assert "step7b_comparison" in globals()
assert "step7c_query_impact" in globals()
assert "step7d_summary" in globals()
assert "step7e_alpha_results" in globals()
assert "step7g_alpha_results" in globals()
assert "step7h_type" in globals()

print("✓ Step 7B — BGE comparison")
print("✓ Step 7C — BGE impact")
print("✓ Step 7D — Intent availability")
print("✓ Step 7E — Oracle reranking")
print("✓ Step 7G — Predicted-intent reranking")
print("✓ Step 7H — Per-intent impact")


# ------------------------------------------------------------
# 2. Extract baseline metrics
# ------------------------------------------------------------

print("\n[2/5] Building strategy comparison...")

# Baseline E5
baseline_top1 = 21.80
baseline_top3 = 55.00
baseline_unique_top1 = 21.80
baseline_unique_top3 = 46.60


# BGE reranker
bge_row = step7b_comparison.iloc[0:0].copy()

bge_unique_top3 = 47.60
bge_top1 = 21.80
bge_top3 = 56.20
bge_unique_top1 = 21.80


# Oracle intent reranking
oracle_alpha_03 = step7e_alpha_results[
    step7e_alpha_results["alpha"] == 0.03
].iloc[0]

oracle_top1 = (
    oracle_alpha_03["top1_intent_%"]
)

oracle_top3 = (
    oracle_alpha_03["top3_intent_%"]
)

oracle_unique_top1 = (
    oracle_alpha_03[
        "unique_top1_intent_%"
    ]
)

oracle_unique_top3 = (
    oracle_alpha_03[
        "unique_top3_intent_%"
    ])


# Predicted intent reranking
pred_alpha_03 = step7g_alpha_results[
    step7g_alpha_results["alpha"] == 0.03
].iloc[0]

pred_top1 = (
    pred_alpha_03["top1_intent_%"]
)

pred_top3 = (
    pred_alpha_03["top3_intent_%"]
)

pred_unique_top1 = (
    pred_alpha_03[
        "unique_top1_intent_%"
    ]
)

pred_unique_top3 = (
    pred_alpha_03[
        "unique_top3_intent_%"
    ])


# ------------------------------------------------------------
# 3. Strategy table
# ------------------------------------------------------------

print("\n[3/5] Generating final strategy table...")

strategy_df = pd.DataFrame(
    [
        {
            "strategy":
                "E5 Baseline",

            "top1_intent_%":
                baseline_top1,

            "top3_intent_%":
                baseline_top3,

            "unique_top1_intent_%":
                baseline_unique_top1,

            "unique_top3_intent_%":
                baseline_unique_top3,

            "gain_unique_top3_pp":
                0.00
        },

        {
            "strategy":
                "E5 + BGE Reranker",

            "top1_intent_%":
                bge_top1,

            "top3_intent_%":
                bge_top3,

            "unique_top1_intent_%":
                bge_unique_top1,

            "unique_top3_intent_%":
                bge_unique_top3,

            "gain_unique_top3_pp":
                bge_unique_top3
                - baseline_unique_top3
        },

        {
            "strategy":
                "E5 + Oracle Intent",

            "top1_intent_%":
                oracle_top1,

            "top3_intent_%":
                oracle_top3,

            "unique_top1_intent_%":
                oracle_unique_top1,

            "unique_top3_intent_%":
                oracle_unique_top3,

            "gain_unique_top3_pp":
                oracle_unique_top3
                - baseline_unique_top3
        },

        {
            "strategy":
                "E5 + Predicted Intent",

            "top1_intent_%":
                pred_top1,

            "top3_intent_%":
                pred_top3,

            "unique_top1_intent_%":
                pred_unique_top1,

            "unique_top3_intent_%":
                pred_unique_top3,

            "gain_unique_top3_pp":
                pred_unique_top3
                - baseline_unique_top3
        }
    ]
)


print("\n" + "-" * 75)
print("STRATEGY COMPARISON")
print("-" * 75)

print(
    strategy_df.to_string(
        index=False,
        formatters={
            "top1_intent_%":
                "{:.2f}".format,

            "top3_intent_%":
                "{:.2f}".format,

            "unique_top1_intent_%":
                "{:.2f}".format,

            "unique_top3_intent_%":
                "{:.2f}".format,

            "gain_unique_top3_pp":
                "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 4. Candidate-pool ceiling analysis
# ------------------------------------------------------------

print("\n[4/5] Candidate-pool ceiling analysis...")

candidate_ceiling = 85.20

pred_gap_to_ceiling = (
    candidate_ceiling
    - pred_unique_top3
)

oracle_gap_to_ceiling = (
    candidate_ceiling
    - oracle_unique_top3
)

pred_vs_oracle_gap = (
    oracle_unique_top3
    - pred_unique_top3
)


ceiling_df = pd.DataFrame(
    [
        {
            "metric":
                "E5 baseline",

            "unique_top3_intent_%":
                baseline_unique_top3,

            "gap_to_candidate_ceiling_pp":
                candidate_ceiling
                - baseline_unique_top3
        },

        {
            "metric":
                "Predicted-intent reranking",

            "unique_top3_intent_%":
                pred_unique_top3,

            "gap_to_candidate_ceiling_pp":
                pred_gap_to_ceiling
        },

        {
            "metric":
                "Oracle-intent reranking",

            "unique_top3_intent_%":
                oracle_unique_top3,

            "gap_to_candidate_ceiling_pp":
                oracle_gap_to_ceiling
        }
    ]
)


print(
    ceiling_df.to_string(
        index=False,
        formatters={
            "unique_top3_intent_%":
                "{:.2f}".format,

            "gap_to_candidate_ceiling_pp":
                "{:.2f}".format
        }
    )
)

print(
    f"\nCandidate-pool ceiling : "
    f"{candidate_ceiling:.2f}%"
)

print(
    f"Predicted vs Oracle gap : "
    f"{pred_vs_oracle_gap:.2f} pp"
)


# ------------------------------------------------------------
# 5. Final decision summary
# ------------------------------------------------------------

print("\n[5/5] Final strategy decision...")

classifier_accuracy = 89.60

decision_df = pd.DataFrame(
    [
        {
            "criterion":
                "Intent classifier accuracy",

            "value":
                classifier_accuracy,

            "unit":
                "%"
        },

        {
            "criterion":
                "Baseline unique Top-3 intent",

            "value":
                baseline_unique_top3,

            "unit":
                "%"
        },

        {
            "criterion":
                "BGE unique Top-3 intent",

            "value":
                bge_unique_top3,

            "unit":
                "%"
        },

        {
            "criterion":
                "Predicted-intent unique Top-3",

            "value":
                pred_unique_top3,

            "unit":
                "%"
        },

        {
            "criterion":
                "Predicted-intent gain",

            "value":
                pred_unique_top3
                - baseline_unique_top3,

            "unit":
                "pp"
        },

        {
            "criterion":
                "Oracle upper-bound unique Top-3",

            "value":
                oracle_unique_top3,

            "unit":
                "%"
        }
    ]
)


print(
    decision_df.to_string(
        index=False,
        formatters={
            "value":
                "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Save artifacts
# ------------------------------------------------------------

step7i_strategy = strategy_df
step7i_ceiling = ceiling_df
step7i_decision = decision_df


print("\n" + "=" * 75)
print("STEP 7I COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ step7i_strategy")
print("✓ step7i_ceiling")
print("✓ step7i_decision")

print("\nNo new model inference.")
print("No embeddings recomputed.")
print("No FAISS changes.")

===========================================================================
STEP 7I — FINAL STRATEGY COMPARISON
===========================================================================

[1/5] Validating existing evaluation artifacts...
✓ Step 7B — BGE comparison
✓ Step 7C — BGE impact
✓ Step 7D — Intent availability
✓ Step 7E — Oracle reranking
✓ Step 7G — Predicted-intent reranking
✓ Step 7H — Per-intent impact

[2/5] Building strategy comparison...

[3/5] Generating final strategy table...

---------------------------------------------------------------------------
STRATEGY COMPARISON
---------------------------------------------------------------------------
             strategy top1_intent_% top3_intent_% unique_top1_intent_% unique_top3_intent_% gain_unique_top3_pp
          E5 Baseline         21.80         55.00                21.80                46.60               +0.00
    E5 + BGE Reranker         21.80         56.20                21.80                47.60               +1.00
   E5 + Oracle Intent         85.20         85.20                85.20                85.20              +38.60
E5 + Predicted Intent         78.00         79.80                78.00                79.80              +33.20

[4/5] Candidate-pool ceiling analysis...
                    metric unique_top3_intent_% gap_to_candidate_ceiling_pp
               E5 baseline                46.60                       38.60
Predicted-intent reranking                79.80                        5.40
   Oracle-intent reranking                85.20                        0.00

Candidate-pool ceiling : 85.20%
Predicted vs Oracle gap : 5.40 pp

[5/5] Final strategy decision...
                      criterion value unit
     Intent classifier accuracy 89.60    %
   Baseline unique Top-3 intent 46.60    %
        BGE unique Top-3 intent 47.60    %
  Predicted-intent unique Top-3 79.80    %
          Predicted-intent gain 33.20   pp
Oracle upper-bound unique Top-3 85.20    %

===========================================================================
STEP 7I COMPLETED SUCCESSFULLY
===========================================================================
✓ step7i_strategy
✓ step7i_ceiling
✓ step7i_decision

No new model inference.
No embeddings recomputed.
No FAISS changes.

In [85]:
# ============================================================
# STEP 8A — FINAL EVALUATION ARTIFACT AUDIT
# ============================================================

print("=" * 75)
print("STEP 8A — FINAL EVALUATION ARTIFACT AUDIT")
print("=" * 75)

required_artifacts = [
    "train_df",
    "test_df",
    "train_corpus",
    "index",

    "step6c_evaluation",
    "step6c_metrics",

    "step6d_duplication",
    "step6d_domain",

    "step6e_threshold_df",
    "step6e_threshold_results",

    "step6f_proxy_eval",
    "step6f_proxy_metrics",

    "step6g_disagreement",

    "step6h_gap_analysis",

    "step6i_tie_analysis",

    "step6j_duplication_analysis",

    "step6k_duplicate_metadata",

    "step6l_unique_content",
    "step6l_original_to_unique",
    "step6l_copy_counts",

    "step6m_dedup_eval",

    "step6n_unique_profile",
    "step6n_position_summary",

    "step6o_domain_diversity",
    "step6o_group_summary",
    "step6o_position_diversity",

    "step6p_top1_alignment",
    "step6p_answerability_alignment",
    "step6p_alignment_distribution",

    "step6q_domain_mismatch",
    "step6q_representative",

    "step6r_type_analysis",
    "step6r_type_summary",
    "step6r_answerability_by_type",
    "step6r_weakest_types",

    "step6s_top3_coverage",
    "step6s_coverage_by_answerability",

    "step6t_type_top3",
    "step6t_largest_gain",
    "step6t_persistent_weak",

    "step6u_intent_alignment",
    "step6u_position_summary",
    "step6u_query_intent",
    "step6u_type_intent",

    "step6v_hard_misses",
    "step6v_audit",
    "step6v_representative",

    "step6w_root_cause",
    "step6w_root_summary",
    "step6w_type_root",

    "step6x_recovery",
    "step6x_summary",
    "step6x_type_recovery",

    "step6y_proxy_availability",
    "step6y_availability_summary",
    "step6y_type_availability",

    "step7a_reranked_evaluation",

    "step7b_baseline_eval",
    "step7b_reranked_eval",
    "step7b_comparison",

    "step7c_paired",
    "step7c_query_impact",
    "step7c_type_impact",

    "step7d_intent_availability",
    "step7d_summary",
    "step7d_rank_distribution",

    "step7e_alpha_results",

    "step7f_classifier",
    "step7f_predictions",
    "step7f_metrics",
    "step7f_confusion_matrix",

    "step7g_candidate_df",
    "step7g_alpha_results",

    "step7h_query",
    "step7h_type",
    "step7h_summary",

    "step7i_strategy",
    "step7i_ceiling",
    "step7i_decision"
]


missing = [
    name
    for name in required_artifacts
    if name not in globals()
]


print("\nRequired artifacts :", len(required_artifacts))
print("Available          :", len(required_artifacts) - len(missing))
print("Missing            :", len(missing))


if missing:
    print("\n⚠️ Missing artifacts:")
    for name in missing:
        print(" -", name)
else:
    print("\n✓ ALL REQUIRED ARTIFACTS ARE AVAILABLE")


# ------------------------------------------------------------
# Basic integrity checks
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("BASIC INTEGRITY CHECKS")
print("-" * 75)

print(
    "Train rows       :",
    len(train_df)
)

print(
    "Test rows        :",
    len(test_df)
)

print(
    "Train chunks     :",
    len(train_corpus)
)

print(
    "FAISS vectors    :",
    index.ntotal
)

print(
    "Test evaluations :",
    len(step6c_evaluation)
)

print(
    "Step 7H queries   :",
    len(step7h_query)
)

print(
    "Step 7I strategies:",
    len(step7i_strategy)
)


assert len(train_df) == 27427
assert len(test_df) == 500
assert len(train_corpus) == 164456
assert index.ntotal == 164456
assert len(step6c_evaluation) == 500
assert len(step7h_query) == 500
assert len(step7i_strategy) == 4


print("\n✓ Dataset integrity passed")
print("✓ Corpus integrity passed")
print("✓ FAISS integrity passed")
print("✓ Evaluation integrity passed")
print("✓ Strategy comparison integrity passed")

print("\n" + "=" * 75)
print("STEP 8A COMPLETED")
print("=" * 75)

print("No inference.")
print("No embedding computation.")
print("No FAISS rebuild.")

===========================================================================
STEP 8A — FINAL EVALUATION ARTIFACT AUDIT
===========================================================================

Required artifacts : 79
Available          : 77
Missing            : 2

⚠️ Missing artifacts:
 - step6i_tie_analysis
 - step6k_duplicate_metadata

---------------------------------------------------------------------------
BASIC INTEGRITY CHECKS
---------------------------------------------------------------------------
Train rows       : 27427
Test rows        : 500
Train chunks     : 164456
FAISS vectors    : 164456
Test evaluations : 500
Step 7H queries   : 500
Step 7I strategies: 4

✓ Dataset integrity passed
✓ Corpus integrity passed
✓ FAISS integrity passed
✓ Evaluation integrity passed
✓ Strategy comparison integrity passed

===========================================================================
STEP 8A COMPLETED
===========================================================================
No inference.
No embedding computation.
No FAISS rebuild.

In [86]:
# ============================================================
# STEP 8A-FIX — ARTIFACT NAME RECONCILIATION
# ============================================================

print("=" * 75)
print("STEP 8A-FIX — ARTIFACT NAME RECONCILIATION")
print("=" * 75)


# ------------------------------------------------------------
# 1. Inspect nearby Step 6 artifacts
# ------------------------------------------------------------

print("\n[1/3] Inspecting existing Step 6 artifacts...")

step6_artifacts = sorted([
    name for name in globals()
    if name.startswith("step6")
])

for name in step6_artifacts:
    print("✓", name)


# ------------------------------------------------------------
# 2. Resolve the two missing references
# ------------------------------------------------------------

print("\n[2/3] Resolving artifact aliases...")

# Step 6I
# The analysis was completed successfully, but the object name
# used in the audit does not match the actual notebook object.
step6i_candidates = [
    name for name in globals()
    if name.startswith("step6i")
]

print("\nStep 6I candidates:")
for name in step6i_candidates:
    obj = globals()[name]
    print(
        f" - {name}: "
        f"{type(obj).__name__}"
        + (
            f", shape={obj.shape}"
            if hasattr(obj, "shape")
            else ""
        )
    )


# Step 6K
step6k_candidates = [
    name for name in globals()
    if name.startswith("step6k")
]

print("\nStep 6K candidates:")
for name in step6k_candidates:
    obj = globals()[name]
    print(
        f" - {name}: "
        f"{type(obj).__name__}"
        + (
            f", shape={obj.shape}"
            if hasattr(obj, "shape")
            else ""
        )
    )


# ------------------------------------------------------------
# 3. Final reconciliation
# ------------------------------------------------------------

print("\n[3/3] Final reconciliation...")

# We only create aliases when exactly one candidate exists.
if len(step6i_candidates) == 1:
    step6i_tie_analysis = globals()[step6i_candidates[0]]
    print(
        f"✓ step6i_tie_analysis "
        f"← {step6i_candidates[0]}"
    )
elif "step6i_tie_analysis" in globals():
    print("✓ step6i_tie_analysis already exists")
else:
    print(
        "⚠️ Step 6I requires manual name inspection."
    )


if len(step6k_candidates) == 1:
    step6k_duplicate_metadata = globals()[step6k_candidates[0]]
    print(
        f"✓ step6k_duplicate_metadata "
        f"← {step6k_candidates[0]}"
    )
elif "step6k_duplicate_metadata" in globals():
    print("✓ step6k_duplicate_metadata already exists")
else:
    print(
        "⚠️ Step 6K requires manual name inspection."
    )


# ------------------------------------------------------------
# Final status
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("FINAL STATUS")
print("-" * 75)

print(
    "step6i_tie_analysis :",
    "AVAILABLE"
    if "step6i_tie_analysis" in globals()
    else "MISSING"
)

print(
    "step6k_duplicate_metadata :",
    "AVAILABLE"
    if "step6k_duplicate_metadata" in globals()
    else "MISSING"
)

print("\n" + "=" * 75)
print("STEP 8A-FIX COMPLETED")
print("=" * 75)

===========================================================================
STEP 8A-FIX — ARTIFACT NAME RECONCILIATION
===========================================================================

[1/3] Inspecting existing Step 6 artifacts...
✓ step6a_proxy_df
✓ step6b_proxy_df
✓ step6c_evaluation
✓ step6c_metrics
✓ step6d_domain
✓ step6d_duplication
✓ step6e_threshold_df
✓ step6e_threshold_results
✓ step6f_proxy_eval
✓ step6f_proxy_metrics
✓ step6g_disagreement
✓ step6h_gap_analysis
✓ step6i_tie_diagnostic
✓ step6j_duplication_analysis
✓ step6k_duplicate_groups
✓ step6l_copy_counts
✓ step6l_original_to_unique
✓ step6l_unique_content
✓ step6m_dedup_eval
✓ step6n_position_summary
✓ step6n_unique_profile
✓ step6o_domain_diversity
✓ step6o_group_summary
✓ step6o_position_diversity
✓ step6p_alignment_distribution
✓ step6p_answerability_alignment
✓ step6p_top1_alignment
✓ step6q_domain_mismatch
✓ step6q_representative
✓ step6r_answerability_by_type
✓ step6r_type_analysis
✓ step6r_type_summary
✓ step6r_weakest_types
✓ step6s_coverage_by_answerability
✓ step6s_top3_coverage
✓ step6t_largest_gain
✓ step6t_persistent_weak
✓ step6t_type_top3
✓ step6u_intent_alignment
✓ step6u_position_summary
✓ step6u_query_intent
✓ step6u_type_intent
✓ step6v_audit
✓ step6v_hard_misses
✓ step6v_representative
✓ step6w_root_cause
✓ step6w_root_summary
✓ step6w_type_root
✓ step6x_recovery
✓ step6x_summary
✓ step6x_type_recovery
✓ step6y_availability_summary
✓ step6y_proxy_availability
✓ step6y_type_availability

[2/3] Resolving artifact aliases...

Step 6I candidates:
 - step6i_tie_diagnostic: DataFrame, shape=(500, 9)

Step 6K candidates:
 - step6k_duplicate_groups: DataFrame, shape=(41179, 10)

[3/3] Final reconciliation...
✓ step6i_tie_analysis ← step6i_tie_diagnostic
✓ step6k_duplicate_metadata ← step6k_duplicate_groups

---------------------------------------------------------------------------
FINAL STATUS
---------------------------------------------------------------------------
step6i_tie_analysis : AVAILABLE
step6k_duplicate_metadata : AVAILABLE

===========================================================================
STEP 8A-FIX COMPLETED
===========================================================================

In [89]:
# ============================================================
# STEP 8B-INSPECT — INSPECT EXISTING RETRIEVAL ARTIFACT
# ============================================================

print("=" * 75)
print("STEP 8B-INSPECT — RETRIEVAL ARTIFACT STRUCTURE")
print("=" * 75)

print("\nType:")
print(type(step6c_evaluation))

print("\nNumber of query results:")
print(len(step6c_evaluation))

print("\nFirst element type:")
print(type(step6c_evaluation[0]))

print("\nFirst element:")
print(step6c_evaluation[0])

print("\n" + "=" * 75)
print("INSPECTION COMPLETED")
print("=" * 75)

===========================================================================
STEP 8B-INSPECT — RETRIEVAL ARTIFACT STRUCTURE
===========================================================================

Type:
<class 'list'>

Number of query results:
500

First element type:
<class 'dict'>

First element:
{'test_idx': 0, 'test_id': '6875-0', 'question': 'أريد إغلاق حسابي فوراً! لقد سئمت من هذه الإجراءات، أخبروني كيف أنهي هذا الاشتراك الآن!', 'answerable': True, 'gold_chunk_ids': [np.int64(2)], 'retrieved': [{'rank': 1, 'corpus_idx': 33508, 'score': 0.8562403917312622, 'id': '1398-3', 'chunk_idx': 3, 'row_idx': 5580, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 2, 'corpus_idx': 33501, 'score': 0.8562403917312622, 'id': '1398-2', 'chunk_idx': 3, 'row_idx': 5579, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 3, 'corpus_idx': 33494, 'score': 0.8562403917312622, 'id': '1398-1', 'chunk_idx': 3, 'row_idx': 5578, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 4, 'corpus_idx': 33487, 'score': 0.8562403917312622, 'id': '1398-0', 'chunk_idx': 3, 'row_idx': 5577, 'domain': 'streaming service', 'country': 'Morocco', 'company': 'شاشة المغرب', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب تقديم طلب عبر البريد الإلكتروني قبل 48 ساعة من تاريخ انتهاء الاشتراك الحالي. سيتم حذف جميع بيانات المشاهدة والقوائم المفضلة خلال 15 يوماً من تاريخ تأكيد إغلاق الحساب.'}, {'rank': 5, 'corpus_idx': 129954, 'score': 0.8544511795043945, 'id': '5427-3', 'chunk_idx': 5, 'row_idx': 21655, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 6, 'corpus_idx': 129947, 'score': 0.8544511795043945, 'id': '5427-2', 'chunk_idx': 5, 'row_idx': 21654, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 7, 'corpus_idx': 129940, 'score': 0.8544511795043945, 'id': '5427-1', 'chunk_idx': 5, 'row_idx': 21653, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 8, 'corpus_idx': 129933, 'score': 0.8544511795043945, 'id': '5427-0', 'chunk_idx': 5, 'row_idx': 21652, 'domain': 'hotel chain', 'country': 'Bahrain', 'company': 'فنادق لؤلؤة الخليج', 'chunk_text': 'لإغلاق حساب العضوية الخاص بك، يرجى إرسال طلب رسمي عبر البريد الإلكتروني إلى قسم العضويات. يتم معالجة طلب إغلاق الحساب خلال 5 أيام عمل، مع حذف كافة البيانات الشخصية من سجلاتنا.'}, {'rank': 9, 'corpus_idx': 41754, 'score': 0.8533371686935425, 'id': '1740-3', 'chunk_idx': 4, 'row_idx': 6945, 'domain': 'food delivery app', 'country': 'Lebanon', 'company': 'سريع-لقمة', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب إرسال طلب عبر البريد الإلكتروني للدعم الفني. يستغرق معالجة طلب إغلاق الحساب 48 ساعة عمل، وسيتم حذف كافة البيانات الشخصية وسجل الطلبات من خوادمنا بشكل نهائي.'}, {'rank': 10, 'corpus_idx': 41747, 'score': 0.8533371686935425, 'id': '1740-2', 'chunk_idx': 4, 'row_idx': 6944, 'domain': 'food delivery app', 'country': 'Lebanon', 'company': 'سريع-لقمة', 'chunk_text': 'لإغلاق الحساب نهائياً، يجب إرسال طلب عبر البريد الإلكتروني للدعم الفني. يستغرق معالجة طلب إغلاق الحساب 48 ساعة عمل، وسيتم حذف كافة البيانات الشخصية وسجل الطلبات من خوادمنا بشكل نهائي.'}]}

===========================================================================
INSPECTION COMPLETED
===========================================================================

In [90]:
# ============================================================
# STEP 8B — FINAL RETRIEVAL EVALUATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 8B — FINAL RETRIEVAL EVALUATION")
print("=" * 75)


# ------------------------------------------------------------
# 1. Dataset & corpus statistics
# ------------------------------------------------------------

print("\n[1/6] Dataset & corpus statistics...")

total_train = len(train_df)
total_test = len(test_df)
total_chunks = len(train_corpus)

answerable_test = int(test_df["answerable"].sum())
unanswerable_test = total_test - answerable_test

unique_chunks = train_corpus["chunk_text"].nunique()

duplicate_slot_rate = (
    1 - unique_chunks / total_chunks
) * 100

print(f"Train records       : {total_train:,}")
print(f"Test records        : {total_test:,}")
print(f"Train chunks        : {total_chunks:,}")
print(f"Unique chunk texts  : {unique_chunks:,}")
print(f"Duplicate slot rate : {duplicate_slot_rate:.2f}%")
print(f"Answerable test     : {answerable_test}")
print(f"Unanswerable test   : {unanswerable_test}")


# ------------------------------------------------------------
# 2. Baseline E5 retrieval
# ------------------------------------------------------------

print("\n[2/6] Baseline E5 retrieval...")

assert isinstance(step6c_evaluation, list)
assert len(step6c_evaluation) == 500

top1_scores = []

for result in step6c_evaluation:

    assert isinstance(result, dict)
    assert "retrieved" in result
    assert len(result["retrieved"]) == 10

    top1_scores.append(
        float(result["retrieved"][0]["score"])
    )

top1_scores = np.asarray(
    top1_scores,
    dtype=np.float32
)

baseline_top1_score = float(top1_scores.mean())
baseline_top1_score_median = float(np.median(top1_scores))

print(
    f"Top-1 mean similarity   : "
    f"{baseline_top1_score:.4f}"
)

print(
    f"Top-1 median similarity : "
    f"{baseline_top1_score_median:.4f}"
)

print(
    f"Top-1 minimum           : "
    f"{top1_scores.min():.4f}"
)

print(
    f"Top-1 maximum           : "
    f"{top1_scores.max():.4f}"
)


# ------------------------------------------------------------
# 3. Domain & intent alignment
# ------------------------------------------------------------

print("\n[3/6] Domain & intent alignment...")

top1_domain = 53.00
top3_domain = 65.80

top1_intent = 21.80
top3_intent = 55.00

unique_top1_intent = 21.80
unique_top3_intent = 46.60

alignment_df = pd.DataFrame([
    {
        "metric": "Top-1 Same Domain",
        "value_%": top1_domain
    },
    {
        "metric": "Top-3 Domain Coverage",
        "value_%": top3_domain
    },
    {
        "metric": "Top-1 Same Intent",
        "value_%": top1_intent
    },
    {
        "metric": "Top-3 Intent Coverage",
        "value_%": top3_intent
    },
    {
        "metric": "Unique Top-1 Same Intent",
        "value_%": unique_top1_intent
    },
    {
        "metric": "Unique Top-3 Intent Coverage",
        "value_%": unique_top3_intent
    }
])

print(
    alignment_df.to_string(
        index=False,
        formatters={
            "value_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 4. Answerability analysis
# ------------------------------------------------------------

print("\n[4/6] Answerability analysis...")

answerability_metrics = pd.DataFrame([
    {
        "group": "Answerable",
        "count": 446,
        "top1_mean_score": 0.8679,
        "top1_same_domain_%": 55.38
    },
    {
        "group": "Unanswerable",
        "count": 54,
        "top1_mean_score": 0.8572,
        "top1_same_domain_%": 33.33
    }
])

print(
    answerability_metrics.to_string(
        index=False,
        formatters={
            "top1_mean_score": "{:.4f}".format,
            "top1_same_domain_%": "{:.2f}".format
        }
    )
)

score_difference = 0.8679 - 0.8572

print(
    f"\nAnswerable − Unanswerable "
    f"Top-1 score difference: "
    f"{score_difference:.4f}"
)


# ------------------------------------------------------------
# 5. Conservative proxy evaluation
# ------------------------------------------------------------

print("\n[5/6] Conservative proxy evaluation...")

proxy_total = 465
proxy_reliable = 174

proxy_recall = pd.DataFrame([
    {
        "metric": "Proxy Recall@1",
        "value_%": 0.00
    },
    {
        "metric": "Proxy Recall@3",
        "value_%": 0.00
    },
    {
        "metric": "Proxy Recall@5",
        "value_%": 2.30
    },
    {
        "metric": "Proxy Recall@10",
        "value_%": 4.02
    }
])

print(
    f"Gold chunks examined    : {proxy_total}"
)

print(
    f"Reliable proxy mappings : {proxy_reliable}"
)

print(
    f"Reliable mapping rate   : "
    f"{proxy_reliable / proxy_total * 100:.2f}%"
)

print(
    proxy_recall.to_string(
        index=False,
        formatters={
            "value_%": "{:.2f}".format
        }
    )
)


# ------------------------------------------------------------
# 6. Final retrieval summary
# ------------------------------------------------------------

print("\n[6/6] Final retrieval summary...")

final_retrieval_summary = pd.DataFrame([
    {
        "category": "Dataset",
        "metric": "Train records",
        "value": total_train
    },
    {
        "category": "Dataset",
        "metric": "Test records",
        "value": total_test
    },
    {
        "category": "Corpus",
        "metric": "Train chunks",
        "value": total_chunks
    },
    {
        "category": "Corpus",
        "metric": "Unique chunk texts",
        "value": unique_chunks
    },
    {
        "category": "Corpus",
        "metric": "Duplicate slot rate (%)",
        "value": duplicate_slot_rate
    },
    {
        "category": "Retrieval",
        "metric": "Top-1 mean E5 similarity",
        "value": baseline_top1_score
    },
    {
        "category": "Retrieval",
        "metric": "Top-1 median E5 similarity",
        "value": baseline_top1_score_median
    },
    {
        "category": "Alignment",
        "metric": "Top-1 same domain (%)",
        "value": top1_domain
    },
    {
        "category": "Alignment",
        "metric": "Top-3 domain coverage (%)",
        "value": top3_domain
    },
    {
        "category": "Alignment",
        "metric": "Unique Top-1 intent (%)",
        "value": unique_top1_intent
    },
    {
        "category": "Alignment",
        "metric": "Unique Top-3 intent coverage (%)",
        "value": unique_top3_intent
    },
    {
        "category": "Proxy",
        "metric": "Reliable mappings (%)",
        "value": proxy_reliable / proxy_total * 100
    },
    {
        "category": "Proxy",
        "metric": "Proxy Recall@10 (%)",
        "value": 4.02
    }
])

print("\n" + "-" * 75)

print(
    final_retrieval_summary.to_string(
        index=False,
        formatters={
            "value": lambda x:
                f"{x:,.4f}"
                if isinstance(x, (float, np.floating))
                else f"{x:,}"
        }
    )
)


# ------------------------------------------------------------
# Save Step 8B artifacts
# ------------------------------------------------------------

step8b_alignment = alignment_df
step8b_answerability = answerability_metrics
step8b_proxy = proxy_recall
step8b_summary = final_retrieval_summary


print("\n" + "=" * 75)
print("STEP 8B COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ step8b_alignment")
print("✓ step8b_answerability")
print("✓ step8b_proxy")
print("✓ step8b_summary")

print("\nNo new inference.")
print("No embeddings recomputed.")
print("No FAISS rebuild.")

===========================================================================
STEP 8B — FINAL RETRIEVAL EVALUATION
===========================================================================

[1/6] Dataset & corpus statistics...
Train records       : 27,427
Test records        : 500
Train chunks        : 164,456
Unique chunk texts  : 41,179
Duplicate slot rate : 74.96%
Answerable test     : 446
Unanswerable test   : 54

[2/6] Baseline E5 retrieval...
Top-1 mean similarity   : 0.8667
Top-1 median similarity : 0.8671
Top-1 minimum           : 0.8046
Top-1 maximum           : 0.9324

[3/6] Domain & intent alignment...
                      metric value_%
           Top-1 Same Domain   53.00
       Top-3 Domain Coverage   65.80
           Top-1 Same Intent   21.80
       Top-3 Intent Coverage   55.00
    Unique Top-1 Same Intent   21.80
Unique Top-3 Intent Coverage   46.60

[4/6] Answerability analysis...
       group  count top1_mean_score top1_same_domain_%
  Answerable    446          0.8679              55.38
Unanswerable     54          0.8572              33.33

Answerable − Unanswerable Top-1 score difference: 0.0107

[5/6] Conservative proxy evaluation...
Gold chunks examined    : 465
Reliable proxy mappings : 174
Reliable mapping rate   : 37.42%
         metric value_%
 Proxy Recall@1    0.00
 Proxy Recall@3    0.00
 Proxy Recall@5    2.30
Proxy Recall@10    4.02

[6/6] Final retrieval summary...

---------------------------------------------------------------------------
 category                           metric        value
  Dataset                    Train records  27,427.0000
  Dataset                     Test records     500.0000
   Corpus                     Train chunks 164,456.0000
   Corpus               Unique chunk texts  41,179.0000
   Corpus          Duplicate slot rate (%)      74.9605
Retrieval         Top-1 mean E5 similarity       0.8667
Retrieval       Top-1 median E5 similarity       0.8671
Alignment            Top-1 same domain (%)      53.0000
Alignment        Top-3 domain coverage (%)      65.8000
Alignment          Unique Top-1 intent (%)      21.8000
Alignment Unique Top-3 intent coverage (%)      46.6000
    Proxy            Reliable mappings (%)      37.4194
    Proxy              Proxy Recall@10 (%)       4.0200

===========================================================================
STEP 8B COMPLETED SUCCESSFULLY
===========================================================================
✓ step8b_alignment
✓ step8b_answerability
✓ step8b_proxy
✓ step8b_summary

No new inference.
No embeddings recomputed.
No FAISS rebuild.

In [91]:
# ============================================================
# STEP 8C — FINAL RERANKING & INTENT EVALUATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 8C — FINAL RERANKING & INTENT EVALUATION")
print("=" * 75)


# ------------------------------------------------------------
# 1. Validate existing artifacts
# ------------------------------------------------------------

print("\n[1/5] Validating existing artifacts...")

required = [
    "step7b_comparison",
    "step7e_alpha_results",
    "step7f_metrics",
    "step7g_alpha_results",
    "step7h_summary",
    "step7i_strategy"
]

missing = [
    x for x in required
    if x not in globals()
]

if missing:
    print("⚠️ Missing:")
    for x in missing:
        print(" -", x)
    raise RuntimeError("Required Step 7 artifact is missing.")

print("✓ All Step 7 artifacts available")


# ------------------------------------------------------------
# 2. Extract baseline / BGE
# ------------------------------------------------------------

print("\n[2/5] Baseline vs BGE...")

baseline_unique_top3 = 46.60
baseline_top1 = 21.80

bge_unique_top3 = 47.60
bge_top1 = 21.80

bge_gain = (
    bge_unique_top3
    - baseline_unique_top3
)

print(
    f"Baseline Unique Top-3 Intent : "
    f"{baseline_unique_top3:.2f}%"
)

print(
    f"BGE Unique Top-3 Intent      : "
    f"{bge_unique_top3:.2f}%"
)

print(
    f"BGE gain                     : "
    f"{bge_gain:+.2f} pp"
)


# ------------------------------------------------------------
# 3. Oracle intent reranking
# ------------------------------------------------------------

print("\n[3/5] Oracle intent upper bound...")

oracle_row = step7e_alpha_results[
    step7e_alpha_results["alpha"] == 0.03
].iloc[0]

oracle_top1 = float(
    oracle_row["top1_intent_%"]
)

oracle_top3 = float(
    oracle_row["top3_intent_%"]
)

oracle_unique_top3 = float(
    oracle_row["unique_top3_intent_%"]
)

oracle_gain = (
    oracle_unique_top3
    - baseline_unique_top3
)

print(
    f"Oracle Top-1 Intent         : "
    f"{oracle_top1:.2f}%"
)

print(
    f"Oracle Top-3 Intent         : "
    f"{oracle_top3:.2f}%"
)

print(
    f"Oracle Unique Top-3 Intent  : "
    f"{oracle_unique_top3:.2f}%"
)

print(
    f"Oracle gain                 : "
    f"{oracle_gain:+.2f} pp"
)


# ------------------------------------------------------------
# 4. Predicted intent reranking
# ------------------------------------------------------------

print("\n[4/5] Predicted-intent reranking...")

pred_row = step7g_alpha_results[
    step7g_alpha_results["alpha"] == 0.03
].iloc[0]

pred_top1 = float(
    pred_row["top1_intent_%"]
)

pred_top3 = float(
    pred_row["top3_intent_%"]
)

pred_unique_top3 = float(
    pred_row["unique_top3_intent_%"]
)

pred_gain = (
    pred_unique_top3
    - baseline_unique_top3
)

pred_vs_oracle = (
    oracle_unique_top3
    - pred_unique_top3
)

print(
    f"Predicted Top-1 Intent        : "
    f"{pred_top1:.2f}%"
)

print(
    f"Predicted Top-3 Intent        : "
    f"{pred_top3:.2f}%"
)

print(
    f"Predicted Unique Top-3 Intent : "
    f"{pred_unique_top3:.2f}%"
)

print(
    f"Predicted gain                : "
    f"{pred_gain:+.2f} pp"
)

print(
    f"Gap to Oracle                : "
    f"{pred_vs_oracle:.2f} pp"
)


# ------------------------------------------------------------
# 5. Final comparison table
# ------------------------------------------------------------

print("\n[5/5] Building final comparison table...")

classifier_accuracy = 89.60
classifier_macro_f1 = 89.46

final_reranking_comparison = pd.DataFrame([
    {
        "strategy": "E5 Baseline",
        "top1_intent_%": baseline_top1,
        "top3_intent_%": 55.00,
        "unique_top3_intent_%": baseline_unique_top3,
        "gain_vs_baseline_pp": 0.00
    },
    {
        "strategy": "E5 + BGE Reranker",
        "top1_intent_%": bge_top1,
        "top3_intent_%": 56.20,
        "unique_top3_intent_%": bge_unique_top3,
        "gain_vs_baseline_pp": bge_gain
    },
    {
        "strategy": "E5 + Predicted Intent",
        "top1_intent_%": pred_top1,
        "top3_intent_%": pred_top3,
        "unique_top3_intent_%": pred_unique_top3,
        "gain_vs_baseline_pp": pred_gain
    },
    {
        "strategy": "E5 + Oracle Intent",
        "top1_intent_%": oracle_top1,
        "top3_intent_%": oracle_top3,
        "unique_top3_intent_%": oracle_unique_top3,
        "gain_vs_baseline_pp": oracle_gain
    }
])

print(
    "\n" + "-" * 75
)

print(
    final_reranking_comparison.to_string(
        index=False,
        formatters={
            "top1_intent_%": "{:.2f}".format,
            "top3_intent_%": "{:.2f}".format,
            "unique_top3_intent_%": "{:.2f}".format,
            "gain_vs_baseline_pp": "{:+.2f}".format
        }
    )
)


# ------------------------------------------------------------
# Classifier summary
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("INTENT CLASSIFIER")
print("-" * 75)

print(
    f"Accuracy  : {classifier_accuracy:.2f}%"
)

print(
    f"Macro F1   : {classifier_macro_f1:.2f}%"
)


# ------------------------------------------------------------
# Production interpretation
# ------------------------------------------------------------

print("\n" + "-" * 75)
print("PRODUCTION INTERPRETATION")
print("-" * 75)

print(
    "1. E5 remains the retrieval backbone."
)

print(
    "2. BGE provides only a modest intent-alignment gain."
)

print(
    "3. Predicted-intent reranking provides the strongest "
    "deployable improvement."
)

print(
    "4. Oracle intent represents an upper-bound diagnostic, "
    "not a deployable configuration."
)

print(
    f"5. Predicted-intent reranking is "
    f"{pred_vs_oracle:.2f} pp below the oracle ceiling."
)

print(
    "6. α = 0.03 is treated as the best observed diagnostic "
    "setting, not as a formally held-out tuned hyperparameter."
)


# ------------------------------------------------------------
# Save artifact
# ------------------------------------------------------------

step8c_comparison = final_reranking_comparison

step8c_classifier = pd.DataFrame([
    {
        "metric": "Accuracy",
        "value_%": classifier_accuracy
    },
    {
        "metric": "Macro F1",
        "value_%": classifier_macro_f1
    }
])

step8c_summary = pd.DataFrame([
    {
        "metric": "Baseline Unique Top-3 Intent",
        "value_%": baseline_unique_top3
    },
    {
        "metric": "BGE Unique Top-3 Intent",
        "value_%": bge_unique_top3
    },
    {
        "metric": "Predicted Intent Unique Top-3",
        "value_%": pred_unique_top3
    },
    {
        "metric": "Oracle Unique Top-3",
        "value_%": oracle_unique_top3
    },
    {
        "metric": "Predicted Intent Gain",
        "value_pp": pred_gain
    },
    {
        "metric": "Gap to Oracle",
        "value_pp": pred_vs_oracle
    }
])

print("\n" + "=" * 75)
print("STEP 8C COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ step8c_comparison")
print("✓ step8c_classifier")
print("✓ step8c_summary")

print("\nNo new inference.")
print("No embeddings recomputed.")
print("No FAISS rebuild.")

===========================================================================
STEP 8C — FINAL RERANKING & INTENT EVALUATION
===========================================================================

[1/5] Validating existing artifacts...
✓ All Step 7 artifacts available

[2/5] Baseline vs BGE...
Baseline Unique Top-3 Intent : 46.60%
BGE Unique Top-3 Intent      : 47.60%
BGE gain                     : +1.00 pp

[3/5] Oracle intent upper bound...
Oracle Top-1 Intent         : 85.20%
Oracle Top-3 Intent         : 85.20%
Oracle Unique Top-3 Intent  : 85.20%
Oracle gain                 : +38.60 pp

[4/5] Predicted-intent reranking...
Predicted Top-1 Intent        : 78.00%
Predicted Top-3 Intent        : 79.80%
Predicted Unique Top-3 Intent : 79.80%
Predicted gain                : +33.20 pp
Gap to Oracle                : 5.40 pp

[5/5] Building final comparison table...

---------------------------------------------------------------------------
             strategy top1_intent_% top3_intent_% unique_top3_intent_% gain_vs_baseline_pp
          E5 Baseline         21.80         55.00                46.60               +0.00
    E5 + BGE Reranker         21.80         56.20                47.60               +1.00
E5 + Predicted Intent         78.00         79.80                79.80              +33.20
   E5 + Oracle Intent         85.20         85.20                85.20              +38.60

---------------------------------------------------------------------------
INTENT CLASSIFIER
---------------------------------------------------------------------------
Accuracy  : 89.60%
Macro F1   : 89.46%

---------------------------------------------------------------------------
PRODUCTION INTERPRETATION
---------------------------------------------------------------------------
1. E5 remains the retrieval backbone.
2. BGE provides only a modest intent-alignment gain.
3. Predicted-intent reranking provides the strongest deployable improvement.
4. Oracle intent represents an upper-bound diagnostic, not a deployable configuration.
5. Predicted-intent reranking is 5.40 pp below the oracle ceiling.
6. α = 0.03 is treated as the best observed diagnostic setting, not as a formally held-out tuned hyperparameter.

===========================================================================
STEP 8C COMPLETED SUCCESSFULLY
===========================================================================
✓ step8c_comparison
✓ step8c_classifier
✓ step8c_summary

No new inference.
No embeddings recomputed.
No FAISS rebuild.

In [92]:
# ============================================================
# STEP 8D — FINAL PROJECT VERDICT & PRODUCTION CONFIGURATION
# ============================================================

import pandas as pd
import numpy as np

print("=" * 75)
print("STEP 8D — FINAL PROJECT VERDICT & PRODUCTION CONFIGURATION")
print("=" * 75)


# ------------------------------------------------------------
# 1. Final production architecture
# ------------------------------------------------------------

print("\n[1/7] Final production architecture...")

production_architecture = [
    "Arabic User Query",
    "E5 Query Embedding — intfloat/multilingual-e5-base",
    "FAISS Inner-Product Search — Top-10",
    "TF-IDF + LinearSVC Intent Classification",
    "Predicted Question Type",
    "Intent-aware Candidate Reranking",
    "Final Top-K Context Selection",
    "Grounded Answer Generation"
]

for i, component in enumerate(
    production_architecture,
    start=1
):
    print(f"{i}. {component}")


# ------------------------------------------------------------
# 2. Final model configuration
# ------------------------------------------------------------

print("\n[2/7] Final model configuration...")

final_config = {
    "embedding_model":
        "intfloat/multilingual-e5-base",

    "embedding_dimension":
        768,

    "query_prefix":
        "query:",

    "passage_prefix":
        "passage:",

    "vector_index":
        "FAISS IndexFlatIP",

    "similarity":
        "Cosine similarity via normalized inner product",

    "retrieval_top_k":
        10,

    "intent_classifier":
        "TF-IDF char n-grams + LinearSVC",

    "tfidf_ngram_range":
        "(3, 5)",

    "tfidf_min_df":
        2,

    "tfidf_max_features":
        300000,

    "tfidf_sublinear_tf":
        True,

    "linear_svc_C":
        1.0,

    "reranking":
        "E5 score + alpha × intent_match",

    "observed_diagnostic_alpha":
        0.03
}

for key, value in final_config.items():
    print(f"{key:28s}: {value}")


# ------------------------------------------------------------
# 3. Production vs diagnostic components
# ------------------------------------------------------------

print("\n[3/7] Production vs diagnostic components...")

deployment_status = pd.DataFrame([
    {
        "component":
            "multilingual-e5-base",

        "status":
            "PRODUCTION",

        "reason":
            "Retrieval backbone"
    },
    {
        "component":
            "FAISS IndexFlatIP",

        "status":
            "PRODUCTION",

        "reason":
            "Fast vector retrieval"
    },
    {
        "component":
            "TF-IDF + LinearSVC",

        "status":
            "PRODUCTION",

        "reason":
            "89.60% intent classification accuracy"
    },
    {
        "component":
            "Predicted-intent reranking",

        "status":
            "PRODUCTION CANDIDATE",

        "reason":
            "+33.20 pp Unique Top-3 intent alignment"
    },
    {
        "component":
            "BGE reranker",

        "status":
            "NOT SELECTED",

        "reason":
            "Only +1.00 pp Unique Top-3 intent gain"
    },
    {
        "component":
            "Oracle intent reranking",

        "status":
            "DIAGNOSTIC ONLY",

        "reason":
            "Uses ground-truth Test intent"
    }
])

print(
    deployment_status.to_string(
        index=False
    )
)


# ------------------------------------------------------------
# 4. Final evaluation metrics
# ------------------------------------------------------------

print("\n[4/7] Final evaluation metrics...")

final_metrics = pd.DataFrame([
    {
        "metric":
            "Train records",

        "value":
            27427,

        "type":
            "Dataset"
    },
    {
        "metric":
            "Test records",

        "value":
            500,

        "type":
            "Dataset"
    },
    {
        "metric":
            "Train chunks",

        "value":
            164456,

        "type":
            "Corpus"
    },
    {
        "metric":
            "Unique chunk texts",

        "value":
            41179,

        "type":
            "Corpus"
    },
    {
        "metric":
            "Duplicate slot rate",

        "value":
            74.96,

        "type":
            "Corpus diagnostic"
    },
    {
        "metric":
            "E5 Top-1 mean similarity",

        "value":
            0.8667,

        "type":
            "Retrieval diagnostic"
    },
    {
        "metric":
            "Top-1 same-domain",

        "value":
            53.00,

        "type":
            "Alignment diagnostic"
    },
    {
        "metric":
            "Top-3 domain coverage",

        "value":
            65.80,

        "type":
            "Alignment diagnostic"
    },
    {
        "metric":
            "Baseline Unique Top-3 intent",

        "value":
            46.60,

        "type":
            "Alignment diagnostic"
    },
    {
        "metric":
            "BGE Unique Top-3 intent",

        "value":
            47.60,

        "type":
            "Alignment diagnostic"
    },
    {
        "metric":
            "Intent classifier accuracy",

        "value":
            89.60,

        "type":
            "Held-out classification"
    },
    {
        "metric":
            "Intent classifier Macro F1",

        "value":
            89.46,

        "type":
            "Held-out classification"
    },
    {
        "metric":
            "Predicted-intent Unique Top-3",

        "value":
            79.80,

        "type":
            "Alignment diagnostic"
    },
    {
        "metric":
            "Predicted-intent gain",

        "value":
            33.20,

        "type":
            "Improvement (pp)"
    },
    {
        "metric":
            "Oracle Unique Top-3",

        "value":
            85.20,

        "type":
            "Upper-bound diagnostic"
    },
    {
        "metric":
            "Gap to Oracle",

        "value":
            5.40,

        "type":
            "Gap (pp)"
    },
    {
        "metric":
            "Reliable proxy mappings",

        "value":
            174,

        "type":
            "Proxy evaluation"
    },
    {
        "metric":
            "Proxy Recall@10",

        "value":
            4.02,

        "type":
            "Proxy diagnostic"
    }
])

print(
    final_metrics.to_string(
        index=False
    )
)


# ------------------------------------------------------------
# 5. Critical methodological limitations
# ------------------------------------------------------------

print("\n[5/7] Critical methodological limitations...")

limitations = [
    "Train/Test companies are disjoint.",
    "Therefore exact Test gold chunks are not present in the Train FAISS index.",
    "Exact Gold Recall@K against the Train index is structurally unavailable.",
    "Proxy retrieval evaluation covers only independently validated reliable mappings.",
    "Only 174/465 gold chunks received reliable proxy mappings.",
    "Proxy Recall@K must not be reported as official Gold Recall@K.",
    "Intent-alignment metrics measure candidate relevance by question type, not answer correctness.",
    "Oracle intent reranking is an upper-bound diagnostic only.",
    "Alpha=0.03 is the best observed diagnostic setting, not formally tuned on a separate validation set.",
    "A final production release should tune alpha on a dedicated validation split."
]

for i, limitation in enumerate(
    limitations,
    start=1
):
    print(f"{i}. {limitation}")


# ------------------------------------------------------------
# 6. Final recommendation
# ------------------------------------------------------------

print("\n[6/7] Final recommendation...")

final_recommendation = {
    "retrieval_backbone":
        "intfloat/multilingual-e5-base",

    "vector_database":
        "FAISS IndexFlatIP",

    "retrieval_candidates":
        "Top-10",

    "intent_model":
        "TF-IDF + LinearSVC",

    "intent_accuracy":
        "89.60%",

    "intent_macro_f1":
        "89.46%",

    "reranking_strategy":
        "Predicted-intent reranking",

    "observed_alpha":
        0.03,

    "unique_top3_intent":
        "79.80%",

    "gain_over_baseline":
        "+33.20 pp",

    "oracle_ceiling":
        "85.20%",

    "gap_to_oracle":
        "5.40 pp",

    "bge_decision":
        "Do not include in default pipeline"
}

for key, value in final_recommendation.items():
    print(f"{key:28s}: {value}")


# ------------------------------------------------------------
# 7. Save final project artifacts
# ------------------------------------------------------------

print("\n[7/7] Saving final Step 8D artifacts...")

step8d_architecture = production_architecture
step8d_config = final_config
step8d_deployment_status = deployment_status
step8d_metrics = final_metrics
step8d_limitations = limitations
step8d_recommendation = final_recommendation


print("\n" + "=" * 75)
print("STEP 8D COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ step8d_architecture")
print("✓ step8d_config")
print("✓ step8d_deployment_status")
print("✓ step8d_metrics")
print("✓ step8d_limitations")
print("✓ step8d_recommendation")

print("\nFINAL VERDICT:")
print("E5 + FAISS + Intent Classifier + Predicted-Intent Reranking")

print("\nNo new inference.")
print("No embeddings recomputed.")
print("No FAISS rebuild.")

===========================================================================
STEP 8D — FINAL PROJECT VERDICT & PRODUCTION CONFIGURATION
===========================================================================

[1/7] Final production architecture...
1. Arabic User Query
2. E5 Query Embedding — intfloat/multilingual-e5-base
3. FAISS Inner-Product Search — Top-10
4. TF-IDF + LinearSVC Intent Classification
5. Predicted Question Type
6. Intent-aware Candidate Reranking
7. Final Top-K Context Selection
8. Grounded Answer Generation

[2/7] Final model configuration...
embedding_model             : intfloat/multilingual-e5-base
embedding_dimension         : 768
query_prefix                : query:
passage_prefix              : passage:
vector_index                : FAISS IndexFlatIP
similarity                  : Cosine similarity via normalized inner product
retrieval_top_k             : 10
intent_classifier           : TF-IDF char n-grams + LinearSVC
tfidf_ngram_range           : (3, 5)
tfidf_min_df                : 2
tfidf_max_features          : 300000
tfidf_sublinear_tf          : True
linear_svc_C                : 1.0
reranking                   : E5 score + alpha × intent_match
observed_diagnostic_alpha   : 0.03

[3/7] Production vs diagnostic components...
                 component               status                                  reason
      multilingual-e5-base           PRODUCTION                      Retrieval backbone
         FAISS IndexFlatIP           PRODUCTION                   Fast vector retrieval
        TF-IDF + LinearSVC           PRODUCTION   89.60% intent classification accuracy
Predicted-intent reranking PRODUCTION CANDIDATE +33.20 pp Unique Top-3 intent alignment
              BGE reranker         NOT SELECTED  Only +1.00 pp Unique Top-3 intent gain
   Oracle intent reranking      DIAGNOSTIC ONLY           Uses ground-truth Test intent

[4/7] Final evaluation metrics...
                       metric       value                    type
                Train records  27427.0000                 Dataset
                 Test records    500.0000                 Dataset
                 Train chunks 164456.0000                  Corpus
           Unique chunk texts  41179.0000                  Corpus
          Duplicate slot rate     74.9600       Corpus diagnostic
     E5 Top-1 mean similarity      0.8667    Retrieval diagnostic
            Top-1 same-domain     53.0000    Alignment diagnostic
        Top-3 domain coverage     65.8000    Alignment diagnostic
 Baseline Unique Top-3 intent     46.6000    Alignment diagnostic
      BGE Unique Top-3 intent     47.6000    Alignment diagnostic
   Intent classifier accuracy     89.6000 Held-out classification
   Intent classifier Macro F1     89.4600 Held-out classification
Predicted-intent Unique Top-3     79.8000    Alignment diagnostic
        Predicted-intent gain     33.2000        Improvement (pp)
          Oracle Unique Top-3     85.2000  Upper-bound diagnostic
                Gap to Oracle      5.4000                Gap (pp)
      Reliable proxy mappings    174.0000        Proxy evaluation
              Proxy Recall@10      4.0200        Proxy diagnostic

[5/7] Critical methodological limitations...
1. Train/Test companies are disjoint.
2. Therefore exact Test gold chunks are not present in the Train FAISS index.
3. Exact Gold Recall@K against the Train index is structurally unavailable.
4. Proxy retrieval evaluation covers only independently validated reliable mappings.
5. Only 174/465 gold chunks received reliable proxy mappings.
6. Proxy Recall@K must not be reported as official Gold Recall@K.
7. Intent-alignment metrics measure candidate relevance by question type, not answer correctness.
8. Oracle intent reranking is an upper-bound diagnostic only.
9. Alpha=0.03 is the best observed diagnostic setting, not formally tuned on a separate validation set.
10. A final production release should tune alpha on a dedicated validation split.

[6/7] Final recommendation...
retrieval_backbone          : intfloat/multilingual-e5-base
vector_database             : FAISS IndexFlatIP
retrieval_candidates        : Top-10
intent_model                : TF-IDF + LinearSVC
intent_accuracy             : 89.60%
intent_macro_f1             : 89.46%
reranking_strategy          : Predicted-intent reranking
observed_alpha              : 0.03
unique_top3_intent          : 79.80%
gain_over_baseline          : +33.20 pp
oracle_ceiling              : 85.20%
gap_to_oracle               : 5.40 pp
bge_decision                : Do not include in default pipeline

[7/7] Saving final Step 8D artifacts...

===========================================================================
STEP 8D COMPLETED SUCCESSFULLY
===========================================================================
✓ step8d_architecture
✓ step8d_config
✓ step8d_deployment_status
✓ step8d_metrics
✓ step8d_limitations
✓ step8d_recommendation

FINAL VERDICT:
E5 + FAISS + Intent Classifier + Predicted-Intent Reranking

No new inference.
No embeddings recomputed.
No FAISS rebuild.

In [95]:
# ============================================================
# STEP 9A-FIX 2 — SAFE TF-IDF ARTIFACT DISCOVERY
# ============================================================

print("=" * 75)
print("STEP 9A-FIX 2 — SAFE TF-IDF ARTIFACT DISCOVERY")
print("=" * 75)

import os

# Snapshot globals first to avoid:
# RuntimeError: dictionary changed size during iteration
global_items = list(globals().items())

print("\n[1/3] Searching current session...")

tfidf_candidates = []

for name, obj in global_items:

    try:
        obj_type = type(obj).__name__

        if (
            "tfidf" in name.lower()
            or "vectorizer" in name.lower()
            or "tfidf" in obj_type.lower()
            or "vectorizer" in obj_type.lower()
        ):
            tfidf_candidates.append(
                (name, obj_type)
            )

    except Exception:
        continue


if tfidf_candidates:

    for name, obj_type in tfidf_candidates:
        print(
            f"✓ {name:35s} → {obj_type}"
        )

else:
    print(
        "✗ No TF-IDF/vectorizer object found "
        "by name/type."
    )


print("\n[2/3] Inspecting intent_classifier...")

if "intent_classifier" in globals():

    clf = intent_classifier

    print(
        f"✓ Type: {type(clf).__name__}"
    )

    if hasattr(clf, "steps"):

        print("✓ Pipeline detected")

        for step_name, step_obj in clf.steps:
            print(
                f"  - {step_name}: "
                f"{type(step_obj).__name__}"
            )

    else:

        print("✓ Standalone classifier")

        if hasattr(clf, "n_features_in_"):
            print(
                f"  n_features_in_: "
                f"{clf.n_features_in_}"
            )

else:

    print(
        "✗ intent_classifier not found"
    )


print("\n[3/3] Inspecting saved model directory...")

models_dir = "/content/arabic_faq_data/models"

if os.path.exists(models_dir):

    files = sorted(
        os.listdir(models_dir)
    )

    if files:

        for filename in files:

            path = os.path.join(
                models_dir,
                filename
            )

            size_mb = (
                os.path.getsize(path)
                / (1024 ** 2)
            )

            print(
                f"✓ {filename:35s} "
                f"{size_mb:.2f} MB"
            )

    else:

        print(
            "✓ Models directory exists "
            "but is empty."
        )

else:

    print(
        "✓ Models directory does not exist yet."
    )


print("\n" + "=" * 75)
print("STEP 9A-FIX 2 COMPLETED")
print("=" * 75)

print("No retraining.")
print("No inference.")
print("No embeddings recomputed.")
print("No FAISS rebuild.")

===========================================================================
STEP 9A-FIX 2 — SAFE TF-IDF ARTIFACT DISCOVERY
===========================================================================

[1/3] Searching current session...
✓ TfidfVectorizer                     → type
✓ vectorizer                          → TfidfVectorizer
✓ train_tfidf                         → csr_matrix
✓ gold_tfidf                          → csr_matrix
✓ tfidf_candidates                    → list

[2/3] Inspecting intent_classifier...
✓ Type: Pipeline
✓ Pipeline detected
  - tfidf: TfidfVectorizer
  - classifier: LinearSVC

[3/3] Inspecting saved model directory...
✓ Models directory does not exist yet.

===========================================================================
STEP 9A-FIX 2 COMPLETED
===========================================================================
No retraining.
No inference.
No embeddings recomputed.
No FAISS rebuild.

In [96]:
# ============================================================
# STEP 9A — SAVE COMPLETE INTENT CLASSIFICATION PIPELINE
# ============================================================

import os
import joblib

print("=" * 75)
print("STEP 9A — SAVE COMPLETE INTENT CLASSIFICATION PIPELINE")
print("=" * 75)


# ------------------------------------------------------------
# 1. Validate existing pipeline
# ------------------------------------------------------------

print("\n[1/5] Validating existing intent pipeline...")

if "intent_classifier" not in globals():
    raise RuntimeError(
        "intent_classifier is missing. "
        "Do NOT retrain."
    )

intent_pipeline = intent_classifier

print(
    f"✓ Pipeline type: "
    f"{type(intent_pipeline).__name__}"
)

if not hasattr(intent_pipeline, "steps"):
    raise RuntimeError(
        "intent_classifier is not a Pipeline."
    )

print("✓ Pipeline steps:")

for step_name, step_obj in intent_pipeline.steps:
    print(
        f"  - {step_name}: "
        f"{type(step_obj).__name__}"
    )


# ------------------------------------------------------------
# 2. Create production directory
# ------------------------------------------------------------

print("\n[2/5] Creating production model directory...")

models_dir = "/content/arabic_faq_data/models"

os.makedirs(
    models_dir,
    exist_ok=True
)

print(f"✓ {models_dir}")


# ------------------------------------------------------------
# 3. Save complete pipeline
# ------------------------------------------------------------

print("\n[3/5] Saving complete intent pipeline...")

pipeline_path = os.path.join(
    models_dir,
    "intent_classifier.joblib"
)

joblib.dump(
    intent_pipeline,
    pipeline_path
)

print(
    f"✓ Saved: {pipeline_path}"
)


# ------------------------------------------------------------
# 4. Verify saved file
# ------------------------------------------------------------

print("\n[4/5] Verifying saved artifact...")

if not os.path.exists(pipeline_path):
    raise RuntimeError(
        "Pipeline save verification failed."
    )

size_mb = (
    os.path.getsize(pipeline_path)
    / (1024 ** 2)
)

print(
    f"✓ File exists"
)

print(
    f"✓ File size: {size_mb:.2f} MB"
)


# ------------------------------------------------------------
# 5. Reload verification
# ------------------------------------------------------------

print("\n[5/5] Reloading pipeline from disk...")

loaded_intent_pipeline = joblib.load(
    pipeline_path
)

print(
    f"✓ Reloaded type: "
    f"{type(loaded_intent_pipeline).__name__}"
)

print("✓ Reloaded steps:")

for step_name, step_obj in loaded_intent_pipeline.steps:
    print(
        f"  - {step_name}: "
        f"{type(step_obj).__name__}"
    )


print("\n" + "=" * 75)
print("STEP 9A COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ TF-IDF preserved inside Pipeline")
print("✓ LinearSVC preserved inside Pipeline")
print("✓ Complete intent pipeline saved")
print("✓ Complete intent pipeline successfully reloaded")
print("✓ No retraining")
print("✓ No inference")
print("✓ No embeddings recomputed")
print("✓ No FAISS rebuild")

===========================================================================
STEP 9A — SAVE COMPLETE INTENT CLASSIFICATION PIPELINE
===========================================================================

[1/5] Validating existing intent pipeline...
✓ Pipeline type: Pipeline
✓ Pipeline steps:
  - tfidf: TfidfVectorizer
  - classifier: LinearSVC

[2/5] Creating production model directory...
✓ /content/arabic_faq_data/models

[3/5] Saving complete intent pipeline...
✓ Saved: /content/arabic_faq_data/models/intent_classifier.joblib

[4/5] Verifying saved artifact...
✓ File exists
✓ File size: 8.33 MB

[5/5] Reloading pipeline from disk...
✓ Reloaded type: Pipeline
✓ Reloaded steps:
  - tfidf: TfidfVectorizer
  - classifier: LinearSVC

===========================================================================
STEP 9A COMPLETED SUCCESSFULLY
===========================================================================
✓ TF-IDF preserved inside Pipeline
✓ LinearSVC preserved inside Pipeline
✓ Complete intent pipeline saved
✓ Complete intent pipeline successfully reloaded
✓ No retraining
✓ No inference
✓ No embeddings recomputed
✓ No FAISS rebuild

In [97]:
# ============================================================
# STEP 9B — SAVE FAISS CORPUS METADATA
# ============================================================

import os
import pandas as pd

print("=" * 75)
print("STEP 9B — SAVE FAISS CORPUS METADATA")
print("=" * 75)


# ------------------------------------------------------------
# 1. Validate existing artifacts
# ------------------------------------------------------------

print("\n[1/5] Validating existing corpus and FAISS index...")

if "train_corpus" not in globals():
    raise RuntimeError(
        "train_corpus is missing. "
        "Do NOT rebuild it yet."
    )

if "index" not in globals():
    raise RuntimeError(
        "FAISS index is missing. "
        "Do NOT rebuild it."
    )

print(f"✓ Train corpus rows : {len(train_corpus):,}")
print(f"✓ FAISS vectors     : {index.ntotal:,}")

if len(train_corpus) != index.ntotal:
    raise RuntimeError(
        "Corpus/FAISS size mismatch!"
    )

print("✓ Corpus and FAISS index are aligned")


# ------------------------------------------------------------
# 2. Define production metadata columns
# ------------------------------------------------------------

print("\n[2/5] Preparing production metadata...")

metadata_columns = [
    "row_idx",
    "id",
    "company_id",
    "company",
    "domain",
    "country",
    "chunk_idx",
    "chunk_text",
    "question",
    "answer",
    "answerable"
]

missing_columns = [
    col
    for col in metadata_columns
    if col not in train_corpus.columns
]

if missing_columns:
    raise RuntimeError(
        f"Missing metadata columns: {missing_columns}"
    )

train_metadata = train_corpus[
    metadata_columns
].copy()

print(
    f"✓ Metadata columns: "
    f"{len(metadata_columns)}"
)

print(
    f"✓ Metadata rows   : "
    f"{len(train_metadata):,}"
)


# ------------------------------------------------------------
# 3. Validate corpus index alignment
# ------------------------------------------------------------

print("\n[3/5] Validating FAISS index mapping...")

expected_indices = np.arange(
    len(train_metadata)
)

actual_indices = train_metadata.index.to_numpy()

if np.array_equal(
    actual_indices,
    expected_indices
):
    print(
        "✓ Metadata row positions "
        "match FAISS corpus_idx"
    )
else:
    print(
        "⚠ DataFrame index is not sequential."
    )

    train_metadata = (
        train_metadata
        .reset_index(drop=True)
    )

    if np.array_equal(
        train_metadata.index.to_numpy(),
        expected_indices
    ):
        print(
            "✓ Metadata index reset successfully"
        )
    else:
        raise RuntimeError(
            "Could not establish corpus_idx mapping."
        )


# ------------------------------------------------------------
# 4. Save metadata
# ------------------------------------------------------------

print("\n[4/5] Saving metadata...")

data_dir = "/content/arabic_faq_data"

os.makedirs(
    data_dir,
    exist_ok=True
)

metadata_path = os.path.join(
    data_dir,
    "train_chunks_metadata.parquet"
)

train_metadata.to_parquet(
    metadata_path,
    index=False
)

print(
    f"✓ Saved: {metadata_path}"
)


# ------------------------------------------------------------
# 5. Reload and verify
# ------------------------------------------------------------

print("\n[5/5] Reloading and verifying metadata...")

loaded_metadata = pd.read_parquet(
    metadata_path
)

print(
    f"✓ Reloaded rows: "
    f"{len(loaded_metadata):,}"
)

print(
    f"✓ Reloaded columns: "
    f"{len(loaded_metadata.columns)}"
)

if len(loaded_metadata) != index.ntotal:
    raise RuntimeError(
        "Reloaded metadata size does not match FAISS!"
    )

if not loaded_metadata[
    "chunk_idx"
].notna().all():
    raise RuntimeError(
        "Missing chunk_idx detected."
    )

if not loaded_metadata[
    "chunk_text"
].notna().all():
    raise RuntimeError(
        "Missing chunk_text detected."
    )

print(
    "✓ Metadata/FAISS row count verified"
)

print(
    "✓ chunk_idx verified"
)

print(
    "✓ chunk_text verified"
)


print("\n" + "=" * 75)
print("STEP 9B COMPLETED SUCCESSFULLY")
print("=" * 75)

print(
    f"✓ {metadata_path}"
)

print(
    "✓ FAISS corpus_idx → metadata mapping preserved"
)

print(
    "✓ No embeddings recomputed"
)

print(
    "✓ No FAISS rebuild"
)

print(
    "✓ No retraining"
)

print(
    "✓ No inference"
)

===========================================================================
STEP 9B — SAVE FAISS CORPUS METADATA
===========================================================================

[1/5] Validating existing corpus and FAISS index...
✓ Train corpus rows : 164,456
✓ FAISS vectors     : 164,456
✓ Corpus and FAISS index are aligned

[2/5] Preparing production metadata...
✓ Metadata columns: 11
✓ Metadata rows   : 164,456

[3/5] Validating FAISS index mapping...
✓ Metadata row positions match FAISS corpus_idx

[4/5] Saving metadata...
✓ Saved: /content/arabic_faq_data/train_chunks_metadata.parquet

[5/5] Reloading and verifying metadata...
✓ Reloaded rows: 164,456
✓ Reloaded columns: 11
✓ Metadata/FAISS row count verified
✓ chunk_idx verified
✓ chunk_text verified

===========================================================================
STEP 9B COMPLETED SUCCESSFULLY
===========================================================================
✓ /content/arabic_faq_data/train_chunks_metadata.parquet
✓ FAISS corpus_idx → metadata mapping preserved
✓ No embeddings recomputed
✓ No FAISS rebuild
✓ No retraining
✓ No inference

In [98]:
# ============================================================
# STEP 9C — PRODUCTION ARTIFACT LOAD TEST
# ============================================================

import os
import faiss
import joblib
import pandas as pd

print("=" * 75)
print("STEP 9C — PRODUCTION ARTIFACT LOAD TEST")
print("=" * 75)


# ------------------------------------------------------------
# 1. Define production paths
# ------------------------------------------------------------

print("\n[1/6] Checking production files...")

DATA_DIR = "/content/arabic_faq_data"
MODELS_DIR = os.path.join(DATA_DIR, "models")

FAISS_PATH = os.path.join(
    DATA_DIR,
    "train_chunks.faiss"
)

METADATA_PATH = os.path.join(
    DATA_DIR,
    "train_chunks_metadata.parquet"
)

INTENT_PATH = os.path.join(
    MODELS_DIR,
    "intent_classifier.joblib"
)

required_files = {
    "FAISS index": FAISS_PATH,
    "Metadata": METADATA_PATH,
    "Intent pipeline": INTENT_PATH
}

for label, path in required_files.items():

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{label} not found: {path}"
        )

    size_mb = (
        os.path.getsize(path)
        / (1024 ** 2)
    )

    print(
        f"✓ {label:18s}: "
        f"{size_mb:.2f} MB"
    )


# ------------------------------------------------------------
# 2. Load FAISS
# ------------------------------------------------------------

print("\n[2/6] Loading FAISS index...")

production_index = faiss.read_index(
    FAISS_PATH
)

print(
    f"✓ Index type : "
    f"{type(production_index).__name__}"
)

print(
    f"✓ Dimension  : "
    f"{production_index.d}"
)

print(
    f"✓ Vectors    : "
    f"{production_index.ntotal:,}"
)


# ------------------------------------------------------------
# 3. Load metadata
# ------------------------------------------------------------

print("\n[3/6] Loading corpus metadata...")

production_metadata = pd.read_parquet(
    METADATA_PATH
)

print(
    f"✓ Rows       : "
    f"{len(production_metadata):,}"
)

print(
    f"✓ Columns    : "
    f"{len(production_metadata.columns)}"
)

print(
    f"✓ First columns: "
    f"{list(production_metadata.columns[:5])}"
)


# ------------------------------------------------------------
# 4. Load intent pipeline
# ------------------------------------------------------------

print("\n[4/6] Loading intent pipeline...")

production_intent_model = joblib.load(
    INTENT_PATH
)

print(
    f"✓ Type: "
    f"{type(production_intent_model).__name__}"
)

if hasattr(
    production_intent_model,
    "steps"
):

    print("✓ Pipeline steps:")

    for step_name, step_obj in (
        production_intent_model.steps
    ):
        print(
            f"  - {step_name}: "
            f"{type(step_obj).__name__}"
        )


# ------------------------------------------------------------
# 5. Cross-artifact integrity checks
# ------------------------------------------------------------

print("\n[5/6] Running cross-artifact integrity checks...")

# FAISS ↔ metadata
if (
    production_index.ntotal
    != len(production_metadata)
):

    raise RuntimeError(
        "FAISS vector count does not "
        "match metadata row count!"
    )

print(
    "✓ FAISS ↔ metadata row count"
)

# Expected embedding dimension
if production_index.d != 768:

    raise RuntimeError(
        f"Unexpected FAISS dimension: "
        f"{production_index.d}"
    )

print(
    "✓ FAISS dimension = 768"
)

# Required metadata
required_metadata_columns = [
    "row_idx",
    "id",
    "company_id",
    "company",
    "domain",
    "country",
    "chunk_idx",
    "chunk_text",
    "question",
    "answer",
    "answerable"
]

missing_metadata = [
    col
    for col in required_metadata_columns
    if col not in production_metadata.columns
]

if missing_metadata:

    raise RuntimeError(
        f"Missing metadata columns: "
        f"{missing_metadata}"
    )

print(
    "✓ Required metadata columns"
)

# Corpus index alignment
expected_indices = range(
    len(production_metadata)
)

if not all(
    production_metadata.index
    == pd.RangeIndex(
        start=0,
        stop=len(production_metadata)
    )
):

    raise RuntimeError(
        "Metadata index is not sequential."
    )

print(
    "✓ Metadata index alignment"
)


# ------------------------------------------------------------
# 6. Final load test report
# ------------------------------------------------------------

print("\n[6/6] Production artifact load test summary...")

print(
    f"FAISS vectors       : "
    f"{production_index.ntotal:,}"
)

print(
    f"Metadata rows       : "
    f"{len(production_metadata):,}"
)

print(
    f"Embedding dimension : "
    f"{production_index.d}"
)

print(
    f"Intent model        : "
    f"{type(production_intent_model).__name__}"
)

print("\n" + "=" * 75)
print("STEP 9C COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ FAISS loaded from disk")
print("✓ Metadata loaded from disk")
print("✓ Intent pipeline loaded from disk")
print("✓ Cross-artifact integrity verified")
print("✓ No retraining")
print("✓ No inference")
print("✓ No embeddings recomputed")
print("✓ No FAISS rebuild")

===========================================================================
STEP 9C — PRODUCTION ARTIFACT LOAD TEST
===========================================================================

[1/6] Checking production files...
✓ FAISS index       : 481.80 MB
✓ Metadata          : 17.62 MB
✓ Intent pipeline   : 8.33 MB

[2/6] Loading FAISS index...
✓ Index type : IndexFlatIP
✓ Dimension  : 768
✓ Vectors    : 164,456

[3/6] Loading corpus metadata...
✓ Rows       : 164,456
✓ Columns    : 11
✓ First columns: ['row_idx', 'id', 'company_id', 'company', 'domain']

[4/6] Loading intent pipeline...
✓ Type: Pipeline
✓ Pipeline steps:
  - tfidf: TfidfVectorizer
  - classifier: LinearSVC

[5/6] Running cross-artifact integrity checks...
✓ FAISS ↔ metadata row count
✓ FAISS dimension = 768
✓ Required metadata columns
✓ Metadata index alignment

[6/6] Production artifact load test summary...
FAISS vectors       : 164,456
Metadata rows       : 164,456
Embedding dimension : 768
Intent model        : Pipeline

===========================================================================
STEP 9C COMPLETED SUCCESSFULLY
===========================================================================
✓ FAISS loaded from disk
✓ Metadata loaded from disk
✓ Intent pipeline loaded from disk
✓ Cross-artifact integrity verified
✓ No retraining
✓ No inference
✓ No embeddings recomputed
✓ No FAISS rebuild

In [99]:
# ============================================================
# STEP 9D-1 — CREATE PRODUCTION RETRIEVAL MODULE
# ============================================================

import os
from pathlib import Path

print("=" * 75)
print("STEP 9D-1 — CREATE PRODUCTION RETRIEVAL MODULE")
print("=" * 75)

# ------------------------------------------------------------
# 1. Create project structure
# ------------------------------------------------------------

print("\n[1/4] Creating production project structure...")

PROJECT_DIR = Path("/content/arabic_faq_rag")
SRC_DIR = PROJECT_DIR / "src"

SRC_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print(f"✓ Project : {PROJECT_DIR}")
print(f"✓ Source  : {SRC_DIR}")


# ------------------------------------------------------------
# 2. Create retrieval.py
# ------------------------------------------------------------

print("\n[2/4] Creating retrieval.py...")

retrieval_code = r'''
import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer


class ArabicFAQRetriever:
    """
    Production Arabic FAQ semantic retriever.

    Pipeline:
        User Query
            ↓
        multilingual-e5-base
            ↓
        FAISS IndexFlatIP
            ↓
        Top-K FAQ chunks
    """

    def __init__(
        self,
        faiss_path: str,
        metadata_path: str,
        model_name: str = "intfloat/multilingual-e5-base",
        device: str = "cpu",
    ):
        self.faiss_path = faiss_path
        self.metadata_path = metadata_path
        self.model_name = model_name
        self.device = device

        # Load FAISS index
        self.index = faiss.read_index(
            self.faiss_path
        )

        # Load metadata
        self.metadata = pd.read_parquet(
            self.metadata_path
        )

        # Validate FAISS ↔ metadata alignment
        if self.index.ntotal != len(self.metadata):
            raise ValueError(
                "FAISS index size does not match "
                "metadata row count."
            )

        # Load embedding model
        self.model = SentenceTransformer(
            self.model_name,
            device=self.device
        )

        # Validate embedding dimension
        if self.index.d != self.model.get_sentence_embedding_dimension():
            raise ValueError(
                "FAISS dimension does not match "
                "embedding model dimension."
            )

    def search(
        self,
        query: str,
        top_k: int = 10,
    ):
        """
        Retrieve top-k FAQ chunks for an Arabic query.

        Returns:
            list[dict]
        """

        if not isinstance(query, str):
            raise TypeError(
                "query must be a string."
            )

        query = query.strip()

        if not query:
            raise ValueError(
                "query cannot be empty."
            )

        top_k = min(
            int(top_k),
            self.index.ntotal
        )

        # E5 query prefix
        query_text = f"query: {query}"

        # Encode query
        query_embedding = self.model.encode(
            [query_text],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        query_embedding = (
            query_embedding
            .astype("float32")
        )

        # FAISS search
        scores, indices = self.index.search(
            query_embedding,
            top_k
        )

        results = []

        for rank, (
            score,
            corpus_idx
        ) in enumerate(
            zip(
                scores[0],
                indices[0]
            ),
            start=1
        ):

            if corpus_idx < 0:
                continue

            row = self.metadata.iloc[
                int(corpus_idx)
            ]

            results.append({
                "rank": rank,
                "corpus_idx": int(corpus_idx),
                "score": float(score),
                "id": row["id"],
                "company_id": row["company_id"],
                "company": row["company"],
                "domain": row["domain"],
                "country": row["country"],
                "chunk_idx": int(row["chunk_idx"]),
                "chunk_text": row["chunk_text"],
                "question": row["question"],
                "answer": row["answer"],
                "answerable": bool(row["answerable"]),
            })

        return results
'''

retrieval_path = SRC_DIR / "retrieval.py"

retrieval_path.write_text(
    retrieval_code,
    encoding="utf-8"
)

print(f"✓ Created: {retrieval_path}")


# ------------------------------------------------------------
# 3. Syntax validation
# ------------------------------------------------------------

print("\n[3/4] Validating Python syntax...")

compile(
    retrieval_code,
    str(retrieval_path),
    "exec"
)

print("✓ retrieval.py syntax is valid")


# ------------------------------------------------------------
# 4. Final verification
# ------------------------------------------------------------

print("\n[4/4] Verifying file...")

if not retrieval_path.exists():
    raise RuntimeError(
        "retrieval.py was not created."
    )

file_size_kb = (
    retrieval_path.stat().st_size
    / 1024
)

print(
    f"✓ File size: "
    f"{file_size_kb:.2f} KB"
)

print("\n" + "=" * 75)
print("STEP 9D-1 COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ Production retrieval module created")
print("✓ E5 query prefix preserved")
print("✓ Normalized embeddings preserved")
print("✓ FAISS Top-K search preserved")
print("✓ FAISS ↔ metadata validation included")
print("✓ No training")
print("✓ No corpus embedding")
print("✓ No FAISS rebuild")

===========================================================================
STEP 9D-1 — CREATE PRODUCTION RETRIEVAL MODULE
===========================================================================

[1/4] Creating production project structure...
✓ Project : /content/arabic_faq_rag
✓ Source  : /content/arabic_faq_rag/src

[2/4] Creating retrieval.py...
✓ Created: /content/arabic_faq_rag/src/retrieval.py

[3/4] Validating Python syntax...
✓ retrieval.py syntax is valid

[4/4] Verifying file...
✓ File size: 3.51 KB

===========================================================================
STEP 9D-1 COMPLETED SUCCESSFULLY
===========================================================================
✓ Production retrieval module created
✓ E5 query prefix preserved
✓ Normalized embeddings preserved
✓ FAISS Top-K search preserved
✓ FAISS ↔ metadata validation included
✓ No training
✓ No corpus embedding
✓ No FAISS rebuild

In [101]:
# ============================================================================
# STEP 9D-2A — FIX PRODUCTION METADATA WITH QUESTION TYPE
# ============================================================================

from pathlib import Path
import pandas as pd

print("=" * 75)
print("STEP 9D-2A — FIX PRODUCTION METADATA")
print("=" * 75)

DATA_DIR = Path("/content/arabic_faq_data")

metadata_path = DATA_DIR / "train_chunks_metadata.parquet"
output_path = DATA_DIR / "train_chunks_metadata_v2.parquet"

# --------------------------------------------------------------------------
# 1. Load existing production metadata
# --------------------------------------------------------------------------
metadata_df = pd.read_parquet(metadata_path)

print(f"\nOriginal metadata shape: {metadata_df.shape}")

# --------------------------------------------------------------------------
# 2. Verify train_corpus exists
# --------------------------------------------------------------------------
if "train_corpus" not in globals():
    raise RuntimeError(
        "train_corpus is not available in memory."
    )

if "train_df" not in globals():
    raise RuntimeError(
        "train_df is not available in memory."
    )

required_corpus_cols = ["row_idx"]
required_train_cols = ["question_type"]

for col in required_corpus_cols:
    if col not in train_corpus.columns:
        raise RuntimeError(
            f"train_corpus is missing required column: {col}"
        )

for col in required_train_cols:
    if col not in train_df.columns:
        raise RuntimeError(
            f"train_df is missing required column: {col}"
        )

# --------------------------------------------------------------------------
# 3. Create row_idx -> question_type mapping
# --------------------------------------------------------------------------
row_to_intent = train_df["question_type"].to_dict()

# Map each corpus row to its original train question_type
metadata_v2 = metadata_df.copy()

metadata_v2["question_type"] = (
    metadata_v2["row_idx"]
    .map(row_to_intent)
)

# --------------------------------------------------------------------------
# 4. Validation
# --------------------------------------------------------------------------
missing_intents = metadata_v2["question_type"].isna().sum()

print(f"Missing question_type values: {missing_intents}")

if missing_intents > 0:
    missing_rows = metadata_v2.loc[
        metadata_v2["question_type"].isna(),
        "row_idx"
    ].head(10).tolist()

    raise RuntimeError(
        f"Could not map question_type for {missing_intents} rows. "
        f"Example row_idx values: {missing_rows}"
    )

# Preserve exact FAISS corpus_idx -> metadata row mapping
metadata_v2 = metadata_v2.reset_index(drop=True)

# --------------------------------------------------------------------------
# 5. Save
# --------------------------------------------------------------------------
metadata_v2.to_parquet(
    output_path,
    index=False
)

# --------------------------------------------------------------------------
# 6. Reload verification
# --------------------------------------------------------------------------
reloaded = pd.read_parquet(output_path)

print(f"\nNew metadata shape: {reloaded.shape}")
print(f"Saved to: {output_path}")
print(f"Question types: {reloaded['question_type'].nunique()}")
print(f"Missing question types: {reloaded['question_type'].isna().sum()}")

print("\nColumns:")
for i, col in enumerate(reloaded.columns, 1):
    print(f"{i:2d}. {col}")

# Critical integrity checks
assert len(reloaded) == len(metadata_df) == 164456
assert "question_type" in reloaded.columns
assert reloaded["question_type"].isna().sum() == 0

# Verify corpus_idx mapping remains positional
assert reloaded.iloc[0]["row_idx"] == metadata_df.iloc[0]["row_idx"]
assert reloaded.iloc[-1]["row_idx"] == metadata_df.iloc[-1]["row_idx"]

print("\n" + "=" * 75)
print("STEP 9D-2A COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ question_type added")
print("✓ 164,456 metadata rows preserved")
print("✓ FAISS ↔ metadata positional mapping preserved")
print("✓ No embeddings recomputed")
print("✓ No FAISS rebuild")
print("✓ No model retraining")

===========================================================================
STEP 9D-2A — FIX PRODUCTION METADATA
===========================================================================

Original metadata shape: (164456, 11)
Missing question_type values: 0

New metadata shape: (164456, 12)
Saved to: /content/arabic_faq_data/train_chunks_metadata_v2.parquet
Question types: 8
Missing question types: 0

Columns:
 1. row_idx
 2. id
 3. company_id
 4. company
 5. domain
 6. country
 7. chunk_idx
 8. chunk_text
 9. question
10. answer
11. answerable
12. question_type

===========================================================================
STEP 9D-2A COMPLETED SUCCESSFULLY
===========================================================================
✓ question_type added
✓ 164,456 metadata rows preserved
✓ FAISS ↔ metadata positional mapping preserved
✓ No embeddings recomputed
✓ No FAISS rebuild
✓ No model retraining

In [102]:
# ============================================================================
# STEP 9D-2B — CREATE PRODUCTION INTENT MODULE
# ============================================================================

from pathlib import Path

PROJECT_DIR = Path("/content/arabic_faq_rag")
SRC_DIR = PROJECT_DIR / "src"

intent_py = r'''
from pathlib import Path
import joblib


class ArabicFAQIntentClassifier:
    """
    Production wrapper for the trained Arabic FAQ question-type classifier.

    Model:
        TF-IDF (char n-grams 3-5) + LinearSVC

    The complete sklearn Pipeline is loaded from disk.
    """

    def __init__(self, model_path=None):
        if model_path is None:
            model_path = (
                Path("/content/arabic_faq_data/models")
                / "intent_classifier.joblib"
            )

        self.model_path = Path(model_path)

        if not self.model_path.exists():
            raise FileNotFoundError(
                f"Intent classifier not found: {self.model_path}"
            )

        self.model = joblib.load(self.model_path)

        if not hasattr(self.model, "predict"):
            raise TypeError(
                "Loaded intent model does not implement predict()."
            )

    def predict(self, query):
        """
        Predict the question type for a single Arabic query.
        """
        if not isinstance(query, str):
            raise TypeError("query must be a string.")

        query = query.strip()

        if not query:
            raise ValueError("query cannot be empty.")

        prediction = self.model.predict([query])

        return str(prediction[0])

    def predict_batch(self, queries):
        """
        Predict question types for multiple queries.
        """
        if not isinstance(queries, (list, tuple)):
            raise TypeError("queries must be a list or tuple.")

        cleaned = []

        for query in queries:
            if not isinstance(query, str):
                raise TypeError("Every query must be a string.")

            query = query.strip()

            if not query:
                raise ValueError("Queries cannot contain empty strings.")

            cleaned.append(query)

        predictions = self.model.predict(cleaned)

        return [str(x) for x in predictions]

    @property
    def classes(self):
        """
        Return the classifier's known question-type classes.
        """
        if hasattr(self.model, "classes_"):
            return [str(x) for x in self.model.classes_]

        # sklearn Pipeline stores classifier classes inside the final step
        if hasattr(self.model, "named_steps"):
            classifier = self.model.named_steps.get("classifier")

            if classifier is not None and hasattr(classifier, "classes_"):
                return [str(x) for x in classifier.classes_]

        return []


if __name__ == "__main__":
    # Lightweight standalone sanity test
    classifier = ArabicFAQIntentClassifier()

    test_query = "أريد إلغاء اشتراكي نهائياً"

    prediction = classifier.predict(test_query)

    print("Intent classifier loaded successfully.")
    print(f"Test query: {test_query}")
    print(f"Predicted intent: {prediction}")
    print(f"Known classes: {len(classifier.classes)}")
'''

intent_path = SRC_DIR / "intent.py"
intent_path.write_text(intent_py, encoding="utf-8")

print("=" * 75)
print("STEP 9D-2B — CREATE PRODUCTION INTENT MODULE")
print("=" * 75)

print(f"\n✓ Created: {intent_path}")
print(f"✓ File size: {intent_path.stat().st_size / 1024:.2f} KB")

# Syntax validation
import py_compile

py_compile.compile(
    str(intent_path),
    doraise=True
)

print("✓ intent.py syntax is valid")

# Import validation
import sys
sys.path.insert(0, str(SRC_DIR))

from intent import ArabicFAQIntentClassifier

classifier = ArabicFAQIntentClassifier()

print("✓ Intent classifier loaded from disk")
print(f"✓ Number of classes: {len(classifier.classes)}")

print("\nKnown intents:")
for i, intent in enumerate(classifier.classes, 1):
    print(f"  {i}. {intent}")

print("\n" + "=" * 75)
print("STEP 9D-2B COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ Production intent module created")
print("✓ Saved classifier loaded successfully")
print("✓ Original TF-IDF + LinearSVC pipeline preserved")
print("✓ No training")
print("✓ No retraining")

===========================================================================
STEP 9D-2B — CREATE PRODUCTION INTENT MODULE
===========================================================================

✓ Created: /content/arabic_faq_rag/src/intent.py
✓ File size: 2.90 KB
✓ intent.py syntax is valid
✓ Intent classifier loaded from disk
✓ Number of classes: 8

Known intents:
  1. account or subscription management (upgrade, renewal, closing)
  2. availability, coverage or delivery time
  3. billing dispute or a charge on the account
  4. comparison between two products or plans
  5. policy (refund, cancellation, warranty, exchange)
  6. pricing or fees
  7. product or plan details (specs, what is included)
  8. troubleshooting a problem with the product or service

===========================================================================
STEP 9D-2B COMPLETED SUCCESSFULLY
===========================================================================
✓ Production intent module created
✓ Saved classifier loaded successfully
✓ Original TF-IDF + LinearSVC pipeline preserved
✓ No training
✓ No retraining

In [103]:
# ============================================================================
# STEP 9D-3 — CREATE PRODUCTION RERANKING MODULE
# ============================================================================

from pathlib import Path
import py_compile
import sys

PROJECT_DIR = Path("/content/arabic_faq_rag")
SRC_DIR = PROJECT_DIR / "src"

reranking_py = r'''
class IntentAwareReranker:
    """
    Intent-aware reranker for Arabic FAQ retrieval.

    Final score:
        final_score = E5_score + alpha * intent_match

    Where:
        intent_match = 1 if candidate intent matches predicted query intent
        intent_match = 0 otherwise

    The default alpha (0.03) comes from the observed diagnostic experiment.
    It should be treated as a deployment candidate, not as a formally
    validation-tuned hyperparameter.
    """

    def __init__(self, alpha=0.03):
        if not isinstance(alpha, (int, float)):
            raise TypeError("alpha must be numeric.")

        if alpha < 0:
            raise ValueError("alpha must be >= 0.")

        self.alpha = float(alpha)

    def rerank(self, candidates, predicted_intent, top_k=None):
        """
        Rerank retrieved candidates using predicted question type.

        Parameters
        ----------
        candidates : list[dict]
            Retrieval candidates returned by ArabicFAQRetriever.search().

        predicted_intent : str
            Intent predicted by ArabicFAQIntentClassifier.

        top_k : int or None
            Number of candidates to return.
            If None, return all candidates.

        Returns
        -------
        list[dict]
            Reranked candidates with:
                - original E5 score
                - intent_match
                - final_score
                - rerank_rank
        """

        if not isinstance(candidates, list):
            raise TypeError("candidates must be a list.")

        if not isinstance(predicted_intent, str):
            raise TypeError("predicted_intent must be a string.")

        predicted_intent = predicted_intent.strip()

        if not predicted_intent:
            raise ValueError("predicted_intent cannot be empty.")

        if not candidates:
            return []

        reranked = []

        for candidate in candidates:
            if not isinstance(candidate, dict):
                raise TypeError("Each candidate must be a dictionary.")

            if "score" not in candidate:
                raise KeyError("Candidate is missing 'score'.")

            if "question_type" not in candidate:
                raise KeyError(
                    "Candidate is missing 'question_type'. "
                    "Production metadata must include question_type."
                )

            e5_score = float(candidate["score"])

            candidate_intent = str(
                candidate["question_type"]
            ).strip()

            intent_match = int(
                candidate_intent == predicted_intent
            )

            final_score = (
                e5_score +
                self.alpha * intent_match
            )

            item = dict(candidate)

            item["e5_score"] = e5_score
            item["candidate_intent"] = candidate_intent
            item["intent_match"] = intent_match
            item["final_score"] = final_score

            reranked.append(item)

        # Stable deterministic sorting:
        # 1. Higher final score
        # 2. Higher original E5 score
        # 3. Lower original rank
        reranked.sort(
            key=lambda x: (
                x["final_score"],
                x["e5_score"],
                -int(x.get("rank", 10**9))
            ),
            reverse=True
        )

        for new_rank, item in enumerate(reranked, 1):
            item["rerank_rank"] = new_rank

        if top_k is not None:
            if not isinstance(top_k, int):
                raise TypeError("top_k must be an integer or None.")

            if top_k <= 0:
                raise ValueError("top_k must be > 0.")

            reranked = reranked[:top_k]

        return reranked


if __name__ == "__main__":
    # Lightweight standalone sanity test
    reranker = IntentAwareReranker(alpha=0.03)

    candidates = [
        {
            "rank": 1,
            "score": 0.86,
            "question_type": "pricing or fees"
        },
        {
            "rank": 2,
            "score": 0.87,
            "question_type": "policy (refund, cancellation, warranty, exchange)"
        }
    ]

    predicted_intent = "pricing or fees"

    results = reranker.rerank(
        candidates,
        predicted_intent,
        top_k=2
    )

    print("Reranker loaded successfully.")

    for result in results:
        print(
            result["rerank_rank"],
            result["candidate_intent"],
            result["e5_score"],
            result["final_score"]
        )
'''

reranking_path = SRC_DIR / "reranking.py"

reranking_path.write_text(
    reranking_py,
    encoding="utf-8"
)

print("=" * 75)
print("STEP 9D-3 — CREATE PRODUCTION RERANKING MODULE")
print("=" * 75)

print(f"\n✓ Created: {reranking_path}")
print(
    f"✓ File size: "
    f"{reranking_path.stat().st_size / 1024:.2f} KB"
)

# --------------------------------------------------------------------------
# Syntax validation
# --------------------------------------------------------------------------
py_compile.compile(
    str(reranking_path),
    doraise=True
)

print("✓ reranking.py syntax is valid")

# --------------------------------------------------------------------------
# Import validation
# --------------------------------------------------------------------------
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from reranking import IntentAwareReranker

reranker = IntentAwareReranker(alpha=0.03)

# --------------------------------------------------------------------------
# Functional sanity test
# --------------------------------------------------------------------------
test_candidates = [
    {
        "rank": 1,
        "score": 0.86,
        "question_type": "pricing or fees"
    },
    {
        "rank": 2,
        "score": 0.87,
        "question_type": "policy (refund, cancellation, warranty, exchange)"
    }
]

test_intent = "pricing or fees"

test_results = reranker.rerank(
    test_candidates,
    test_intent,
    top_k=2
)

assert test_results[0]["candidate_intent"] == test_intent
assert test_results[0]["intent_match"] == 1
assert test_results[0]["final_score"] == 0.89

print("✓ Reranker imported successfully")
print("✓ Alpha: 0.03")
print("✓ Intent-aware scoring verified")
print("✓ Matching candidate receives +0.03")
print("✓ Deterministic ranking verified")

print("\n" + "=" * 75)
print("STEP 9D-3 COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ Production reranking module created")
print("✓ E5 score preserved")
print("✓ Predicted-intent matching preserved")
print("✓ Alpha = 0.03")
print("✓ No training")
print("✓ No embeddings")
print("✓ No FAISS rebuild")

===========================================================================
STEP 9D-3 — CREATE PRODUCTION RERANKING MODULE
===========================================================================

✓ Created: /content/arabic_faq_rag/src/reranking.py
✓ File size: 4.45 KB
✓ reranking.py syntax is valid
✓ Reranker imported successfully
✓ Alpha: 0.03
✓ Intent-aware scoring verified
✓ Matching candidate receives +0.03
✓ Deterministic ranking verified

===========================================================================
STEP 9D-3 COMPLETED SUCCESSFULLY
===========================================================================
✓ Production reranking module created
✓ E5 score preserved
✓ Predicted-intent matching preserved
✓ Alpha = 0.03
✓ No training
✓ No embeddings
✓ No FAISS rebuild

In [108]:
# ============================================================================
# STEP 9D-4A — INSPECT RETRIEVAL MODULE
# ============================================================================

from pathlib import Path

RETRIEVAL_PATH = Path("/content/arabic_faq_rag/src/retrieval.py")

print("=" * 75)
print("STEP 9D-4A — INSPECT RETRIEVAL MODULE")
print("=" * 75)

if not RETRIEVAL_PATH.exists():
    raise FileNotFoundError(
        f"retrieval.py not found: {RETRIEVAL_PATH}"
    )

source = RETRIEVAL_PATH.read_text(encoding="utf-8")

print(f"\nFile: {RETRIEVAL_PATH}")
print(f"Size: {len(source) / 1024:.2f} KB")
print("\n" + "-" * 75)
print("CURRENT retrieval.py")
print("-" * 75)

print(source)

print("\n" + "=" * 75)
print("INSPECTION COMPLETED")
print("=" * 75)

===========================================================================
STEP 9D-4A — INSPECT RETRIEVAL MODULE
===========================================================================

File: /content/arabic_faq_rag/src/retrieval.py
Size: 3.50 KB

---------------------------------------------------------------------------
CURRENT retrieval.py
---------------------------------------------------------------------------

import faiss
import numpy as np
import pandas as pd
from sentence_transformers import SentenceTransformer


class ArabicFAQRetriever:
    """
    Production Arabic FAQ semantic retriever.

    Pipeline:
        User Query
            ↓
        multilingual-e5-base
            ↓
        FAISS IndexFlatIP
            ↓
        Top-K FAQ chunks
    """

    def __init__(
        self,
        faiss_path: str,
        metadata_path: str,
        model_name: str = "intfloat/multilingual-e5-base",
        device: str = "cpu",
    ):
        self.faiss_path = faiss_path
        self.metadata_path = metadata_path
        self.model_name = model_name
        self.device = device

        # Load FAISS index
        self.index = faiss.read_index(
            self.faiss_path
        )

        # Load metadata
        self.metadata = pd.read_parquet(
            self.metadata_path
        )

        # Validate FAISS ↔ metadata alignment
        if self.index.ntotal != len(self.metadata):
            raise ValueError(
                "FAISS index size does not match "
                "metadata row count."
            )

        # Load embedding model
        self.model = SentenceTransformer(
            self.model_name,
            device=self.device
        )

        # Validate embedding dimension
        if self.index.d != self.model.get_sentence_embedding_dimension():
            raise ValueError(
                "FAISS dimension does not match "
                "embedding model dimension."
            )

    def search(
        self,
        query: str,
        top_k: int = 10,
    ):
        """
        Retrieve top-k FAQ chunks for an Arabic query.

        Returns:
            list[dict]
        """

        if not isinstance(query, str):
            raise TypeError(
                "query must be a string."
            )

        query = query.strip()

        if not query:
            raise ValueError(
                "query cannot be empty."
            )

        top_k = min(
            int(top_k),
            self.index.ntotal
        )

        # E5 query prefix
        query_text = f"query: {query}"

        # Encode query
        query_embedding = self.model.encode(
            [query_text],
            normalize_embeddings=True,
            convert_to_numpy=True,
            show_progress_bar=False,
        )

        query_embedding = (
            query_embedding
            .astype("float32")
        )

        # FAISS search
        scores, indices = self.index.search(
            query_embedding,
            top_k
        )

        results = []

        for rank, (
            score,
            corpus_idx
        ) in enumerate(
            zip(
                scores[0],
                indices[0]
            ),
            start=1
        ):

            if corpus_idx < 0:
                continue

            row = self.metadata.iloc[
                int(corpus_idx)
            ]

            results.append({
                "rank": rank,
                "corpus_idx": int(corpus_idx),
                "score": float(score),
                "id": row["id"],
                "company_id": row["company_id"],
                "company": row["company"],
                "domain": row["domain"],
                "country": row["country"],
                "chunk_idx": int(row["chunk_idx"]),
                "chunk_text": row["chunk_text"],
                "question": row["question"],
                "answer": row["answer"],
                "answerable": bool(row["answerable"]),
            })

        return results


===========================================================================
INSPECTION COMPLETED
===========================================================================

In [109]:
# ============================================================================
# STEP 9D-4A — PATCH RETRIEVAL MODULE
# ============================================================================

from pathlib import Path
import py_compile

RETRIEVAL_PATH = Path("/content/arabic_faq_rag/src/retrieval.py")

source = RETRIEVAL_PATH.read_text(encoding="utf-8")

# --------------------------------------------------------------------------
# 1. Add question_type to candidate output
# --------------------------------------------------------------------------

old = '''                "answerable": bool(row["answerable"]),
            })'''

new = '''                "answerable": bool(row["answerable"]),
                "question_type": row["question_type"],
            })'''

if old not in source:
    raise RuntimeError(
        "Expected candidate output block was not found. "
        "No changes were made."
    )

source = source.replace(old, new, 1)

# --------------------------------------------------------------------------
# 2. Write patched retrieval.py
# --------------------------------------------------------------------------

RETRIEVAL_PATH.write_text(
    source,
    encoding="utf-8"
)

print("=" * 75)
print("STEP 9D-4A — PATCH RETRIEVAL MODULE")
print("=" * 75)

print("\n✓ Added question_type to retrieval candidates")
print(f"✓ Updated: {RETRIEVAL_PATH}")

# --------------------------------------------------------------------------
# 3. Syntax validation
# --------------------------------------------------------------------------

py_compile.compile(
    str(RETRIEVAL_PATH),
    doraise=True
)

print("✓ retrieval.py syntax is valid")

# --------------------------------------------------------------------------
# 4. Verify patch
# --------------------------------------------------------------------------

updated_source = RETRIEVAL_PATH.read_text(
    encoding="utf-8"
)

assert '"question_type": row["question_type"]' in updated_source

print("✓ question_type output field verified")

print("\n" + "=" * 75)
print("STEP 9D-4A COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ Retrieval module patched")
print("✓ question_type will now be returned")
print("✓ No embeddings recomputed")
print("✓ No FAISS rebuild")
print("✓ No model retraining")

===========================================================================
STEP 9D-4A — PATCH RETRIEVAL MODULE
===========================================================================

✓ Added question_type to retrieval candidates
✓ Updated: /content/arabic_faq_rag/src/retrieval.py
✓ retrieval.py syntax is valid
✓ question_type output field verified

===========================================================================
STEP 9D-4A COMPLETED SUCCESSFULLY
===========================================================================
✓ Retrieval module patched
✓ question_type will now be returned
✓ No embeddings recomputed
✓ No FAISS rebuild
✓ No model retraining

In [110]:
# ============================================================================
# STEP 9D-4B — FINAL END-TO-END PRODUCTION TEST
# ============================================================================

from pathlib import Path
import sys
import time
import importlib

print("=" * 75)
print("STEP 9D-4B — FINAL END-TO-END PRODUCTION TEST")
print("=" * 75)

PROJECT_DIR = Path("/content/arabic_faq_rag")
SRC_DIR = PROJECT_DIR / "src"
DATA_DIR = Path("/content/arabic_faq_data")

FAISS_PATH = DATA_DIR / "train_chunks.faiss"
METADATA_PATH = DATA_DIR / "train_chunks_metadata_v2.parquet"
INTENT_PATH = DATA_DIR / "models" / "intent_classifier.joblib"

# --------------------------------------------------------------------------
# 1. Import latest modules
# --------------------------------------------------------------------------

print("\n[1/5] Loading latest production modules...")

if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

import retrieval
import intent
import reranking

importlib.reload(retrieval)
importlib.reload(intent)
importlib.reload(reranking)

from retrieval import ArabicFAQRetriever
from intent import ArabicFAQIntentClassifier
from reranking import IntentAwareReranker

print("✓ Modules loaded")

# --------------------------------------------------------------------------
# 2. Load production artifacts
# --------------------------------------------------------------------------

print("\n[2/5] Loading production artifacts...")

start = time.time()

retriever = ArabicFAQRetriever(
    faiss_path=str(FAISS_PATH),
    metadata_path=str(METADATA_PATH),
    model_name="intfloat/multilingual-e5-base",
    device="cuda",
)

intent_classifier = ArabicFAQIntentClassifier(
    model_path=INTENT_PATH
)

reranker = IntentAwareReranker(
    alpha=0.03
)

load_time = time.time() - start

print(f"✓ E5 + FAISS retriever loaded")
print(f"✓ Intent classifier loaded")
print(f"✓ Reranker loaded")
print(f"✓ Load time: {load_time:.2f} sec")

# --------------------------------------------------------------------------
# 3. Validate production artifacts
# --------------------------------------------------------------------------

print("\n[3/5] Validating production artifacts...")

assert retriever.index.ntotal == 164456
assert len(retriever.metadata) == 164456
assert retriever.index.d == 768
assert "question_type" in retriever.metadata.columns
assert len(intent_classifier.classes) == 8
assert reranker.alpha == 0.03

print(f"✓ FAISS vectors: {retriever.index.ntotal:,}")
print(f"✓ FAISS dimension: {retriever.index.d}")
print(f"✓ Metadata rows: {len(retriever.metadata):,}")
print(f"✓ Intent classes: {len(intent_classifier.classes)}")
print(f"✓ Reranker alpha: {reranker.alpha}")

# --------------------------------------------------------------------------
# 4. Full pipeline
# --------------------------------------------------------------------------

print("\n[4/5] Running complete production pipeline...")

test_queries = [
    "أريد إلغاء اشتراكي نهائياً",
    "ما الفرق بين الباقة الأساسية والمميزة؟",
    "لماذا تم خصم مبلغ إضافي من حسابي؟",
]

for query_no, query in enumerate(test_queries, 1):

    print("\n" + "-" * 75)
    print(f"QUERY {query_no}")
    print("-" * 75)

    print(f"Question: {query}")

    # -------------------------
    # Retrieval
    # -------------------------
    t0 = time.time()

    retrieved = retriever.search(
        query,
        top_k=10
    )

    retrieval_time = time.time() - t0

    assert len(retrieved) == 10

    print(f"\n[Retrieval]")
    print(f"✓ Candidates: {len(retrieved)}")
    print(f"✓ Time: {retrieval_time:.3f} sec")
    print(f"✓ Top-1 E5 score: {retrieved[0]['score']:.6f}")

    # -------------------------
    # Intent
    # -------------------------
    predicted_intent = intent_classifier.predict(query)

    print(f"\n[Intent]")
    print(f"✓ Predicted: {predicted_intent}")

    # -------------------------
    # Candidate validation
    # -------------------------
    assert all(
        "question_type" in candidate
        for candidate in retrieved
    )

    print("✓ All candidates contain question_type")

    # -------------------------
    # Reranking
    # -------------------------
    t1 = time.time()

    reranked = reranker.rerank(
        retrieved,
        predicted_intent=predicted_intent,
        top_k=10
    )

    rerank_time = time.time() - t1

    assert len(reranked) == 10

    print(f"\n[Reranking]")
    print(f"✓ Candidates: {len(reranked)}")
    print(f"✓ Time: {rerank_time:.4f} sec")

    intent_matches = sum(
        candidate["intent_match"]
        for candidate in reranked
    )

    print(f"✓ Intent matches in Top-10: {intent_matches}/10")

    # -------------------------
    # Final ranking validation
    # -------------------------
    scores = [
        float(candidate["final_score"])
        for candidate in reranked
    ]

    assert scores == sorted(scores, reverse=True)

    print("✓ Final ranking order valid")

    # -------------------------
    # Top 3
    # -------------------------
    print("\nFinal Top-3:")

    for candidate in reranked[:3]:

        print(
            f"\n  Rank {candidate['rerank_rank']}"
            f" | Final={candidate['final_score']:.6f}"
            f" | E5={candidate['e5_score']:.6f}"
            f" | Match={candidate['intent_match']}"
        )

        print(
            f"  ID={candidate['id']}"
            f" | Domain={candidate['domain']}"
        )

        print(
            f"  Intent={candidate['candidate_intent']}"
        )

        print(
            f"  Text={candidate['chunk_text'][:150]}..."
        )

# --------------------------------------------------------------------------
# 5. Final status
# --------------------------------------------------------------------------

print("\n" + "=" * 75)
print("STEP 9D-4B COMPLETED SUCCESSFULLY")
print("=" * 75)

print("✓ E5 retrieval verified")
print("✓ FAISS search verified")
print("✓ Metadata v2 verified")
print("✓ question_type propagation verified")
print("✓ Intent classifier verified")
print("✓ Intent-aware reranking verified")
print("✓ Final ranking verified")
print("✓ End-to-end production pipeline verified")
print("✓ No training")
print("✓ No embedding recomputation")
print("✓ No FAISS rebuild")

===========================================================================
STEP 9D-4B — FINAL END-TO-END PRODUCTION TEST
===========================================================================

[1/5] Loading latest production modules...
✓ Modules loaded

[2/5] Loading production artifacts...

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

/content/arabic_faq_rag/src/retrieval.py:58: FutureWarning: The `get_sentence_embedding_dimension` method has been renamed to `get_embedding_dimension`.
  if self.index.d != self.model.get_sentence_embedding_dimension():

✓ E5 + FAISS retriever loaded
✓ Intent classifier loaded
✓ Reranker loaded
✓ Load time: 16.92 sec

[3/5] Validating production artifacts...
✓ FAISS vectors: 164,456
✓ FAISS dimension: 768
✓ Metadata rows: 164,456
✓ Intent classes: 8
✓ Reranker alpha: 0.03

[4/5] Running complete production pipeline...

---------------------------------------------------------------------------
QUERY 1
---------------------------------------------------------------------------
Question: أريد إلغاء اشتراكي نهائياً

[Retrieval]
✓ Candidates: 10
✓ Time: 0.310 sec
✓ Top-1 E5 score: 0.856000

[Intent]
✓ Predicted: account or subscription management (upgrade, renewal, closing)
✓ All candidates contain question_type

[Reranking]
✓ Candidates: 10
✓ Time: 0.0001 sec
✓ Intent matches in Top-10: 3/10
✓ Final ranking order valid

Final Top-3:

  Rank 1 | Final=0.886000 | E5=0.856000 | Match=1
  ID=3787-3 | Domain=water utility
  Intent=account or subscription management (upgrade, renewal, closing)
  Text=تتيح سياسة إلغاء الاشتراك للمشتركين إنهاء العقد خلال 30 يوماً من تاريخ التفعيل مع استرداد 80% من الرسوم المدفوعة مقدماً. يجب تقديم طلب الإلغاء كتابياً...

  Rank 2 | Final=0.880358 | E5=0.850358 | Match=1
  ID=3401-1 | Domain=gym / fitness club chain
  Intent=account or subscription management (upgrade, renewal, closing)
  Text=سياسة إلغاء الاشتراك: يمكن للعضو إلغاء اشتراكه في أي وقت بشرط تقديم طلب كتابي قبل 15 يوماً من تاريخ التجديد. يتم استرداد 50% من قيمة الأشهر المتبقية ف...

  Rank 3 | Final=0.878884 | E5=0.848884 | Match=1
  ID=6487-2 | Domain=gym / fitness club chain
  Intent=account or subscription management (upgrade, renewal, closing)
  Text=سياسة إلغاء الاشتراك: يمكن للعضو إلغاء اشتراكه في أي وقت بشرط إخطار الإدارة كتابياً قبل ١٥ يوماً من تاريخ التجديد. يتم رد المبالغ المدفوعة عن الشهور ا...

---------------------------------------------------------------------------
QUERY 2
---------------------------------------------------------------------------
Question: ما الفرق بين الباقة الأساسية والمميزة؟

[Retrieval]
✓ Candidates: 10
✓ Time: 0.098 sec
✓ Top-1 E5 score: 0.844692

[Intent]
✓ Predicted: comparison between two products or plans
✓ All candidates contain question_type

[Reranking]
✓ Candidates: 10
✓ Time: 0.0000 sec
✓ Intent matches in Top-10: 0/10
✓ Final ranking order valid

Final Top-3:

  Rank 1 | Final=0.844692 | E5=0.844692 | Match=0
  ID=4437-3 | Domain=mobile wallet / payments app
  Intent=billing dispute or a charge on the account
  Text=تتيح باقة 'الأساسية' فتح حساب مجاني، بينما تبلغ رسوم الاشتراك في باقة 'المميزة' 25 درهماً مغربياً شهرياً. تمنح الباقة المميزة المستخدم إمكانية تحويل م...

  Rank 2 | Final=0.844692 | E5=0.844692 | Match=0
  ID=4437-2 | Domain=mobile wallet / payments app
  Intent=availability, coverage or delivery time
  Text=تتيح باقة 'الأساسية' فتح حساب مجاني، بينما تبلغ رسوم الاشتراك في باقة 'المميزة' 25 درهماً مغربياً شهرياً. تمنح الباقة المميزة المستخدم إمكانية تحويل م...

  Rank 3 | Final=0.844692 | E5=0.844692 | Match=0
  ID=4437-1 | Domain=mobile wallet / payments app
  Intent=pricing or fees
  Text=تتيح باقة 'الأساسية' فتح حساب مجاني، بينما تبلغ رسوم الاشتراك في باقة 'المميزة' 25 درهماً مغربياً شهرياً. تمنح الباقة المميزة المستخدم إمكانية تحويل م...

---------------------------------------------------------------------------
QUERY 3
---------------------------------------------------------------------------
Question: لماذا تم خصم مبلغ إضافي من حسابي؟

[Retrieval]
✓ Candidates: 10
✓ Time: 0.064 sec
✓ Top-1 E5 score: 0.847801

[Intent]
✓ Predicted: billing dispute or a charge on the account
✓ All candidates contain question_type

[Reranking]
✓ Candidates: 10
✓ Time: 0.0000 sec
✓ Intent matches in Top-10: 1/10
✓ Final ranking order valid

Final Top-3:

  Rank 1 | Final=0.866889 | E5=0.836889 | Match=1
  ID=5994-2 | Domain=streaming service
  Intent=billing dispute or a charge on the account
  Text=في حال ظهور مبلغ إضافي غير مبرر على الفاتورة، يجب تقديم طلب مراجعة مالية خلال 14 يوماً من تاريخ الخصم. تقوم الشركة بمعالجة الطلب وإعادة المبالغ المخصو...

  Rank 2 | Final=0.847801 | E5=0.847801 | Match=0
  ID=667-3 | Domain=streaming service
  Intent=comparison between two products or plans
  Text=لتطوير الحساب من الباقة الأساسية إلى المميزة، يتم خصم المبلغ المتبقي من أيام الشهر الحالي من قيمة الباقة الجديدة. يتم تفعيل المزايا الإضافية فوراً، وي...

  Rank 3 | Final=0.847801 | E5=0.847801 | Match=0
  ID=667-2 | Domain=streaming service
  Intent=account or subscription management (upgrade, renewal, closing)
  Text=لتطوير الحساب من الباقة الأساسية إلى المميزة، يتم خصم المبلغ المتبقي من أيام الشهر الحالي من قيمة الباقة الجديدة. يتم تفعيل المزايا الإضافية فوراً، وي...

===========================================================================
STEP 9D-4B COMPLETED SUCCESSFULLY
===========================================================================
✓ E5 retrieval verified
✓ FAISS search verified
✓ Metadata v2 verified
✓ question_type propagation verified
✓ Intent classifier verified
✓ Intent-aware reranking verified
✓ Final ranking verified
✓ End-to-end production pipeline verified
✓ No training
✓ No embedding recomputation
✓ No FAISS rebuild

In [111]:
# ============================================================================
# STEP 10A — PREPARE PROJECT EXPORT
# ============================================================================

from pathlib import Path
import shutil
import os

print("=" * 75)
print("STEP 10A — PREPARING PROJECT EXPORT")
print("=" * 75)

PROJECT_DIR = Path("/content/arabic_faq_rag")
DATA_DIR = Path("/content/arabic_faq_data")
EXPORT_DIR = Path("/content/arabic_faq_rag_export")

# Remove previous export if it exists
if EXPORT_DIR.exists():
    shutil.rmtree(EXPORT_DIR)

EXPORT_DIR.mkdir(parents=True)

# --------------------------------------------------------------------------
# 1. Copy source code
# --------------------------------------------------------------------------

src_src = PROJECT_DIR / "src"
src_dst = EXPORT_DIR / "src"

if src_src.exists():
    shutil.copytree(src_src, src_dst)

# --------------------------------------------------------------------------
# 2. Copy production artifacts needed by the application
# --------------------------------------------------------------------------

data_dst = EXPORT_DIR / "data"
data_dst.mkdir()

files_to_copy = [
    DATA_DIR / "train_chunks.faiss",
    DATA_DIR / "train_chunks_metadata_v2.parquet",
]

models_dst = data_dst / "models"
models_dst.mkdir()

files_to_copy_models = [
    DATA_DIR / "models" / "intent_classifier.joblib"
]

for src in files_to_copy:
    if not src.exists():
        raise FileNotFoundError(f"Missing required artifact: {src}")
    shutil.copy2(src, data_dst / src.name)

for src in files_to_copy_models:
    if not src.exists():
        raise FileNotFoundError(f"Missing required model: {src}")
    shutil.copy2(src, models_dst / src.name)

# --------------------------------------------------------------------------
# 3. Create project README placeholder
# --------------------------------------------------------------------------

readme = EXPORT_DIR / "README.md"

readme.write_text(
    """# Arabic FAQ RAG

Production Arabic FAQ retrieval and intent-aware reranking system.

## Architecture

Arabic Query
→ multilingual-e5-base
→ FAISS
→ Top-K Retrieval
→ Intent Classification
→ Intent-Aware Reranking

## Core Components

- multilingual-e5-base
- FAISS IndexFlatIP
- TF-IDF + LinearSVC intent classifier
- Intent-aware reranking

## Note

The Streamlit application and final documentation will be added in the next steps.
""",
    encoding="utf-8"
)

# --------------------------------------------------------------------------
# 4. Create requirements placeholder
# --------------------------------------------------------------------------

requirements = EXPORT_DIR / "requirements.txt"

requirements.write_text(
    """sentence-transformers
faiss-cpu
scikit-learn
pandas
numpy
joblib
streamlit
pyarrow
""",
    encoding="utf-8"
)

# --------------------------------------------------------------------------
# 5. Inventory
# --------------------------------------------------------------------------

print("\nExport contents:")

total_size = 0

for path in sorted(EXPORT_DIR.rglob("*")):
    if path.is_file():
        size_mb = path.stat().st_size / (1024 ** 2)
        total_size += size_mb
        print(f"✓ {path.relative_to(EXPORT_DIR)} — {size_mb:.2f} MB")

print("\n" + "-" * 75)
print(f"Total export size: {total_size:.2f} MB")
print(f"Export directory: {EXPORT_DIR}")
print("-" * 75)

print("\n" + "=" * 75)
print("STEP 10A COMPLETED SUCCESSFULLY")
print("=" * 75)

===========================================================================
STEP 10A — PREPARING PROJECT EXPORT
===========================================================================

Export contents:
✓ README.md — 0.00 MB
✓ data/models/intent_classifier.joblib — 8.33 MB
✓ data/train_chunks.faiss — 481.80 MB
✓ data/train_chunks_metadata_v2.parquet — 17.67 MB
✓ requirements.txt — 0.00 MB
✓ src/__pycache__/intent.cpython-313.pyc — 0.00 MB
✓ src/__pycache__/reranking.cpython-313.pyc — 0.00 MB
✓ src/__pycache__/retrieval.cpython-313.pyc — 0.00 MB
✓ src/intent.py — 0.00 MB
✓ src/reranking.py — 0.00 MB
✓ src/retrieval.py — 0.00 MB

---------------------------------------------------------------------------
Total export size: 507.83 MB
Export directory: /content/arabic_faq_rag_export
---------------------------------------------------------------------------

===========================================================================
STEP 10A COMPLETED SUCCESSFULLY
===========================================================================

In [112]:
# ============================================================================
# STEP 10B — CLEAN EXPORT + CREATE ZIP
# ============================================================================

from pathlib import Path
import shutil

EXPORT_DIR = Path("/content/arabic_faq_rag_export")
ZIP_BASE = Path("/content/arabic_faq_rag_project")

print("=" * 75)
print("STEP 10B — CLEANING EXPORT AND CREATING ZIP")
print("=" * 75)

# --------------------------------------------------------------------------
# 1. Remove __pycache__ directories
# --------------------------------------------------------------------------

removed = 0

for pycache in EXPORT_DIR.rglob("__pycache__"):
    shutil.rmtree(pycache)
    removed += 1

print(f"\n✓ Removed __pycache__ directories: {removed}")

# --------------------------------------------------------------------------
# 2. Remove any .pyc files just in case
# --------------------------------------------------------------------------

for pyc in EXPORT_DIR.rglob("*.pyc"):
    pyc.unlink()

print("✓ Removed .pyc files")

# --------------------------------------------------------------------------
# 3. Create ZIP
# --------------------------------------------------------------------------

zip_path = shutil.make_archive(
    str(ZIP_BASE),
    "zip",
    root_dir=EXPORT_DIR
)

zip_file = Path(zip_path)

size_mb = zip_file.stat().st_size / (1024 ** 2)

print(f"\n✓ ZIP created successfully")
print(f"✓ File: {zip_file}")
print(f"✓ Size: {size_mb:.2f} MB")

# --------------------------------------------------------------------------
# 4. Final inventory
# --------------------------------------------------------------------------

print("\nFinal project contents:")

for path in sorted(EXPORT_DIR.rglob("*")):
    if path.is_file():
        size_mb_file = path.stat().st_size / (1024 ** 2)
        print(
            f"✓ {path.relative_to(EXPORT_DIR)} "
            f"— {size_mb_file:.2f} MB"
        )

print("\n" + "=" * 75)
print("STEP 10B COMPLETED SUCCESSFULLY")
print("=" * 75)

===========================================================================
STEP 10B — CLEANING EXPORT AND CREATING ZIP
===========================================================================

✓ Removed __pycache__ directories: 1
✓ Removed .pyc files

✓ ZIP created successfully
✓ File: /content/arabic_faq_rag_project.zip
✓ Size: 214.59 MB

Final project contents:
✓ README.md — 0.00 MB
✓ data/models/intent_classifier.joblib — 8.33 MB
✓ data/train_chunks.faiss — 481.80 MB
✓ data/train_chunks_metadata_v2.parquet — 17.67 MB
✓ requirements.txt — 0.00 MB
✓ src/intent.py — 0.00 MB
✓ src/reranking.py — 0.00 MB
✓ src/retrieval.py — 0.00 MB

===========================================================================
STEP 10B COMPLETED SUCCESSFULLY
===========================================================================